### PR TITLE
[ticket/14229]Responsive topic specific paging

### PR DESCRIPTION
**Pull request by hanakin**
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14229
image

PHPBB3-14229

### CODE REVIEW

**Comment by hanakin** [comment]
!set Style

**Comment by Nicofuma** [comment]
It used to be displayed like that but I like how it looks with this PR

**Comment by marc1706** [comment]
Are the report and topic approval icons supposed to split lines?
bildschirmfoto vom 2015-10-17 12 23 16
This happens on latest Chrome right before the <dd> tags are hidden while reducing the viewport size.

**Comment by hanakin** [comment]
its inline-block need to add inline to .icons possibly

**Pull request merged**
