### PR TITLE
[ticket/15900]Converting install/index.html to UTF-8 and fixing tag.

### PR DESCRIPTION
**Pull request by orynider**
Checklist:

- [ ] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-12345

### CODE REVIEW

**Comment by orynider** [comment]
https://tracker.phpbb.com/browse/PHPBB3-15900

**Comment by 3D-I** [comment]
Should be

```
[ticket/15900] Converting install/index.html to UTF-8 and fixing tag

PHPBB3-15900
```

**Comment by orynider** [comment]
@3D-I This space is important wile I commit ?

**Comment by 3D-I** [comment]
The space and the new blank line after the first one and the third line containing `PHPBB3-15900`.

As you can see above.

You forgot to close a bunch of failed PRs, if you like you can close them BTW.

**Comment by 3D-I** [comment]
You may want to CLOSE the PR before to delete the branch?

**Pull request closed without merging**
