### PR TITLE
[ticket/16238] Remove S_REDIRECT_LOGIN work around

### PR DESCRIPTION
**Pull request by mrgoldy**
PHPBB3-16238

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16238

### CODE REVIEW

**Comment by rubencm** [comment]
I would remove it in 4.0 better

**Comment by marc1706** [comment]
Yes, I agree. It's better to keep this now and then have the breaking change in 4.0 (as one would expect ;) ).

**Comment by marc1706** [comment]
Changed base to master 👍

**Comment by marc1706** [comment]
Depends on #5773

**Pull request merged**
