### PR TITLE
[ticket/14343] Add missing $phpbb_dispatcher

### PR DESCRIPTION
**Pull request by kasimi**
[PHPBB3-14343](https://tracker.phpbb.com/browse/PHPBB3-14343)

PR #4066 is missing the $phpbb_dispatcher

### CODE REVIEW

**Comment by Nicofuma** [comment]
@nickvergessen I think it's needed to rebuild the 3.1.7 packages with this fix. Otherwise locking/unlocking may throw fatal errors, right?

**Comment by kasimi** [comment]
Unfortunately, yes.

**Comment by nickvergessen** [comment]
Well let's not repackage, but also increase the version then, because packages are public quite a few days already

**Comment by marc1706** [comment]
@kasimi Builds fails because you were using an incorrect ticket id in your commit message heading and were missing ```PHPBB3-14343``` in your commit message after the heading.

**Comment by marc1706** [comment]
Replaced by #4109

**Pull request closed without merging**
