### PR TITLE
[ticket/16274] Fix compact() call to undefined variables in search.php

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16274

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16274

### CODE REVIEW

**Comment by marc1706** [comment]
How does this relate to https://tracker.phpbb.com/browse/PHPBB3-16262 ?

**Comment by 3D-I** [comment]
Oh I see, well I noticed this bug during my continous testing here and I implemented my fix which is different from this one https://github.com/phpbb/phpbb/pull/5783/commits/faca59b3a6ded459bf67e66cf1088380e9850048 (I am not duplicating an existing line etc.).

**Comment by marc1706** [comment]
I have now fixed the conflicts between this and brunoais' PR. There were a few inconsistencies which I think should be fixed now. Apart from that, we should still cover this in here: https://github.com/phpbb/phpbb/pull/5783#issuecomment-569191429

**Comment by 3D-I** [comment]
> 
> 
> .... we should still cover this in here: [#5783 (comment)](https://github.com/phpbb/phpbb/pull/5783#issuecomment-569191429)

I was gonna open another ticket on that, but okay, tested.

**Pull request merged**
