### PR TITLE
[ticket/14496] Cache last update of update list instead of using filemtime

### PR DESCRIPTION
**Pull request by marc1706**
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14496

### CODE REVIEW

**Comment by Elsensee** [comment]
This creates an extra file just for the time. I would rather not do that and just call it `update_list_time` so it gets into the global cache. Or is the global one non existent in the installer?

**Comment by marc1706** [comment]
Yes, should definitely go into the global cache file.

**Comment by marc1706** [comment]
@Elsensee turns out that the global cache does not work as expected in the installer. Went back to using the underscore prefix.

**Comment by Elsensee** [comment]
Oh. Then maybe we can write it to installer_config instead?

**Comment by marc1706** [comment]
As this is for 3.1.x, there is not installer config.

**Pull request merged**
