### PR TITLE
[ticket/15631] Remove / from void HTML elements

### PR DESCRIPTION
**Pull request by scootergrisen**
Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15631

### CODE REVIEW

**Comment by Skouat** [comment]
Hi,
The `<br>` is not the only one that required to be converted.
There is the tag `<input>` and the attribute `checked`.

https://www.w3schools.com/tags/att_input_checked.asp

**Comment by hanakin** [comment]
@Skouat thats in the front-end this is meant to fix the language var usage only.

@scootergrisen your commit message is in the wrong format

**Comment by scootergrisen** [comment]
Is it good now?

**Comment by hanakin** [comment]
No you need to complete rebase and squash your commits.

**Comment by scootergrisen** [comment]
I dont know what to do.
I was trying to submit each commit as a pull request but it seems to put the new commits in the same pull request.

**Comment by hanakin** [comment]
You do not want that.. commits are peices of pull requests. If you are tying to fix different things then you need to create separate branches and push each branch separately to create different pull requests

**Comment by scootergrisen** [comment]
I made https://github.com/phpbb/phpbb/pull/5204 instead.

**Pull request closed without merging**
