### PR TITLE
[ticket/13603] Add index_body_stat_blocks_after event

### PR DESCRIPTION
**Pull request by senky**
PHPBB3-13603

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-13603

### CODE REVIEW

**Comment by 3D-I** [comment]
Why subsilver2?

**Comment by marc1706** [comment]
Why not? It's still supported.

**Comment by 3D-I** [comment]
My bad. ;)

**Comment by javiexin** [comment]
The merge of this is making 3.2 builds fail: apparently the events.md changes have not been properly merged into 3.2. Merge conflict?

Questions: why the name of the PR is different from the name of the event?
And why the name of the event is `_birthday_block_` while all other events in the same file are`_block_birthday_` or `_block_stats_`and so on?

**Comment by marc1706** [comment]
The build failure is caused by me failing at merging things. Should be fixed now. The naming is imho ok, especially since it affects a different part.

**Comment by javiexin** [comment]
Thanks a lot.

**Pull request merged**
