### PR TITLE
[ticket/15369] Update composer

### PR DESCRIPTION
**Pull request by VSEphpbb**
PHPBB3-15369

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15369

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Hmm, it seems this PR is no longer necessary

**Comment by 3D-I** [comment]
Latest composer's release is now 1.6 (1.6.1 in snapshots)

**Comment by rxu** [comment]
We should probably indeed update it to 1.6 because of this annoying bug https://github.com/composer/composer/issues/6859#issuecomment-355023696
I'm not sure if it does affect the actual core/extensions operation though.

**Comment by VSEphpbb** [comment]
No clue what that is failing but it has nothing to do with this PR's changes

**Comment by hubaishan** [comment]
composer used with 3.2.x also need update it has `count()` bug with PHP 7.2 see https://tracker.phpbb.com/browse/PHPBB3-15557

**Pull request merged**
