### PR TITLE
[ticket/15219] Update hashes to bcrypt with cron

### PR DESCRIPTION
**Pull request by marc1706**
PHPBB3-15219

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15219

### CODE REVIEW

**Comment by Nicofuma** [comment]
Please add a CLI command which can do that aswell (better than cron for big boards)

**Comment by marc1706** [comment]
Will do

**Comment by marc1706** [comment]
What heading should the console command be using? The db: heading might make sense but not 100%. Maybe create a new one for passwords?

**Comment by Nicofuma** [comment]
It could be fixup I think

**Comment by marc1706** [comment]
Added the console command

**Pull request merged**
