### PR TITLE
[ticket/13987] Add --dry-run option to reparser CLI

### PR DESCRIPTION
**Pull request by s9e**
https://tracker.phpbb.com/browse/PHPBB3-13987

### CODE REVIEW

**Comment by s9e** [comment]
!set WIP

**Comment by s9e** [comment]
@Nicofuma Changes made as per your comment. I didn't like having an optional argument in `reparse_range()` to indicate a dry run so I added `disable_save()` and `enable_save()` to the reparser API.

If all tests pass, it should be good to go. !unset WIP

**Comment by s9e** [comment]
!unset WIP

**Comment by Nicofuma** [comment]
:+1:

**Comment by Nicofuma** [comment]
The tests are failing and the PR needs to be rebased

**Comment by s9e** [comment]
@Nicofuma Rebased. The test failure seems unrelated, [something about Gravatar](https://travis-ci.org/phpbb/phpbb/jobs/69664596).

**Pull request merged**
