### PR TITLE
[ticket/16899] Add SVG and WEBP to ranks, smilies and topic icons

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16899

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16899

### CODE REVIEW

**Comment by hanakin** [comment]
probably look into applying something like

```
.profile-rank img {
	max-width: 160px; /* In my case the original size is 480x90px */
	image-rendering: -moz-crisp-edges;  /* Firefox */
	image-rendering:   -o-crisp-edges;   /* Opera */
	image-rendering: -webkit-optimize-contrast;   /* Webkit (non-standard naming) */
	image-rendering: crisp-edges;
	-ms-interpolation-mode: nearest-neighbor;  /* IE (non-standard property) */
}
```

suggested here: https://www.phpbb.com/community/viewtopic.php?p=15579991#p15579991

while your att it for fallback

**Comment by 3D-I** [comment]
https://caniuse.com/?search=image-rendering 

Looks like `image-rendering: crisp-edges;` is enough?

**Comment by 3D-I** [comment]
Is IE still supported on 3.3.x?

**Comment by hanakin** [comment]
was just think that technically IE11 is

**Pull request merged**
