### PR TITLE
[ticket/15422] Removed the unnecessary helpline function & help_line array

### PR DESCRIPTION
**Pull request by kwnthe**
Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15422

### CODE REVIEW

**Comment by hanakin** [comment]
@kwnthe you have removed the js aspects but have not removed any of the code spidered throughout the HTML

**Comment by kwnthe** [comment]
What do you mean? The array and the function are not being used anywhere in the system

**Comment by hanakin** [comment]
Do a search on the project files for helpline

**Comment by kwnthe** [comment]
I searched using grep but didn't found anything that is related directly with the helpline function and array. Sorry for the trouble but it is my first pull request.
I just executed what the ticket requested and since a phpBB employee suggested me this ticket to start with i thought that it is correct.

**Comment by hanakin** [comment]
There are function calls in the html files I will have a look and try and provide some better guidance when I get home tonight from work

**Comment by kwnthe** [comment]
Ok thank you

**Comment by hanakin** [comment]
@kwnthe there are lots of references to helpline throughout the code. try searching for L_BBCODE_HELPLINE and you will see no variable by that name yet its used in the html. then try L_BBCODE_B_HELP and you will see the same etc...

**Pull request closed without merging**
