### PR TITLE
[ticket/15605] Correct Right-Margin for ribbon image

### PR DESCRIPTION
**Pull request by dnssh**
Checklist:

- [ ] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **15605**):

https://tracker.phpbb.com/browse/PHPBB3-15605

### CODE REVIEW

**Comment by hanakin** [comment]
Check the commit I left on your commit as the message needs fixed slightly

**Comment by dnssh** [comment]
Hello Sir,
@hanakin Thank you for your kind suggestion.
Pls review whether below commit has correct format

$ git commit -m "[ticket/15605] Correct Right-Margin for ribbon image

PHPBB3-15605"

Regards,
Devansh Shah

**Comment by hanakin** [comment]
@dnssh looks good

**Comment by dnssh** [comment]
Thank You @hanakin  ,all the changes have been committed successfully.

**Comment by hanakin** [comment]
@dnssh ok a couple of things. First, why did you create a new ticket in the tracker? Please do not do this use the ticket that is there next time. second, all you need is a `margin: 5px;`

**Comment by dnssh** [comment]
Ok thanks ,will consider these things further.

**Comment by hanakin** [comment]
@dnssh are you going to make the suggested change?

**Comment by dnssh** [comment]
OK Sir @hanakin  made those suggested changes

**Pull request merged**
