### PR TITLE
[ticket/17365] Prevent search limit being bypassed with operators

### PR DESCRIPTION
**Pull request by crowjake**
Provided `$countable_keywords` wherein the existing `$keywords` value is modified so that any `-`, `+` and `|` characters without preceding spaces is replaced with the same but with a space in front of each. 

These spaces allow the string to be more accurately split when used instead of $keywords inside the $num_keywords calculation. 

This prevents the word limit being bypassed in search by the use of operators without whitespace.

PHPBB-17365

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB-17365

### CODE REVIEW

**Comment by marc1706** [comment]
There is no need to close and open new pull requests every time you want to change something. You can either close and reopen the same PR or request a rerun of tests if something else failed.

**Comment by crowjake** [comment]
> There is no need to close and open new pull requests every time you want to change something. You can either close and reopen the same PR or request a rerun of tests if something else failed.

Noted, and thanks for clarifying. I had a few false starts before I worked out how to do it correctly, I'll make sure I'm doing it the right way from here on out.

**Comment by crowjake** [comment]
I had to force-push so that the previous commit message could be amended to have lines shorter than 80 characters - this was necessary because "Tests / PHP 7.2 - none (pull_request)" was failing due to this standard being unmet.

**Comment by marc1706** [comment]
Thanks for the PR. I've added a test that should cover the different cases based on the ticket description.

**Pull request merged**
