### PR TITLE
[WIP][ticket/11595] REST API

### PR DESCRIPTION
**Pull request by galaxyAbstractor**
Creating an API for phpBB to enable ease of access by other applications

PHPBB3-11595

### CODE REVIEW

**Comment by alamops** [comment]
Well, It sounds good.
Congrats @galaxyAbstractor !!
Was it already approved?

**Comment by callumacrae** [comment]
@alamops read the comments above

**Comment by mtangoo** [comment]
Is this going anywhere? @galaxyAbstractor can you comment if you have time to make it into a PHPBB3 somehow?

**Comment by Bew78LesellB** [comment]
Hi @galaxyAbstractor,

Any update on this, I'd like to use it, is this PR stable ?
@nickvergessen & others moderators: Do you plan to merge anytime soon ?

**Comment by DavidIQ** [comment]
@Bew78LesellB you do realize WIP means Work In Progress right and that this is closed right, as indicated by the red bar at the top and the comments preceding yours? This was even based on a branch that no longer exists.

I'll lock comments now and leave the following note for those that happen to come here: **This PR is closed and cannot be merged or used as is. If you are here and would like to continue working on this PR you will need to redo most of it, but might want to take a look at the work done to do your implementation based on it.**

**Pull request closed without merging**
