### PR TITLE
Update mcp_reports.php [skip ci]

### PR DESCRIPTION
**Pull request by cybernet**
nothing much :)

### CODE REVIEW

**Comment by callumacrae** [comment]
It needs to be in the commit message

http://docs.travis-ci.com/user/how-to-skip-a-build/

**Comment by marc1706** [comment]
Definitely not going to happen in 3.1.x and I'm not sure whether we want to merge something that is just whitespace changes (nothing is broken here really, it's just tiny cosmetics).

**Comment by bantu** [comment]
This seems to fix indentation on github, but breaks indentation in my editor (Kate). Maybe someone can work out the details on the difference between the two.

**Comment by marc1706** [comment]
This actually breaks indentation as @bantu said. It was better before.

**Comment by Elsensee** [comment]
@bantu Github uses a tab size of 8, while we use a tab size of 4. :/ I think there are some browser extensions which can fix that. github-forcetabsize for Chrome used to work in the past for me but somehow it has stopped working. "Github Tab Size" for Chrome should work though.

**Comment by nickvergessen** [comment]
https://github.com/phpbb/phpbb/pull/3650/files?ts=4 no need for a plugin ;)

**Comment by Sumanai** [comment]
> I think there are some browser extensions which can fix that.

I use stilish and behold the following code:
```
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("github.com") {
.tab-size-8{-moz-tab-size:4;tab-size:4}
}
```

**Pull request closed without merging**
