### PR TITLE
[ticket/11063] Use HTTPS for phpBB's version check

### PR DESCRIPTION
**Pull request by Nicofuma**
Checklist:
- [X] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [X] Tests pass
- [X] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [X] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-11063

PHPBB3-11063

### CODE REVIEW

**Comment by Nicofuma** [comment]
@michaelcullum a small gift

**Comment by 3D-I** [comment]
Does that means that we will be able to use our github repositories for the extensions' version-checkers instead of working-around creating a github'd website for that, as I (and others) did?

**Comment by michaelcullum** [comment]
Hah. Thanks.

**Comment by Nicofuma** [comment]
@3D-I it is already possible, you need to set the `ssl` key to `true` for that

**Comment by 3D-I** [comment]
@Nicofuma Yes, but I can't ask the end user to hard-code its own phpBB.

**Comment by Nicofuma** [comment]
I was talking about the version check definition of your own extensions

**Comment by 3D-I** [comment]
@Nicofuma I don't think I am following you, care to explain? I know this is not the right place though.

**Comment by Nicofuma** [comment]
```
		"version-check": {
			"host": "nicofuma.github.io",
			"directory": "/",
			"filename": "webprofiler.json",
			"ssl": true,
}
```

**Comment by marc1706** [comment]
@Nicofuma label says 3.1 target while PR shows master branch. I take it this is intended for 3.1 then?

**Comment by Nicofuma** [comment]
not sure actually, that's quite a big change

**Comment by marc1706** [comment]
I guess one could still overrride it with setting ssl to false?
I'd aim this at 3.2 then though.

**Comment by 3D-I** [comment]
@Nicofuma thanks, got it.

**Comment by marc1706** [comment]
Moving to 3.2 milestone

**Comment by Nicofuma** [comment]
pushed back to 3.3 as I'd prefer to have a proper ssl support for that. (may be included in one of the 3.2.x version if the diff is not too big or complex)

**Comment by michaelcullum** [comment]
Long-term: Require a PSR-7 http client abstraction, then use Guzzle
Short term why not enable ssl?

**Comment by Elsensee** [comment]
What is stopping this from happening?

**Comment by marc1706** [comment]
I think there were a few questions regarding the support for this on shared hosting.

**Comment by rubencm** [comment]
I think this should be something like
`extension_loaded  ('openssl') && in_array("https", stream_get_wrappers())`
(I havent check, and i am not sure about the first condition)

**Pull request merged**
