### PR TITLE
[ticket/17398] Add referer to delete cookies route to ensure proper URLs

### PR DESCRIPTION
**Pull request by marc1706**
PHPBB-17398

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB-17398

### CODE REVIEW

**Comment by rxu** [comment]
Tested on localhost and the fix has worked.

**Comment by phpbbtr** [comment]
The fix worked but URL structure is very bad.

**Comment by rxu** [comment]
Works with the latest commit too. The URL looks like
```
[ROOT]/user/delete_cookies?_=1728574399309&confirm_key=4NXK26TVY7&confirm_uid=1&sess=a695b217dfe97cd81be690e5ce08be9b&sid=a695b217dfe97cd81be690e5ce08be9b
```

**Comment by marc1706** [comment]
> Works with the latest commit too. The URL looks like
> 
> ```
> [ROOT]/user/delete_cookies?_=1728574399309&confirm_key=4NXK26TVY7&confirm_uid=1&sess=a695b217dfe97cd81be690e5ce08be9b&sid=a695b217dfe97cd81be690e5ce08be9b
> ```

I think he was complaining about the initial URL when you hover over the navbar link :)

**Comment by rxu** [comment]
>  initial URL when you hover over the navbar link

It's just `./user/delete_cookies`

**Review by Derky — APPROVED** [review]

**Pull request merged**
