### PR TITLE
[ticket/14325] Preserve event variable BC

### PR DESCRIPTION
**Pull request by CHItA**
[PHPBB3-14325](https://tracker.phpbb.com/browse/PHPBB3-14325)

### CODE REVIEW

**Comment by CHItA** [comment]
@VSEphpbb

**Comment by VSEphpbb** [comment]
Actually should be @Nicofuma who looks at this

**Comment by CHItA** [comment]
I meant that you could check if all event variable names are changed 
back correctly now.

**Comment by VSEphpbb** [comment]
Oh, yeah, you caught all of them.

**Comment by Nicofuma** [comment]
:+1: that's the way to go

**Comment by marc1706** [comment]
Any reason why the tests were cancelled?

**Comment by naderman** [comment]
If we change all of this code already why not change it to no longer use references at all?

**Comment by CHItA** [comment]
The ACP should be rewritten from scratch anyway and this was way faster to do

**Comment by naderman** [comment]
Heh fair enough

**Pull request merged**
