### PR TITLE
[ticket/15719] Add core events to viewtopic to edit the post_list sql query

### PR DESCRIPTION
**Pull request by toxyy**
Event added in viewtopic.php so you can modify post_list sql

The query, sql limit, sql start, sort keys and days are editable

PHPBB3-15719

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15719

### CODE REVIEW

**Comment by 3D-I** [comment]
Isn't your fault IMHO.
That's something the developers need to fix here at github/repo/settings.

A lot of PRs are failing the same way. Hold the line pls.

**Comment by 3D-I** [comment]
In fact.

**Comment by toxyy** [comment]
Yeah for some reason it was linking to the wrong one, but I checked the travis queue and it was still running. Looks like you relinked it right somehow.  Thanks :)  How did you do that?

**Comment by 3D-I** [comment]
I believe it's based on the success of this PR https://github.com/phpbb/phpbb/pull/5284
I did nothing by my side, I can't.

**Comment by toxyy** [comment]
Thank you very much :) now just to wait for the appveyor queue to process.  Do you know when 3.2.4 will be released so I can properly release my extension?

**Comment by DavidIQ** [comment]
@3D-I No idea what setting you think we need to change here? Travis failing in the previous prs were a result of bad line endings and looks like also using the github interface for commits or commit messages.

**Comment by 3D-I** [comment]
@DavidIQ  that's another PR which haven't had that issue as the previous ones.

The errors of the present PR prior of its success were the same as per some others.

```
HEAD is now at 93990ab... v0.33.11
Downloading https://nodejs.org/dist/v4.9.1/node-v4.9.1-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
-npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
\npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
\npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
\npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
-npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
|npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
|npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
\npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
\npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
/npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
+stylelint 'phpBB/styles/prosilver/theme/*.css'
+stylelint 'phpBB/adm/style/*.css'
``

This one got automatically restarted/fixed when the above PR of Marc I above linked passed on travis.

Name it a coincidence

**Comment by DavidIQ** [comment]
Then I guess part of the problem was that the pr was incorrectly targeting master instead of the 3.2.x branch. That seems to be corrected in this pr. Marc’s pr fixes the CSS linting issues in master but is not merged so wouldn’t really do anything for other prs that are targeting master.

As far as 3.2.4 goes: we’re preparing to release 3.2.3 now so it’ll be a while before 3.2.4 is released.

**Comment by 3D-I** [comment]
@DavidIQ 
Thanks for the explaination, dunno why I am sure it was targeting the 3.2 branch though.. I could be wrong.  /me getting older, sadly.

Any chance to re-start this PR? https://github.com/phpbb/phpbb/pull/5285 btw.

**Comment by 3D-I** [comment]
@toxyy 
you can also put your extension in the development forum, saying there is the need of this changes (hence 3.2.4-RC1) in order the extension to work. Isn't the first time I have seen a such started topic over there.

**Comment by DavidIQ** [comment]
No point in doing that. Marc’s fix for the build issues has not been merged yet and then I think Ruben might have to rebase.

**Comment by toxyy** [comment]
Yeah one of the earlier ones that failed was because I forgot to select master so I made another pr with 3.2.x selected.  If you mean the extension developer forum I got [this topic](https://www.phpbb.com/community/viewtopic.php?f=461&t=2290536) from there so I didn't think it was necessary to make a topic about it.  I still have a few things I'd like to fix first, and make the acp and migrations work, before I post it to the extensions in development forum.

I was planning on just posting the changes that I made to viewtopic.php to

**Comment by 3D-I** [comment]
@DavidIQ 
sorry to bother you, is there any reason why also this PR suddenly restarted and got fixed on travis?

https://github.com/phpbb/phpbb/pull/5219

this has been made about 19 hours ago https://travis-ci.org/phpbb/phpbb/builds/401492548?utm_source=github_status&utm_medium=notification

**Comment by 3D-I** [comment]
https://github.com/phpbb/phpbb/pull/5152 about 19 hours ago

**Comment by DavidIQ** [comment]
That wasn’t restarted. Commit was pushed. See the commit history and note that it has a date of July 8, presumably because the change was amended and then force-pushed.

**Comment by 3D-I** [comment]
I give up, nice to see all of of this activity though. :-D
Sleepy time has come, have you all a nice day/night. Thx.

**Comment by 3D-I** [comment]
@toxyy 
I meant extensions in development forum.

**Comment by toxyy** [comment]
Depending on how many roadblocks I run into probably this week.

**Pull request merged**
