### PR TITLE
[ticket/14058] Contact us form missing email subject field in subsilver2

### PR DESCRIPTION
**Pull request by Oyabun1**
https://tracker.phpbb.com/browse/PHPBB3-14061

### CODE REVIEW

**Comment by RMcGirr83** [comment]
@Oyabun1 you need to place PHPBB3-14058 into the commit message

**Comment by Oyabun1** [comment]
@RMcGirr83
Travis said
> Error: heading should be a sentence beginning with a letter. 
> You entered: 
> ticket/14058 

How is "t" not a letter?

**Comment by RMcGirr83** [comment]
Though that is the error that is displayed, it is not accurate.

**Comment by Oyabun1** [comment]
I don't know what is wrong with the commit message. I've compared it to successful commits and the syntax is now the same, but it still fails.

**Comment by Elsensee** [comment]
It checks the first commits as well, so it fails.
Just squash the commits and keep the commit message of the last commit.

In case you don't know, here's a HowTo:
If you got git bash, open it and try:
`git rebase -i f34f28f`
An editor should open with the three commits which are currently in this branch. Change the second and third "pick" to "squash", save it and close it.
Another editor should open and asking you what the new message should be. Delete everything before the last commit message (there should be all three displayed under each other) Please note that there has to be an empty line before `PHPBB3-14058`
Hope everything's clear. ;)

**Comment by Oyabun1** [comment]
Finally got there. Thanks for the help guys. I still hate Git.

**Comment by RMcGirr83** [comment]
:+1:

**Pull request merged**
