### PR TITLE
[ticket/15436] remove folder icons code from index

### PR DESCRIPTION
**Pull request by vinny**
Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

https://tracker.phpbb.com/browse/PHPBB3-15436

### CODE REVIEW

**Comment by Crizz0** [comment]
There are a few extensions which display these icons as a caption in the board index. The PR will lead in reworking of their function, right?

**Comment by vinny** [comment]
Yes. https://www.phpbb.com/community/viewtopic.php?f=461&t=2444711

**Comment by By-oussef** [comment]
+1

**Comment by marc1706** [comment]
Re-creating for 3.3.x target

**Comment by marc1706** [comment]
Replaced by https://github.com/phpbb/phpbb/pull/5694

**Pull request closed without merging**
