### PR TITLE
Ticket/13587

### PR DESCRIPTION
**Pull request by Oyabun1**
Fix two SQL syntax errors in get_prune_users()

### CODE REVIEW

**Comment by rxu** [comment]
@Oyabun1 The PR seems to be messed, only the last commit is related to the bugfix.

**Comment by nickvergessen** [comment]
@rxu its not messed, it's just based on develop instead of develop-ascraeus

**Comment by RMcGirr83** [comment]
@nickvergessen will you be cherry picking or would you prefer I do a new ticket and reference the one from Oyabun1?

**Comment by RMcGirr83** [comment]
https://github.com/phpbb/phpbb/pull/3439

**Pull request closed without merging**
