### PR TITLE
[ticket/15689] Show statistics of storages on acp_storage

### PR DESCRIPTION
**Pull request by rubencm**
Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Depends on #4933 

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15689

### CODE REVIEW

**Comment by rubencm** [comment]
!set WIP :construction:

**Comment by rubencm** [comment]
!unset WIP :construction:

**Comment by Nicofuma** [comment]
when we have the free space information we could display some kind of progress bar showing how full the storage is (or use a specific color code).
Other wise, looks good.

**Comment by Nicofuma** [comment]
btw, don't hesitate to add a screenshot when you make visual changes :)

**Comment by Nicofuma** [comment]
nice

**Comment by Nicofuma** [comment]
please rebase on master

**Comment by rubencm** [comment]
@Nicofuma i did it yesterday with all pull requests

**Pull request merged**
