### PR TITLE
[ticket/14154] Add extension composer name as tooltip

### PR DESCRIPTION
**Pull request by Zoddo**
[PHPBB3-14154](https://tracker.phpbb.com/browse/PHPBB3-14154)

### CODE REVIEW

**Comment by Nicofuma** [comment]
I'd rather have it with a float:right or with brackets

**Comment by Zoddo** [comment]
@Nicofuma : Oh, yes, I've forgot the brackets!

**Comment by VSEphpbb** [comment]
I don't like this. This is what the **Details** link is for if a user really must know. This just adds clutter and inconsistency. It seems to be addressing a problem that doesn't really exist.

**Comment by dragosvr92** [comment]
VSE, i have fully explained why this is needed. After you uninstall an extension, you need to know where to browse to delete the extension files. Why should we have to check the details to find out where it is installed? But, if it is indeed considered disturbing, maybe it would be best to have the clean name on all extensions while we hover on their Extension name, as i suggested in the ticket. There is a topic and a ticket where we can discuss this.

**Comment by VSEphpbb** [comment]
Having the clean name everywhere is a disaster. Nobody has ever complained of this, it's just not been an issue. The details link, 1 click, has all the info you need.

**Comment by dragosvr92** [comment]
Its not everywhere. It is somewhere where people need it. People also never complained publicly about the difficulty to follow an extension, without a hover highlighter on the extensions list. Besides me. And you wrote the patch for it yesterday. 

When you are set to remove an extension, you have two steps in mind; disable it, then you need to know where it is stored and go delete its files. Why add the Check details page to see where it is stored, in between? Checking the Details page for the path can be frustrating. 

I have already suggested moving the clean name to the title twice. What you saying ? :P

**Comment by VSEphpbb** [comment]
We are currently working on an extension management interface that should eliminate the need to go to FTP, so this whole topic is going to be a moot point soon. ;)

**Comment by dragosvr92** [comment]
Nice. Can i have a peek in its current design? :grinning: I am guessing that the extension management would go out in 3.2 or 4.0. So, we could add this as a title hover until then. It is easy enough to merge.

**Comment by VSEphpbb** [comment]
I have always complained about the row thing. Just last week in #phpbb-dev: 
> VSE: Anyone else think it'd be nice to have hover row highlighting in the ACP extensions manager?

Also, bear in mind. People don't normally remove an extension one day out of the blue. They install one. they update one. Both of which involve immediate handling of the package, so they know what it's called. Normally when somebody uninstalls an extension, it's in close proximity time-wise to when they installed (as in they realize they don't like it or have problems because of it). It's just very rare that users decide to uninstall one so far away from the time when they know what the package naming was.

**Comment by VSEphpbb** [comment]
> Nice. Can i have a peek in its current design? :grinning: I am guessing that the extension management would go out in 3.2 or 4.0. So, we could add this as a title hover until then. It is easy enough to merge.

A hover/title attribute would be OK, even into the future. Yes, you will be able to see the code once PRs start popping up.

**Comment by dragosvr92** [comment]
I have installed and updated many extensions i have installed. i still have no clue where many of them are stored. When you find out there is a new version, you check the details, see the path, and the download link for the update. Also, there are those people that dont update their software. 

I have about 32 extensions. I only remember some of the paths of developers im acquainted to. 

The other day i realised i had one active extension that i never used and i need to delete it. 
There were also disabled extensions that i was considering to use, but never did. 

 @Zoddo Could you please move the clean name to a title? 
Not sure how to implement it. Maybe change the <strong> with a <span> and add the title tag and set the bold in css ?

**Comment by VSEphpbb** [comment]
> Not sure how to implement it. Maybe change the < strong > with a < span > and add the title tag and set the bold in css ?

No, just add the title attribute to the strong tag. Simple.

**Comment by dragosvr92** [comment]
We can do that? I mean, i know we can, and it works. But, im not sure if it is html valid...?

**Comment by VSEphpbb** [comment]
It is. title is a global attribute, available in any html tag.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

**Comment by dragosvr92** [comment]
hum, ok. Thanks for letting me know. I had the impression that its not recommended to use style and id/class attributes in simple elements like < b > or < i > and we should use spans or divs for complexish things.

**Comment by dragosvr92** [comment]
Btw, i love how git sends messages instantly and updates the page also instantly. It works so very smooth. I hope phpbb will inspire from gits behaviour. Its a bit annoying to have it load and refresh so much.

**Comment by VSEphpbb** [comment]
> Thanks for letting me know. I had the impression that its not recommended to use style and id/class attributes

It's not styling. It's an HTML tag attribute.

**Comment by Zoddo** [comment]
> @Zoddo Could you please move the clean name to a title? 

Done

**Comment by dragosvr92** [comment]
Thank you @Zoddo :smile: 
@Nicofuma, would it be possible to rush this into the 3.1.6 Branch?

**Comment by VSEphpbb** [comment]
> would it be possible to rush this into the 3.1.6 Branch?
No it won't.

**Comment by dragosvr92** [comment]
I recently realised it has been released. I thought there was still time.

**Pull request merged**
