### PR TITLE
[ticket/14447] Remove trailing white spaces in Prosilver

### PR DESCRIPTION
**Pull request by VSEphpbb**
https://tracker.phpbb.com/browse/PHPBB3-14447

PHPBB3-14447

### CODE REVIEW

**Comment by bantu** [comment]
We should detect those ...

**Comment by marc1706** [comment]
I think the code sniffer only checks PHP files right now. We definitely might want to check for trailing spaces in html files, too.

**Comment by bantu** [comment]
@marc1706 PHP Code Sniffer does not seem to like being applied to HTML files. Hummm.

**Comment by bantu** [comment]
This PR looks good. :+1:

**Comment by Nicofuma** [comment]
I don't really like this sort of PR (poor style team and contributors...) but... it's kinda necessary.

Thanks @VSEphpbb

**Pull request merged**
