### PR TITLE
[ticket/14700] Prevent an exception on duplicate smilies in text_formatter

### PR DESCRIPTION
**Pull request by JoshyPHP**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

https://tracker.phpbb.com/browse/PHPBB3-14700

PHPBB3-14700

### CODE REVIEW

**Comment by Crizz0** [comment]
Why do you name your pull request 14700? You are not solving this, right? https://tracker.phpbb.com/browse/PHPBB3-14700

**Comment by JoshyPHP** [comment]
@Crizz0 The ticket number is correct; It should fix this particular issue.

I recognize the error message `Item ':confused:' already exists` as something that originates from s9e\TextFormatter, caused by duplicate emoticons. I guess there are multiple `:confused:` smilies in that database. This change should fix that.

By the way, I don't know who's supposed to check those checkboxes at the top. Is it the PR author? I assumed a bot would check the last three after the test suite ran. Either way, the PR is good to go if you want to merge it.

**Comment by marc1706** [comment]
Yes, those checkboxes are for the PR author. Hopefully people will use it to actually confirm that they're doing everything correctly. ;)

**Comment by Crizz0** [comment]
@JoshyPHP I was confused by the second link to another ticket and the different title. :cry:

**Comment by JoshyPHP** [comment]
@Crizz0 Yeah it's my fault, I didn't notice that the placeholder link to the tracker didn't match the ticket number. I was in a hurry and didn't have time to describe what the patch did but I wanted to submit the PR anyway to let Travis do its thing while I was away.

**Pull request merged**
