### PR TITLE
[ticket/15025] Use SSL in version check for extension

### PR DESCRIPTION
**Pull request by tas2580**
Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket 

https://tracker.phpbb.com/browse/PHPBB3-15025

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Can you squash all these commits into 1

**Comment by tas2580** [comment]
If you can say me how. [This](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) dosn't work.

**Comment by marc1706** [comment]
Will have to cherry-pick this into 3.2.x.

**Comment by Nicofuma** [comment]
merged

**Pull request closed without merging**
