### PR TITLE
[ticket/12143] Make it possible to use translated group names for non-special groups

### PR DESCRIPTION
**Pull request by Elsensee**
Yeah, so I did this... out of the old PR #2247 

I had to do a new method in language service - I think it should be fine to do that in this PR.

I want to create another class like this, which is based on the function get_username_string, but splitted up to several functions like get_name, get_color, etc.
These methods (get_name, get_color) can be added to this class to at a later point too, I guess.

[PHPBB3-12143](https://tracker.phpbb.com/browse/PHPBB3-12143)

### CODE REVIEW

**Comment by Nicofuma** [comment]
https://travis-ci.org/phpbb/phpbb/jobs/64566865#L1174-L1186

**Comment by Nicofuma** [comment]
bump

**Comment by Nicofuma** [comment]
you need to rebase again ;)

**Comment by Elsensee** [comment]
*sigh* rebased.. :P

**Comment by Nicofuma** [comment]
looks good

**Pull request merged**
