### PR TITLE
[ticket/14497] Support second app.php script in install folder

### PR DESCRIPTION
**Pull request by marc1706**
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14497

### CODE REVIEW

**Comment by marc1706** [comment]
@bantu mind having a look?

**Comment by marc1706** [comment]
The nginx sample config is now included in the tests and I've also added tests for browsing to the installer.

@bantu ^

**Comment by Nicofuma** [comment]
lgtm

**Comment by marc1706** [comment]
lgtm = lol, get the manual?

**Comment by Nicofuma** [comment]
looks good to me ;)

**Pull request merged**
