### PR TITLE
[ticket/17352] Fix overflow of long rank titles on profile page

### PR DESCRIPTION
**Pull request by danieltj27**
Users that had very long rank titles would cause the rest of their profile details to be pushed down below the avatar and rank details breaking the layout. This change limits the width of the avatar and rank details.

PHPBB-17352

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB-17352

### CODE REVIEW

**Comment by danieltj27** [comment]
I'm not 100% sure why previous commits are attached to this PR but I think it's working? 🥴

Sorry for duping the PR if everything was fine in #6653. I thought I broke something again.

**Comment by Crizz0** [comment]
Try to rebase your commits on base of 3.3.x: https://area51.phpbb.com/docs/dev/3.3.x/development/git.html#fixing-merge-conflicts

**Comment by danieltj27** [comment]
I recreated the branch and tried to start from a current working 3.3.x (with my fork sync'd to this repo) so I'm not sure what I did or did not do to cause this problem.

I ran the commands you linked above got this:

>  public  ⚡️ git rebase origin/3.3.x
Auto-merging phpBB/composer.json
CONFLICT (content): Merge conflict in phpBB/composer.json
Auto-merging phpBB/composer.lock
CONFLICT (content): Merge conflict in phpBB/composer.lock
Auto-merging phpBB/docs/README.html
CONFLICT (content): Merge conflict in phpBB/docs/README.html
Auto-merging phpBB/install/convertors/convert_phpbb20.php
CONFLICT (content): Merge conflict in phpBB/install/convertors/convert_phpbb20.php
Auto-merging phpBB/install/phpbbcli.php
CONFLICT (content): Merge conflict in phpBB/install/phpbbcli.php
Auto-merging phpBB/language/en/install.php
CONFLICT (content): Merge conflict in phpBB/language/en/install.php
Auto-merging phpBB/styles/prosilver/style.cfg
CONFLICT (content): Merge conflict in phpBB/styles/prosilver/style.cfg
error: could not apply 93f932b80f... [ticket/14495] Revert changes in master
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 93f932b80f... [ticket/14495] Revert changes in master

I'll check my repo again and see if it's behind.

**Comment by rubencm** [comment]
Let me try to fix this

**Comment by danieltj27** [comment]
Sorry I've just undone what you did. I'm going to have to delete my fork and start over because I have no idea how my 3.3.x is somehow matching the phpbb/master branch now. I think that's why all of these commits are attached to it.

I can't figure out how to update my fork and sync changes.

I'm really sorry.

**Comment by rubencm** [comment]
No worries

**Pull request closed without merging**
