### PR TITLE
[ticket/15191] Purge cache directory even on dummy driver

### PR DESCRIPTION
**Pull request by Elsensee**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:
https://tracker.phpbb.com/browse/PHPBB3-15191

### CODE REVIEW

**Comment by ErnadoO** [comment]
Hello

This PR doesn't fix the ticket issue, because somes files are never removed:

> else if (strpos($filename, 'container_') === 0 ||
> 				strpos($filename, 'autoload_') === 0 ||
> 				strpos($filename, 'url_matcher') === 0 ||
> 				strpos($filename, 'url_generator') === 0 ||
> 				strpos($filename, 'sql_') === 0  ||
> 				strpos($filename, 'data_') === 0)
> 			{
> 				$this->remove_file($fileInfo->getPathname());
> 			}
in base::purge() :

**Comment by rxu** [comment]
```cache_dir``` is never being initialized for this driver, so there's nothing to purge anyway.

**Comment by ErnadoO** [comment]
Yes but some classes doesn't care about which driver cache is used and write files directly in the cache directory.

I's the case for container_builder():
https://github.com/phpbb/phpbb/blob/b1e37871978702910fbe75acc019268c44bb026b/phpBB/phpbb/di/container_builder.php#L480

router():
https://github.com/phpbb/phpbb/blob/b1e37871978702910fbe75acc019268c44bb026b/phpBB/phpbb/routing/router.php#L213
https://github.com/phpbb/phpbb/blob/b1e37871978702910fbe75acc019268c44bb026b/phpBB/phpbb/routing/router.php#L268


I think these files should never be cached with dummy driver (it's the goal of this driver no ?)

**Comment by rxu** [comment]
> it's the goal of this driver no ?

It should be, as it's previous name is ```null``` 😃

**Comment by Nicofuma** [comment]
Actually these files are not part of the cache managed by these classes.
In phpBB there is 2 different kind of cache:
 - The first one is used to cache data (from the database, an external API, etc. like the list of available styles, the acl...)
 - The second one is used to store generated PHP files for some component that either have a far more important impact on the board performance or just can't work without these files. 

In the future we should better handle that, but for now this PR is acceptable. We just need to ensure that the dummy driver will never fail (even if it can't remove a file)

**Comment by marc1706** [comment]
@rxu is correct. The cache dir is not set so this change will not result in the cache directory being emptied. Therefore I don't see a point in this PR.

**Pull request closed without merging**
