### PR TITLE
[ticket/14607] Missing Auto Increment in Report Table

### PR DESCRIPTION
**Pull request by JimMH**
Adding $report_id to the array in the report handler and adding auto_increment to the DB field report id

PHPBB3-14607

### CODE REVIEW

**Comment by marc1706** [comment]
This will probably need a new migration file to correctly update previously installed boards.

**Comment by rxu** [comment]
The question is whether this was done intentionally (non-autoincrement field) and why, if yes.

**Comment by marc1706** [comment]
Caused by: https://github.com/phpbb/phpbb/commit/7cd7bb3c015be1355ab634d3cb704c1d764bf8b0

There needs to be a migration that reverts the incorrect change to not use auto_increment and the migration changing the default data types needs to be modified to use auto_increment for report_id.

**Comment by marc1706** [comment]
Closing for incomplete fix

**Pull request closed without merging**
