### PR TITLE
[ticket/12821] Convert all images to gradients

### PR DESCRIPTION
**Pull request by hanakin**
This is two changes
1. Fix all the current gradients to be consistent and handled correctly
2. Replace the remaining gradient gifs with css gradients IE: .headerbar, .forabg, .forumbg, .button1-3 , .forums, .dropdown-extended .header

TODO:

 - [x] Chrome
 - [x] Firefox
 - [x] Safari
 - [x] IE 9+

Old PR: https://github.com/phpbb/phpbb/pull/2702
Ticket: https://tracker.phpbb.com/browse/PHPBB3-12821

PHPBB3-12821

### CODE REVIEW

**Comment by hanakin** [comment]
This is ready for review

**Comment by Nicofuma** [comment]
@cyberalien can give this PR a look please?

**Comment by cyberalien** [comment]
@Nicofuma tested, everything works correctly

**Comment by hanakin** [comment]
@Nicofuma ready for merge

**Comment by hanakin** [comment]
@Nicofuma This one is ready as well

**Comment by Nicofuma** [comment]
Thank you.

**Pull request merged**
