### PR TITLE
[ticket/12745] Allow Unicode characters from the SMP to be used in text

### PR DESCRIPTION
**Pull request by s9e**
https://tracker.phpbb.com/browse/PHPBB3-12745
https://tracker.phpbb.com/browse/PHPBB3-13178
~~https://tracker.phpbb.com/browse/PHPBB3-11711~~

[This update to s9e\TextFormatter](https://github.com/s9e/TextFormatter/commit/42d614c08e5f3ce5d35a29867d58a7f50fed7c91) automatically encodes characters from the Supplementary Multilingual Plane, making it possible to use those characters in formatted text regardless of the database.

### CODE REVIEW

**Comment by s9e** [comment]
!set WIP

**Comment by s9e** [comment]
!unset WIP

**Comment by s9e** [comment]
!set WIP

**Comment by s9e** [comment]
@Nicofuma This should be good to go.

And in case your WIP-bot is back online:
!unset WIP

**Comment by bantu** [comment]
I am not sure I like that approach.

**Comment by bantu** [comment]
If we're still storing HTML anyway, this might be fine, though.

**Comment by s9e** [comment]
This is XML. What is it that you don't like in that approach?

**Comment by bantu** [comment]
Please add a test verifiying that input "&#128512;" comes out as "&#128512;" and is not converted to 😀.

**Comment by s9e** [comment]
@bantu I'm not familiar with the Crawler used in phpBB's test suite and I can't run the functional tests locally for some reason. I used the following:
```php
$this->assertContains('&#128512;', $crawler->text());
```
I assume this tests that the given string appears in the document's `textContent`. That means that if someone types `&#128512;` it should appear as `&amp;#128512;` in the HTML.

**Pull request merged**
