### PR TITLE
[ticket/16881] Fix ACP Statistic Table

### PR DESCRIPTION
**Pull request by Dark1z**
PHPBB3-16881

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16881

### CODE REVIEW

**Comment by 3D-I** [comment]
I left a comment in the tracker

Here is the full statistics block
image

**Comment by Dark1z** [comment]
Ahh!!! I forgot to reserve the 2nd comment for Explanation.

So here is it:
Only use empty table row if required.

Before: 

&


After:

&


Best regards 👍

**Comment by Dark1z** [comment]
> I left a comment in the tracker
> 
> Here is the full statistics block - so you are removing it if zeroed?

I left a comment for you on tracker too.
But let me reply the same here:
>No!
>the table on RHS.
>
>If "orphan attachments" row is not used in LHS table then remove the BLANK row from RHS table.
>Before due to the BLANK row from RHS table, there was a Blank row on both the tables as shown in Image.

Best regards 👍

**Comment by 3D-I** [comment]
I don't see such a discrepance here, example of your second IMG

image

**Comment by Dark1z** [comment]
> I don't see such a discrepance here, example of your second IMG
> 
> So again, you are willing to hide the orphan attachments row if zeroed and as such you need to modify the template?

@3D-I ,

Try disabling the attachments.

Also do check the changed code properly,
I am not hiding "orphan attachments row" at all,
I am hiding the BLANK row.

**Comment by 3D-I** [comment]
> 
> Try disabling the attachments.
> 

I can see it now. 
Why didn't you also indicate how to reproduce this problem?
I would never have imagined disabling attachments in a forum. 
I would have avoided commenting at least. ;-)

**Comment by Dark1z** [comment]
can somebody restart the following jobs:
1. https://github.com/phpbb/phpbb/pull/6298/checks?check_run_id=3691466604
2. https://github.com/phpbb/phpbb/pull/6298/checks?check_run_id=3691466658
It happened due to internal SQL or PHP error, and not related to the code changes.

Thanking you, Best regards 👍

**Comment by Dark1z** [comment]
> > Try disabling the attachments.
> 
> I can see it now.
> Why didn't you also indicate how to reproduce this problem?
> I would never have imagined disabling attachments in a forum.
> I would have avoided commenting at least. ;-)

No problem, it happens , an itch to comment.
I have been there ;-)

**Comment by 3D-I** [comment]
Does the "orphan attachments" row disappear also if positive, when disabling attachments?
I mean the row disappears only if zeroed?

**Comment by Dark1z** [comment]
> Does the "orphan attachments" row disappear also if positive, when disabling attachments?
> I mean that row disappears only if zeroed?

Yes!
coz of this:
https://github.com/phpbb/phpbb/pull/6298/commits/119e6882cc1c36a567b32d1febe542338ec00ba0#diff-2ea3f5f13d7a3be05b231a4502fd49a24ca26da726b892abc7abc70bf07de214R142

**Comment by 3D-I** [comment]
I think that the bug is elsewhere, in ACP 
https://github.com/phpbb/phpbb/blob/3d76942cdfe1ca86adf39a6ca1d8b125e73f16b1/phpBB/includes/acp/acp_main.php#L547-L560

All the attachment related rows are shown per default also if zeroed, same way the "orphans" should act.
This way there is no need to modify the template and everything will be more consistent, IMHO.

**Comment by Dark1z** [comment]
> I think that the bug is elsewhere, in ACP
> https://github.com/phpbb/phpbb/blob/3d76942cdfe1ca86adf39a6ca1d8b125e73f16b1/phpBB/includes/acp/acp_main.php#L547-L560
> 
> All the attachment related rows are shown per default also if zeroed, same way the "orphans" should act.
> This way there is no need to modify the template and everything will be more consistent, IMHO.

Yes! sure you can make it as your new PR.

My goal is to handle the Extra BLANK table row on RHS table.
Hence this PR.

**Comment by 3D-I** [comment]
Ok, i pushed my own PR in case https://github.com/phpbb/phpbb/pull/6299

**Comment by Dark1z** [comment]
> Ok, i pushed my own PR in case #6299

Ok. closing this issue due to PR #6299 

Best regards 👍

**Pull request closed without merging**
