### PR TITLE
[ticket/14484] Add possibility to use extensions in UI tests

### PR DESCRIPTION
**Pull request by marc1706**
Also updated the webdriver.

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14484

Also updated ui test case file to have same feature set as
the 3.2.x version.

PHPBB3-14484

### CODE REVIEW

**Comment by VSEphpbb** [comment]
So extensions can use phpbb_ui_test_case.php like they use the functional and db test cases ? :)

**Comment by marc1706** [comment]
That's the plan, yes

**Comment by VSEphpbb** [comment]
Looks like this needs to be for 3.2 and above

**Comment by marc1706** [comment]
Will only need to modify the webdriver version for this to work with 3.1, too.

**Comment by marc1706** [comment]
@VSEphpbb mind testing the implementation of the UI tests for extensions?

**Comment by VSEphpbb** [comment]
@marc1706 I can't tell if it works. The test I created just gets skipped, with no message.

**Comment by marc1706** [comment]
Ah, you probably don't have phantomjs running. Will try myself now. :)

**Comment by VSEphpbb** [comment]
Even though I can't write a working UI test to save my life, I can confirm that this is working (i.e.: installing extensions and allowing them to use UI test case).

**Comment by marc1706** [comment]
See the linked issue in Board3 Portal for an example of UI tests in extensions.

**Comment by VSEphpbb** [comment]
@marc1706 i know how to write the test... just each time I tried  wanted to test something the facebok driver couldnt perform... like the result of an on change effect after selecting a pull-down menu item

**Comment by marc1706** [comment]
The facebook driver can only perform that when the phantomjs properly works :)

**Comment by marc1706** [comment]
bump @phpbb/development-team

**Comment by Nicofuma** [comment]
LGTM

**Comment by Nicofuma** [comment]
3.1 or 3.2? @marc1706

**Comment by marc1706** [comment]
I've modified the webdriver version to also make this compatible with 3.1. We can always increase versions on 3.2.x+ in the future but I think this should go into 3.1.

**Comment by Nicofuma** [comment]
it does not merge cleanly in 3.2 (both composer and tests/test_framework/phpbb_ui_test_case.php conflicts)

**Pull request merged**
