### PR TITLE
[ticket/15945] Allow redirection to subdomains

### PR DESCRIPTION
**Pull request by ajquick**
This change improves the way phpBB prevents redirection to outside domains through the redirection function. This change allows phpBB to redirect any domain or subdomain that is covered under the cookie settings.

PHPBB3-15945

https://tracker.phpbb.com/browse/PHPBB3-15945

### CODE REVIEW

**Comment by mrgoldy** [comment]
You have to keep doing your commit messages as you did with the first one.
Your latest commit does not have the `[ticket/15945]` and `PHPBB3-15945`.

**Comment by ajquick** [comment]
Any idea how to do that? Also it seems to only be failing the tests because the current master is failing, otherwise this passes the tests.

**Comment by DavidIQ** [comment]
This is failing because of your commit messages, not because of master:

```
The following lines are greater than 80 characters long: 
3:Keep existing function in tact for when cookie_domain is not defined (typically during testing). 
Aborting commit. 
```

You'll need to do an interactive rebase and fix that commit message.

**Comment by battye** [comment]
> This is failing because of your commit messages, not because of master:
> 
> ```
> The following lines are greater than 80 characters long: 
> 3:Keep existing function in tact for when cookie_domain is not defined (typically during testing). 
> Aborting commit. 
> ```
> You'll need to do an interactive rebase and fix that commit message.

What is the difference between doing an interactive rebase and something like this?

```
git reset HEAD~ 
git add .
git commit -m "[ticket/15945] My amended commit message"
git push -f origin mybranch
```

**Comment by DavidIQ** [comment]
> > This is failing because of your commit messages, not because of master:
> > ```
> > The following lines are greater than 80 characters long: 
> > 3:Keep existing function in tact for when cookie_domain is not defined (typically during testing). 
> > Aborting commit. 
> > ```
> > You'll need to do an interactive rebase and fix that commit message.
> 
> What is the difference between doing an interactive rebase and something like this?
> 
> ```
> git reset HEAD~ 
> git add .
> git commit -m "[ticket/15945] My amended commit message"
> git push -f origin mybranch
> ```

```
git rebase -i HEAD~
```
Then follow the instructions that come up on your editor, i.e. change `pick` to `reword` or `r` for the commit that comes up and on the next editor that comes up put in the right commit message. Either way will work.

**Comment by ajquick** [comment]
Got it sorted thanks @battye.

**Comment by ajquick** [comment]
I believe ```!empty($url_parts['scheme'])``` should potentially be changed too, to allow for no http/https/ftp scheme to be present. After all relative URIs are completely valid such as:

> //www.domain.com

But since $url_parts['scheme'] is empty this will fail in functions.php ([line 1821](https://github.com/phpbb/phpbb/blob/04aadf77ca7df85f2b64619c7b9431e2acddd946/phpBB/includes/functions.php#L1821)).

**Comment by ajquick** [comment]
I hate this shit.

**Pull request closed without merging**
