### PR TITLE
[ticket/15429] Add function phpbb_general_select() to functions.php

### PR DESCRIPTION
**Pull request by hubaishan**
Add function `phpbb_general_select()` to help extension writers who want to add their config to core ACP configs with combobox

PHPBB3-15429

Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-15429

### CODE REVIEW

**Comment by DavidIQ** [comment]
This looks so specific to your particular needs that I don't see it helping anyone else much if at all...

If this really is for the ACP then just use `build_cfg_template` which is in `functions_acp.php`.

**Comment by hubaishan** [comment]
> If this really is for the ACP then just use build_cfg_template which is in functions_acp.php.

This new function will be called by build_cfg_template to build 'select' options

**Comment by rubencm** [comment]
Talking about forms..., i think i need something like this #1922

**Comment by hubaishan** [comment]
> Ah yes, forgot about that part of build_cfg_template. That does not, however, change my comment about this only benefiting your specific need.
No it's general. many extension developer may need it, if they want their extension configurations lay beside phpBB core  configurations not in separate module.  they can use 'core.acp_board_config_edit_add' event to add textboxs and radio buttons but not comboboxes because 'build_cfg_template' need a function call to build comboboxes options, this PR will add general function will be useful in many cases.

**Comment by marc1706** [comment]
I'm having a few issues with this pull request. First of, we're trying to get rid of functions that generate HTML inside PHP files. Secondly, your function is missing a phpbb_ prefix to create a more unique name. Thirdly, you're using globals instead of passing the user class object directly.

**Comment by hanakin** [comment]
@rubencm Agree prefer a twig function for this. No HMTL in core...

**Pull request closed without merging**
