### PR TITLE
[ticket/14928] Users will not understand the phrase '"%s" is not a valid stability'

### PR DESCRIPTION
**Pull request by Rishabh04-02**
[ticket/14928]

https://tracker.phpbb.com/browse/PHPBB3-14928
File modified - phpBB/language/en/cli.php

14928

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-12345

### CODE REVIEW

**Comment by DavidIQ** [comment]
Your commit message is too long and is why the build is failing for your pr

**Comment by Rishabh04-02** [comment]
Thanks @DavidIQ  i'll correct it.

**Comment by Rishabh04-02** [comment]
@DavidIQ what should i do now?

**Comment by DavidIQ** [comment]
You still have the original commit message, which is too long, and now you also a second line in your commit message that causes the build to fail as well. You needed to edit your original commit message and force push to your branch, not add a second one while leaving the original bad commit intact. Please read the documentation for complete information on proper commit messages:
https://area51.phpbb.com/docs/dev/31x/development/git.html#commit-messages

You will probably want to squash your commits here and correct the commit message.

**Pull request closed without merging**
