### PR TITLE
[ticket/13782] Rename classes that use reserved PHP7 keywords

### PR DESCRIPTION
**Pull request by marc1706**
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13782

### CODE REVIEW

**Comment by timriker** [comment]
Will this change or a similar one get merged into 3.1.x?

**Comment by marc1706** [comment]
It will not as phpBB 3.1.x would require adding feature changes like the new BBCode parser. That's what phpBB 3.2.x is for that is currently in its RC stage.

**Comment by timriker** [comment]
copying phpbb/cache/driver/null.php to phpbb/cache/driver/dummy.php with class rename and editing install/install/install_update.php to reference dummy instead of null at least allowed me to get the upgrade run through on php7. Not ready to move my production instance to php 3.2.x but my development node is already running php7. It would be nice to get minimal php7 support in 3.1.x at least to support people migrating in the future.

**Comment by nikitasius** [comment]
i confirm, copy&rename `null.php` in `dummy.php` (with renaming `null` to `dummy` in) and changing `/driver/null` to `/driver/dummy` in `install_convert.php` and `install_install.php` fixed for me this bug on php7 after installation.

**Pull request merged**
