### PR TITLE
[ticket/15679] notifications ucp front-page looks poor due to cp styling inheritance

### PR DESCRIPTION
**Pull request by hanakin**
Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15679

https://tracker.phpbb.com/browse/PHPBB3-15679

### CODE REVIEW

**Comment by 3D-I** [comment]
Have you got a `before/after` visive example to show?

**Comment by hanakin** [comment]
its on the ticket. its only an issue with 3.0 by the way due to the notification dropdown refactor

**Comment by Nicofuma** [comment]
could you add a before/after screenshot?

**Comment by hanakin** [comment]
before 
screenshot 2018-06-03 18 40 04

after
screenshot 2018-06-03 19 55 41

**Comment by Nicofuma** [comment]
ho nice, I didn't realize that was the before/after ^^

**Pull request merged**
