### PR TITLE
[ticket/14615] Fix HTML5 validation errors on avatar deletion

### PR DESCRIPTION
**Pull request by Senky**
[PHPBB3-14615](https://tracker.phpbb.com/browse/PHPBB3-14615)

Empty is default. So why do we default it "0"? Giving it proper default value fixes validation errors as well.

### CODE REVIEW

**Comment by DavidIQ** [comment]
This removes the protection given by casting the input to an int and can lead to more issues elsewhere if the administrator puts something other than a number.  I think this should be taken care of via the two template files by checking if these have a value before setting them as the minvalue.

**Comment by Senky** [comment]
I don't get it. Validation is done in `process_form` method, where I kept input cast to int. `prepare_form` serves only to display the values, so no protection is removed.

**Comment by DavidIQ** [comment]
You're right.  I didn't look at the rest of the file.  My bad.  Why are we even using the request object here then?

**Comment by Senky** [comment]
Good point! According to my inspection, it is used there to ensure that data sent by the user will be displayed again even if form contains errors.

**Comment by DavidIQ** [comment]
Kind of weird we aren't doing the same for email...

**Comment by Senky** [comment]
I agree. Email should be kept as well. However, this is not part of this ticket. Should I create a new ticket so that we do not forget about it?

**Pull request merged**
