### PR TITLE
[ticket/15374] Add core event to modify page title in viewforum.php

### PR DESCRIPTION
**Pull request by rxu**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

<a href="https://tracker.phpbb.com/browse/PHPBB3-15374">PHPBB3-15374</a>.

### CODE REVIEW

**Comment by rxu** [comment]
!set Event

**Comment by DavidIQ** [comment]
`core.page_header` already exists in the `page_header` function which should allow you to do this already. Any reason we need to do it specifically on viewforum.php?

**Comment by rxu** [comment]
Yes, but if you use ```core.page_header```, the listener will be called for any page call and not for ```viewforum.php``` only. Having this event, you can save unnecessary listener calls.
Also, there're similar events in other places, f.e. ```core.index_modify_page_title```,  ```core.viewtopic_modify_page_title```.

**Comment by rxu** [comment]
To add, there're no specific variables in that event, like '''start``` for pagination, ```forum_id``` or```forum_data``` which may be needed to generate the title :)

**Comment by DavidIQ** [comment]
Other than the forum_data, forum_id and start variables would be retrievable from the querystring 😝  If we've already propagated events for such a thing to other areas then I guess a precedent/pattern has already been set so... 🤷‍♂️

**Comment by rxu** [comment]
Well, let's say the event can be also useful not only for the page title but for other purposes too, as currently the 1st "root" event in ```viewforum.php``` (the one isn't wrapped by any conditionals) is only around line 428 😛

**Pull request merged**
