### PR TITLE
[Ticket/14038] Jumpbox improvements

### PR DESCRIPTION
**Pull request by hanakin**
Provide some visualization back to the jumpbox

Tracker: https://tracker.phpbb.com/browse/PHPBB3-14038

PHPBB3-14038

### CODE REVIEW

**Comment by hanakin** [comment]
!set Styles

**Comment by hanakin** [comment]
@Louis7777 & @cyberalien can you please review this

**Comment by Zoddo** [comment]
`PHPBB3-14038` is missing at the end of commit message :)

**Comment by cyberalien** [comment]
I'm not sure about this. It would be logical to highlight categories, but this code highlights root level elements regardless of their type.

In phpBB it is possible to setup forums without category. With this change those forums will be bold that looks rather ugly:

untitled-1

I think better solution would be to:
1. Highlight only categories
2. Replace |-- for last forum with └

Rough draft:
untitled-2

**Comment by hanakin** [comment]
so you are not wanting to highlight root if no subs? Do not think that is possible given current function for jump-box

**Comment by cyberalien** [comment]
Yes. It would require some fiddling with php code

**Comment by hanakin** [comment]
not sure I want to go messing with that this late in the game

**Comment by Louis7777** [comment]
Looks fine to me. I agree with cyberalien's second suggestion, if it can be done.

**Comment by hanakin** [comment]
figured it out post changes in a few

**Comment by hanakin** [comment]
thoughts? https://www.dropbox.com/s/ww2zparsif0pgc8/Screenshot%202015-08-30%2018.31.51.png?dl=0

**Comment by cyberalien** [comment]
Looks awesome. Maybe tone down indent a bit for first level?

**Comment by hanakin** [comment]
That I am unable to control based on how the levels work in the php it just returns tru or false if sub. The space is just generated in the template loop compound with spacers

**Comment by hanakin** [comment]
can pull it off but it requires using empty span tags as spacers

**Comment by hanakin** [comment]
@cyberalien if you have no issues with the use of the spans then this is pretty much good to go.

**Comment by cyberalien** [comment]
This looks great.

However arrow color doesn't match the rest of links. Maybe keep white background for forum links? Also I suggest to keep same hover color as in notifications dropdown for consistency.

Try this css:

	.jumpbox .dropdown li {
		border-top-color: #ccc;
	}

	.jumpbox .dropdown li.jumpbox-cat-link, .jumpbox .dropdown li.jumpbox-cat-link + li {
		border-top-color: #0076B1;
	}

	.jumpbox .dropdown li.jumpbox-cat-link:hover, .jumpbox .dropdown li.jumpbox-cat-link:hover + li {
		border-top-color: #12A3EB;
	}

	.jumpbox li.jumpbox-cat-link a {
		background-color: #0076b1;
		color: #FFFFFF;
	}

	.jumpbox li:hover a {
		background-color: #cfe1f6;
	}

	.jumpbox li.jumpbox-cat-link:hover a { 
		background-color: #12A3EB;
		color: #FFFFFF;
	}

and jumpbox.html:

	
		<li class="jumpbox-sub-linkjumpbox-cat-linkjumpbox-forum-link"><a href="{jumpbox_forums.LINK}"><span class="spacer"></span> <span> &#8627; &nbsp; {jumpbox_forums.FORUM_NAME}</span></a></li>

**Comment by hanakin** [comment]
FYI the notification hover color is currently not a valid color. https://github.com/phpbb/phpbb/pull/3867 currently its #CFE1F6 which is not a standard color for hovers #F1F8FF is a valid color for the UI.

hows it look now

**Comment by cyberalien** [comment]
Looks good! I think this is ready for merge.

**Comment by hanakin** [comment]
@Nicofuma ^^^^

**Comment by Nicofuma** [comment]
that's really nice. thank you

**Pull request merged**
