### PR TITLE
[ticket/16113] Add core.mcp_topic_modify_sql_ary

### PR DESCRIPTION
**Pull request by dark-1**
PHPBB3-16113

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16113

### CODE REVIEW

**Comment by dark-1** [comment]
!set Event

**Comment by 3D-I** [comment]
I will check this one tomorrow, looks a bit strange a a first glance. Did you try this code as it is?

**Comment by dark-1** [comment]
> I will check this one tomorrow, looks a bit strange a a first glance. Did you try this code as it is?

What's wrong do you think??? Some pointers.... please... @3D-I ???

**Comment by 3D-I** [comment]
Not sure, I could be wrong. Let me see this one again tomorrow.

**Comment by dark-1** [comment]
> Not sure, I could be wrong. Let me see this one again tomorrow.

Ok... 😄

**Comment by dark-1** [comment]
> I will check this one tomorrow, looks a bit strange a a first glance. Did you try this code as it is?

> Not sure, I could be wrong. Let me see this one again tomorrow.

I just checked...
The code works as expected.
Also hooking an extension to it also works as expected.

Still if you say something is wrong then let me know.

Best Regards 👍

**Comment by 3D-I** [comment]
I'd replace this lines though

```
	$sql = $db->sql_build_query('SELECT', $sql_ary);
	unset($sql_ary);

	$result = $db->sql_query_limit($sql, $posts_per_page, $start);
```

with

```
	$result = $db->sql_query_limit($db->sql_build_query('SELECT', $sql_ary), $posts_per_page, $start);
```

it's up to you if you want to add some existing variables to the array.

**Comment by dark-1** [comment]
> I'd replace this lines though (on the fly)
> 
> ```
> 	$sql = $db->sql_build_query('SELECT', $sql_ary);
> 	unset($sql_ary);
> 
> 	$result = $db->sql_query_limit($sql, $posts_per_page, $start);
> ```
> 
> with
> 
> ```
> 	$result = $db->sql_query_limit($db->sql_build_query('SELECT', $sql_ary), $posts_per_page, $start);
> ```
> 
> To add, it's up to you if you want to add some existing variables to the array.

I had done that because , i have seen it done in many places in phpBB core code.
Also it's better for readability of code , especially to newbees...

Best regards 👍

**Pull request merged**
