### PR TITLE
[ticket/16496] Fix html special chars in custom BBcode help line

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16496

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16496

### CODE REVIEW

**Comment by 3D-I** [comment]
immagine


immagine

**Comment by marc1706** [comment]
Somehow your example does not work as displayed above:
image

**Comment by 3D-I** [comment]
What commit are you using?

**Comment by marc1706** [comment]
Latest in this PR. :)

**Comment by 3D-I** [comment]
I guess I was right then, wait pls.

**Comment by 3D-I** [comment]
Data's stored as in

immagine


In the database, thus we need to decode it.

**Comment by kasimi** [comment]
1. BBCode help text entered in the ACP: `Same effect as > or < "HTML tags"`
2. The value stored in the database (`htmlspecialchars()` applied by the `type_cast_helper`): `Same effect as &gt; or &lt; &quot;HTML tags&quot;`
3. `htmlspecialchars_decode()` applied, as currently proposed in this PR: `Same effect as > or < "HTML tags"`. This is the value of the `BBCODE_HELPLINE` template variable.
4. Twig filter `e('html_attr')` applied in both `posting_buttons.html` and `acp_posting_buttons.html`: `Same&#x20;effect&#x20;as&#x20;&gt;&#x20;or&#x20;&lt;&#x20;&quot;HTML&#x20;tags&quot;`

While this works, I see two problems:
* There is unescaped data in the template, while usually all data assigned to the template (usernames, post text etc) has their HTML entities encoded. This means that the `BBCODE_HELPLINE` variable should not be used as is, but needs to be encoded when rendering, not just by the core but also by extension that use it. Again, this is not the default behavior.
* Why decode the entities in step 3 only to encode them again in step 4? It's perfectly fine to use the value in step 2 in an HTML attribute value without further escaping.

Unless I'm missing something, I'd suggest to remove the code from steps 3 and 4.

@marc1706 can you please test again?

**Comment by 3D-I** [comment]
> Unless I'm missing something, I'd suggest to remove the code from steps **3** and **4**.

Unless I am missing something I recall I have already tried it all, I am on phpBB 3.3.x testing here, if that matters. :thinking:

**Comment by kasimi** [comment]
It's the final output.

image

**Comment by 3D-I** [comment]
Never seen here.

**Comment by mrgoldy** [comment]
The usual way this is dealt with is running `htmlspecialchars_decode($var, ENT_COMPAT);` on the requested value when saving it. This ensures the 'correct' value is stored in the database, and not something encoded. Then it's just a matter of displaying and escaping it where it's needed.

**Comment by kasimi** [comment]
Example in the core of a user-controller title attribute:

* Value is assigned to the template without decoding: https://github.com/phpbb/phpbb/blob/release-3.2.9/phpBB/includes/functions_display.php#L624
* Value is rendered without escaping: https://github.com/phpbb/phpbb/blob/release-3.2.9/phpBB/styles/prosilver/template/forumlist_body.html#L96

**Comment by 3D-I** [comment]
@kasimi Do you confirm this commit is right then?

https://github.com/phpbb/phpbb/pull/5990/commits/13914b91df40df99d826036a2a05f4f8653122cd

@marc1706 said it hasn't worked.

By my side both are working so whatever you decide is ok.

**Comment by marc1706** [comment]
Looks good now.

**Pull request merged**
