### PR TITLE
[ticket/14264] Don't use constants as return values

### PR DESCRIPTION
**Pull request by Elsensee**
This will prevent BC breaking in the future if we decide to get rid of constants.

[PHPBB3-14264](https://tracker.phpbb.com/browse/PHPBB3-14264)

### CODE REVIEW

**Comment by prototech** [comment]
Not all of the core tables are defined in tables.yml, including some of the ones that you use here. They should all be defined in a separate PR.

**Comment by Elsensee** [comment]
All tables are defined in #4011 so I'll continue working on this PR when the other is merged.

**Comment by bantu** [comment]
#4011 was merged.

**Comment by Elsensee** [comment]
Thank you, I've rebased it. :)

**Comment by bantu** [comment]
Still failing.

`tests/text_reparser/plugins/test_row_based_plugin.php:			FROM ' . $reparser->get_table_name() . '`

**Comment by Elsensee** [comment]
Yes, fixed that. :)

**Pull request merged**
