### PR TITLE
[ticket/16385] Add lazy-loading attribute to img bbcode

### PR DESCRIPTION
**Pull request by DavidIQ**
PHPBB3-16385

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16385

### CODE REVIEW

**Comment by marc1706** [comment]
This currently results in this warning being logged in the console on Chrome:
```
[Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323
```

**Comment by SiteSplat** [comment]
loading=lazy needs height and width to be specified. IE:

**Comment by DavidIQ** [comment]
> loading=lazy needs height and width to be specified.

Those aren't actually required: https://web.dev/native-lazy-loading/#image-loading

The warning is to prevent a browser reflow bug that happens in Chromium browsers. However I might have an idea on how to apply these so Chrome browsers don't complain.

**Comment by hanakin** [comment]
Closing this for a jquery alternative

**Pull request closed without merging**
