### PR TITLE
[ticket/12578] Lazy-load template service

### PR DESCRIPTION
**Pull request by senky**
PHPBB3-12578

Checklist:

- [ ] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-12578

### CODE REVIEW

**Comment by senky** [comment]
Btw I think pretty much every service should be lazy-loaded. Even `@user` isn't used on every request. What do you think, @phpbb/development-team?

**Comment by Elsensee** [comment]
Well, are there downsides to this?

**Comment by Nicofuma** [comment]
complexity and complex bugs, a long time ago I think I tried to make everything lazy and it was a bad idea. But it was a long time ago.

Also it is not always worth it (especially when the constructor does nothing)

**Comment by Elsensee** [comment]
Yeah, it probably isn't worth it. Also, the proxy service that is instantiated there adds something to the memory footprint so it's rather bad than good?

Except of course we instantiate objects in the constructor of an service that we really don't need.. Then it might be worth it but I'm not sure.

**Comment by senky** [comment]
Generally, it's a good idea. Most of the requests don't use even half of the services that are initiated. But as @Nicofuma pointed out, it's somehow buggy and the proxy doesn't behave like intended. Or rather it doesn't work at all, it won't expose the required service upon call. So it's a good idea that would reduce the server resources but for the cost of the huge changes to the core.

**Pull request closed without merging**
