### PR TITLE
[ticket/11742] Remove tabs-to-space conversion in [code]

### PR DESCRIPTION
**Pull request by s9e**
PHPBB3-11742

### CODE REVIEW

**Comment by Nicofuma** [comment]
tests fail

**Comment by s9e** [comment]
I've updated the tests to reflect the change in the default `code` BBCode.

**Comment by Nicofuma** [comment]
it's still wip?

**Comment by s9e** [comment]
It wasn't, but I've just tested on my local board and it still needs work. There must be some CSS that prevents `<pre>` from preserving whitespace.

**Comment by Elsensee** [comment]
what about `<code style="white-space: pre;">`?

**Pull request closed without merging**
