### PR TITLE
[ticket/15202] To disable, an extension must be enabled

### PR DESCRIPTION
**Pull request by javiexin**
PHPBB3-15202

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-15202

### CODE REVIEW

**Comment by javiexin** [comment]
Test failure is unrelated :) : timeout on file download.

**Comment by javiexin** [comment]
Error was introduced here: https://github.com/phpbb/phpbb/pull/4698/commits/2e3d90e05b7b08f6df89b9e3a98b1716d52cf340#diff-fed83124ff227940ce169372861d50f3R266

**Comment by DavidIQ** [comment]
Really? Because all I did was restart the test. ;)

**Comment by javiexin** [comment]
Jajajaja, thanks a lot David. I noticed someone had restarted the build, but didn't know Who!
The other comment was just to point out that it was me that introduced the error in the first place :(

**Pull request merged**
