### PR TITLE
[ticket/14129] Cache custom extensions autoloaders

### PR DESCRIPTION
**Pull request by rxu**
<a href="https://tracker.phpbb.com/browse/PHPBB3-14129">PHPBB3-14129</a>.

### CODE REVIEW

**Comment by rxu** [comment]
!set WIP

**Comment by rxu** [comment]
!unset WIP

**Comment by Elsensee** [comment]
Is this really necessary? Does this really increase the performance if many extensions are installed?

**Comment by rxu** [comment]
Yes, it is. Without caching, it takes about 10% of page generation time as per my measurements.

**Comment by Nicofuma** [comment]
I don't like hacking the cache like that.... instead I think I'd prefer to write a cache/<env>/autoload.php file which will load all these autoloaders:

```
<?php

require '<root>/ext/my/ext1/vendor/autoload.php'
....
```

This file will be written (and then loaded) here instead of loading the individual files https://github.com/phpbb/phpbb/blob/master/phpBB/phpbb/di/container_builder.php#L380-L385 and also loaded here https://github.com/phpbb/phpbb/blob/master/phpBB/phpbb/di/container_builder.php#L132 if `$this->use_extensions` is `true`. I think I'd prefer something like that.

**Comment by rxu** [comment]
Anyway, I guess this PR should be closed as it's made against 3.1.x.

**Comment by Nicofuma** [comment]
didn't notice that :p

for 3.1... I don't know. @nickvergessen what do you think? And for 3.2, you know what I think ^^

**Comment by rxu** [comment]
!set WIP

**Comment by marc1706** [comment]
Performance "hack"/improvement == new feature --> 3.2

**Comment by rxu** [comment]
I have <a href="https://gist.github.com/rxu/af652c7ffbb79c05e9dc">another approach</a> for this, probably hackish again (for 3.1 only though, as in 3.2 the relevant code has been changed fully).

**Comment by marc1706** [comment]
@nickvergessen your call I guess

**Comment by Nicofuma** [comment]
replaced by https://github.com/phpbb/phpbb/pull/4142

**Comment by rxu** [comment]
Actually #4142 doesn't replace this PR as the current one was for 3.1 :wink:

**Pull request closed without merging**
