### PR TITLE
adds to Notepad

### PR DESCRIPTION
**Pull request by Gilbert-Mwimba**
Here is my contribution

Checklist:

- [ ] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-12345

### CODE REVIEW

**Comment by DavidIQ** [comment]
Not sure what this is but it doesn't go here.

**Comment by Gilbert-Mwimba** [comment]
This is just a test of my first contribution

**Comment by Gilbert-Mwimba** [comment]
Hi there,
Just testing how to contribute to a first project. Any help will be
appreciated

Thanks

**Comment by DavidIQ** [comment]
All development contribution information for our project can be found on our Area 51 site: https://area51.phpbb.com/

**Pull request closed without merging**
