### PR TITLE
[ticket/13851] Fix ignore flood limit check

### PR DESCRIPTION
**Pull request by RMcGirr83**
[PHPBB3-13851](https://tracker.phpbb.com/browse/PHPBB3-13851)

### CODE REVIEW

**Comment by RMcGirr83** [comment]
https://tracker.phpbb.com/browse/PHPBB3-13851

**Comment by Nicofuma** [comment]
This is not an easy question.

The problem is that we have 2 permissions (one user based and one forum based) and that we have only 2 status for the permissions: yes/no and the default value for f_ignoreflood is no...
Therefore there is some case to decide:

u_ignoreflood | f_ignoreflood | result
------------------|--------------------|--------
yes|yes|yes
yes|no| ?
no|no|no
no|yes| ?

With this PR the result is the following (and as you see, f_ignoreflood can be removed):
u_ignoreflood | f_ignore_flood | result
------------------|--------------------|--------
yes|yes|yes
yes|no| yes
no|no|no
no|yes| no

@DavidIQ

**Comment by RMcGirr83** [comment]
@Nicofuma I don't agree with this logic

u_ignoreflood | f_ignoreflood | result
----------------- | ----------------- | -------
no | yes | no

believe it would be instead?

u_ignoreflood | f_ignoreflood | result
----------------- | ----------------- | -------
no | yes | yes

In fact I did test it by setting groups can ignore flood permission to no and forum group permission to yes and it seems to work as I state above.

**Comment by Nicofuma** [comment]
right

**Comment by Nicofuma** [comment]
fine with me this way

**Comment by marc1706** [comment]
Fine with me, too.

**Comment by DavidIQ** [comment]
Since I was tagged, although a little late in responding: yes the user permission should take precedence over the forum permission, as everyone else has stated.

**Comment by Nicofuma** [comment]
thanks

**Pull request merged**
