### PR TITLE
[ticket/13944] Fix the test framework compatibility with Oracle

### PR DESCRIPTION
**Pull request by Nicofuma**
https://tracker.phpbb.com/browse/PHPBB3-13944

PHPBB3-13944

### CODE REVIEW

**Comment by bantu** [comment]
@Nicofuma I agree with Noxwizard here. See https://tracker.phpbb.com/browse/PHPBB3-13944?focusedCommentId=56436&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-56436 It seems like you have been missing that tests on Oracle just fail because the implementations don't work on there. There is (mostly) nothing wrong with the test framework.

**Comment by bantu** [comment]
Maybe don't push the Oracle status then?

**Comment by bantu** [comment]
Maybe we should just drop Oracle support to make this official.

**Comment by Nicofuma** [comment]
I'm not, actually there is 2 things with Oracle:
1) The tests are failing
2) It doesn't always work because only one DSN is supported and we don't handle `custom_dsn` and also because we try to delete all the tables and not only the tables related to phpBB

My fix isn't correct yet be it will be later.
And for the status, I have disable the Oracle Job and I think we can add a plan for it (like we do with MsSQL)

**Comment by Noxwizard** [comment]
Can you expand on 2)? I have yet to see tests fail because of the DSN or because of errors deleting system tables.

**Comment by Nicofuma** [comment]
https://bamboo.phpbb.com/browse/PHPBB3-PRDOCKER-UTP6O-44/log for the DSN
and for the system tables I don't have the logs on Bamboo because I ran the tests locally but the error was:
>   [SQLSTATE[HY000]: General error: 4098 OCIStmtExecute: ORA-04098: trigger 'SYSTEM.T_PHPBB_USERS' is invalid and failed re-validation
>  (/usr/src/php/ext/pdo_oci/oci_statement.c:148)]
> 
> /data/tests/test_framework/phpbb_database_test_case.php:115
> /data/tests/auth/provider_apache_test.php:25

**Comment by Noxwizard** [comment]
None of those indicate an issue with the DSN format. If I run the entire suite, I get an output similar to Bamboo's. If I run them in filtered groups, I get normal SQL errors (e.g. invalid hex number) instead of TNS errors. This seems more related to the configuration of the database instance itself, or we need to look into connecting directly and bypass TNS.

I have not seen the error trying to drop the trigger in my runs.

**Comment by Nicofuma** [comment]
I took the wrong error for the second point...
For the DNS it may be related to the install yes but the DNS I introduce is the one documented in the PHP doc. (Btw,  my install is a standard oracle XE install but running on a different host)

**Comment by Nicofuma** [comment]
About the system tables, there isn't any error actually I saw that by dumping the table list before and after the clean

**Comment by CHItA** [comment]
Added pending closure as there is no activity on this ticket since 2015. Also we should rewrite the test framework at some point.

**Pull request closed without merging**
