### PR TITLE
[ticket/16981] Fix HTML-encoded emojis in email subject line

### PR DESCRIPTION
**Pull request by lionel-rowe**
Fixes [PHPBB-16981 — HTML-encoded emojis `&#128396;️ &#128208;` in email subject line](https://tracker.phpbb.com/browse/PHPBB3-16981)

This fix is a straight find-and-replace of all instances of `htmlspecialchars_decode` with `html_entity_decode` (excluding `phpBB/install/convert` and `phpBB/install/convertors`).

Background: For compatibility with buggy legacy MySQL encodings (`utf8mb3` and `utf8`, the latter of which is an alias for the former rather than true UTF-8), emojis and other non-BMP Unicode characters are being stored in many places as the equivalent HTML entities, rather than as raw UTF-8.

Due to this, `htmlspecialchars_decode` is insufficient to normalize strings into a non-HTML format, because it converts `&amp;`, `&quot;`, `&#039;`, `&lt;`, `&gt;` but nothing else.

Replacing a few specific instances of `htmlspecialchars_decode` would fix the observed bug, but leave the door wide open to a class of related bugs popping up in other places (different email templates, different email fields, forum names, usernames, etc.)

Blanket replacement of `htmlspecialchars_decode` with `html_entity_decode` is safe, because `htmlspecialchars_decode` is only ever used in instances where the result is expected to be non-HTML-encoded, and the replacement has no effect where the source text contains no emoji HTML entities.

With that said, it'd be good to get more eyes on this, in case there are some corner cases I haven't thought about.

A [performance comparison between the two methods](https://replit.com/@lionel_rowe/html-entity-decode-perf#main.php) generally gives near-identical results. Typical results as follows:

```
htmlspecialchars_decode:    0.9544191360s (1,000,000 iterations)
html_entity_decode:         0.9495959282s (1,000,000 iterations)
```

---

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16981

### CODE REVIEW

**Comment by 3D-I** [comment]
No need to change 55 files for to fix `HTML-encoded emojis in email subject`,  moreover ... as I said in the tracker, your isue is not replicable.

**Comment by marc1706** [comment]
I am able to reproduce this issue, but I would also go for a different approach. Instead of applying this to all places where we do htmlspecialchars_decode, I'd rather opt for applying it where needed right now. In this case I'd say let's apply it to the email variables in the notification types. You could even just use ut8_decode_ncr().

**Comment by lionel-rowe** [comment]
> @3D-I as I said in the tracker, your issue is not replicable by my side.

Did you try the replication steps I specified when I replied to that tracker comment more than a week ago? You never responded.

> @marc1706 Instead of applying this to all places where we do htmlspecialchars_decode, I'd rather opt for applying it where needed right now. In this case I'd say let's apply it to the email variables in the notification types. You could even just use `ut8_decode_ncr()`.

Per my comments in the PR:

> Replacing a few specific instances of `htmlspecialchars_decode` would fix the observed bug, but leave the door wide open to a class of related bugs popping up in other places (different email templates, different email fields, forum names, usernames, etc.)
>
> Blanket replacement of `htmlspecialchars_decode` with `html_entity_decode` is safe, because `htmlspecialchars_decode` is only ever used in instances where the result is expected to be non-HTML-encoded, and the replacement has no effect where the source text contains no emoji HTML entities.
>
> A [performance comparison between the two methods](https://replit.com/@lionel_rowe/html-entity-decode-perf#main.php) generally gives near-identical results.

Fixing the problem in 1 place but not others, even with no bugs elsewhere yet observed, simply means it is likely to recur in other places. Given that replacing all instances with `html_entity_decode` has no effect on unaffected strings, not even a performance effect, what's the argument in favor of the whack-a-mole approach?

**Comment by 3D-I** [comment]
I've had my say.

**Comment by lionel-rowe** [comment]
How do I move this forward? I'm willing to change it to the ad-hoc version if that's the only way it'll get approved, though I've laid out my case for why that's the wrong approach and would prefer to hear what the counterarguments are first.

**Comment by 3D-I** [comment]
Use `ut8_decode_ncr()` in the right places. Forget all the rest.

**Comment by lionel-rowe** [comment]
> Use `ut8_decode_ncr()`
> ( which is the HTML counterpart of `utf8_encode_ucr()` )
> in the right places.
>
> Forget all the rest.

OK, so what's the reasoned argument for why that's the best approach? What are the benefits of that approach, and what are the drawbacks of the one I'm proposing?

**Comment by 3D-I** [comment]
I had my say. /me back to my duties.

**Review by marc1706 — APPROVED** [review]

**Comment by marc1706** [comment]
> > @3D-I as I said in the tracker, your issue is not replicable by my side.
> 
> Did you try the replication steps I specified when I replied to that tracker comment more than a week ago? You never responded.
> 
> > @marc1706 Instead of applying this to all places where we do htmlspecialchars_decode, I'd rather opt for applying it where needed right now. In this case I'd say let's apply it to the email variables in the notification types. You could even just use `ut8_decode_ncr()`.
> 
> Per my comments in the PR:
> 
> > Replacing a few specific instances of `htmlspecialchars_decode` would fix the observed bug, but leave the door wide open to a class of related bugs popping up in other places (different email templates, different email fields, forum names, usernames, etc.)
> > Blanket replacement of `htmlspecialchars_decode` with `html_entity_decode` is safe, because `htmlspecialchars_decode` is only ever used in instances where the result is expected to be non-HTML-encoded, and the replacement has no effect where the source text contains no emoji HTML entities.
> > A [performance comparison between the two methods](https://replit.com/@lionel_rowe/html-entity-decode-perf#main.php) generally gives near-identical results.
> 
> Fixing the problem in 1 place but not others, even with no bugs elsewhere yet observed, simply means it is likely to recur in other places. Given that replacing all instances with `html_entity_decode` has no effect on unaffected strings, not even a performance effect, what's the argument in favor of the ad-hoc approach?

I have checked the code and deemed the changes to be fine.

**Pull request merged**
