### PR TITLE
[ticket/15156] Simplify user online notification

### PR DESCRIPTION
**Pull request by hanakin**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

PHPBB3-15155
https://tracker.phpbb.com/browse/PHPBB3-15155

### CODE REVIEW

**Comment by hanakin** [comment]
!set Styles

**Comment by marc1706** [comment]
Can you please add screenshots when e.g. adding something to the style so we can get an idea of what it looks like and also confirm this during testing?

**Comment by hanakin** [comment]
yeah plan too but twig errors att?

**Comment by hanakin** [comment]
Here are some screens based on inspector editing on area51 for these changes.

screenshot 2017-04-17 19 49 24
screenshot 2017-04-17 19 51 56
screenshot 2017-04-17 20 00 15
screenshot 2017-04-18 07 31 02

**Comment by hanakin** [comment]
!set WIP

**Comment by hanakin** [comment]
!unset WIP

**Comment by hanakin** [comment]
@marc1706 tests were failing due to the removal of the `en` folder contents...not sure what this had to do with the acp?

**Comment by hanakin** [comment]
ok here are all the screens

screen shot 2017-04-20 at 6 47 00 am
screenshot 2017-04-20 07 01 03 3
screenshot 2017-04-20 07 01 03 2
screenshot 2017-04-20 07 01 03

**Comment by Persian-phpBB** [comment]
I think the username and rank must be in center. just like avatar

**Comment by hanakin** [comment]
@Persian-phpBB outside the scope of this pr as everything else if left aligned

**Comment by hanakin** [comment]
!unset WIP

**Comment by marc1706** [comment]
I somehow have the old user online gif still showing up:
image

**Comment by hanakin** [comment]
@marc related to the error with acp hopefully this fixes it and allows tests to pass

**Comment by vinny** [comment]
@hanakin why keep `styles/prosilver/theme/en/stylesheet.css`?

**Comment by hanakin** [comment]
because for some reason the acp is requireing it and im not sure how to fix the error

**Pull request merged**
