### PR TITLE
[ticket/15616] Remove jumpbox from login_forum.html

### PR DESCRIPTION
**Pull request by senky**
PHPBB3-15616

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15616

### CODE REVIEW

**Comment by hanakin** [comment]
@Elsensee The question is really do we need a jumpbox from the login form? login auto redirects to index anyway...Do guests need to jump around?

**Comment by Elsensee** [comment]
@hanakin Clearly not. I don't even know if the jumpbox is used that often in general...
But to me, this one is about consistency.

**Comment by senky** [comment]
@hanakin but this isn't general login box. This is the page where you type a password for password-protected forum. You are redirected to the forum afterwards. So maybe it makes sense.

**Comment by hanakin** [comment]
Wait this sounds like a larger stupid issue then. Essentially jump box is not callable outside of the individual pages which is just stupid. This should be a 100% agnostic capability. It’s the same issue we currently face with the ucp and mcp not being accessible outside itself

**Comment by Elsensee** [comment]
@senky Can you reword the commit message, then this is good to go.

@hanakin I see why this was done this way. In earlier version we had our shitty own template engine which was not very capable of doing stuff, so in order to save resources and avoid querying all accessible forums on every page, there had to be a special function call.
Now, with twig, we could technically just remove that function call. We could just do `{{ jumpbox() }}` and then the calculation would run right there and no extra call in the code is necessary.

**Pull request merged**
