### PR TITLE
[ticket/15444] Merge duplicate BBCodes via a migration

### PR DESCRIPTION
**Pull request by JoshyPHP**
I expect it to be working but I haven't tested it yet. Depends on #5053

PHPBB3-15444

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15444

### CODE REVIEW

**Comment by JoshyPHP** [comment]
!set wip

**Comment by gooof** [comment]
It could work that way:
\phpbb\db\migration\data\v320\bbcode_merge_duplicates.php
```php
<?php
/**
 *
 * This file is part of the phpBB Forum Software package.
 *
 * @copyright (c) phpBB Limited <https://www.phpbb.com>
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 * For full copyright and license information, please see
 * the docs/CREDITS.txt file.
 *
 */

namespace phpbb\db\migration\data\v320;

use phpbb\textreparser\bbcode_merger;

class bbcode_merge_duplicates extends \phpbb\db\migration\migration
{
	static public function depends_on()
	{
		return array(
			'\phpbb\db\migration\data\v320\allowed_schemes_links',
		);
	}

	public function effectively_installed()
	{
		return version_compare($this->config['version'], '3.2.2', '>=');
	}

	public function update_data()
	{
		return array(
			array('custom', array(array($this, 'merge_bbcodes'))),
		);
	}

	public function merge_bbcodes($resume_data)
	{
		$bbcode_merger = $this->container->get('text_formatter.s9e.bbcode_merger');

		$merged = $bbcode_merger->merge_bbcodes(	...	);

		// SQL
		$sql = 'UPDATE ' . $this->table_prefix . "bbcodes
			SET bbcode = {$merged[0]}
			WHERE " . $xy;
		$this->db->sql_query($sql);

		if ($complete)
		{
			return true;
		}
	}
}
```

**Comment by JoshyPHP** [comment]
@marc1706 I'd really like this PR to ship with 3.2.2 because it would halve the number of topics I have to reply to on phpBB.com's Support forums. Can you give me a heads up a few days before your merge window closes? Thanks.

**Comment by marc1706** [comment]
I noticed you still have the WIP label on this which is why I hadn't considered it for a merge yet. Is it ready for review now?

**Comment by JoshyPHP** [comment]
I haven't tested it yet apart from running the migration on a default installation. Is there a way to test migrations automatically or does it have to be done by hand?

Also, note that this PR depends on #5053 which depends on #5046.

**Comment by rxu** [comment]
@JoshyPHP 
As the migration should be fixed anyway... should it merge similar but different case BBCodes? Like ```CODE``` and ```code=``` for example. Currently it doesn't.

**Comment by JoshyPHP** [comment]
@rxu It should. I don't know whether it does but if it doesn't, it would be a good idea to fix it and rerun the migration on next version.

**Comment by rxu** [comment]
Well, it can't wait until the next version because of fastal error https://tracker.phpbb.com/browse/PHPBB3-15502
I'm gonna fix it altogether then 😃 
Should the resulting BBCode be uppercased or lowercased?

**Comment by JoshyPHP** [comment]
No preference as far as I'm concerned. BBCode names are normalized to uppercase in s9e\TextFormatter so the case doesn't matter in the input.

You may want to leave the case as-is and use a case-insensitive comparison.

**Comment by rxu** [comment]
> You may want to leave the case as-is and use a case-insensitive comparison.

Well, as far as one of BBCodes should be deleted, The opper|lower case should be chosen anyway.
Ok, I got the point, thanks.

**Comment by JoshyPHP** [comment]
Just looked at the code, it's [not an a string comparison](https://github.com/phpbb/phpbb/blob/master/phpBB/phpbb/db/migration/data/v32x/merge_duplicate_bbcodes.php#L34). I would probably normalize it to lowercase on the offchance there a dotted I in a Turkish locale that doesn't get case-folded the right way, or something contrived like that.

**Comment by rxu** [comment]
I see. Is ```strtolower()``` enough then or should it be ```utf8_strtolower()``` (which is just a wrapper for ```mb_strtolower()```)?

**Comment by JoshyPHP** [comment]
Come to think of it, the library will only accept A-Z letters for BBCode names so it doesn't matter either way.

**Comment by rxu** [comment]
Oh. Then I rather choose ```strtolower()```.

**Comment by rxu** [comment]
@JoshyPHP https://github.com/phpbb/phpbb/pull/5079/files#diff-59ffeb846a6620e1605d8476afbfe103

**Comment by JoshyPHP** [comment]
@rxu That seems fine.

**Pull request merged**
