### PR TITLE
[ticket/13774] Update s9e\TextFormatter

### PR DESCRIPTION
**Pull request by s9e**
For context:

 * https://github.com/phpbb/phpbb/pull/3541#issuecomment-95196634
 * https://github.com/s9e/TextFormatter/commit/559f3c4def03e5fbbf5301198ccd69c91d902659

### CODE REVIEW

**Comment by bantu** [comment]
@s9e Which composer command was used to produde this diff?

**Comment by s9e** [comment]
In the phpBB dir:
```bash
../composer.phar update s9e/text-formatter
```

**Comment by bantu** [comment]
Hmm. I am getting a different result. Not sure why. https://gist.github.com/bantu/164bed5766dd37eb7c14

**Comment by s9e** [comment]
I tried deleting my `vendor` folder (in addition to deleting `~/.composer`, which I do semi-frequently) and it did produce a better `composer.lock` without unrelated changes. Strangely, it didn't change the hash in composer.lock. I assumed the hash was based on the installed packages, but evidently it's not.

**Comment by bantu** [comment]
@s9e The hash is not supposed to change. It's md5sum of composer.json.

**Pull request merged**
