### PR TITLE
[ticket/16255] Fix PHP 7.4 deprecation warning

### PR DESCRIPTION
**Pull request by SagePtr**
Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16255

### CODE REVIEW

**Comment by 3D-I** [comment]
Commit message is wrong, should be

```
[ticket/16255] Fix PHP 7.4 deprecation warning

PHPBB3-16255
```

**Comment by SagePtr** [comment]
> Commit message is wrong, should be
> 
> ```
> [ticket/16255] Fix PHP 7.4 deprecation warning
> 
> PHPBB3-16255
> ```
> 
> https://area51.phpbb.com/docs/dev/3.2.x/development/git.html#commit-messages

amended and pushed the change

**Comment by 3D-I** [comment]
Looks good.

**Comment by rxu** [comment]
Currently used versions of `Phing` and `squizlabs\php_codesniffer` use curly braces syntax as well. If they're used for release versions, we should update them to the latest where the issue has been fixed. @marc1706

**Comment by marc1706** [comment]
@rxu while I generally agree with this, those two dependencies only affect the dev setup and users that enable the display of deprecation notices. Additionally, we're currently using the latest versions of both of these. This should however not hold us back with releasing 3.3.

**Comment by marc1706** [comment]
@SagePtr Thanks for your PR, good job.

**Pull request merged**
