### PR TITLE
Add dropdown for smiles

### PR DESCRIPTION
**Pull request by YasaraPeiris**
Checklist:

    Correct branch: master for new features
    Tests pass
    Code follows coding guidelines: master
    Commit follows commit message format

PHPBB3-15109

https://tracker.phpbb.com/browse/PHPBB3-15109

In here I have added a smiley dropdown toeditor to save some screen
space. Mainly I have modified posting_editor.html file to remove the
existing side smilebox container. Then I have added a new file called
smiley_dropdown.html display smiley dropdown. This newly created file is
included to the posting_editor.html. After that I did necessarry
modifications to styles in colour.css, forms.css and common.css. All the
modifications are commented for easy identification.

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Thanks but the commit message needs to be updated. See some of the other PRs for examples, and here is the documentation:
https://area51.phpbb.com/docs/dev/31x/development/git.html#commit-messages

**Comment by hanakin** [comment]
as @VSEphpbb pointed out you still have not gotten the commit msg correct and keep changing the default pr msg but close enough on that. I will look over the code though when i get some time but there are going to be a lot of linting errors you need to fix...pls run `npm install` in your local repo root folder and then run `stylelint "phpBB/styles/prosilver/theme/*.css"` if its not already configured to run by default in your editor.

**Comment by YasaraPeiris** [comment]
Dear sir,

I ran the command  npm install in my local repo folder and it was
successful. But when I tried to run the command  stylelint
"phpBB/styles/prosilver/theme/*.css" , it gives me an error saying
"stylelint is not recognized as an internal or external command". Seems
like I'm bothering you too much sir. This is my first attempt and it would
be really grateful if you could help me at the begining. Thank you.




*Yasara Peiris,University of Moratuwa,mobile : +94 710 197 418email   :
 yasarapeiris.13@cse.mrt.ac.lk <yasarapeiris.13@cse.mrt.ac.lk>*

**Comment by VSEphpbb** [comment]
@hanakin side note: if you're expecting users to run npm install on their repo, you should probably add node_modules to the .gitignore. I see in gitignore it ignores node_modules inside phpBB, but in reality the folder is created in the project root.

**Comment by hanakin** [comment]
@VSEphpbb god catch never had an issue as mines global but we will have to update that.

@YasaraPeiris just to confirm you do have the node_modules folder in the project root? and you are running the command in terminal from this folder as well? Also what editor do you use?

**Comment by YasaraPeiris** [comment]
After you asked me I executed the command "npm install" in my local repository. So after that new folder called node_modules has created inside my project folder. But previously there wasn't a folder called node_modules inside my project. 

I'm using Intellij idea ide editor and to install npm I used command in terminal form.

**Comment by VSEphpbb** [comment]
You should ammend your commit and change its message to the required format, then force push it to your remote repository.

**Comment by YasaraPeiris** [comment]
@VSEphpbb changed the commit message to the required format. Thanks for your support.

**Comment by hanakin** [comment]
the commit msg format is still not right it has to be ``[ticket/15109] added a dropdown for smiles`` format is [ticket/#] brief msg... also there are no spaces in the body for the ``PHPBB3-15109``

**Comment by YasaraPeiris** [comment]
[ticket/15109] added a dropdown for smiles.

In here I have added a smiley dropdown toeditor to save some screen
space.
Modified files
posting_editor.html  - To remove existing side smilebox container. Then
included a file called smiley_dropdown.html.
smiley_dropdown.html - New file created to display smiley dropdown.
colour.css, forms.css and common.css - Made necessary modifications to
style sheet. All the modifications are commented for easy identification.

PHPBB3-15109


Can I know whether this format is correct or not?





*Yasara Peiris,University of Moratuwa,mobile : +94 710 197 418email   :
 yasarapeiris.13@cse.mrt.ac.lk <yasarapeiris.13@cse.mrt.ac.lk>*

**Comment by hanakin** [comment]
yes what you have there is fine

**Comment by YasaraPeiris** [comment]
Thank you very much.




*Yasara Peiris,University of Moratuwa,mobile : +94 710 197 418email   :
 yasarapeiris.13@cse.mrt.ac.lk <yasarapeiris.13@cse.mrt.ac.lk>*

**Comment by hanakin** [comment]
you will still need to fix all the linting errors but it also looks like there may be still something wrong with your commit msg, its saying you have some unessecary white space which happens when you copy paste at the end sometimes?

I recommend removing ll of the body redundant text

> In here a smiley dropdown is added to editor to save some screen space.
Modified files
	posting_editor.html - Removed existing side smilebox container.
			      Then included a file called smiley_dropdown.html.
	smiley_dropdown.html -New file created to display smiley dropdown.
	colour.css,forms.css,common.css - Made necessary modifications to
					  stylesheets. All the
					  modifications are
					  commented for easy
					  identification.

all you need in your commit msg is the heading i provide and the footer so in other words

```
[ticket/15109] added a dropdown for smiles.
PHPBB3-15109
```

**Comment by YasaraPeiris** [comment]
Done. 😊




*Yasara Peiris,University of Moratuwa,mobile : +94 710 197 418email   :
 yasarapeiris.13@cse.mrt.ac.lk <yasarapeiris.13@cse.mrt.ac.lk>*

**Comment by hanakin** [comment]
you seem to be using an outdated version of the repo pls rebase before attempting to fix the errors

**Pull request closed without merging**
