### PR TITLE
[ticket/15631] Change <br> to <br />

### PR DESCRIPTION
**Pull request by scootergrisen**
Checklist:

- [ ] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15631

### CODE REVIEW

**Comment by hanakin** [comment]
Not for nothing but the / is an html 4 requirement and not nessecary for html 5

**Comment by DavidIQ** [comment]
Then we just update the documentation. Not sure going backwards in HTML standards is what we want to do. Also think the other tag requirements are dated. Maybe @hanakin should look that over to see.

**Comment by hanakin** [comment]
Update all to be same but html 5 standard as xhtml is a 4 standard and no longer valid so I would say just use <br>

**Comment by scootergrisen** [comment]
I'm fine with using `<br>`.
There is also a single  element using / in this string we could fix:
`	'HELP_BBCODE_IMAGES_BASIC_ANSWER'	=> 'phpBB BBCode incorporates a tag for including images in your posts. Two very important things to remember when using this tag are: many users do not appreciate lots of images being shown in posts and secondly the image you display must already be available on the internet (it cannot exist only on your computer for example, unless you run a webserver!). To display an image you must surround the URL pointing to the image with <strong>[img][/img]</strong> tags. For example:<br /><br /><strong>[img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img]</strong><br /><br />As noted in the URL section above you can wrap an image in a <strong>[url][/url]</strong> tag if you wish, e.g.<br /><br /><strong>[url=https://www.phpbb.com/][img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img][/url]</strong><br /><br />would generate:<br /><br /><a href="https://www.phpbb.com/"></a>',
`

**Comment by hanakin** [comment]
Agree

**Comment by scootergrisen** [comment]
I made https://github.com/phpbb/phpbb/pull/5196 instead.

**Pull request closed without merging**
