### PR TITLE
[ticket/15072] Remove current responsiveness

### PR DESCRIPTION
**Pull request by hanakin**
Checklist:

PHPBB3-15072

Depends on 
https://github.com/phpbb/phpbb/pull/4685
https://github.com/phpbb/phpbb/pull/4686

- [x] Correct branch: master for new features; 3.3
- [ ] Tests pass
- [x] Code follows coding guidelines
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

https://tracker.phpbb.com/browse/PHPBB3-15072

### CODE REVIEW

**Comment by Nicofuma** [comment]
I'm not sure that's something we want to do in prosilver. I already can imagine it breaking all style again and I don't think that's something we want to do.

**Comment by hanakin** [comment]
@Nicofuma the benefits of this will out way the negatives. It will be far simpler to understand and make the changes needed then it currently is as most individuals have no idea how things are accomplished do to the crappy us hacks and use of the giant parser function to handle what should noteably be all CSS work for the majority. It's not actually that much work since i have the reference of the current version to work off for the look and feel. It's just a transposition. It's early on so we can see and compare once I get everything up. If nothing else all the us stuff needs to go.

**Comment by hanakin** [comment]
!set WIP

**Comment by hanakin** [comment]
!set Styles

**Pull request closed without merging**
