### PR TITLE
[ticket/13467] Add a CONTRIBUTING file to the project on Github

### PR DESCRIPTION
**Pull request by Senky**
[PHPBB3-13467](https://tracker.phpbb.com/browse/PHPBB3-13467)

### CODE REVIEW

**Comment by nickvergessen** [comment]
I think this needs to be simpler in the end.
@naderman you planned something on this.

**Comment by bantu** [comment]
Patch is not good as it basically just duplicates README.md content.

**Comment by naderman** [comment]
@bantu Please read the ticket, there is a point to doing that to a degree.
@nickvergessen while we should try to simplify the process, documenting it as is makes sense too.

**Comment by bantu** [comment]
@naderman Don't get it. Let's try this another way: README.md either needs to have CONTRIBUTING removed completely or it needs to link to CONTRIBUTING.md. Otherwise there is duplication.

**Comment by MGaetan89** [comment]
I think adding a link in the `README.md` to `CONTRIBUTING.md` is the best solution.
This way contribution tips are displayed when creating a new PR.

**Comment by bantu** [comment]
@MGaetan89 I agree
@Senky Can you incorporate that please?

**Comment by naderman** [comment]
Personally I think it's good to have this pretty short list available in both places, and not just a link in the README. Duplicating 4 list items to two places that both need to document it, is perfectly fine.

**Comment by Senky** [comment]
So what now?
Personally, I agree with @naderman

**Comment by Nicofuma** [comment]
:thumbsup:

maybe add a link to the coding guidelines?

**Comment by Nicofuma** [comment]
@phpbb/development-team bump

**Comment by Nicofuma** [comment]
By the way, shouldn't it be in olympus too?

**Comment by marc1706** [comment]
:+1: 

I personally don't really care if it is in olympus as the amount of contributions for olympus should be rather low in the coming months and the focus should be more on 3.1 and 3.2.

**Comment by naderman** [comment]
Yeah I don't think it matters, just put this in 3.1.

**Comment by Nicofuma** [comment]
merged

**Pull request closed without merging**
