### PR TITLE
[ticket/14683] Fix typos in email templates.

### PR DESCRIPTION
**Pull request by rxu**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

<a href="https://tracker.phpbb.com/browse/PHPBB3-14683">PHPBB3-14683</a>.

### CODE REVIEW

**Comment by lavigor** [comment]
@rxu, is it a reverse for https://github.com/phpbb/phpbb/pull/1685?
I mean, has it been tested for the username `0`?

phpBB adds the support for `===` and `!==` [here](https://github.com/phpbb/phpbb/tree/3.1.x/phpBB/phpbb/template/twig/node/expression/binary) - there are no typos here.

BTW Twig has `sameas` comparison that [is the equivalent to === in PHP](http://twig.sensiolabs.org/doc/tests/sameas.html).

**Comment by rxu** [comment]
@lavigor I didn't see that PR before, but with ```!==``` comparison the test throws error
> phpbb_email_parsing_test::test_email_parsing
Twig_Error_Syntax: Unexpected token "operator" of value "=" in "newtopic_notify.txt" at line 5

which can be fixed by replacing ```!==``` with ```!=```. I have no idea for now why phpBB parser doesn't help that.

**Comment by rxu** [comment]
@marc1706 ^

**Comment by lavigor** [comment]
@rxu, maybe the test should be updated then?
Because according to the documentation, Twig supports custom operators in extensions.
That is the way used by phpBB [here](https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/phpbb/template/twig/extension.php#L113).

**Comment by rxu** [comment]
Then that has probably something to do with lexer in #4357 again rather than with test.

**Comment by lavigor** [comment]
@rxu, no, it is not related to lexer, because the extension is defined [here](https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/phpbb/template/twig/twig.php#L111-L116).

BTW where is `phpbb_email_parsing_test` defined?
I could not find it in the `tests` directory.

**Comment by rxu** [comment]
See the PR I referred sbove.

**Comment by lavigor** [comment]
Oh, sorry.
But the phpBB extension is not added there indeed.

**Comment by rxu** [comment]
Isn't it added on the twig class initializing?

**Comment by lavigor** [comment]
Yes, the method `$twig->addExtension` is not fired.
The extension is just being added to the phpBB container.

I haven't tested that, but probably we can try something like that:
```php
		$twig_extension = new \phpbb\template\twig\extension($context, $user);
		$context = new \phpbb\template\context();
		$phpbb_container->set('template.twig.extensions.collection', array($twig_extension), phpbb_mock_container_builder::SCOPE_PROTOTYPE);

		$twig = new \phpbb\template\twig\environment(
			$config,
			$filesystem,
			$phpbb_path_helper,
			$cache_path,
			null,
			new \phpbb\template\twig\loader($filesystem, ''),
			array(
				'cache'			=> false,
				'debug'			=> false,
				'auto_reload'	=> true,
				'autoescape'	=> false,
			)
		);
		$this->twig->addExtension($twig_extension);
```

**Comment by rxu** [comment]
The point is that the test uses core methods to parse the email template and doesn't do it on its own. Thus, if the test fails, that means the core template parsing will fail and should be fixed, not the test. Do you get the point? :wink:

**Comment by lavigor** [comment]
@rxu, core extension is just ignored in the test => test fails.
But it does not mean that the extension is not supported.
It is still a part of the phpBB core.

That's why those templates are parsed OK in the core (`!==` was not the reason of the problem in 3.2) but not in the test because those core methods do not know about the non-added extension in the test.

That's why it is worth trying the code above I think.

**Comment by rxu** [comment]
I'm not talking about twig extensions but about the messenger class.

**Comment by lavigor** [comment]
Messenger class does not know about Twig extensions because initializing them is outside of its responsibility.

**Comment by rxu** [comment]
Please see its ```setup_template()``` method in 3.2.x branch.

**Comment by lavigor** [comment]
@rxu, but `lexer` uses the environment initialized in the test, not in the messenger.
See `vendor\twig\twig\lib\Twig\Lexer.php`:
```php
    protected function getOperatorRegex()
    {
        $operators = array_merge(
            array('='),
            array_keys($this->env->getUnaryOperators()),
            array_keys($this->env->getBinaryOperators())
        );
```
The environment is being defined [here](https://github.com/phpbb/phpbb/pull/4357/files#diff-9c7e3c7cdaff8095daa6f7ae2c11c53aR92) - it does not have the extension initialized as I have described above.

So you were right about the lexer, but the problem comes from the test, not from the core code.

**Comment by rxu** [comment]
Well, extensions collection is set several lines above here https://github.com/phpbb/phpbb/pull/4357/files#diff-9c7e3c7cdaff8095daa6f7ae2c11c53aR76

**Comment by lavigor** [comment]
@rxu, that collection is not used anywhere before you send `$twig` to lexer, or after that.
It is used in messenger for its own environment, that is not passed to lexer.

Maybe I can create another PR to fix that?

**Comment by rxu** [comment]
> Maybe I can create another PR to fix that?

Feel free to.

**Comment by lavigor** [comment]
@rxu, hmm... As for the test itself, `!= ''` is also OK for `0` username.
But maybe it should be tested however.
I've just improved the test here: #4372.

Should we leave `!=` as it is now then?

**Comment by rxu** [comment]
Well, currently I can't see why the result of ```!= ''``` should be different from ```!== ''```. Does the type comparison matter here?

**Comment by lavigor** [comment]
Probably all AUTHOR_NAME assignments are strings - then it is OK.

**Comment by rxu** [comment]
I'm sure username should always be string.

**Pull request merged**
