### PR TITLE
[ticket/15593] Do not allow print view with direct URL

### PR DESCRIPTION
**Pull request by senky**
PHPBB3-15593

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15593

### CODE REVIEW

**Comment by Elsensee** [comment]
*prints the page without print view*

**Comment by Elsensee** [comment]
Let me elaborate: I think it's stupid that you can disallow printing in the ACP because, well, you can't.
Administrators get a sense of false security if they choose to do so.

**Comment by hanakin** [comment]
The current prosilver print file is fairly deprecated we have not maintained it. I am honestly looking not looking to include this in the new theme as it’s not really something I think very many use

**Comment by senky** [comment]
I created a ticket to remove print view in 3.3 so we don't forget about it when the new style is up:
https://tracker.phpbb.com/browse/PHPBB3-15810

**Comment by Louis7777** [comment]
Shame, I liked that one... I once had a forum with recipes and I know a few people would "print view" before printing (the first post with the recipe).

**Comment by DavidIQ** [comment]
>           Shame, I liked that one... I once had a forum with recipes and I know a few people would "print view" before printing (the first post with the recipe).

A "print view" is possible with just CSS and does not require an actual feature for it (I agree that having it as a permissions-controlled feature is dumb). This is apparently what @hanakin plans to do in the new style. 😃

**Comment by hanakin** [comment]
Tbh it’s a separate theme really so it will not be something that is part of the new theme. It should be something in the all folder

**Comment by marc1706** [comment]
I think this fix is fine as it stands as it enforces what should already be enforced. Having a different type of print view is something for 3.3 and is somewhat unrelated to this change.

**Pull request merged**
