### PR TITLE
[ticket/14640] Changes docu-link in language/en/install.php from 3.3 to 3.2

### PR DESCRIPTION
**Pull request by Crizz0**
PHPBB3-14640

https://tracker.phpbb.com/browse/PHPBB3-14640

### CODE REVIEW

**Comment by CHItA** [comment]
This link is invalid as well. @michaelcullum

**Comment by Crizz0** [comment]
I thought the website-team will create it on 3.2.0 release. But 3.3 is clearly wrong.

**Comment by CHItA** [comment]
Yeah, probably. That's why I poked Micheal, so we can blame him if we 
all forget about it :P


2016.05.18. 22:40 keltezéssel, Christian Schnegelberger írta:

**Comment by CHItA** [comment]
I guess we should merge it when we have the support forum link as well. @Nicofuma

**Comment by Nicofuma** [comment]
:+1:

**Comment by michaelcullum** [comment]
Yep, will be created shortly before release when we update the site. This location change should go in a list somewhere of changes to make when branches are split. @marc1706

**Pull request merged**
