### PR TITLE
Update functions.php

### PR DESCRIPTION
**Pull request by billynoah**
Login form should respect security setting for "Allow password reset"

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-12345

### CODE REVIEW

**Comment by Crizz0** [comment]
Did you create a ticket for this?

**Comment by billynoah** [comment]
Sorry I don't have time for that.  It's a bug, i fixed it.  Throw it away or merge it, your choice.

**Comment by Crizz0** [comment]
> 
> 
> Sorry I don't have time for that. It's a bug, i fixed it. Throw it away or merge it, your choice.

okay, would you please say one sentence how to reproduce this bug?

**Comment by DavidIQ** [comment]
Checks fail because your commit message is in the wrong format. Can't merge.

**Comment by CHItA** [comment]
Replaced by #6116. Thanks for the PR!

**Pull request closed without merging**
