### PR TITLE
[ticket/14175] Refactor responsive implementation for easier manipulation

### PR DESCRIPTION
**Pull request by hanakin**
The current way we include and use the responsive stylesheet is very dated and improperly handled. All media queries should be handled in the file itself and all code should be consolidated by breakpoint. This makes for setting of a style at a specific breakpoint very simplistic.

ticket: https://tracker.phpbb.com/browse/PHPBB3-14175
PHPBB3-14175

### CODE REVIEW

**Comment by hanakin** [comment]
@cyberalien when u get a chance please review

**Comment by hanakin** [comment]
@cyberalien @VSEphpbb can you please review this when you get a chance

**Comment by hanakin** [comment]
!set Styles

**Comment by cyberalien** [comment]
I suggest to change more stuff:
- Remove "only screen" and max-device-width from media queries to make them shorter
- Move link to responsive.css to stylesheet.css, so it would be handled same way as other .css files

Also patch is missing changes in simple_header.html

**Comment by hanakin** [comment]
@cyberalien changes made

**Comment by cyberalien** [comment]
Everything looks good

**Comment by marc1706** [comment]
There seems to be a minor issue with the index page on an iPhone 4 screen size:
yourdomain com - index page

Looks like the last post column doesn't automatically hide anymore

**Comment by cyberalien** [comment]
You are running IE in compatibility mode, which switches it to IE7 rendering engine.

**Comment by marc1706** [comment]
Screenshot is from up-to-date Chrome with iPhone 4 emulated.

**Comment by hanakin** [comment]
@marc1706 try it now? this also depends on https://github.com/phpbb/phpbb/pull/3949 for viewforum as its unrelated to this PR

**Comment by marc1706** [comment]
Looks good now

**Comment by marc1706** [comment]
@cyberalien Care to take another look?

**Comment by cyberalien** [comment]
Looks good

**Pull request merged**
