### PR TITLE
[Ticket/14206]Fix jumpbox UI consistency

### PR DESCRIPTION
**Pull request by hanakin**
ticket: https://tracker.phpbb.com/browse/PHPBB3-14206
PHPBB3-14206

### CODE REVIEW

**Comment by hanakin** [comment]
!set Styles

**Comment by hanakin** [comment]
@VSEphpbb this should fix the arrow as well or at least move it slightly to be less obtrusive

**Comment by marc1706** [comment]
Depends on #3928

**Comment by hanakin** [comment]
@marc1706 it does not depend on it it was split from it.

**Comment by marc1706** [comment]
button-secondary does not exist without #3928 or am I wrong?

**Comment by hanakin** [comment]
depends on https://github.com/phpbb/phpbb/pull/3932

**Pull request merged**
