### PR TITLE
Small fix for the aligment quick links

### PR DESCRIPTION
**Pull request by melvingb**
https://tracker.phpbb.com/browse/PHPBB3-14371

### CODE REVIEW

**Comment by hanakin** [comment]
!set Styles

**Comment by hanakin** [comment]
pls add screenshots and examples of what the issue is and why this is nessecary

**Comment by melvingb** [comment]
@hanakin, here the screenshots for the apply fix

Without the change in the common.css file


With the change in the common.css file

**Comment by VSEphpbb** [comment]
Yeah, left alignment was fubbed up, as you can see on area51. This looks like it fixes it.

**Comment by marc1706** [comment]
Replaced by https://github.com/phpbb/phpbb/pull/4099

**Pull request closed without merging**
