### PR TITLE
[ticket/13590] Headers of remember me login keys are not centered

### PR DESCRIPTION
**Pull request by RMcGirr83**
PHPBB3-13590

### CODE REVIEW

**Comment by bantu** [comment]
I am not sure, but I think the general idea to not have CSS in HTML.

**Comment by marc1706** [comment]
Yeah, definitely shouldn't be using the style HTML attribute.

**Comment by RMcGirr83** [comment]
Suggest a class.  I was told once that tables shouldn't be used in prosilver?

**Comment by bantu** [comment]
> I was told once that tables shouldn't be used in prosilver?

I think it is "do not use tables for styling", e.g. splitting the page layout into halfes. It is fine to use tables for actual tables.

**Pull request merged**
