### PR TITLE
[ticket/15643] Fix open_basedir warnings

### PR DESCRIPTION
**Pull request by AlfredoRamos**
PHPBB3-15643

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15643

### CODE REVIEW

**Comment by AlfredoRamos** [comment]
I don't think the changes I made are related to the Travis CI error:

```
There was 1 error:

1) ui_permission_roles_test::test_permission_roles

Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session/933bc300-ce9f-11e9-bc40-13057711088a/url with params: {"url":"http:\/\/localhost\/ucp.php"}

Operation timed out after 30001 milliseconds with 0 bytes received

/home/travis/build/phpbb/phpbb/phpBB/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:92
/home/travis/build/phpbb/phpbb/phpBB/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:320
/home/travis/build/phpbb/phpbb/phpBB/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:547
/home/travis/build/phpbb/phpbb/phpBB/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:195
/home/travis/build/phpbb/phpbb/tests/test_framework/phpbb_ui_test_case.php:161
/home/travis/build/phpbb/phpbb/tests/test_framework/phpbb_ui_test_case.php:581
/home/travis/build/phpbb/phpbb/tests/ui/permission_roles_test.php:22
```

Do I need to trigger the test again (close/open pull request)?
Can someone trigger the job [#23910.9](https://travis-ci.org/phpbb/phpbb/jobs/580462594)? it seems the only one that failed.

**Comment by rubencm** [comment]
I have restarted the test

**Comment by AlfredoRamos** [comment]
@rubencm thanks.

**Comment by marc1706** [comment]
Thanks for your PR.

**Pull request merged**
