### PR TITLE
[ticket/14458] Explicitly state RewriteBase into .htaccess root file

### PR DESCRIPTION
**Pull request by Mauron**
The statement `RewriteBase /` needs to be explicitly typed down into the .htaccess file in root in order to reduce all the support requests about the implicit statement and the URL rewriting not working.

[PHPBB3-14458](https://tracker.phpbb.com/browse/PHPBB3-14458)

### CODE REVIEW

**Comment by Mauron** [comment]
Good!
Despite having only added comments to a file, I assume passing test means that I properly file a patch, did I?

**Comment by Nicofuma** [comment]
Exactly :) thank for contributing

**Comment by Mauron** [comment]
Hello,
Why the PR got rejected?

**Comment by rxu** [comment]
It wasn't rejected :wink: It was merged with 663ee34f66d6ded7eb3c5cc81d1d1df32a31966f.

**Comment by Mauron** [comment]
It looks weird.
Anyway, it should go to `master` as well, shouldn't it?

**Comment by Nicofuma** [comment]
I have rebased your branch against 3.1.x, then merge it into 3.1.x and finally merge 3.1.x into master :)

**Pull request closed without merging**
