### PR TITLE
[ticket/14715] Add template events in posting_topic_review & mcp_topic

### PR DESCRIPTION
**Pull request by kasimi**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:
https://tracker.phpbb.com/browse/PHPBB3-14715

The events will allow adding content before and after the post details in topic review and topic moderation.

PHPBB3-14715

### CODE REVIEW

**Comment by kasimi** [comment]
Not sure what Travis is complaining about, any ideas?

**Comment by Crizz0** [comment]
The commit messages only allows a maximum of 80 characters per line. You have more characters in the line with "the Events will allow...."

Please rebase your commit and change it.

Am 21. Juli 2016 16:37:28 MESZ, schrieb kasimi <notifications@github.com>:

**Comment by kasimi** [comment]
Thanks! I think I got it fixed now.

I read that closing and re-opening the PR is supposed to trigger a new Travis build but that doesn't seem to work. :confused:

**Comment by Crizz0** [comment]
Travis is testing right now. So what is the problem?

**Comment by kasimi** [comment]
Oh, it just took longer than usual to start. But it's still failing. :confused:

**Comment by kasimi** [comment]
Aha! It didn't like [my tabs in the events.md](https://github.com/phpbb/phpbb/blob/release-3.1.9/phpBB/phpbb/event/md_exporter.php#L382).

Will these events be merged to 3.2.x automatically or should I create another PR?

**Comment by Crizz0** [comment]
This will be merged "up stream", so the merge will go into 3.1, then 3.2 and then in master.

**Comment by kasimi** [comment]
Great, thanks!

**Pull request merged**
