### PR TITLE
[ticket/14892] Revert to twig 1.24 to have working assets again

### PR DESCRIPTION
**Pull request by marc1706**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14892

Twig 1.25 and after introduced a way of handling both relative and
absolute paths. However, it seems to handle absolute windows paths as
relative paths. This breaks any assets or similar ways of including files
into the main template files.

PHPBB3-14892

### CODE REVIEW

**Comment by marc1706** [comment]
php ../composer.phar update
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing s9e/text-formatter (0.8.3)
  - Installing s9e/text-formatter (0.8.4)
    Loading from cache

  - Removing symfony/filesystem (v2.8.13)
  - Installing symfony/filesystem (v2.8.14)
    Loading from cache

  - Removing symfony/config (v2.8.13)
  - Installing symfony/config (v2.8.14)
    Loading from cache

  - Removing symfony/debug (v2.8.13)
  - Installing symfony/debug (v2.8.14)
    Loading from cache

  - Removing symfony/console (v2.8.13)
  - Installing symfony/console (v2.8.14)
    Loading from cache

  - Removing symfony/finder (v2.8.13)
  - Installing symfony/finder (v2.8.14)
    Loading from cache

  - Removing symfony/http-foundation (v2.8.13)
  - Installing symfony/http-foundation (v2.8.14)
    Loading from cache

  - Removing symfony/event-dispatcher (v2.8.13)
  - Installing symfony/event-dispatcher (v2.8.14)
    Loading from cache

  - Removing symfony/http-kernel (v2.8.13)
  - Installing symfony/http-kernel (v2.8.14)
    Loading from cache

  - Removing symfony/dependency-injection (v2.8.13)
  - Installing symfony/dependency-injection (v2.8.14)
    Loading from cache

  - Removing squizlabs/php_codesniffer (2.7.0)
  - Installing squizlabs/php_codesniffer (2.7.1)
    Loading from cache

  - Removing symfony/proxy-manager-bridge (v2.8.13)
  - Installing symfony/proxy-manager-bridge (v2.8.14)
    Loading from cache

  - Removing symfony/routing (v2.8.13)
  - Installing symfony/routing (v2.8.14)
    Loading from cache

  - Removing twig/twig (v1.26.1)
  - Installing twig/twig (v1.24.2)
    Loading from cache

  - Removing symfony/twig-bridge (v2.8.12)
  - Installing symfony/twig-bridge (v2.8.11)
    Loading from cache

  - Removing symfony/yaml (v2.8.13)
  - Installing symfony/yaml (v2.8.14)
    Loading from cache

  - Removing symfony/dom-crawler (v2.8.13)
  - Installing symfony/dom-crawler (v2.8.14)
    Loading from cache

  - Removing symfony/browser-kit (v2.8.13)
  - Installing symfony/browser-kit (v2.8.14)
    Loading from cache

  - Removing symfony/css-selector (v2.8.13)
  - Installing symfony/css-selector (v2.8.14)
    Loading from cache

  - Removing symfony/process (v2.8.13)
  - Installing symfony/process (v2.8.14)
    Loading from cache

  - Removing sebastian/comparator (1.2.0)
  - Installing sebastian/comparator (1.2.2)
    Loading from cache

Writing lock file
Generating autoload files
> echo 'You MUST manually modify the clean-vendor-dir target in build/build.xml when adding or upgrading dependencies.'
'You MUST manually modify the clean-vendor-dir target in build/build.xml when adding or upgrading dependencies.'

**Comment by Nicofuma** [comment]
Again? .....

**Comment by marc1706** [comment]
Twig 1.25 and above seem to now turn all relative paths to absolute ones. This resulted in it appending the absolute path to the absolute path for no reason. Will have to investigate this further though.

**Comment by Crizz0** [comment]
At the moment the 3.1.x-branch still has:
`"twig/twig": "1.*"`
This will cause an update to 1.31.0, too. Maybe we should change that there, too.

**Pull request merged**
