### PR TITLE
 [ticket/14887] ACP profile step 1 lang specific event

### PR DESCRIPTION
**Pull request by javiexin**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-14887

### CODE REVIEW

**Comment by javiexin** [comment]
Can anyone check these Travis errors?  They seem to be related to the Progress search backend, nothing to do with these code changes...

**Comment by javiexin** [comment]
!set EVENT

**Comment by CHItA** [comment]
Could you please squash the commits?

**Comment by javiexin** [comment]
Sorry, don't know how to do it without breaking everything...  If you let me know how, I will be glad to do it.
I have looked at git rebase -i HEAD~4 (while in this branch) but that does not give me the right commits...

**Comment by marc1706** [comment]
We can do the squashing for you while merging. Could you still change the event name to `acp_profile_step_one_lang_after`? IMHO fits in better with other event names.

**Comment by javiexin** [comment]
Name change is done, but cannot commit as is.  I think I did something trying to squash the commits that has worsened things.  Closing this one and reopening, sorry.

**Pull request closed without merging**
