### PR TITLE
[ticket/13549] Compare ORIG_PATH_INFO with SCRIPT_NAME for checking trailing paths

### PR DESCRIPTION
**Pull request by marc1706**
The ORIG_PATH_INFO on IIS also contains the script name. Only use that
for killing the script after removing the script name from ORIG_PATH_INFO.

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13549

### CODE REVIEW

**Comment by marc1706** [comment]
Tested to be working on Microsoft IIS 8.5 & PHP 5.6.0

**Comment by nickvergessen** [comment]
https://www.phpbb.com/community/viewtopic.php?p=13919786#p13919786
Seems to happen on non IIS aswell?

**Comment by marc1706** [comment]
@nickvergessen Yeah, which is why this doesn't check for IIS anymore and should work for all server types. ;)

**Comment by bantu** [comment]
Replaced by #3348

**Pull request closed without merging**
