### PR TITLE
[ticket/14333] Change br tags in acp files

### PR DESCRIPTION
**Pull request by RMcGirr83**
Start of changing break tags to be HTML 5 compliant

PHPBB3-14333

### CODE REVIEW

**Comment by RMcGirr83** [comment]
!set WIP

**Comment by marc1706** [comment]
Is this actually being flagged as invalid html5? If not, then this should be against 3.2 and not 3.1.

**Comment by VSEphpbb** [comment]
`<br />` is HTML5 valid. Technically it's correct too, since it is a self-closing tag.

I'm against this change as well since its unnecessary and will lead to a lot of discrepancy with styles and extensions..

**Comment by RMcGirr83** [comment]
Simple enough close the ticket and mark as invalid

**Comment by marc1706** [comment]
Closed the ticket and therefore closing the PR.

**Pull request closed without merging**
