### PR TITLE
[ticket/14382] Specify the branch-alias in the composer.json files

### PR DESCRIPTION
**Pull request by Nicofuma**
PHPBB3-14382

### CODE REVIEW

**Comment by Nicofuma** [comment]
@naderman

**Comment by naderman** [comment]
Shouldn't that be 3.1.x-dev?

**Comment by Nicofuma** [comment]
3.1-dev I think. Otherwise it's not a valid version number?

**Comment by marc1706** [comment]
```.x-dev``` is allowed according to https://getcomposer.org/doc/articles/aliases.md#branch-alias

**Comment by Nicofuma** [comment]
updated

**Pull request merged**
