### PR TITLE
[ticket/16719] Fix PHP notice/warnings on update/install - PHP 8

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16719

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16719

### CODE REVIEW

**Comment by 3D-I** [comment]
@marc1706 I guess the issue with tests is not mine?

**Comment by 3D-I** [comment]
Tests are not my fault IMHO. @marc1706

**Comment by rxu** [comment]
So basically you're reverting the fix back?

**Comment by 3D-I** [comment]
Not really, I am removing such definition completely. Still in progress though, tomorrow I will do some test.

**Comment by rxu** [comment]
As far as I remember, the definition is needed until `config.php` got created during installation.

**Comment by 3D-I** [comment]
Tested fresh install and update from previous version as well.

image

**Comment by rxu** [comment]
I guess initial issue will be back again with this patch, won't it?

**Comment by 3D-I** [comment]
> 
> 
> I guess initial issue will be back again with this patch, won't it?

No issues here, also looking at your ticket in the tracker. Is there something more we should be aware of?

**Pull request merged**
