### PR TITLE
[ticket/14928] fixing validity

### PR DESCRIPTION
**Pull request by Rishabh04-02**
https://tracker.phpbb.com/browse/PHPBB3-14928
file changed - phpBB/language/en/cli.php
14928

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-12345

### CODE REVIEW

**Comment by Rishabh04-02** [comment]
The bug due to which checks failing is reported at - #4731

**Comment by CHItA** [comment]
LGTM, thanks for the contribution.

@phpbb/development-team @phpbb/native

**Comment by Nicofuma** [comment]
Merged in 3.2.x by https://github.com/phpbb/phpbb/commit/ed2d0863021d0449fe16d769ff2e76781f2c6813

**Comment by Rishabh04-02** [comment]
@Nicofuma  : I've a little confusion, This pr is shown to be merged when visiting [Merged with master](https://github.com/phpbb/phpbb/commit/ed2d0863021d0449fe16d769ff2e76781f2c6813) 
But unlike my other pr's here at the top its shown **Closed** While at my other pr's when they're merged at the top its shown **Merged**. Just curious.

**Comment by Nicofuma** [comment]
It is shown as Closed because I had to rebase your PR before merging it into 3.2.x
Therefor the commit merged is not the same as the one of your PR and Gthub can not detect it.

**Comment by Rishabh04-02** [comment]
Actually I am an aspiring candidate for GSOC-2017 & want to apply in your organization.
So in proposal how can i mention pr as while reviewing the person can find it closed instead of merged?
Will that affect my proposal in anyway?

**Comment by CHItA** [comment]
Nope, a) we will know that it was merged, b) AFAIK you don't need to be merged, if you worked on something that's a plus.

**Comment by Rishabh04-02** [comment]
Thanks @CHItA  for clearing my doubts.

**Comment by Rishabh04-02** [comment]
The issue is which is solved in this PR has been reopened here - [PHPBB3-14928](https://tracker.phpbb.com/browse/PHPBB3-14928)

**Pull request closed without merging**
