### PR TITLE
[ticket/16672] Fix invalid lang key content for delete backup in ACP

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16672

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16672

### CODE REVIEW

**Comment by 3D-I** [comment]
_Note:_ that's only for the master branch (4.0.x).

**Comment by 3D-I** [comment]
!set Language/text

**Review by marc1706 — APPROVED** [review]

**Comment by 3D-I** [comment]
@marc1706 this PR has not been added to its milestone.

**Comment by marc1706** [comment]
@3D-I fixed, thanks

**Pull request merged**
