### PR TITLE
[ticket/15171] Replace all BBCode templates by default

### PR DESCRIPTION
**Pull request by rubencm**
PHPBB3-15171

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15171

### CODE REVIEW

**Comment by rubencm** [comment]
I think there is a problem here with the parser or with bbcode.html? @JoshyPHP

**Comment by JoshyPHP** [comment]
@rubencm Apply this to your branch and it will fix it.

```diff
diff --git a/phpBB/phpbb/textformatter/s9e/factory.php b/phpBB/phpbb/textformatter/s9e/factory.php
index d5ad8283d..15d0a5e3e 100644
--- a/phpBB/phpbb/textformatter/s9e/factory.php
+++ b/phpBB/phpbb/textformatter/s9e/factory.php
@@ -78,7 +78,7 @@ class factory implements \phpbb\textformatter\cache_interface
         'b'     => '[B]{TEXT}[/B]',
         'code'  => '[CODE lang={IDENTIFIER;optional}]{TEXT}[/CODE]',
         'color' => '[COLOR={COLOR}]{TEXT}[/COLOR]',
-        'email' => '[EMAIL={EMAIL;useContent} subject={TEXT;optional;postFilter=rawurlencode} body={TEXT;optional;postFilter=rawurlencode}]{TEXT}[/EMAIL]',
+        'email' => '[EMAIL={EMAIL;useContent} subject={TEXT1;optional;postFilter=rawurlencode} body={TEXT2;optional;postFilter=rawurlencode}]{TEXT}[/EMAIL]',
         'flash' => '[FLASH={NUMBER1},{NUMBER2} width={NUMBER1;postFilter=#flashwidth} height={NUMBER2;postFilter=#flashheight} url={URL;useContent} /]',
         'i'     => '[I]{TEXT}[/I]',
         'img'   => '[IMG src={IMAGEURL;useContent}]',
```

**Comment by rubencm** [comment]
Thank you

**Comment by hanakin** [comment]
ok just tried this and it does not seem to work. just tried to manually make some bold text and it still renders the hardcode spans instead of the template strong tag

**Comment by rubencm** [comment]
Where?, it shouldn't https://github.com/phpbb/phpbb/pull/4976/files#diff-b786e86adb15b678076bf3de6a3317e2L238
Maybe you have to clean the cache or something

**Comment by hanakin** [comment]
Not sure how, I made a new post... I look at it again when I get a chance

**Comment by hanakin** [comment]
@rubencm i purged the cache and all seems to work 🥇

**Comment by rubencm** [comment]
I'm not sure if i should add a migration to update prosilver bitfield

**Comment by marc1706** [comment]
@rubencm I think it would make sense to add a migration. Otherwise people will wonder why this does not change anything for them.

**Comment by rubencm** [comment]
@marc1706 Done, but not tested

**Pull request merged**
