### PR TITLE
[ticket/14204]Fix form buttons to use consistent button codebase

### PR DESCRIPTION
**Pull request by hanakin**
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14204
PHPBB3-14204

### CODE REVIEW

**Comment by hanakin** [comment]
!set Styles

**Comment by hanakin** [comment]
!set WIP

**Comment by hanakin** [comment]
!unset WIP

**Comment by hanakin** [comment]
ready for review @VSEphpbb @cyberalien

**Comment by prototech** [comment]
@hanakin Please see IRC note.

**Comment by hanakin** [comment]
@prototech this is more of a standardization as button class will most likely be similar in future theme/s but can be pushed til 3.3

**Comment by hanakin** [comment]
!set WIP

**Comment by VSEphpbb** [comment]
Buttons look good. I think we should give them a little border radius like all our other buttons have (3px)?

**Comment by VSEphpbb** [comment]
Why in some place (like UCP prefs) is the Reset button Bold, and submit plain? Should be the opposite IMO.

**Comment by VSEphpbb** [comment]
..Also, `Go` buttons, next to drop downs are often bold. I don't think they need to be bold. I think bold buttons are really only effective when you have 2 (or more buttons) in a row, and you want the bold button to stand out as the primary choice.

**Comment by VSEphpbb** [comment]
On Posting, `Save Draft` is bold?? Should be `Submit` that is bold ;)

**Comment by VSEphpbb** [comment]
Also Add Attachments is bold, since that button is a singleton, it' should not be bold. In general all lone buttons should not be bold IMO.

**Comment by VSEphpbb** [comment]
In general, comparing this to the existing phpBB, it looks to me like the bold buttons are all reversed... What should be bold is not bold, and vice versa. So I think in general you need to reverse all your bold and unbold button assignments here.

**Comment by hanakin** [comment]
hmm looks like I replace the styles in reverse easy fix

**Comment by hanakin** [comment]
Refactored

**Comment by marc1706** [comment]
There seems to be an issue with the alignment of text inside the buttons. The marging between the text and the top border is 5px while it's 8px underneath the text. Not sure if this is only limited to my linux mint & chrome installation or if it also happens on other machines but it certainly looks weird.

**Comment by marc1706** [comment]
image

**Comment by hanakin** [comment]
Chrome on OSX
screenshot 2017-03-18 12 23 10

**Pull request merged**
