### PR TITLE
[ticket/14199] Fix screen reader compatability

### PR DESCRIPTION
**Pull request by hanakin**
To properly support screen readers we need to add aria-hidden="true" to all the i tags

http://ryanfrederick.com/sandbox/d8/icon-test/

ticket: https://tracker.phpbb.com/browse/PHPBB3-14199
PHPBB3-14199

### CODE REVIEW

**Comment by hanakin** [comment]
@callumacrae please review

**Comment by callumacrae** [comment]
looks good to me :+1:

**Comment by hanakin** [comment]
ready for merge

**Comment by hanakin** [comment]
@marc1706

**Pull request merged**
