### PR TITLE
[ticket/15203] Include missing constants in web installer

### PR DESCRIPTION
**Pull request by rubencm**
PHPBB3-15203

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15203

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Hopefully this doesn't cause any issue with https://github.com/phpbb/phpbb/pull/4773

**Comment by rubencm** [comment]
Uhm, probably yes, because phpbbcli.php includes startup.php

**Comment by marc1706** [comment]
Currently seems to be aiming at 3.3. Is that intended?

**Comment by rxu** [comment]
I thought there was a plan to get rid of globals in 3.3+, wasn't it?

**Comment by rubencm** [comment]
@marc1706 Yes, i dont have the error with 3.2.x

**Pull request merged**
