### PR TITLE
[ticket/15010] Fix incorrect use of request

### PR DESCRIPTION
**Pull request by rmcgirr83**
Checklist:

- [X] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [X] Tests pass
- [X] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [X] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

https://tracker.phpbb.com/browse/PHPBB3-15010

PHPBB3-15010

### CODE REVIEW

**Comment by javiexin** [comment]
Shouldn't this be reapplied to 3.1 branch?  
There is a `request_var` call there, so it does not fail as in 3.2.0, but still it should be made consistent (there are a number of calls to `this->request->variable` in the same class already).

**Comment by DavidIQ** [comment]
Just for consistency? I don't think so. Not sure what exactly that will accomplish in a product that has been released already.

**Comment by rmcgirr83** [comment]
If it ain't broke, don't fix it?

**Comment by javiexin** [comment]
Fine.  Forget it then.

**Pull request merged**
