### PR TITLE
ticket/15309 Fixing prosilver so that pagination icons don't hit text

### PR DESCRIPTION
**Pull request by v12mike**
Fixing prosilver so that pagination icons don't hit text,
and text reflows nicely when viewport reduced on viewforum
and search results pages.

Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15309

### CODE REVIEW

**Comment by Crizz0** [comment]
Maybe this PR should be against 3.1.x or 3.2.x branch.

**Comment by DavidIQ** [comment]
Should be against 3.2.x.

**Comment by v12mike** [comment]
Sorry, I don't know quite how that happened, should I make a new PR, or will you sort it?

**Comment by rxu** [comment]
I think you should be able to edit the current one right here to change the base branch.

**Comment by v12mike** [comment]
OK, changed the base, and the conflict has gone...

**Comment by rxu** [comment]
It seems that tests didn't run on this PR though.

**Comment by v12mike** [comment]
OK, I will close this one and try again

**Comment by rxu** [comment]
That wasn't needed, you had an option of closing and reopening it again to restart tests.

**Pull request closed without merging**
