### PR TITLE
[ticket/12230] Make new users post limit retroactive

### PR DESCRIPTION
**Pull request by Elsensee**
I could imagine to do this the other way around as well, so users who weren't in the group will go into it (again) when the administrator sets the limit up.. (again)

I'm just not sure *how* because if I just do this for all users the administrator could get into that group too. We could exclude him with `user_type <> USER_FOUNDER` but what if there are other administrators? I don't think there is a simple way we could get all administrators with some SQL query to exclude them from this.

[PHPBB3-12230](https://tracker.phpbb.com/browse/PHPBB3-12230)

### CODE REVIEW

**Comment by rxu** [comment]
Actually if the newly registered membership limit is lowered/eliminated users will be removed from the related usergroup as soon as they visit the board. Is it really needed to be fixed this way?

**Comment by gn36** [comment]
I would not add new users to the group if the setting is changed. This might cause a lot of administrators to accidentally restrict existing users, which, from my experience, will only cause trouble. 

The only benefit I would see from removing the users immediately from the group is that some random mod/extension might depend on the question whether a user is in the newly registered users group to determine whether or not to send them a notification or an E-Mail. I don't know such a mod, though.

**Comment by Elsensee** [comment]
@rxu Right, but they are only removed from the group if the setting is not 0, because `empty(0)` returns true... I missed that too, so we should rather fix that if condition.

**Comment by Elsensee** [comment]
Replaced by #3553.

**Pull request closed without merging**
