### PR TITLE
[ticket/16675] Allow test builds on fix branches in forked repositories

### PR DESCRIPTION
**Pull request by rxu**
Builds will be triggered on branches named by the ticket/* mask.

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

<a href="https://tracker.phpbb.com/browse/PHPBB3-16675">PHPBB3-16675</a>.

### CODE REVIEW

**Comment by CHItA** [comment]
I don't really like this. If you want to build your branch before making a PR, there are many ways to do that. You can edit your own action list for your branch and then revert it, or you can create a PR against your fork. This adds a bunch of load to actions as this changes forces all forks to build all branches. Even if you are creating the PR right away.

**Comment by 3D-I** [comment]
Let the author chime on this please.

**Comment by rxu** [comment]
Well, the point of redundant GA load is understandable, so makes sense I guess.

**Comment by 3D-I** [comment]
Of course it's understandable otherwise I don't think he went any further, I just can't quantify the damage or the mockery.

**Pull request closed without merging**
