### PR TITLE
[ticket/16144] Provide extra fallback to board's default style for $user

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16144

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16144

### CODE REVIEW

**Comment by 3D-I** [comment]
!set WIP
!set php

**Comment by 3D-I** [comment]
- [ ] Redirect Bots 
- [ ] Admin log

**Comment by EA117** [comment]
One observation:  If we are going to change the user-selected style ID by updating "user_style" automatically for them, shouldn't we just go ahead and do that _instead_ of throwing the NO_STYLE_DATA notice?

Meaning go ahead and set "user_style" to "default_style", but then validate whether the style ID from "default_style" exists in the phpbb_styles database, too.  And only throw the NO_STYLE_DATA notice if we find ourselves _still_ in the situation of having an invalid style ID.

**Comment by 3D-I** [comment]
Well, the logic is what should have been, now.

**Comment by 3D-I** [comment]
immagine

**Comment by 3D-I** [comment]
!unset WIP

**Comment by 3D-I** [comment]
Something went bad with resetting commits, sorry.

**Pull request closed without merging**
