### PR TITLE
[ticket/15671] Limit accepted formats for avatar upload

### PR DESCRIPTION
**Pull request by rubencm**
PHPBB3-15671

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15671

### CODE REVIEW

**Comment by marc1706** [comment]
Have you checked whether it's viable to use the phobb\avatar\driver\driver $allowed_extensions instead of hard coding this?

**Comment by rubencm** [comment]
!set WIP :construction:

**Comment by senky** [comment]
You can use it like this:
```
constant('phpbb\\avatar\\driver\\driver::allowed_extensions')|join(',')
```
But then `$allowed_extensions` needs to be public I think.

**Comment by rubencm** [comment]
Is better to pass it as variable i think

**Comment by rubencm** [comment]
!unset WIP :construction:

**Comment by senky** [comment]
Hmm, maybe:
```php
'AVATAR_ALLOWED_EXTENSIONS' => implode(',', preg_replace('/^/', '.', $this->allowed_extensions)),
```
and then:
```
accept="{{ AVATAR_ALLOWED_EXTENSIONS }}" 
```

**Comment by rubencm** [comment]
Yes, that's much better

**Pull request merged**
