### PR TITLE
[ticket/15023] fix responsive post row paging

### PR DESCRIPTION
**Pull request by hanakin**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

PHPBB3-15023

https://tracker.phpbb.com/browse/PHPBB3-15023

### CODE REVIEW

**Comment by marc1706** [comment]
Just on a general note, it's always nice to have screenshots for style changes. (not that this is especially needed here though)

**Comment by hanakin** [comment]
@marc1706 will do next time was having trouble with my repo this time since the switch to 3.2.x branch

**Comment by VSEphpbb** [comment]
Is this PR responsible for pagination getting even more ruined looking on Area51???

screen shot 2017-01-19 at 11 09 52 pm

**Comment by marc1706** [comment]
No, Area51 still uses the code state from 5 days ago.

**Comment by VSEphpbb** [comment]
ah, ok

**Pull request merged**
