### PR TITLE
[ticket/13723] Add Elsensee to authors list

### PR DESCRIPTION
**Pull request by Nicofuma**
https://tracker.phpbb.com/browse/PHPBB3-13723

PHPBB3-13723

### CODE REVIEW

**Comment by Nicofuma** [comment]
Leave for @Elsensee as merge practise please

**Comment by nickvergessen** [comment]
Elsensee's nickname is uppercase?

**Comment by Elsensee** [comment]
whops.. accidentally closed it ...

**Comment by Nicofuma** [comment]
wrong branch...

**Pull request closed without merging**
