### PR TITLE
[ticket/9435] Replace BBcode magic numbers with constants

### PR DESCRIPTION
**Pull request by Senky**
[PHPBB3-9435](https://tracker.phpbb.com/browse/PHPBB3-9435)

### CODE REVIEW

**Comment by RMcGirr83** [comment]
You should prepend your commit message with the ticket number

**Comment by Senky** [comment]
Well, I believe that `[ticket/9435]` prefix is just what you mean.

**Comment by VSEphpbb** [comment]
I'd prefer to see BBCODE_ID_XXX. Looks better and more readable that way.

**Comment by Elsensee** [comment]
I don't see the point in this patch. You're patching an old, abandoned part which will likely be removed in one of the next versions. And the new BBCode Parser doesn't need any IDs.

**Comment by Nicofuma** [comment]
I agree but it doesn't harm.
Looks acceptable to me, @marc1706 what do you think?

**Pull request merged**
