### PR TITLE
[ticket/14815] Fix facebook link on memberlist.php

### PR DESCRIPTION
**Pull request by khan0604**
PHPBB3-14815

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14815

### CODE REVIEW

**Comment by khan0604** [comment]
can someone please review my changes?

**Comment by Nicofuma** [comment]
@marc1706 I don't really remember how this part work, could you review it please?

**Comment by khan0604** [comment]
Hey! @marc1706 I have solved the issue, could you please review my changes?

**Comment by hanakin** [comment]
@khan0604

Will try to look at this tomorrow.

**Comment by khan0604** [comment]
@hanakin do you think my pull request can be merged?

**Comment by hanakin** [comment]
@marc

**Comment by marc1706** [comment]
I'm currently trying to understand what the initial goal was as to why the linking was not done. Overall the PR seems to work as described though.

**Comment by khan0604** [comment]
Thank You @marc1706 for your review

**Comment by khan0604** [comment]
@marc1706 when will you merge my PR ?

**Comment by DavidIQ** [comment]
@khan0604 it doesn't really matter when this will be merged because a release of the next maintenance version does not currently have a timeframe (i.e. it's not currently scheduled). Whenever that happens pull requests that are ready will be looked at for merging into the release candidates. Basically even if this were merged right now it would not have a release version tagged for it.

**Comment by khan0604** [comment]
Thank You @DavidIQ for the information.

**Comment by Elsensee** [comment]
Thank you very much for your contribution.

However, there's something wrong with it..
`memberrow.custom_fields.PROFILE_FIELD_CONTACT` doesn't always contain a value, thus the link could sometimes be just empty. (Not every custom profile field is a contact field)
It would be better if you say something like `<!-- IF memberrow.custom_fields.PROFILE_FIELD_CONTACT -->new behaviour<!-- ELSE -->old behaviour<!-- ENDIF-->` or something like that.

Also this PR should go against 3.2.x branch I believe.

**Comment by marc1706** [comment]
Replaced by https://github.com/phpbb/phpbb/pull/5677

**Pull request closed without merging**
