### PR TITLE
[ticket/13377] Fix decoding for www type URLs in function decode_message()

### PR DESCRIPTION
**Pull request by rxu**
<a href="https://tracker.phpbb.com/browse/PHPBB3-13377">PHPBB3-13377</a>.

### CODE REVIEW

**Comment by Nicofuma** [comment]
can you add a test please?

**Comment by rxu** [comment]
Sure, will do.

**Comment by rxu** [comment]
> Note2: can you check if it is still present in 3.2?

Yes, it is here:
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/includes/functions.php#L3365

**Comment by Nicofuma** [comment]
while rebasing, if you could send a new PR against master and close this one it will be awesome :)

**Comment by rxu** [comment]
Oh, just noticed your comment. Sure.

**Comment by Nicofuma** [comment]
thanks

**Comment by rxu** [comment]
Replaced with #3747.

**Pull request closed without merging**
