### PR TITLE
Change {L_MARK_READ} to {L_MARK}

### PR DESCRIPTION
**Pull request by eshagh79**
To solve the problem of translating the variable "mark read" in the user control panel => notifications list

### CODE REVIEW

**Comment by DavidIQ** [comment]
What problem with `MARK_READ` is this addressing? Also the template you removed when putting in your description has links that explain in detail what is required for a pull request. Not doing those things means the checks won't pass.

**Comment by eshagh79** [comment]
This was my first pull request phpbb. 
I thought they were not needed.
About the problem: In Persian, the translation "mark read" is very loud And it does not fit in 80 pixels
If this variable changes to "mark", the problem will be solved like other parts

**Comment by eshagh79** [comment]
I am using Google Translator . If I made a mistake in answering, please forgive me

**Comment by DavidIQ** [comment]
Sorry, but that then causes a problem for other languages. In English "Mark" and "Mark read" are two very different actions.

**Comment by eshagh79** [comment]
this problem in : 
Board index => User Control Panel => Overview => Manage notifications : List header => Checkbox label

**Comment by eshagh79** [comment]
My explanation is very awful.
I think you did not understand correctly

**Comment by DavidIQ** [comment]
I understood perfectly. The correct text is being produced. `MARK` and `MARK_READ` are not interchangeable so you can either do a direct translation or find a different translation.

**Pull request closed without merging**
