### PR TITLE
[ticket/14987] Board closed error message can contain valid HTML

### PR DESCRIPTION
**Pull request by balabky9**
Adds ability to add HTML formatting to board closed error messages by
adding html_entities_decode function
before displaying the board error message.

PHPBB3-14987

Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **14987**):

https://tracker.phpbb.com/browse/PHPBB3-14987

### CODE REVIEW

**Comment by marc1706** [comment]
I don't think it's a good idea to allow HTML in something that should be a simple message.

**Comment by balabky9** [comment]
It is helpful in the sense let us say you want to add a link to the message, which goes to a twitter post explaining the issue of an outage, or you might want to bold a part, adjust font and colors etc. It is not just a message but a way of expressing your regret to your user. You can also then probably put in a timer counting down there. Many possibilities by a simple change. Its all about presentation in a forum, so I thought it will be a good idea.

**Comment by marc1706** [comment]
Don't you think it might be better to support BBCodes instead of HTML in those messages? Might actually be a nicer approach then having to enter HTML directly.

**Comment by balabky9** [comment]
I did think so and I'll implement a solution for it.
Both can be supported maybe.
But I don't see a big advantage. If we use bbcode then we would need a
bb-code editor placed over there, so other template changes are needed, but
definitely a nice idea.

**Comment by marc1706** [comment]
Closing as previously noted.

**Pull request closed without merging**
