### PR TITLE
[ticket/9674] Use poster auth instead of current user auth

### PR DESCRIPTION
**Pull request by Senky**
[PHPBB3-9674](https://tracker.phpbb.com/browse/PHPBB3-9674)

Side effect of this modification is, that post awaiting approval edited by moderator does not get approved automatically upon editing. But imho this is desired behaviour, just ignored by everyone till now.

### CODE REVIEW

**Comment by VSEphpbb** [comment]
That's ugly...another query during posting !?! Any way, at the very least it should be checking if the current user is not the poster, so this is not always being run.

**Comment by marc1706** [comment]
Posts awaiting approval will no longer be approved while being edited by moderators upon editing posts (as of https://github.com/phpbb/phpbb/pull/4205).

**Comment by VSEphpbb** [comment]
Good that's a way better fix :)

**Comment by marc1706** [comment]
This change poses a high risk of privilege escalation. Also, I'm not able to confirm this issue on the latest 3.1.x branch.

**Comment by Senky** [comment]
> ...I'm not able to confirm this issue on the latest 3.1.x branch.

True.

**Pull request closed without merging**
