### PR TITLE
[ticket/13759] Take post_time into account

### PR DESCRIPTION
**Pull request by RMcGirr83**
when using the submit_post function

PHPBB3-13759

### CODE REVIEW

**Comment by RMcGirr83** [comment]
[PHPBB3-13759] (https://tracker.phpbb.com/browse/PHPBB3-13759)

https://github.com/phpbb/phpbb/pull/3531

**Comment by Nicofuma** [comment]
:+1:

**Comment by RMcGirr83** [comment]
:point_up:

**Comment by nickvergessen** [comment]
Regression: https://area51.phpbb.com/phpBB/viewtopic.php?f=99&t=48056 please revert or fix

**Comment by rxu** [comment]
Probably can be fixed just by excluding the ```quote``` mode
```php
if ($mode != 'quote' && !empty($data['post_time']))
```

**Comment by nickvergessen** [comment]
and edit, and ... ?

**Comment by nickvergessen** [comment]
Or just dont send in post_time to submit_post in our calls

**Comment by RMcGirr83** [comment]
Editing passes the posts time as well.  Not sure about all the other modes though.  Reply doesn't seem to.  It's a bit odd that there is this line in posting.php prior to the submit_post function

`'post_time'				=> (isset($post_data['post_time'])) ? (int) $post_data['post_time'] : $current_time,`

but then $current_time is used as default in submit_post function and I can't see where $data['post_time'] is ever used.

**Comment by RMcGirr83** [comment]
Any comment from anyone?

**Comment by nickvergessen** [comment]
Well I guess if you make sure this is really not the case, you can remove it, so it is not injected by default?

**Comment by RMcGirr83** [comment]
I tested pretty extensively if $data doesn't have post_time within it and ran across no issues.  So should I amend this ticket or start a new one (will require new ticket in tracker?).

Would you prefer the code be commented out or completely removed?

**Comment by marc1706** [comment]
I'd recommend you remove the line if it's really not needed and properly explain why this was done in the commit message.

**Comment by RMcGirr83** [comment]
https://github.com/phpbb/phpbb/pull/3734

**Pull request merged**
