### PR TITLE
[ticket/16525] Remove usage of pg_constraint.consrc for PostgreSQL 12

### PR DESCRIPTION
**Pull request by AlfredoRamos**
Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-16525

### CODE REVIEW

**Comment by AlfredoRamos** [comment]
!set PHP

**Comment by AlfredoRamos** [comment]
@marc1706 So this pull request can be closed?

Because I've seen that my changes were merged at https://github.com/phpbb/phpbb/commit/05a58e8942f6b5bd4c519aab152cd7a2e497eef2 (without my authoring) and the ticket updated (but not closed).

**Comment by marc1706** [comment]
Yes, this was merged into 3.3.x. Thanks for your PR.

**Comment by AlfredoRamos** [comment]
@marc1706 In that case you could have notified me to rebase against the 3.3.x branch...

**Comment by marc1706** [comment]
There was no need to rebase it as it cleanly merged into 3.3.x, hence why I didn't ask you to rebase. ;)

**Pull request closed without merging**
