### PR TITLE
[ticket/15220] Fix undefined variable $phpbb_root_path in acp_extensions.php

### PR DESCRIPTION
**Pull request by rxu**
For the master branch only.
Fixes the #4815 merge bug.

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

<a href="https://tracker.phpbb.com/browse/PHPBB3-15220">PHPBB3-15220</a>.

### CODE REVIEW

**Comment by rxu** [comment]
Tests fail is unrelated (stylelint issues which should be fixed in different PR).

**Comment by marc1706** [comment]
Test failure is also caused by the `tucket` instead of `ticket` in the commit message.

**Comment by rxu** [comment]
Lol. Fixed.

**Comment by rxu** [comment]
Regrettably, the ```s9e/TextFormatter``` is not 7.2-dev compatible currently, so the Textformatter-related failures fixing is postponed until it got this compatible..

**Pull request merged**
