### PR TITLE
[ticket/15200] Allow extensions using custom templates for help/faq controllers

### PR DESCRIPTION
**Pull request by rxu**
For 3.2.x/master only.

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

<a href="https://tracker.phpbb.com/browse/PHPBB3-15200">PHPBB3-15200</a>.

### CODE REVIEW

**Comment by rxu** [comment]
!set Event

**Comment by rxu** [comment]
Tests fail is unrelated.

**Comment by Crizz0** [comment]
Everybody says that 😁😉

**Comment by javiexin** [comment]
This is unrelated: apparently, the (recent) merge of https://github.com/phpbb/phpbb/pull/4672 into 3.1 has propagated correctly in the template file, but not in the events.md to 3.2.  That is creating the mismatch, and the errors.

**Pull request merged**
