### PR TITLE
[ticket/17376] Add aria label to quote reference link

### PR DESCRIPTION
**Pull request by danieltj27**
Adds an aria label attribute to the quoted post reference link so that screen readers can inform the user of what the link is used for. Before this change the link was too vague and would not have been well described to users of its purpose if they couldn't see it.

PHPBB-17376

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB-17376

### CODE REVIEW

**Comment by danieltj27** [comment]
I used `{L_VIEW_QUOTED_POST}` instead of `{{ lang('VIEW_QUOTED_POST') }}` to match the rest of the file for conformity but I'll happily switch the the newer syntax if needed. It's a small change, and might not be 'prefect' as such but it is definitely a step in the right direction.

Perhaps this link could be changed from an arrow to just text in a future version. However that would be a matter of preference and not necessarily on-topic with the issue here.

`aria-label`: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

**Comment by GanstaZ** [comment]
I think it's best to use `{{ lang('VIEW_QUOTED_POST') }}`.

**Comment by danieltj27** [comment]
> I think it's best to use `{{ lang('VIEW_QUOTED_POST') }}`.

I did try that but Twig wouldn't parse it so I had to match what was already there with the single brackets.

I've updated the template to fix both instances of the anchor that's added and also replace the unicode icon with a Font Awesome icon so it stands out a bit more. Not saying this is a perfect solution and will make everyone happy, but it's certainly more obvious and much better for accessibility.

What it looks like 👇

phpbb-quote-update-fa-icon-anchor

**Comment by danieltj27** [comment]
Had to force push again because my commit message went just over the limit 😅

**Comment by battye** [comment]
> Does anyone know why the php tests are failing? I can't understand the error messages.

Hi @danieltj27, it looks to be because of the test data in https://github.com/phpbb/phpbb/blob/c64055509ffd0916d4df9a6acfc0f9a4a4785ce7/tests/text_formatter/s9e/default_formatting_test.php#L286

The failure is: 

```
1) phpbb_textformatter_s9e_default_formatting_test::test_default_formatting with data set #55 ('[quote=Username post_id=123]....quote]', '<blockquote cite="phpBB/viewt...quote>')
Failed asserting that two strings are identical.

--- Expected
+++ Actual
@@ @@

-'<blockquote cite="phpBB/viewtopic.php?p=123#p123"><div><cite>Username wrote: <a href="phpBB/viewtopic.php?p=123#p123" data-post-id="123" onclick="if(document.getElementById(hash.substr(1)))href=hash">↑</a></cite>...</div></blockquote>'

+'<blockquote cite="phpBB/viewtopic.php?p=123#p123"><div><cite>Username wrote: <a href="phpBB/viewtopic.php?p=123#p123" aria-label="VIEW_QUOTED_POST" data-post-id="123" onclick="if(document.getElementById(hash.substr(1)))href=hash"><i class="icon fa-arrow-circle-up fa-fw" aria-hidden="true"></i></a></cite>...</div></blockquote>'
```

Interestingly, it looks like the language text isn't parsing either because it's printing VIEW_QUOTED_POST verbatim in the actual result, but the reason it's failing is because the test data hasn't been updated to include your change with the aria-label.

**Comment by rxu** [comment]
`tests/text_formatter/s9e/default_formatting_test.php` quote tests should be adjusted to reflect new expected results in affected datasets.
As for the language entry, `viewtopic.php` language file has to be loaded to the test file to be parsed correctly.

**Comment by danieltj27** [comment]
This looks like it's going to be a head scratcher for me then.

Do you know where I would include the `viewtopic` file in the test to ensure the language is brought across properly or do I even need to do that, should I insert the text as is without the language key?

For example on line 81, the word `wrote` doesn't rely on languages.
```
			array(
				'[quote="username"]quoted[/quote]',
				'<blockquote><div><cite>username wrote:</cite>quoted</div></blockquote>'
			),
```

**Comment by rxu** [comment]
As for the test, I guess you just need to change erroring extected data from 
```html
<blockquote cite="phpBB/viewtopic.php?p=123#p123"><div><cite>Username wrote: <a href="phpBB/viewtopic.php?p=123#p123" data-post-id="123" onclick="if(document.getElementById(hash.substr(1)))href=hash">↑</a></cite>...</div></blockquote>
```
to
```html
<blockquote cite="phpBB/viewtopic.php?p=123#p123"><div><cite>Username wrote: <a href="phpBB/viewtopic.php?p=123#p123" aria-label="VIEW_QUOTED_POST" data-post-id="123" onclick="if(document.getElementById(hash.substr(1)))href=hash"><i class="icon fa-arrow-circle-up fa-fw" aria-hidden="true"></i></a></cite>...</div></blockquote>
```

as that's what you do expect to output actually.

As for the language file loading, looking into it deeper I think that won't work directly as far as unit tests don't use language class. You can mock loading language entries though in a similar way to how it's done in https://github.com/phpbb/phpbb/blob/3.3.x/tests/language/language_test.php but I'd leave it as is now (just a language key).

So as a bottom line, you could just try changing that line in the corresponding unit test file and see if it helps.

**Pull request merged**
