### PR TITLE
[ticket/15057] Rewording the FIND_USERNAME_EXPLAIN

### PR DESCRIPTION
**Pull request by jajodiaraghav**
PHPBB3-15057

Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15057

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Thanks for theis PR but this change is not acceptable. phpBB always refers to it's registerants as "members". That should not be changed to users. Also, there are in fact places where multiple members can be selected at once, depending on the form, exactly as described in the original wording (for example in the user control panel on the friends/foes Find a Member form).

screen shot 2017-03-27 at 8 49 45 am

**Comment by jajodiaraghav** [comment]
Then how can we fix the issue PHPBB3-15057. Or is the fix for this issue not required?

**Comment by DavidIQ** [comment]
Basically you should ignore the "members" thing from the ticket. The explanation text could be changed if not coming from ACP so you would have to figure out how to do that. You would end up needing to build the explanation text on the PHP side and dump that out to the template.

**Comment by VSEphpbb** [comment]
Well, actually you'd need to examine everywhere this language is used, and determine if it's a multi or singular selection page, and dole out the intended text for each scenario, which IMO is a little ridiculous considering the original text has it mentioned in parenthesis that some forms allow multiple selects....and this has never been an issue or a complaint or any sort of bug.

**Pull request closed without merging**
