### PR TITLE
Add core event to get_unread_topics() in functions.php

### PR DESCRIPTION
**Pull request by Wolfsblvt**
Adding core event core.get_unread_topics_modify_sql to to funtion
get_unread_topics() in functions.php, so that you now are able to modify
the sql query that retrieves the unread topics.

PHPBB3-13532

### CODE REVIEW

**Comment by RMcGirr83** [comment]
Missing doc blocks for the event (docs/events.md)

**Comment by nickvergessen** [comment]
@RMcGirr83 that file is for template events only

**Comment by RMcGirr83** [comment]
GAH...not enough coffee yet today.  Mea culpa

**Comment by Wolfsblvt** [comment]
Changed commit message to standard now.

**Pull request merged**
