### PR TITLE
[ticket/15987] Table parameters as array

### PR DESCRIPTION
**Pull request by mrgoldy**
PHPBB3-15987

Checklist:

- [ ] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15987

--- 

Currently I've put it against master, as it's not a fix.
I do however, hope for it to be merged as soon as possible so extension writers can start using the table parameter injection more efficiently and they have more time to transition if it's ever decided that this is the prefered approach.

### CODE REVIEW

**Comment by 3D-I** [comment]
I guess for 3.2.x this one needs to be done as a separated PR, in case.

The tables
`backups: '%core.table_prefix%backups'`
`storage: '%core.table_prefix%storage'`
aren't there.

**Comment by mrgoldy** [comment]
For the people finding this PR:
I closed it as with this change it is no longer possible to inject single tables into a service (`- '%tables.users%'`). Or atleast not without completely changing the building of the container.

**Comment by senky** [comment]
@mrgoldy you could have just let the existing parameters be and just add them as array independently. That way a developer could still use `%tables.users%` but also `%tables%`.

**Comment by mrgoldy** [comment]
Not sure what you mean? Could you elaborate?
Because as soon as I make the service parameters (the tables in this case) an array, you can no longer inject the key&value pairs (read: a single table).
An other option would be to have two lists but is rather undesirable aswell. 
So could you please elaborate, I am all for a good possibility, to make life easier on developers and extension writers :)!

**Comment by senky** [comment]
The file could look like this:

```
parameters:
    tables.acl_groups: '%core.table_prefix%acl_groups'
    tables.acl_options: '%core.table_prefix%acl_options'
    tables.acl_roles: '%core.table_prefix%acl_roles'
    tables.acl_roles_data: '%core.table_prefix%acl_roles_data'
    tables.acl_users: '%core.table_prefix%acl_users'
    tables.attachments: '%core.table_prefix%attachments'
    tables.auth_provider_oauth_token_storage: '%core.table_prefix%oauth_tokens'
    tables.auth_provider_oauth_states: '%core.table_prefix%oauth_states'
    tables.auth_provider_oauth_account_assoc: '%core.table_prefix%oauth_accounts'
    tables.backups: '%core.table_prefix%backups'
    tables.banlist: '%core.table_prefix%banlist'
    tables.bbcodes: '%core.table_prefix%bbcodes'
    tables.bookmarks: '%core.table_prefix%bookmarks'
    tables.bots: '%core.table_prefix%bots'
    tables.captcha_qa_questions: '%core.table_prefix%captcha_questions'
    tables.captcha_qa_answers: '%core.table_prefix%captcha_answers'
    tables.captcha_qa_confirm: '%core.table_prefix%qa_confirm'
    tables.config: '%core.table_prefix%config'
    tables.config_text: '%core.table_prefix%config_text'
    tables.confirm: '%core.table_prefix%confirm'
    tables.disallow: '%core.table_prefix%disallow'
    tables.drafts: '%core.table_prefix%drafts'
    tables.ext: '%core.table_prefix%ext'
    tables.extensions: '%core.table_prefix%extensions'
    tables.extension_groups: '%core.table_prefix%extension_groups'
    tables.forums: '%core.table_prefix%forums'
    tables.forums_access: '%core.table_prefix%forums_access'
    tables.forums_track: '%core.table_prefix%forums_track'
    tables.forums_watch: '%core.table_prefix%forums_watch'
    tables.groups: '%core.table_prefix%groups'
    tables.icons: '%core.table_prefix%icons'
    tables.lang: '%core.table_prefix%lang'
    tables.log: '%core.table_prefix%log'
    tables.login_attempts: '%core.table_prefix%login_attempts'
    tables.migrations: '%core.table_prefix%migrations'
    tables.moderator_cache: '%core.table_prefix%moderator_cache'
    tables.modules: '%core.table_prefix%modules'
    tables.notification_types: '%core.table_prefix%notification_types'
    tables.notifications: '%core.table_prefix%notifications'
    tables.poll_options: '%core.table_prefix%poll_options'
    tables.poll_votes: '%core.table_prefix%poll_votes'
    tables.posts: '%core.table_prefix%posts'
    tables.privmsgs: '%core.table_prefix%privmsgs'
    tables.privmsgs_folder: '%core.table_prefix%privmsgs_folder'
    tables.privmsgs_rules: '%core.table_prefix%privmsgs_rules'
    tables.privmsgs_to: '%core.table_prefix%privmsgs_to'
    tables.profile_fields: '%core.table_prefix%profile_fields'
    tables.profile_fields_data: '%core.table_prefix%profile_fields_data'
    tables.profile_fields_options_language: '%core.table_prefix%profile_fields_lang'
    tables.profile_fields_language: '%core.table_prefix%profile_lang'
    tables.ranks: '%core.table_prefix%ranks'
    tables.reports: '%core.table_prefix%reports'
    tables.reports_reasons: '%core.table_prefix%reports_reasons'
    tables.search_results: '%core.table_prefix%search_results'
    tables.search_wordlist: '%core.table_prefix%search_wordlist'
    tables.search_wordmatch: '%core.table_prefix%search_wordmatch'
    tables.sessions: '%core.table_prefix%sessions'
    tables.sessions_keys: '%core.table_prefix%sessions_keys'
    tables.sitelist: '%core.table_prefix%sitelist'
    tables.smilies: '%core.table_prefix%smilies'
    tables.sphinx: '%core.table_prefix%sphinx'
    tables.storage: '%core.table_prefix%storage'
    tables.styles: '%core.table_prefix%styles'
    tables.styles_template: '%core.table_prefix%styles_template'
    tables.styles_template_data: '%core.table_prefix%styles_template_data'
    tables.styles_theme: '%core.table_prefix%styles_theme'
    tables.styles_imageset: '%core.table_prefix%styles_imageset'
    tables.styles_imageset_data: '%core.table_prefix%styles_imageset_data'
    tables.teampage: '%core.table_prefix%teampage'
    tables.topics: '%core.table_prefix%topics'
    tables.topics_posted: '%core.table_prefix%topics_posted'
    tables.topics_track: '%core.table_prefix%topics_track'
    tables.topics_watch: '%core.table_prefix%topics_watch'
    tables.user_group: '%core.table_prefix%user_group'
    tables.user_notifications: '%core.table_prefix%user_notifications'
    tables.users: '%core.table_prefix%users'
    tables.warnings: '%core.table_prefix%warnings'
    tables.words: '%core.table_prefix%words'
    tables.zebra: '%core.table_prefix%zebra'
    tables:
        acl_groups: '%core.table_prefix%acl_groups'
        acl_options: '%core.table_prefix%acl_options'
        acl_roles: '%core.table_prefix%acl_roles'
        acl_roles_data: '%core.table_prefix%acl_roles_data'
        acl_users: '%core.table_prefix%acl_users'
        attachments: '%core.table_prefix%attachments'
        auth_provider_oauth_token_storage: '%core.table_prefix%oauth_tokens'
        auth_provider_oauth_states: '%core.table_prefix%oauth_states'
        auth_provider_oauth_account_assoc: '%core.table_prefix%oauth_accounts'
        backups: '%core.table_prefix%backups'
        banlist: '%core.table_prefix%banlist'
        bbcodes: '%core.table_prefix%bbcodes'
        bookmarks: '%core.table_prefix%bookmarks'
        bots: '%core.table_prefix%bots'
        captcha_qa_questions: '%core.table_prefix%captcha_questions'
        captcha_qa_answers: '%core.table_prefix%captcha_answers'
        captcha_qa_confirm: '%core.table_prefix%qa_confirm'
        config: '%core.table_prefix%config'
        config_text: '%core.table_prefix%config_text'
        confirm: '%core.table_prefix%confirm'
        disallow: '%core.table_prefix%disallow'
        drafts: '%core.table_prefix%drafts'
        ext: '%core.table_prefix%ext'
        extensions: '%core.table_prefix%extensions'
        extension_groups: '%core.table_prefix%extension_groups'
        forums: '%core.table_prefix%forums'
        forums_access: '%core.table_prefix%forums_access'
        forums_track: '%core.table_prefix%forums_track'
        forums_watch: '%core.table_prefix%forums_watch'
        groups: '%core.table_prefix%groups'
        icons: '%core.table_prefix%icons'
        lang: '%core.table_prefix%lang'
        log: '%core.table_prefix%log'
        login_attempts: '%core.table_prefix%login_attempts'
        migrations: '%core.table_prefix%migrations'
        moderator_cache: '%core.table_prefix%moderator_cache'
        modules: '%core.table_prefix%modules'
        notification_types: '%core.table_prefix%notification_types'
        notifications: '%core.table_prefix%notifications'
        poll_options: '%core.table_prefix%poll_options'
        poll_votes: '%core.table_prefix%poll_votes'
        posts: '%core.table_prefix%posts'
        privmsgs: '%core.table_prefix%privmsgs'
        privmsgs_folder: '%core.table_prefix%privmsgs_folder'
        privmsgs_rules: '%core.table_prefix%privmsgs_rules'
        privmsgs_to: '%core.table_prefix%privmsgs_to'
        profile_fields: '%core.table_prefix%profile_fields'
        profile_fields_data: '%core.table_prefix%profile_fields_data'
        profile_fields_options_language: '%core.table_prefix%profile_fields_lang'
        profile_fields_language: '%core.table_prefix%profile_lang'
        ranks: '%core.table_prefix%ranks'
        reports: '%core.table_prefix%reports'
        reports_reasons: '%core.table_prefix%reports_reasons'
        search_results: '%core.table_prefix%search_results'
        search_wordlist: '%core.table_prefix%search_wordlist'
        search_wordmatch: '%core.table_prefix%search_wordmatch'
        sessions: '%core.table_prefix%sessions'
        sessions_keys: '%core.table_prefix%sessions_keys'
        sitelist: '%core.table_prefix%sitelist'
        smilies: '%core.table_prefix%smilies'
        sphinx: '%core.table_prefix%sphinx'
        storage: '%core.table_prefix%storage'
        styles: '%core.table_prefix%styles'
        styles_template: '%core.table_prefix%styles_template'
        styles_template_data: '%core.table_prefix%styles_template_data'
        styles_theme: '%core.table_prefix%styles_theme'
        styles_imageset: '%core.table_prefix%styles_imageset'
        styles_imageset_data: '%core.table_prefix%styles_imageset_data'
        teampage: '%core.table_prefix%teampage'
        topics: '%core.table_prefix%topics'
        topics_posted: '%core.table_prefix%topics_posted'
        topics_track: '%core.table_prefix%topics_track'
        topics_watch: '%core.table_prefix%topics_watch'
        user_group: '%core.table_prefix%user_group'
        user_notifications: '%core.table_prefix%user_notifications'
        users: '%core.table_prefix%users'
        warnings: '%core.table_prefix%warnings'
        words: '%core.table_prefix%words'
        zebra: '%core.table_prefix%zebra'
```
Or maybe symfony will throw error because array access is done in the same way as table names are defined. But did you test the new approach? Does it really not allow using `%tables.users%`?

**Comment by mrgoldy** [comment]
I tested the code I had in place. It does not allow injecting single tables.
Thats why the tests are not passing either.
And apart from the fact that the above example is a complete code repitition,  I am not sure if the array can have the same name, so then it would have to be named something like `all_tables:` or `phpbb_tables:`, etc.. And eventhough I all for having all tables available through a single injection, it's "weird" to have this code repitition. Then one might aswell just use the "table_prefix" approach.

**Comment by senky** [comment]
You have to sacrifice code repetition when backwards compatibility comes into play. There is nothing wrong with that.

**Comment by marc1706** [comment]
I've reworked this PR to support both ways to access this without the need to duplicate everything:
https://github.com/phpbb/phpbb/pull/5583

**Pull request closed without merging**
