### PR TITLE
[PHPBB3-14629] round() the log() explicitly to a proper integer

### PR DESCRIPTION
**Pull request by Leinad4Mind**
Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14629

### CODE REVIEW

**Comment by Elsensee** [comment]
Merging is what I called "squashing" more or less.
If you want to figure it out yourself just google for "git squash". If that is too frustrating for you, don't let it frustrate you and take your time or ask. ;)

**Comment by Leinad4Mind** [comment]
I was able to squash but then to try to push it I merge the branch, and when trying to delete that commit Merge branch I did something wrong lol guess thats better to do this from scratch in one commit, and delete this PR.

**Comment by Elsensee** [comment]
Yeah, maybe do that indeed. :D We can try it then next time if you like :D

**Comment by Leinad4Mind** [comment]
Here it is, like it should: https://github.com/phpbb/phpbb/pull/4967

**Pull request closed without merging**
