### PR TITLE
[ticket/17069] Fix duplicate key in array

### PR DESCRIPTION
**Pull request by rubencm**
PHPBB3-17069

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-17069

### CODE REVIEW

**Comment by rubencm** [comment]
Original pr: https://github.com/phpbb/phpbb/pull/6435

**Comment by arshidkv12** [comment]
Thank you

**Comment by marc1706** [comment]
@rubencm I guess this could also be fixed in 3.3.x?

**Comment by rubencm** [comment]
I dont see this key in 3.3.x

**Comment by arshidkv12** [comment]
I think, not added ogg mime type in 3.3

**Pull request merged**
