### PR TITLE
Ticket/16262 compact() calls with undefined variables causing error page

### PR DESCRIPTION
**Pull request by brunoais**
Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html) **links broken** (except 3.2.x)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html) **(link broken)**

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16262

### CODE REVIEW

**Comment by marc1706** [comment]
I've found more occurences:
- `mode` and `topic_id` are not defined: https://github.com/phpbb/phpbb/blob/3.3.x/phpBB/phpbb/feed/controller/feed.php#L312
- `current_row_number` seems to be undefined: https://github.com/phpbb/phpbb/blob/3.3.x/phpBB/includes/mcp/mcp_topic.php#L318

**Comment by brunoais** [comment]
I'll add them later today

**Comment by brunoais** [comment]
@marc1706 
> `mode` and `topic_id` are not defined: https://github.com/phpbb/phpbb/blob/3.3.x/phpBB/phpbb/feed/controller/feed.php#L312

Those two variables don't exist and are never created... Should I still make them?

> `current_row_number` seems to be undefined: https://github.com/phpbb/phpbb/blob/3.3.x/phpBB/includes/mcp/mcp_topic.php#L318

Renamed `$i` to `$current_row_number`

**Comment by marc1706** [comment]
I think I'd remove mode and topic_id and mention this in a `@changed`

**Comment by 3D-I** [comment]
> 
> 
> I think I'd remove mode and topic_id and mention this in a `@changed`

Actually are 3 those to fix or remove,

```
[phpBB Debug] PHP Notice: in file [ROOT]/phpbb/feed/controller/feed.php on line 319: compact(): Undefined variable: forum_id
[phpBB Debug] PHP Notice: in file [ROOT]/phpbb/feed/controller/feed.php on line 319: compact(): Undefined variable: mode
[phpBB Debug] PHP Notice: in file [ROOT]/phpbb/feed/controller/feed.php on line 319: compact(): Undefined variable: topic_id
```
immagine

In 3.1.x those were instantiated by request variables, see

https://github.com/phpbb/phpbb/blob/dc8ff9da28b8ab4ad11c7ea94cca526f17c87fe5/phpBB/feed.php#L48-L50

Dunno if it is better to remove them or make them with useless data?

**Comment by marc1706** [comment]
I'll cover the rest in @3D-I 's PR: https://github.com/phpbb/phpbb/pull/5795

**Pull request merged**
