### PR TITLE
[ticket/14631] Load truncate_string() if needed

### PR DESCRIPTION
**Pull request by Senky**
[PHPBB3-14631](https://tracker.phpbb.com/browse/PHPBB3-14631)

### CODE REVIEW

**Comment by rmcgirr83** [comment]
functions_content is loaded on every page per the code in common.php

`require($phpbb_root_path . 'includes/functions_content.' . $phpEx);`

Further `$phpbb_root_path` and `$phpEx` are not defined within the file.  Should be `$this->phpbb_root_path` and `$this->php_ext`

**Comment by Senky** [comment]
Apparently, it is not loaded during update process via `phpbbcli`.

It's also really strange, that all tests passed. There is one missing to cover this scenario.

**Comment by rxu** [comment]
@Senky It was discussed before in https://github.com/phpbb/phpbb/pull/4090.

**Comment by Senky** [comment]
Alright, I thought about quickfix for this release. It could be rewritten to proper solution, no problem. But I have a question. Everyone talks about "proper helper class", but none of existing seem to be suitable. A new one, say `content_helper` could be created?

**Pull request merged**
