### PR TITLE
[ticket/16472] [Master] Remove UI tests and php-webdriver/webdriver

### PR DESCRIPTION
**Pull request by mrgoldy**
Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16472

---

Master version of #5969 
Removes `php-webdriver/webdriver` as a dev dependency.

### CODE REVIEW

**Comment by hanakin** [comment]
can we refactor this for 3.2.x? I would rather not have to wait for master to start using proper js? @marc1706 I do not think we really need any test for now and we can look into adding proper tests going forward with the new theme. However, there is most defiantly going to be js changes/additions prior to the release of 4.0

**Comment by marc1706** [comment]
Sure, fine with me

**Comment by mrgoldy** [comment]
#5969 Already removes the tests in 3.3, this PR also removes the composer dependency.
But this means that ES2015 can already be used in 3.3, just not 3.2 which shouldn't be needed anymore?

**Comment by hanakin** [comment]
No it will be needed in 3.2 as we can still have js merged into 3.2

**Comment by marc1706** [comment]
@hanakin after 3.2.10, the 3.2 branch will no longer receive bugfixes apart from security issues

**Comment by marc1706** [comment]
Updated to latest master

**Pull request merged**
