### PR TITLE
[ticket/15580] Remove redundant code from ACP

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-15580

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15580

### CODE REVIEW

**Comment by 3D-I** [comment]
I will wait for instructions.

**Comment by 3D-I** [comment]
I think I got it. 📝

**Comment by 3D-I** [comment]
Commit amended but still no love. Hints?

**Comment by DavidIQ** [comment]
You have to do an interactive rebase not an amend. Something like `git rebase -i HEAD~2` and then go through those 3 commits to keep and squash.

**Comment by 3D-I** [comment]
Oky, makes sense.

**Comment by 3D-I** [comment]
This one triggered the tracker: https://github.com/phpbb/phpbb/pull/5156

**Pull request closed without merging**
