### PR TITLE
[ticket/12649] Change sort & display options in footers to dropdown menu

### PR DESCRIPTION
**Pull request by RMcGirr83**
PHPBB3-12649

### CODE REVIEW

**Comment by RMcGirr83** [comment]
https://github.com/phpbb/phpbb/pull/2541

**Comment by hanakin** [comment]
this needs rebased onto master

**Comment by RMcGirr83** [comment]
@Nicofuma poke

**Comment by Nicofuma** [comment]
It will be 3.2 at least for sure, so rebase on master please

**Comment by RMcGirr83** [comment]
Anyone know why when attempting a rebase auth.php shows up as needing to be rebased?

**Comment by RMcGirr83** [comment]
bump por favor

**Comment by Nicofuma** [comment]
no idea, it shouldn't be an issue

**Comment by hanakin** [comment]
something to keep in mind after the rebase since this is going to be a
dropdown and reducing the cluttered appearence it might be an improvement
to include this in the top action bar as well on the viewtopic?

**Comment by RMcGirr83** [comment]
https://github.com/phpbb/phpbb/pull/4015

**Pull request closed without merging**
