### PR TITLE
[ticket/13407] Update Symfony to 2.7.*@dev

### PR DESCRIPTION
**Pull request by Nicofuma**
https://tracker.phpbb.com/browse/PHPBB3-13407

PHPBB3-13407

### CODE REVIEW

**Comment by Nicofuma** [comment]
bump

**Comment by marc1706** [comment]
Looks good to me.

**Comment by bantu** [comment]
@Nicofuma Looks like we could use `2.7.*@dev` now. What do you think?

**Comment by marc1706** [comment]
I guess we'll have to remove the 5.3.3 build to be compatible with this?

**Comment by Nicofuma** [comment]
php >=5.3.9

right....

**Comment by Nicofuma** [comment]
updated

**Comment by nickvergessen** [comment]
Should probably be discussed and announced prior to the change

**Comment by bantu** [comment]
> Should probably be discussed and announced prior to the change

Using 2.7 LTS is the natural choice. If this implies that we have to update to another minor version, that is just fine. I don't think this needs any discussion. Surely, this needs to be communicated to our users as soon as possible.

**Comment by bantu** [comment]
@Nicofuma Slightly more work required.

**Comment by bantu** [comment]
"Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them."

**Comment by bantu** [comment]
Do you have an RFC for this that needs to be moved?

**Pull request merged**
