### PR TITLE
[ticket/15693] Fix get_rand_string()

### PR DESCRIPTION
**Pull request by rubencm**
PHPBB3-15693

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15693

### CODE REVIEW

**Comment by marc1706** [comment]
I've adjusted the tests to also reflect the changes and added an error message in case these tests would ever fail again (which really should never happen ☕ ).

**Comment by senky** [comment]
I think it caused even more problems. 😅 See my PRs:
https://github.com/phpbb/phpbb/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Asenky

**Comment by rubencm** [comment]
Ah ok, i see, give me a few minutes

**Comment by rubencm** [comment]
Can i fix it with the same ticket or another?

**Comment by marc1706** [comment]
You can use the same ticket

**Comment by rubencm** [comment]
Late

**Pull request merged**
