### PR TITLE
[ticket/13150] Add core.phpbb_log_get_topic_auth_sql_after

### PR DESCRIPTION
**Pull request by senky**
PHPBB3-13150

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-13150

### CODE REVIEW

**Comment by Elsensee** [comment]
I'm sure you meant 3.2?

**Comment by senky** [comment]
I always follow what ticket in the tracker says, but go ahead if you think this is supposed to be in 3.2, change the base branch.

**Comment by Elsensee** [comment]
The ticket is from 2014, a time where 3.1 was not EOL'd.
I'd love to change the base branch but you have set the @since tag to a 3.1.x version, which won't include such event additions.

**Comment by senky** [comment]
@Elsensee since tag changed.

**Pull request merged**
