### PR TITLE
[ticket/14200] Update FAQ to reflect that hidden users can't see himself

### PR DESCRIPTION
**Pull request by Zoddo**
https://tracker.phpbb.com/browse/PHPBB3-14200

### CODE REVIEW

**Comment by bantu** [comment]
Can you dig up the ticket or pull request that changed the behaviour?

**Comment by Zoddo** [comment]
@bantu : Ah no, I remembered that it functioned like that, but after searching in commit history, it appears that the behaviour has never been changed.

I will update my comment on tracker.

**Comment by CHItA** [comment]
I think we might be better fixing the behavior rather then the language file. Though that's kind of another issue.

**Comment by Nicofuma** [comment]
If it is not hard  to do I'd prefer to fix the behaviour too.

@Zoddo can you do that?

**Comment by Zoddo** [comment]
@Nicofuma : Yes, I will open a new PR for that :)

**Comment by Zoddo** [comment]
Replaced by #3957

**Pull request closed without merging**
