### PR TITLE
[ticket/15248] Make use of event parameters of core.modify_posting_auth

### PR DESCRIPTION
**Pull request by javiexin**
Fixes is_authed and error not behaving as expected by extensions.

PHPBB-15248

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-15248

### CODE REVIEW

**Comment by javiexin** [comment]
!set Event

**Comment by javiexin** [comment]
Unrelated error.

**Comment by rxu** [comment]
Currently restarting tests is senseless as the cause is the Travic-CI PHP 5.6 build failure 😉 
See https://github.com/travis-ci/travis-ci/issues/7921

**Comment by javiexin** [comment]
Thanks rxu, was not aware of that

**Pull request merged**
