### PR TITLE
[ticket/15900] Converting install/index.html to UTF-8 and fixing tag

### PR DESCRIPTION
**Pull request by orynider**
PHPBB3-15900

Checklist:

- [ ] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15900

### CODE REVIEW

**Comment by mrgoldy** [comment]
You still have to end your commit messages with an empty line and `PHPBB3-15900`.
```
[ticket/15900] Converting install/index.html to UTF8 and fixing tag

PHPBB3-15900
```

**Comment by 3D-I** [comment]
That file, however, is only there to make sure that the contents of the directory is not seen by pointing it directly. There's no reason to change it, it's just like dozens of others in the package. Practically this PR doesn't make sense as the file only displays a blank page with no text in it. Like the .htaccess colleague.

Examples:

https://github.com/phpbb/phpbb/blob/master/phpBB/files/index.htm
https://github.com/phpbb/phpbb/blob/master/phpBB/download/index.htm
https://github.com/phpbb/phpbb/blob/master/phpBB/cache/index.htm

etc.. etc..

**Comment by marc1706** [comment]
Can you elaborate a little bit on what you're trying to achieve / change with this PR before we talk about specifics like commit message format? The file you're changing is HTML 4.01, you seem to be trying to change it to HTML5 syntax. What I don't understand is why exactly since this file is only used as a placeholder as @3D-I already mentioned.

**Comment by orynider** [comment]
It's about the tag above that line that probably is HTML 4, and there are files like that with open tags at end that we never use but we are redirected to this one and from this one to app.php every time we do a fresh install.
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
. 
 <meta http-equiv="Content-Type" content="text/html" charset="utf-8" />
Replacing this also require a conversion in UTF-8 in Notepad++, or if is just converted to HTML6 standards we can just put the comas correct:
 <meta http-equiv="Content-Type" content="text/html" charset="iso-8859-1" />

**Comment by orynider** [comment]
It's about the tag above that line that probably is HTML 4, and there are files like that with open tags at end that we never use but we are redirected to this one and from this one to app.php every time we do a fresh install.

.

Replacing this also require a conversion in UTF-8 in Notepad++, or if is just converted to HTML6 standards we can just put the comas correct:
<meta http-equiv="Content-Type" content="text/html" charset="iso-8859-1" />
or
<meta http-equiv="Content-Type" content="text/html" "charset=utf-8" />
instead of this line that breaks syntax highlighting in Notepad++:
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

**Pull request closed without merging**
