### PR TITLE
[ticket/13493] Append page name to base url if it doesn't contain it

### PR DESCRIPTION
**Pull request by marc1706**
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13493

### CODE REVIEW

**Comment by Nicofuma** [comment]
I'm not sure that I agree with this PR. We should have at least one test failing without it

**Comment by marc1706** [comment]
The test I added should fail if you remove the change to the controller helper.

**Comment by marc1706** [comment]
Right now this causes a rather bad issue. If you do not have mod rewrite enabled and access the website. for example via http://example.com, and click on an extension link the URL will be missing app.php. This will obviously causes 404 errors.

**Comment by nickvergessen** [comment]
Merged via http://git.io/veRC0

**Pull request closed without merging**
