### PR TITLE
[ticket/13454] Remove unused variables and global definition

### PR DESCRIPTION
**Pull request by MGaetan89**
https://tracker.phpbb.com/browse/PHPBB3-13454

PHPBB3-13454

### CODE REVIEW

**Comment by MGaetan89** [comment]
!set WIP

**Comment by MGaetan89** [comment]
Can anyone give me a clue why the test fails?

**Comment by nickvergessen** [comment]
I dont know, try reapplying your patch file by file?

**Comment by marc1706** [comment]
Needs to be refactored. Should be done for alpha or right after alpha.

**Comment by marc1706** [comment]
Closing as it was abandoned by the author and the repo was deleted.

**Pull request closed without merging**
