### PR TITLE
[ticket/16404] Small bug in prosilver

### PR DESCRIPTION
**Pull request by phpbb-es**
PHPBB3-16404

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16404

### CODE REVIEW

**Comment by Crizz0** [comment]
This is not a bug, in the last line of each CSS rule is no ; needed.

**Comment by hanakin** [comment]
well its a bug in that its against our coding guidelines. But its also something that you can put against 3.2 as its does not break bc

**Comment by mrgoldy** [comment]
It is supposed to go against 3.2.
I've been helping him to get things working, but he went offline.

**Comment by phpbb-es** [comment]
@hanakin  this happens in both files, in both versions 3.2.9 and 3.3.0

I want to emphasize the help of @mrgoldy  for 1 hour or more, I have no words... really, thank you, thank you so much. 

But I must continue learning, if they think it appropriate to close this PR, or if I must do it, they tell me. 

Thank you all.

**Comment by 3D-I** [comment]
@phpbb-es If you made this PR based on `3.2.x` then you can simply edit the title of this PR and change destination branch from here.

immagine

**Comment by dark-1** [comment]
This is not a bug , but correction in coding style.
I suggest make a new PR using correct branch & correct author email that is associated with GitHub, you can also use the email given by GitHub.

Best regards 👍

**Comment by phpbb-es** [comment]
Thanks @3D-I

**Comment by 3D-I** [comment]
@phpbb-es You should try now and `close` then `re-open` this PR from here below.

**Comment by 3D-I** [comment]
Okay, well done.

**Comment by mrgoldy** [comment]
Well done Raul! :tada:

**Pull request merged**
