### PR TITLE
Quote image as thumbnail

### PR DESCRIPTION
**Pull request by dragosvr92**
https://tracker.phpbb.com/browse/PHPBB3-13483

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Whether or not this change is worthwhile is debatable (you shouldn't really be augmenting post content just because it is quoted, and this change seems to be purely a subjective opinion and a-typical behavior, making it better as an extension), however, `colours.css` is for colors and background images. Height changes would go in `content.css`.

**Comment by nickvergessen** [comment]
This needs a RFC first

**Comment by dragosvr92** [comment]
We can add it to either content.css or common.css, wherever it needs to be. 
I was thinking the same thing, but area51 is still down.... :-\

**Comment by nickvergessen** [comment]
Closing as per ticket

**Pull request closed without merging**
