### PR TITLE
[ticket/13823] Move the part of the query, so the update will get it …

### PR DESCRIPTION
**Pull request by nickvergessen**
…correctly

https://tracker.phpbb.com/browse/PHPBB3-13823

**Note:** This will create a conflict on the update from 3.1.4 when you previously updated from 3.1.3 to 3.1.4, due to the missing whitespace change on the ` AND ` which is why we need to move all this around.

### CODE REVIEW

**Comment by Nicofuma** [comment]
https://github.com/phpbb/phpbb/pull/3700

**Comment by marc1706** [comment]
I definitely prefer #3700 over this.

**Comment by nickvergessen** [comment]
@marc1706 we need both, so the section is changed in 3.1.5 and triggers an update of the file from 3.1.4 #3700 just helps to avoid it in future

**Comment by marc1706** [comment]
@nickvergessen I'm pretty sure this file was already included in the 3.1.4 to 3.1.5 without this change. O.o

**Pull request merged**
