### PR TITLE
[ticket/15009] Inconsistency all_configured all_available

### PR DESCRIPTION
**Pull request by javiexin**
PHPBB3-15009

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-15009

### CODE REVIEW

**Comment by javiexin** [comment]
!set WIP

**Comment by javiexin** [comment]
Partial fix: a "configured" extension MUST BE "available".  This is checked EVERY page load (cache is ignored).
Includes the code for https://github.com/phpbb/phpbb/pull/4592, duplicate, but required for this to work as expected.
Side effect of current implementation: the "extension list" in the ACP does NOT show "invalid" but "configured" extensions (while they were listed before).

**Comment by DavidIQ** [comment]
Cache is ignored? What happens to performance when you have 20 or more extensions?

**Comment by javiexin** [comment]
Yes, it is ignored for now.  I have not found an easy way to use the cache yet checking for filesystem availability of the extensions at run time.  Open to suggestions...

**Comment by DavidIQ** [comment]
We are not going to sacrifice performance to correct a user error.

**Comment by javiexin** [comment]
The key here is "for now" and "WIP": this is for discussion, and exploring alternatives.  I agree that we should not sacrifice performance completely, but we may need to do something...

**Comment by javiexin** [comment]
Now cache is back in use, and invalid extensions show up in extension list.

**Comment by javiexin** [comment]
Description of new functionality: https://area51.phpbb.com/phpBB/viewtopic.php?f=126&t=50876

**Comment by javiexin** [comment]
Closed to be replaced by a clean PR.

**Pull request closed without merging**
