### PR TITLE
[ticket/13939] Fix for ajax error message handler

### PR DESCRIPTION
**Pull request by cyberalien**
https://tracker.phpbb.com/browse/PHPBB3-13939

### CODE REVIEW

**Comment by nickvergessen** [comment]
Needs to go into prep, but I will take care of this

**Comment by nickvergessen** [comment]
Merged into prep-release-3.1.5 via https://github.com/phpbb/phpbb/compare/2c65b9b133ff...a50e2c0c4720

Will be merged into 3.1.x on the final release

**Comment by marc1706** [comment]
:+1:

**Comment by bantu** [comment]
@nickvergessen This should be closed too?

**Pull request closed without merging**
