### PR TITLE
[ticket/16430] Sort permissions

### PR DESCRIPTION
**Pull request by mrgoldy**
PHPBB3-16430

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16430

And the _(old)_ RFC:
http://area51.phpbb.com/phpBB/viewtopic.php?f=108&t=43295

### CODE REVIEW

**Comment by mrgoldy** [comment]
To quickly expand on how this works.

Permissions are now ordered by the way they are defined in [phpbb\permissions](https://github.com/phpbb/phpbb/blob/master/phpBB/phpbb/permissions.php#L222).
This is a more natural way of ordering permissions than by array keys (`f_read`, `f_sticky`, etc) and aswell as by their translated language string. This way we can sort them by order of importance / logical follow ups.

Extension permissions are added through an event listener listening to the `core.permissions` event. Which would append the extension's permissions to the end of the array (when done the 'common way' with `$event['permissions'] = array_merge($event['permissions', [...])`. So extensions' permissions are added to the end of a permission list by default, which I would argue is a good default so admins know where to look for new/extra permissions. 
However, this does allow extensions to also position their permissions more precisely, if they insert their permissions in a specific position in the permissions array. And extensions between themselves can use the event listener's priority functionality.

To visualize; **BEFORE**
Screenshot_3
Screenshot_2

**AFTER**
Screenshot_5
Screenshot_4

**Comment by kasimi** [comment]
I tested these changes, works great in the "global permissions", "forum based permissions" and "permission masks" sections, but no sorting is happening when editing any of the "permission roles" (ACP Permission tab, 3rd category in the left sidebar). So when editing these roles, the permissions are still sorted the old way. I tested on 3.2.9 and 3.3.0, same issue on both. Is there any reason why this couldn't be targeting 3.2.x?

**Comment by 3D-I** [comment]
That's more a fix than a new feature and should be addressed to 3.2.x IMHO.

**Comment by marc1706** [comment]
@mrgoldy maybe reconsider this for 3.3.2?

**Comment by mrgoldy** [comment]
Yeah, haven't had the time yet. Will rebase on 3.3 and implement it in permission roles.

**Pull request merged**
