### PR TITLE
[ticket/15918] Fix addslashes in mcp_ban.html

### PR DESCRIPTION
**Pull request by 3D-I**
Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15918

### CODE REVIEW

**Comment by 3D-I** [comment]
Lang keys used in javascript contexts and prefixed with `A_` are automatically escaped by the template engine. This fixes the issue as per the tracker and the regression issued by https://github.com/phpbb/phpbb/commit/4a3c00d1c84284c030e7a7a37efc3ada57228726#diff-b21a294b8b5400fdea6e473cd77f03c6 IMHO.

**Comment by kasimi** [comment]
The current solution removes the fix for line breaks that cause a JS error that was added in #5170.

Please apply the Twig escape filter to both `bans.REASON` and `bans.GIVE_REASON` respectively (not the addslashed `A_` contents). This should fix the backslash being double-escaped while not breaking reasons that contain line breaks.

**Comment by 3D-I** [comment]
Do you mean `{{ bans.GIVE_REASON | e('js') }}` for example?

**Comment by kasimi** [comment]
Yes. :+1:

**Comment by 3D-I** [comment]
Gotcha, thanks @kasimi :+1:

**Comment by kasimi** [comment]
In general I don't see why not, but better not do it in this PR.

**Comment by hanakin** [comment]
We actually would like to convert everything to twig for 3.3 so anything you want to push a pr for go for it ;) also consider if you are making any js fixes for 3.3 to factor out the js completely from the templates and into the js files. For template cars assign as data attributes to the respective elements if you can. Both will go towards making it easier for implementation in the new theme

**Pull request merged**
