### PR TITLE
[ticket/16991] Add events for bookmarks and subscribed topics in UCP

### PR DESCRIPTION
**Pull request by kaileysnay**
Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16991

### CODE REVIEW

**Comment by 3D-I** [comment]
Can I ask for a visual explanation of why these 2 new events are necessary? Do you have any screenshots? Thanks.

**Comment by kaileysnay** [comment]
Not without breaking my NDA. However, it's easy to see in the code. There is a `topiclist_row_topic_title_after` event in search_results.html (line 108) and viewforum_body.html (line 186) along with other various events to show information after the topic title. There are currently no events in ucp_main_bookmarks.html or ucp_main_subscribed.html to show this information after the topic title. This pull request adds these events.

**Comment by 3D-I** [comment]
I do not know what a NDA is, sorry.
And yes, I have already read that code and the ticket.
I also read the PHP side of things, hence my question.

**Comment by kaileysnay** [comment]
> I do not know what a NDA is, sorry.

Non-Disclosure Agreement.

> I also read the PHP side of things, hence my question.

Then you know that there are PHP events that allow you to modify the template vars but no corresponding events in the HTML files that show your extensions vars. For example, `core.ucp_main_subscribed_forum_modify_template_vars` and `core.ucp_main_topiclist_topic_modify_template_vars`. :)

**Comment by 3D-I** [comment]
`core.ucp_main_topiclist_topic_modify_template_vars` allows to modify both subscribed/bookmarked topic row data. See also the events before of it in the same file.

**Review by marc1706 — APPROVED** [review]

**Pull request merged**
