### PR TITLE
[ticket/13898] js coding standards

### PR DESCRIPTION
**Pull request by callumacrae**
https://tracker.phpbb.com/browse/PHPBB3-13898

PR contains no logic changes.

I really wouldn't recommend reading the entire jscsrc, it's pretty much just what we stick to already anyway.

### CODE REVIEW

**Comment by marc1706** [comment]
Do we really need to store the configuration files for the linting inside phpBB? Also, what about some documentation  for this? Like how to actually run this?

**Comment by callumacrae** [comment]
Yes. And that completely depends on your editor! I'll add it to the wiki when this is merged.

**Comment by Nicofuma** [comment]
not the wiki pleas, => https://github.com/phpbb/documentation/tree/3.1.x/development

**Comment by callumacrae** [comment]
I didn't even know that exists :smile:

**Comment by callumacrae** [comment]
https://github.com/phpbb/documentation/pull/32

**Comment by marc1706** [comment]
The package will contain both .jshintrc and .jscsrc. I just checked and at least PhpStorm does look into the main directory of the repository, too. Could you please move them there?

**Comment by callumacrae** [comment]
Whoops, I have the phpBB dir open in IntelliJ, which is why they're added there. I'll move them up a dir

**Comment by callumacrae** [comment]
done

**Pull request merged**
