### PR TITLE
[ticket/11130] Make subscribe and unsubscribe forum clearer.

### PR DESCRIPTION
**Pull request by flash1452**
Change the unsubscribe icon to fa-times from fa-check-square to make it clear that clicking on the link will unsubscribe the user from the forum.
PHPBB3-11130

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to 11130):

https://tracker.phpbb.com/browse/PHPBB3-11130

### CODE REVIEW

**Comment by hanakin** [comment]
!set Styles

**Comment by hanakin** [comment]
best to just upgrade FA to 4.7 or newest version upon release and use http://fontawesome.io/icon/window-close-o/ instead

**Comment by flash1452** [comment]
@hanakin   Should I just update  the css file with new fontawesome.min.css or should I upgrade fonts as well?

**Comment by hanakin** [comment]
right now i think we should hold off as they are working on 5.0 and there is sure to be a 4.8 till then both might change how to implement it. The way font-awsome cdn works has change in recent versions, there are a lot of things to change to upgrade...

Reference:
https://github.com/phpbb/phpbb/pull/3851/files

**Comment by CHItA** [comment]
@hanakin @phpbb/development-team LGTM, so if there is any objections then now is the time. Also which version should it go into? 3.2 patch or merge it to master.

**Comment by hanakin** [comment]
@CHItA no for 3.3 as we will be switching to svgs once I get time ill put up a new pr for it! 
As for 3.2 I think the one we have now is fine no matter how we change it its going to be confusing its a debate that spans pages originally on wether it should show current status or desired status

**Comment by hanakin** [comment]
this can be closed

**Comment by Nicofuma** [comment]
Closed as per @hanakin recommendation.
Thanks anyway @flash1452 for your proposal

**Pull request closed without merging**
