### PR TITLE
[ticket/16123] Show proper banned email message

### PR DESCRIPTION
**Pull request by mrgoldy**
PHPBB3-16123

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16123

---

It might or might not have been me who broke it in the first place. 🙄

### CODE REVIEW

**Comment by mrgoldy** [comment]
!set WIP 🚧 
Work in progress.
This will fail for OAuth checks: https://github.com/phpbb/phpbb/pull/5559

**Comment by 3D-I** [comment]
`!set WIP` should do

**Comment by mrgoldy** [comment]
False alarm, it works as intended!

**Comment by mrgoldy** [comment]
!unset WIP 🚧

**Comment by marc1706** [comment]
Will be merged into prep-release-3.2.8 prior to building the release. Please don't merge it without consulting me first.

**Comment by mrgoldy** [comment]
Thanks for the help @marc1706, with finding the cache issue and amending the commits.

On a side note, the `ban_ip` column might need to be added to the fixtures aswell. With an empty value but I think it should be there. Cause it is both selected in the `SELECT` and used in the `WHERE` statement.

Cause the `WHERE` statement looks like:
```php
$sql = 'WHERE (ban_ip = '' OR ban_exclude = 1) AND (ban_userid = 0 OR ban_exclude = 1)'`
```

**Pull request merged**
