### PR TITLE
[ticket/15858] Unapproved User(s) appearing as Guest in Team Page

### PR DESCRIPTION
**Pull request by dark-1**
PHPBB3-15858

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15858

### CODE REVIEW

**Comment by dark-1** [comment]
Unapproved User(s) appearing as Guest in Team Page,
Due to "NULL" values in first row of SQL query.

----

The Unapproved User:
...........................................

...........................................

Before PR:
...........................................

...........................................

...........................................

After PR:
...........................................

...........................................

...........................................

----

Best Regards. 👍

**Comment by dark-1** [comment]
Can anybody please tell me what is wrong with this : https://ci.appveyor.com/project/phpBB/phpbb/builds/19862302/job/17o6xqllre45mkas#L582 .

Thanking you. 😀

Best regards 👍

**Comment by rubencm** [comment]
It fails very often

**Comment by senky** [comment]
@dark-1 it's nothing wrong with your PR.

**Comment by dark-1** [comment]
Ho! Nice to know. 😀
It was a relief...

Thank you @rubencm & @senky . 😁

Btw can anyone restart that particular build?
That would be greatly appreciated.

Best regards 👍

**Comment by dark-1** [comment]
> I don't have permissions i think.
> You can close and reopen the pull request, or do this:
> git reset HEAD~
> git add .
> git commit -c ORIG_HEAD
> git push --force

Thanks my friend 👍

But somebody restarted the build and it was also successfully returned positive response. :grinning: 
Thank you whoever is that person. :+1: 

Best regards 👍

**Comment by senky** [comment]
> git reset HEAD~
> git add .
> git commit -c ORIG_HEAD
> git push --force

btw even faster is:

```
git commit --amend
git push --force
```

**Pull request merged**
