### PR TITLE
[ticket/10809] Remove MSSQL support

### PR DESCRIPTION
**Pull request by Senky**
[PHPBB3-10809](https://tracker.phpbb.com/browse/PHPBB3-10809)

I am not sure how to test that everything was removed correctly. Travis does not support mssql and manual test is unimaginable.

### CODE REVIEW

**Comment by marc1706** [comment]
At least some language strings need to be removed / updated to reflect this change. Especially the install.html and readme.html should be updated.

**Comment by Nicofuma** [comment]
@Senky bump

**Comment by Senky** [comment]
I just need more time for this. Do I need to hurry?

**Comment by Nicofuma** [comment]
no hurry, it was just to have some news :)

**Comment by Senky** [comment]
!unset WIP

**Comment by marc1706** [comment]
@Noxwizard IIRC you have MSSQL set up somewhere. Mind testing whether the remaining drivers still work as expected?

**Comment by marc1706** [comment]
@Senky this now seems to have a merge conflict. Could you rebase it into the current 3.2.x?

**Comment by Senky** [comment]
@marc1706 I wont' be able to do it next 2 weeks. If you're in hurry with this PR, please, rebase it yourself. If not, I will rebase it on August.

**Comment by Nicofuma** [comment]
LGTM @marc1706 @Noxwizard

**Comment by Noxwizard** [comment]
Installation and basic usage works fine on MSSQL Native and ODBC. phpunit test results don't change before and after the patch.

**Pull request merged**
