### PR TITLE
[ticket/15120] Semicolon missing

### PR DESCRIPTION
**Pull request by Rishabh04-02**
https://tracker.phpbb.com/browse/PHPBB3-15120
PHPBB3-15120

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-12345

### CODE REVIEW

**Comment by Rishabh04-02** [comment]
@DavidIQ please review.

**Comment by Crizz0** [comment]
Why is this neccassary? There is nothing wrong without a missing semicolon. That is allowed in CSS.

**Comment by DavidIQ** [comment]
@Crizz0 I think it's causing build errors elsewhere

**Comment by javiexin** [comment]
@Crizz0 yes, it is causing every build in master to fail.  
This is due to the use of stylelint https://github.com/phpbb/phpbb/pull/4622 that uncovered this case.
May be correct CSS, but does not follow coding standards (as set by stylelint).

**Pull request merged**
