### PR TITLE
[ticket/13508] Add tests for INCLUDEJS & INCLUDECSS with twig syntax

### PR DESCRIPTION
**Pull request by marc1706**
PHPBB3-13508

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-13508

### CODE REVIEW

**Comment by iMattPro** [comment]
soothes will be sort of like an alias to the current tags?

**Comment by marc1706** [comment]
@iMattPro yes, it's just an alias

**Comment by 3D-I** [comment]
> 
> 
> @iMattPro yes, it's just an alias

I understand the reason for the PR as explained in the ticket but I don't know what use an alias is... maybe to distinguish the installability of an extension simply by using the new alias? I also find the old style more comfortable. 

Anyway...

**Comment by marc1706** [comment]
Fair enough. Changed it to only implement the tests instead so not everything was a waste of time. :)

**Comment by 3D-I** [comment]
> 
> 
> Fair enough. Changed it to only implement the tests instead so not everything was a waste of time. :)

It is good that comments and criticism, if constructive, are appreciated. 👍🏼

**Pull request merged**
