### PR TITLE
[ticket/13578] - Add event to ucp_register.php file

### PR DESCRIPTION
**Pull request by RMcGirr83**
PHPBB-13578

### CODE REVIEW

**Comment by rxu** [comment]
Something's wrong with this PR :)

**Comment by RMcGirr83** [comment]
Yeah, this is starting to aggravate the crap out of me.  PR'ed to develop-ascraeus and this pops up wanting to do 1058 commits when I only did one.

I am pretty close to just giving up on this git crap.

**Comment by RMcGirr83** [comment]
I mean what's with this?

noname

**Comment by MGaetan89** [comment]
Did you base your `ticket/13578` branch on `develop` or `develop-ascraeus`?

**Comment by RMcGirr83** [comment]
develop-ascraeus, I believe, as stated here https://github.com/phpbb/phpbb/pull/3371

**Pull request closed without merging**
