### PR TITLE
[Ticket/13628] Add template events ucp profile html

### PR DESCRIPTION
**Pull request by RMcGirr83**
PHPBB-13628

### CODE REVIEW

**Comment by RMcGirr83** [comment]
@nickvergessen my commits are failing Travis with the following

Error: heading should be a sentence beginning with a letter.

You entered:

ticket/13628 

Which makes no sense to me

**Comment by RMcGirr83** [comment]
!set Event

**Comment by marc1706** [comment]
@RMcGirr83 pls take a look at how commit messages should be formatted: https://wiki.phpbb.com/Git#Commit_Messages

**Comment by marc1706** [comment]
Also, this PR seems to also contain the commit from this one: https://github.com/phpbb/phpbb/pull/3415

**Comment by RMcGirr83** [comment]
I do not understand how this commit also has the one from #3415

**Comment by RMcGirr83** [comment]
GD it!!  Now where the hell did my edits go to?  This is annoying as hell.

**Comment by RMcGirr83** [comment]
This farken sucks...I give up.

**Pull request closed without merging**
