### PR TITLE
[ticket/12649] Change sort & display options in footers to dropdown menu

### PR DESCRIPTION
**Pull request by PayBas**
https://tracker.phpbb.com/browse/PHPBB3-12649

display-options

Somewhat depends on https://github.com/phpbb/phpbb/pull/2504 for icons.

### CODE REVIEW

**Comment by Nicofuma** [comment]
bump @PayBas @nickvergessen

**Comment by marc1706** [comment]
While I don't like hiding too much stuff, this is one of the least used features on the viewtopic page so I'm all for adding this drop down.

**Comment by Nicofuma** [comment]
As far as I know, @PayBas doesn't have enough time to work on this these days.
Someone wants to take it over and finish the PR? (needs to be rebased against master to start, and a new PR opened). @hanakin maybe?

**Comment by hanakin** [comment]
This had alot of controversy in its UI implimentation and no one could agree upon a solution. But when I get some time over the weekend I will rebase it if I can as I know its complete as @PayBas included it in his theme.

**Comment by RMcGirr83** [comment]
https://github.com/phpbb/phpbb/pull/4013

**Pull request closed without merging**
