### PR TITLE
[ticket/11532] acp_users_overview.html autocompletes "confirm email" and "password" fields in chrome

### PR DESCRIPTION
**Pull request by Senky**
[PHPBB3-11532](https://tracker.phpbb.com/browse/PHPBB3-11532)

### CODE REVIEW

**Comment by nickvergessen** [comment]
I can not reproduce a problem with this atm
the `autocomplete="off"` on the fields seems to be enough?

**Comment by marc1706** [comment]
Please provide a reasoning for this change. Right now I have to agree with nickvergessen.

**Comment by Senky** [comment]
Seems to be fixed now in Chrome, since I cannot reproduce it myself, too.

**Comment by marc1706** [comment]
Closing as such

**Pull request closed without merging**
