### PR TITLE
[ticket/16316] Fix breadcrumbs markup validation

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16316

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-16316

### CODE REVIEW

**Comment by 3D-I** [comment]
immagine

**Comment by marc1706** [comment]
I think it would make sense to also include this in 3.2.x.

@3D-I I prepared this for 3.2.x: https://github.com/phpbb/phpbb/compare/3.2.x...marc1706:ticket/16316

**Comment by 3D-I** [comment]
@marc1706 Ok, what should I do then?

**Comment by marc1706** [comment]
@3D-I I can either create the PR based on my branch or you can refactor this onto 3.2.x. As your commits are in that branch anyway I think I'd go with option one if that's ok with you?

**Comment by 3D-I** [comment]
Something went wrong, making new request.

**Pull request closed without merging**
