### PR TITLE
[ticket/13013] Explain to user explicitl what "participate more" means

### PR DESCRIPTION
**Pull request by Senky**
[PHPBB3-13013](https://tracker.phpbb.com/browse/PHPBB3-13013)

### CODE REVIEW

**Comment by VSEphpbb** [comment]
I don't see this as really needed, but this is not good English. If any thing, it should be more like "participate more within this board's community'

**Comment by Mauron** [comment]
I'd go for
> _participate more to board activities_

**Comment by DavidIQ** [comment]
That doesn't sound right either.  If this does get reviewed for merging VSE looks to be the closest in providing the proper English for this.

**Comment by Senky** [comment]
The general purpose of the ticket is, that new users might be confused about what exactly "participating more" means. The idea is to explicitly state, that "participating more" means creating more posts. Thus, none of two corrections above sound sufficient to me.

**Comment by RMcGirr83** [comment]
How about 
`may need to participate more by posting in the forum to be able to use this feature.`

**Comment by rxu** [comment]
```may need to [leave|create|have] more posts```

**Comment by marc1706** [comment]
As previously stated this is not proper English. You also don't participate to sth but participate in sth.

@VSEphpbb the idea behind this seems to be to actually tell people that they need to have more posts instead of being vague.

I'd recommend:
`You may have just registered here and may need to participate more in discussions to be able to use this feature.`
or possibly:
`You may have just registered here and may need to participate more in topics to be able to use this feature.`

**Comment by marc1706** [comment]
@VSEphpbb mind reading over the text agan? Thx

**Comment by RMcGirr83** [comment]
FWIW, looks fine to me.

**Comment by VSEphpbb** [comment]
Fine I guess. phpBB is saved.

**Comment by RMcGirr83** [comment]
lol

On Thu, Mar 24, 2016 at 12:07 PM, Matt Friedman <notifications@github.com>
wrote:

> Fine I guess. phpBB is saved.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/phpbb/phpbb/pull/4229#issuecomment-200904143>
>



-- 
Rich McGirr

**Comment by marc1706** [comment]
Last questions: Shouldn't we maybe add this to 3.1.x, too? :)
In which case I'd appreciate a new PR against 3.1.x and not 3.2.x.

**Comment by Nicofuma** [comment]
I think it should be against 3.1.x

**Comment by Senky** [comment]
https://github.com/phpbb/phpbb/pull/4250

**Pull request closed without merging**
