### PR TITLE
[ticket/15178] Update dependencies for 3.1.x

### PR DESCRIPTION
**Pull request by marc1706**
PHPBB3-15178

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15178

### CODE REVIEW

**Comment by marc1706** [comment]
Composer update output:
```
~ $ php ../composer.phar update --ignore-platform-reqs
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing twig/twig (v1.24.1)
  - Installing twig/twig (v1.24.2)
    Loading from cache

  - Removing squizlabs/php_codesniffer (2.6.2)
  - Installing squizlabs/php_codesniffer (2.8.1)
    Loading from cache

  - Removing phpunit/php-timer (1.0.8)
  - Installing phpunit/php-timer (1.0.9)
    Loading from cache

  - Removing sebastian/recursion-context (1.0.2)
  - Installing sebastian/recursion-context (1.0.5)
    Loading from cache

  - Removing sebastian/comparator (1.2.0)
  - Installing sebastian/comparator (1.2.4)
    Loading from cache

  - Removing sebastian/environment (1.3.7)
  - Installing sebastian/environment (1.3.8)
    Loading from cache

  - Removing michelf/php-markdown (1.6.0)
  - Installing michelf/php-markdown (1.7.0)
    Loading from cache

  - Removing symfony/polyfill-mbstring (v1.2.0)
  - Installing symfony/polyfill-mbstring (v1.3.0)
    Loading from cache

  - Removing psr/log (1.0.0)
  - Installing psr/log (1.0.2)
    Loading from cache

  - Removing phpunit/php-token-stream (1.4.8)
  - Installing phpunit/php-token-stream (1.4.11)
    Loading from cache

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Writing lock file
Generating autoload files
> echo 'You MUST manually modify the clean-vendor-dir target in build/build.xml when adding or upgrading dependencies.'
You MUST manually modify the clean-vendor-dir target in build/build.xml when adding or upgrading dependencies.
```

**Comment by Nicofuma** [comment]
About twig, did you tried the latest version?

**Comment by marc1706** [comment]
See #4799 
Could also try adding it here now if you think the fix is ok.

**Comment by marc1706** [comment]
I don't see a good solution to have the latest twig version in 3.1.x so I'd keep it this way for now.

**Pull request merged**
