### PR TITLE
[ticket/11327] Add page to reset password instead of creating a new one

### PR DESCRIPTION
**Pull request by Elsensee**
I had this lying around on here with a merge conflict for some time now. I find this issue kind of important, plus it blocks the situation with the maximum password length currently. I think, though it might be worth having this anyway.
I still have to check if the event in ucp_remind.php can somehow be replaced (that was the merge conflict) and implement a cron job or check if the actkey is older than 24 hours.

Anyway I open this pull request so you can give feedback and discuss about sense and nonsense of this.

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Additionally:
- [x] Replace ~~/remove/add~~ event
- [ ] Cron job

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-11327

### CODE REVIEW

**Comment by hanakin** [comment]
hmm since your adding a completely new page and removing the old one not sure it would meet BC for 3.2 themes. With that in mind might as well just use TWIG instead of Template code

**Comment by Elsensee** [comment]
Indeed, good point. I forgot that.

**Comment by Elsensee** [comment]
I rebased the branch and and fixed some test failures.

**Comment by marc1706** [comment]
Replacing this with a new version that uses controllers

**Comment by marc1706** [comment]
Replaced by https://github.com/phpbb/phpbb/pull/5652

**Pull request closed without merging**
