### PR TITLE
[ticket/14784] missing rewrite for lighttpd

### PR DESCRIPTION
**Pull request by tas2580**
Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14784

PHPBB3-14784

### CODE REVIEW

**Comment by marc1706** [comment]
Shouldn't this also go into 3.1.x and 3.2.x? In which case this should be based on 3.1.x and it would also require another PR against 3.2.x that also takes care of the rewrite for the installer.

**Comment by tas2580** [comment]
It works on 3.1 and 3.2, I use it in both.
I have not testet it with the installer, but it does the same like 

```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ app.php [QSA,L]
```
in htaccess.

**Comment by marc1706** [comment]
The reason I'm mentioning this is that the pull request is based on the master branch of phpBB. However, for merging it into 3.1.x the pull request would need to be based on 3.1.x and then merged upstream (3.1.x --> 3.2.x --> master). If you feel confident to rebase this onto 3.1.x and then create another pull request against 3.1.x we can look at merging it. Of course I can also do the rebase for you if you're not sure how to do it.

**Comment by marc1706** [comment]
Closing in favor of version rebased onto 3.1.x

**Pull request closed without merging**
