### PR TITLE
[ticket/11159] Coding guidelines require "static public"

### PR DESCRIPTION
**Pull request by VSEphpbb**
https://tracker.phpbb.com/browse/PHPBB3-11159
https://area51.phpbb.com/docs/31x/coding-guidelines.html#namingvars (see Class Members)

PHPBB3-11159

### CODE REVIEW

**Comment by nickvergessen** [comment]
Master only please ;)

**Comment by VSEphpbb** [comment]
You don't want this for 3.1?

**Comment by bantu** [comment]
Hmm. You are referencing a ticket that is already fixed/closed.

**Comment by nickvergessen** [comment]
@VSEphpbb I don't think we need to do this in 3.1 yes.
It does not change any behaviour but touch 22 files unnecessarily ;)

**Comment by VSEphpbb** [comment]
Replaced by https://github.com/phpbb/phpbb/pull/3507

**Pull request closed without merging**
