### PR TITLE
[ticket/15646] Add support for Argon2i passwords

### PR DESCRIPTION
**Pull request by JoshyPHP**
This PR implements Argon2i as the preferred password driver where available. It uses the [default cost factors](https://wiki.php.net/rfc/argon2_password_hash#resolved_cost_factors).

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15646

### CODE REVIEW

**Comment by JoshyPHP** [comment]
!set WIP

**Comment by JoshyPHP** [comment]
!set WIP
!set WiP
!set wip

**Comment by JoshyPHP** [comment]
!set WIP

**Comment by marc1706** [comment]
Thanks :+1:

**Comment by rubencm** [comment]
@JoshyPHP @marc1706 this makes vagrant to stop working

**Comment by marc1706** [comment]
Is there a difference between cli PHP version and apache PHP version? E.g. if cli is using PHP 7.2 and apache is using PHP 5.6.

**Comment by rubencm** [comment]
Yes, CLI php 7.2 and nginx php 7.1

**Comment by JoshyPHP** [comment]
I don't know anything about Vagrant so I recommend using the standard debugging procedure and run the password hashing test on a debug-enabled build of PHP under gdb to get a backtrace.

Argon2i was added to PHP 7.2, the tests are skipped on previous versions.

**Pull request merged**
