### PR TITLE
[ticket/15388] List boxes internal corners rounded

### PR DESCRIPTION
**Pull request by Sophist-UK**
[master] List boxes internal corners rounded

Improve the visual style commonality by making the internal corners of the forum and topic list boxes rounded to match the rounded outer corners.

PHPBB3-15388

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15388

### CODE REVIEW

**Comment by hanakin** [comment]
you have some css formatting errors to fix https://travis-ci.org/phpbb/phpbb/jobs/282740826#L627. in 3.3 we now have a strict set of standards for our css. We are working on the docs still but you can use http://hanakin.github.io/base-l/#/css-guidelines as a reference as its the same guidelines.

**Comment by Sophist-UK** [comment]
@hanakin Apologies for not having checked for travis errors. Hopefully the fix I just pushed will pass muster.

**Comment by Sophist-UK** [comment]
Unclear why Travis has failed this time. I can't see any error messages.

**Comment by Crizz0** [comment]
Your commit message is wrong. It should start with [ticket/123456]. See: https://area51.phpbb.com/docs/dev/3.2.x/development/git.html#commit-messages

Please reword your commits: `git rebase -i HEAD~3 ` see: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by Sophist-UK** [comment]
On refresh I got the error message - I seem to be having trouble with the commit formats despite reading the documentation {sigh}. I am not normally this dense.

**Comment by Sophist-UK** [comment]
@Crizz0 Thanks for the help - I thought the branch name needed to be the target branch to merge to not the PR branch. The first Travis test has passed so should be fine now.

**Comment by rxu** [comment]
It would be nice to get some screenshots on this.

**Comment by hanakin** [comment]
just apply the changes in chrome dev tools on area51 😉 
screenshot 2017-10-03 23 46 46

**Comment by rxu** [comment]
Thanks. This look is weird to me. It's not like prosilver definitely 😆

**Comment by Sophist-UK** [comment]
Before and after screenshots also in the ticket.

**Comment by hanakin** [comment]
@Sophist-UK once a pr is created all discussion is to be transitioned onto the pr so in that regards its consider a best practice when making changes to the front-end to post the screenshots on the pr for convenience of the reviewers is all.

**Comment by Sophist-UK** [comment]
I think that the pictures were requested on the ticket before the PR was created. But net time I will add them here too.

**Comment by hanakin** [comment]
yes you will always need it in both places I know its annoying.

**Comment by hanakin** [comment]
also there is a little convince if you make a comment of `!set Styles` , `!set WIP` or `!unset WIP`  you can toggle those labels on your prs

**Comment by Sophist-UK** [comment]
Not really annoying - all decent projects have their procedures to follow to avoid chaos.

Is there documentation on the !set / !unset stuff?

**Comment by hanakin** [comment]
ish https://area51.phpbb.com/phpBB/viewtopic.php?f=99&t=46079

**Comment by hanakin** [comment]
try it out type `!set Styles` in a comment

**Pull request merged**
