### PR TITLE
[ticket/15361] Topic / Forum Icon rendering across all browsers

### PR DESCRIPTION
**Pull request by hanakin**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

PHPBB3-15361

https://tracker.phpbb.com/browse/PHPBB3-15361

You can see the results here: https://codepen.io/hanakin/pen/PKOjLe?editors=1100

### CODE REVIEW

**Comment by hanakin** [comment]
!set Styles

**Comment by Elsensee** [comment]
Is this really everything that is necessary? Impressive!

**Comment by VSEphpbb** [comment]
Not really fixed. They still look bad as long as `image-rendering: -webkit-optimize-contrast;` is in the CSS.
With that CSS:
screen shot 2017-10-05 at 1 13 25 pm

Without:
screen shot 2017-10-05 at 1 13 33 pm

**Comment by hanakin** [comment]
@vse I do not see that in safari and it’s not 1 version of chrome it’s the new versions as well

**Comment by VSEphpbb** [comment]
Well Isee it, hence the screenshots

**Comment by hanakin** [comment]
@VSEphpbb what version of safari

v 11
https://www.dropbox.com/s/0li4h5f0u2kr8y2/Screenshot%202017-10-06%2000.07.52.png?dl=0

try this in your browser https://codepen.io/hanakin/pen/PKOjLe?editors=1100

**Comment by VSEphpbb** [comment]
Safari 11. Of course your code pen works, it does not have  `image-rendering: -webkit-optimize-contrast;`
I add it to your code pen, and they go to shit there too ;)

screen shot 2017-10-05 at 11 53 11 pm

**Comment by hanakin** [comment]
the codepen is using the live repo code...

its on on my end and i have no issue here
screenshot 2017-10-06 02 56 02

**Pull request merged**
