### PR TITLE
[ticket/14193]Fix secondary buttons

### PR DESCRIPTION
**Pull request by hanakin**
ticket: https://tracker.phpbb.com/browse/PHPBB3-14193
PHPBB3-14193

### CODE REVIEW

**Comment by hanakin** [comment]
!set Styles

**Comment by hanakin** [comment]
@VSEphpbb please review

**Comment by VSEphpbb** [comment]
Unfortunately, this has changed a lot of button icons red. Advanced search, New Topic for example. That looks wrong/bad.

Also, text inside of the message editor has been turned blue!?! It should be black.

The custom BBCode buttons look good though. Except for one issue. They should have some top/bottom  spacing. If you have a lot of bbcodes, and they wrap down a line, the buttons touch.

screen shot 2015-09-28 at 2 05 40 pm

**Comment by hanakin** [comment]
yeah these are all kind of wipish as I am trying to muddle through splitting up 14197

**Comment by hanakin** [comment]
hmm @VSEphpbb  can not reproduce the red icon issue on my end maybe a cache thing? but try everything now

**Comment by VSEphpbb** [comment]
Issues are cleared up, but this seems like a lot of "other" changes just to fix the custom bbcode buttons.

Can't you just make a fixer class for the bbcode buttons only, rather than having made a change that seems to be affecting other buttons and resulting in this awkward "button-icon-only" class being added in so many places? Just a thought.

**Comment by hanakin** [comment]
well the fix for the bbcode button is simply the button-secondary class I could break it up into separate prs if absolutely necessary one for the button-secondary and one for the extra spacing between rows

**Comment by hanakin** [comment]
test

**Pull request merged**
