### PR TITLE
[ticket/12960] Remove broken captcha and add incomplete captcha as placeholder

### PR DESCRIPTION
**Pull request by marc1706**
Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-12960

### CODE REVIEW

**Comment by rxu** [comment]
`POST_CONFIRM_INCOMPLETE` key doesn't exist, couldn't find it at least.
Also, as for me, "Incomplete CAPTCHA" term sounds misleading a bit as it makes feel like there's some CAPTCHA enabled and there's some incomplete spambot test, but there're not. Probably naming it like "Not configured" would be more clear.

**Comment by HiFiKabin** [comment]
>  Also, as for me, "Incomplete CAPTCHA" term sounds misleading a bit as it makes feel like there's some CAPTCHA enabled and there's some incomplete spambot test, but there're not. Probably naming it like "Not configured" would be more clear.

Totally Agree.

**Comment by marc1706** [comment]
It currently does display as such in the ACP:
image
Admins will then see this warning message on the front page of the ACP:
image

**Comment by HiFiKabin** [comment]
> It currently does display as such in the ACP: 

Thanks

**Comment by rxu** [comment]
This PR replaces #5422 one so the latter can be probably closed.

**Review by CHItA — APPROVED** [review]

**Pull request merged**
