### PR TITLE
[ticket/14758] Improve the ACP Parameter wording

### PR DESCRIPTION
**Pull request by mukeshkharita**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14758

### CODE REVIEW

**Comment by CHItA** [comment]
The commit message should be 

```
[ticket/14758] Improve the ACP Parameter wording

PHPBB3-14758
```

That's why the build is failing. You should [--amend](https://www.atlassian.com/git/tutorials/rewriting-history), then `push -f` it.

**Comment by CHItA** [comment]
@marc1706

**Comment by Elsensee** [comment]
@CHItA Actually, why not 3.1?

**Comment by CHItA** [comment]
@Elsensee becuase now i saw what happens when you change the base on github to 3.1 :)
but we could merge it to 3.1 so fine with me

**Pull request closed without merging**
