### PR TITLE
[ticket/16679] Respect "allow password reset" setting on login

### PR DESCRIPTION
**Pull request by CHItA**
PHPBB3-16679

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16679

### CODE REVIEW

**Comment by 3D-I** [comment]
This PR seems wrong to me? Please see: https://tracker.phpbb.com/browse/PHPBB3-16658

**Comment by DavidIQ** [comment]
Good point. Looks like the same edit is needed here as well: https://github.com/phpbb/phpbb/blob/3.3.x/phpBB/index.php#L225

**Comment by 3D-I** [comment]
I recall I tested the whole stuff prior to reply at the tracker, as usual. It could be I am missing something though.

**Comment by CHItA** [comment]
I'm not sure I'm following, what did you test?

**Comment by 3D-I** [comment]
What has been reported in the issue I above posted, the logic seemed clear to me, also tested.

**Comment by billynoah** [comment]
> This PR seems wrong to me? Please see: https://tracker.phpbb.com/browse/PHPBB3-16658

From https://tracker.phpbb.com/browse/PHPBB3-16658
> The logic is correct, if you click on the link that is not hidden, an exception is triggered that clearly explains that the option has been disabled. It is of course based on the fact that emails are enabled otherwise they could not be sent to the administrator. To correctly hide that link you have to disable board-wide emails.

Sorry if I'm misunderstanding you, but are you saying that when an admin sets `Allow password reset` to `FALSE` that the forgotten password link should still be displayed?  That seems like it result in a poor user experience.

In my opinion, if the functionality has been disabled, there's no good reason to show the link. Can you explain your reasoning on this?

**Comment by 3D-I** [comment]
https://tracker.phpbb.com/browse/PHPBB3-16658?focusedCommentId=63733&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-63733

**Comment by 3D-I** [comment]
This is the exception thrown by the controller, which clearly explains the reason why is there, to have the chance to contact and Admin ;)

immagine

**Comment by billynoah** [comment]
@3D-I - Ahh.. thanks for elaborating.  Although I don't like this behavior, I understand that way of looking at it. The exception could still be useful if a user had the forgotten password link bookmarked and landed there anyway, but I fail to see why we'd be advertising it as a place they should be going. If the admin wants to be contacted by users who've forgotten their passwords I suggest they either:

1.  Modify their theme with a contact link in such places as it would be useful
2. Leave the forgotten password functionality turned on

**Comment by 3D-I** [comment]
Sorry @billynoah but I do not agree.
I stay with my opinion and the code speaks books to me, if the user can't recover its PW then we just have to give him/her a chance to contact the administrator in order to solve the issue.

**Comment by DavidIQ** [comment]
If the administrator disabled the feature then he probably doesn't want to be contacted. ;)
Also for something like LDAP or third party auth integration a password reset link is in most cases not useful.

**Comment by 3D-I** [comment]
@DavidIQ Then another solution / code should be adopted instead, not this.

**Comment by CHItA** [comment]
As I see it, if the feature is disabled, there should be no link. It is kind of a no brainer, that you would try to contact the board admin if you have some technical problems. That error message will be displayed to anyone who wonders to the disabled password reset page.

**Comment by billynoah** [comment]
One possible solution might be to introduce a third option.

Screen Shot 2021-01-07 at 1 40 40 PM

**Comment by 3D-I** [comment]
> 
> 
> As I see it, if the feature is disabled, there should be no link. It is kind of a no brainer, that you would try to contact the board admin if you have some technical problems. That error message will be displayed to anyone who wonders to the disabled password reset page.

Not really, the contact should be there if an option is checked by the admin. AKA new code.

**Comment by 3D-I** [comment]
> 
> 
> As I see it, if the feature is disabled, there should be no link.

Why not simply change the `protected function init_controller()` and related `UCP_PASSWORD_RESET_DISABLED` language string?

```php

	/**
	 * Init controller
	 */
	protected function init_controller()
	{
		$this->language->add_lang('ucp');

		if (!$this->config['allow_password_reset'])
		{
			throw new http_exception(Response::HTTP_OK, 'UCP_PASSWORD_RESET_DISABLED', [
				'<a href="mailto:' . htmlspecialchars($this->config['board_contact']) . '">',
				'</a>'
			]);
		}
	}

```

and

```php
'UCP_PASSWORD_RESET_DISABLED'	=> 'The password reset functionality has been disabled. If you need help accessing your account, please contact the %sBoard Administrator%s',
```

**Comment by billynoah** [comment]
> > As I see it, if the feature is disabled, there should be no link.
> 
> Why not simply change then the `protected function init_controller()` and related `UCP_PASSWORD_RESET_DISABLED` language string?
> 

I think he meant "no link on the login page", not "no link on the defunct password reset page".

**Comment by 3D-I** [comment]
> 
> 
> > > As I see it, if the feature is disabled, there should be no link.
> > 
> > 
> > Why not simply change then the `protected function init_controller()` and related `UCP_PASSWORD_RESET_DISABLED` language string?
> 
> I think he meant "no link on the login page", not "no link on the defunct password reset page".

The newly proposed code in `index.php` is wrong since itself leads _(again)_ to the same function I spotted above

```php
	case 'sendpassword':
		/** @var \phpbb\controller\helper $controller_helper */
		$controller_helper = $phpbb_container->get('controller.helper');

		redirect($controller_helper->route('phpbb_ucp_forgot_password_controller'));
	break;

```

**Comment by 3D-I** [comment]
> 
> 
> Good point. Looks like the same edit is needed here as well: https://github.com/phpbb/phpbb/blob/3.3.x/phpBB/index.php#L225

https://github.com/phpbb/phpbb/pull/6116#issuecomment-756340090

**Comment by 3D-I** [comment]
> 
> 
> If the administrator disabled the feature then he probably doesn't want to be contacted. ;)
> Also for something like LDAP or third party auth integration a password reset link is in most cases not useful.

Don't forget that, as far as resetting passwords is concerned, some may want only server administrators to reset passwords for users, so a contact or at least some verbal message (no email link) is necessary.

**Review by marc1706 — APPROVED** [review]

**Comment by 3D-I** [comment]
@marc1706 can I ask you why my notes were wrong?

**Comment by marc1706** [comment]
I think there are two topics in this discussion. One about not showing the password reset link when this feature is not enabled, and one about displaying a message that password reset is disabled on the actual page. I opted for merging this to cover topic 1, we can of course create another PR for topic 2.

**Comment by 3D-I** [comment]
All this could have been avoided, there is clearly some dead code left to begin with, at least in my humble opinion.

**Pull request merged**
