### PR TITLE
[ticket/15297] Fix current date broken lines

### PR DESCRIPTION
**Pull request by hubaishan**
[ticket/15297] Fix current date broken lines

Because browsers give priority to style in bidi.css
class copied from  responsive.css to bidi.css

PHPBB3-15297

Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket :

https://tracker.phpbb.com/browse/PHPBB3-15297

### CODE REVIEW

**Comment by hanakin** [comment]
hmm do not use important pls that is a bad practice. you probably just need to account for the class in bidi...

**Comment by hubaishan** [comment]
Done as @hanakin instructed.

**Comment by hanakin** [comment]
This is fixed in 3.2!

**Comment by hubaishan** [comment]
No, It is not fixed in 3.2.
please reopen

**Comment by CHItA** [comment]
It was merged already.

**Comment by hubaishan** [comment]
It is OK, no need to reopen

**Pull request closed without merging**
