### PR TITLE
add core event on index for board statistics

### PR DESCRIPTION
**Pull request by svennd**
[PHPBB3-14112] add event for board statistics

Event added so we can access the board
statistics from an extension;

PHPBB3-14112

### CODE REVIEW

**Comment by rxu** [comment]
You don't need additional event to modify template variables from ```index.php```. You can just use existing event ```'core.index_modify_page_title'``` to simply reassign them via ```assign_vars()``` method.

**Comment by svennd** [comment]
The name of that event is rather restricting and I think renaming events is not allowed.

**Comment by rxu** [comment]
Well, that is just a name. It doesn't affect the way you can use it or restrict anything. So renaming is also would be senseless.

**Comment by svennd** [comment]
Yeah thank, I know, but it would be crazy to add statistics variables to an event called index_modify_page_title. Either way this build failed and I am clueless, I'm gone leave the pro's to fix or to forget about it :)

**Comment by rxu** [comment]
> it would be crazy to add statistics variables to an event called index_modify_page_title

Not at all :)

**Comment by Nicofuma** [comment]
The failure is about your commit message: https://wiki.phpbb.com/Git#Commit_Messages

About the events they are extension points and their name is just indicative, to have a way to find them easily. (they could be name event-1, event-2 etc... but then it will be very to talk about them)

**Comment by svennd** [comment]
Oke Thx @rxu and @Nicofuma I will cancel this and retry later :)

**Pull request closed without merging**
