### PR TITLE
[ticket/14343] Added missing $phpbb_dispatcher

### PR DESCRIPTION
**Pull request by marc1706**
Replaced #4101 

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14343

### CODE REVIEW

**Comment by Nicofuma** [comment]
:+1:

**Comment by kasimi** [comment]
Does this actually have to wait for 3.1.8?

If so, though locking/unlocking posts/topics in 3.1.7 will work, it'll raise a fatal error right [here](https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/includes/mcp/mcp_main.php#L339) and the JS loading indicator is never closed and the page is not reloaded.

**Comment by marc1706** [comment]
We are aware of this. As you might have noticed, phpBB 3.1.7 has not been released yet.

**Comment by kasimi** [comment]
I was just wondering because 3.1.8 is assigned to this issue.

**Pull request merged**
