### PR TITLE
[ticket/14578]

### PR DESCRIPTION
**Pull request by canonknipser**
[master] Changing description for attachment dimensions value

Changing the description to clarify the meaning of the acp-parameter.

https://tracker.phpbb.com/browse/PHPBB3-14758

### CODE REVIEW

**Comment by Crizz0** [comment]
Bugfixes have to be compared to branch 3.1.x., not master. Please edit the pull request. Please also add an PR description.

**Comment by canonknipser** [comment]
Sorry, was not sure if my commit title was correct, so i created another commit with [ticket/..].
I changed the text a little bit, so the second one should be the correct one.

I'll try my best to create a new pull request for 3.1 (but i think it also affects 3.2 and master?)

**Comment by Crizz0** [comment]
Nö. Please don't create an other pull request! Just edit this one!

**Comment by canonknipser** [comment]
Not sure how to edit this pull request to work against 3.1.x. Changing the base gives me a lot of differences in files

**Comment by Crizz0** [comment]
With the "Edit" Button in the right upper corner, you can add a title to the PR and change the branch, you try to push. Change it to "3.1.x".

Then you have to change your local branch, on which you have made the changes to 3.1.x, too. Afterwards push it again to your online copy. With changing your branch you'll try to bring changes from "master" into 3.1.x, which will be a lot more than you should.

The changes from 3.1.x will be included by the team to 3.2x and master. 

Regards

**Comment by canonknipser** [comment]
Closing because i can't switch the "merge from" from master to 3.1. Will create a new pull request based on the correct branches

**Pull request closed without merging**
