### PR TITLE
[ticket/15071] Consolidate all media queries

### PR DESCRIPTION
**Pull request by hanakin**
PHPBB3-15071

Checklist:

- [x] Correct branch: master for new features; 3.3
- [x] Tests pass
- [x] Code follows coding guidelines
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

https://tracker.phpbb.com/browse/PHPBB3-15071

### CODE REVIEW

**Comment by hanakin** [comment]
!set WIP

**Comment by hanakin** [comment]
!set Styles

**Comment by hanakin** [comment]
!set Styles

**Comment by hanakin** [comment]
!unset WIP

**Comment by marc1706** [comment]
@hanakin is this ready for review?

**Comment by hanakin** [comment]
@marc1706 yes

**Comment by hanakin** [comment]
Rdy!

**Comment by hanakin** [comment]
ready for review

**Pull request merged**
