### PR TITLE
[ticket/14661] Fix a typo in twig.php

### PR DESCRIPTION
**Pull request by lavigor**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

https://tracker.phpbb.com/browse/PHPBB3-14661

PHPBB3-14661

### CODE REVIEW

**Comment by lavigor** [comment]
Do I need to mark the checks myself or are they for checking by team members?

**Comment by rxu** [comment]
In 3.2.x the typo seems to be non-existant for some reason.

**Comment by lavigor** [comment]
@rxu [here](https://github.com/phpbb/phpbb/pull/4165/commits/f253a853b8381a343f98c29bb399c8128695b696) is the reason - that commit fixed the issue for phpBB 3.2+.

**Comment by rxu** [comment]
Great, the question is why it wasn't merged into 3.1.x branch :smile: :

**Comment by marc1706** [comment]
@lavigor the idea is that you check those checkboxes yourself. That way you can tell us that you did indeed check if the PR complies with the laid out points.

**Comment by marc1706** [comment]
Is a 3.1.x only issue.

**Pull request merged**
