### PR TITLE
[ticket/16868] Fix links to coding guidelines

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16868

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16868

### CODE REVIEW

**Comment by 3D-I** [comment]
`Note:` there are not 4.0.x coding guidelines ready yet.
That's why the new link redirects to that more exhaustive page instead of nowhere.

**Review by hanakin — APPROVED** [review]

**Review by marc1706 — CHANGES_REQUESTED** [review]
Should target 3.3.x and fix it there as well.

**Comment by 3D-I** [comment]
> 
> 
> Should target 3.3.x and fix it there as well.

This way?

**Comment by marc1706** [comment]
No, your pull request targets the master branch. It should however target the 3.3.x branch. Changes will then be merged into master as well.

**Comment by 3D-I** [comment]
> 
> 
> No, your pull request targets the master branch. It should however target the 3.3.x branch. Changes will then be merged into master as well.

Okay.

**Comment by 3D-I** [comment]
See: https://github.com/phpbb/phpbb/pull/6293

**Pull request closed without merging**
