### PR TITLE
[ticket/14793] Fix "A non-numeric value encountered" PHP warning on PHP 7.1+

### PR DESCRIPTION
**Pull request by rxu**
This PR is for 3.2.x and master branches only.

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

<a href="https://tracker.phpbb.com/browse/PHPBB3-14793">PHPBB3-14793</a>.

### CODE REVIEW

**Comment by rxu** [comment]
Now errors are gone with the PHP nightly tests (only 3 redirect test failures are to resolve).

**Comment by marc1706** [comment]
Mind cherry-picking this into your pull request?
https://github.com/phpbb/phpbb/pull/4424/commits/4f8fcaa95b1ccfb8226fec8f3f237e8b94444078

That way I can close https://github.com/phpbb/phpbb/pull/4424

**Comment by rxu** [comment]
@marc1706 Sure. Merged from #4424.

**Comment by marc1706** [comment]
Regarding remaining failures: https://github.com/phpbb/phpbb/pull/4424#issuecomment-242178363

**Pull request merged**
