### PR TITLE
[ticket/16688] Fix PHP fatal errors on installing extensions via catalog

### PR DESCRIPTION
**Pull request by rxu**
Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

<a href="https://tracker.phpbb.com/browse/PHPBB3-16688">PHPBB3-16688</a>.
<a href="https://tracker.phpbb.com/browse/PHPBB3-16943">PHPBB3-16943</a>.

### CODE REVIEW

**Comment by iMattPro** [comment]
Small issue. The EXTENSION_***_EXPLAIN language keys being used as href titles isn't working because they contain HTML:
Screen Shot 2021-12-22 at 8 41 14 AM

Composer based extension "Update" should say:
> Updating an extension will disable the currently installed extension and delete the extension’s files from the filesystem. The extension's most recent compatible release will be uploaded to your board and re-enabled.

Composer based extension "Remove" should say:
> Removing an extension will remove all of its data and settings and delete the extension’s files from the filesystem.

**Comment by iMattPro** [comment]
Maybe we make these changes:
Rename the HTML keys from `EXTENSION_INSTALL_EXPLAIN` to `EXTENSION_INSTALL_GUIDE`:
```
	'EXTENSION_INSTALL_GUIDE'	=> '<ol>
			<li>Download an extension from phpBB’s extensions database</li>
			<li>Unzip the extension and upload it to the <samp>ext/</samp> directory of your phpBB board</li>
			<li>Enable the extension, here in the Extensions manager</li>
		</ol>',

	'EXTENSION_UPDATE_GUIDE'	=> '<ol>
			<li>Disable the extension</li>
			<li>Delete the extension’s files from the filesystem</li>
			<li>Upload the new files</li>
			<li>Enable the extension</li>
		</ol>',

	'EXTENSION_REMOVE_GUIDE'	=> '<ol>
			<li>Disable the extension</li>
			<li>Delete the extension’s data</li>
			<li>Delete the extension’s files from the filesystem</li>
		</ol>',
```

That will free us up to use `EXTENSION_UPDATE_EXPLAIN` and `EXTENSION_REMOVE_EXPLAIN` after the `EXTENSION_ENABLE_EXPLAIN` key (line 76):
```
'EXTENSION_UPDATE_EXPLAIN '=> 'Updating an extension will disable the currently installed extension and delete the extension’s files from the filesystem. The extension's most recent compatible release will be uploaded to your board and re-enabled.',
'EXTENSION_REMOVE_EXPLAIN' => 'Removing an extension will remove all of its data and settings and delete the extension’s files from the filesystem.',
```

**Comment by marc1706** [comment]
@iMattPro I agree that we should change it as it currently certainly doesn't look too great with that html text. I would however split this into a separate ticket in which we can also take a look whether the HTML is even needed in those language entries.

**Comment by marc1706** [comment]
Ticket created: https://tracker.phpbb.com/browse/PHPBB3-16957

**Pull request merged**
