### PR TITLE
[ticket/16976] Fix search results count

### PR DESCRIPTION
**Pull request by rxu**
`3.3.x` version.

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

<a href="https://tracker.phpbb.com/browse/PHPBB3-16976">PHPBB3-16976</a>.

### CODE REVIEW

**Comment by nomind60s** [comment]
On my local testbed (CentOS Stream 8), MySQL(i) 10.3.28-MariaDB, PHP 7.4.28 with the two changed files I'm getting proper search results again. Search found 1754 matches on 18 pages of results. Posts per page is 100.

**Comment by nomind60s** [comment]
Do the same changes need to also be made to phpbb/search/fulltext_postgres.php?

**Comment by rxu** [comment]
> I'm getting proper search results again.

Are they correct for you for both of posts/topics search results views?

> Do the same changes need to also be made to phpbb/search/fulltext_postgres.php?

Not literally the same I guess, just similar bug was revealed after adding tests here. It's not related to the changes made in 3.3.7 though, so not the regression.

**Comment by nomind60s** [comment]
> > I'm getting proper search results again.
> 
> Are they correct for you for both of posts/topics search results views?
> 
Advanced search, 

- display results as posts -- correct results
- display results as topics -- correct results

**Review by marc1706 — APPROVED** [review]

**Comment by nomind60s** [comment]
Unfortunately when searching within a topic I'm getting "Search found 1 match" and a maximum of one page of posts returned.

**Comment by rxu** [comment]
Do you have any details? Work fine on my side for Native search, f.e.

image

**Comment by nomind60s** [comment]
I've repeated my testing with the new changes. 

Advanced search,

- display results as posts -- correct results
- display results as topics -- correct results

Topic search now returns "Search found xx matches:" and the appropriate number of pages of posts.

**Review by marc1706 — APPROVED** [review]

**Pull request merged**
