### PR TITLE
[ticket/15506] Assign attachrow_template_vars before foreach

### PR DESCRIPTION
**Pull request by marc1706**
The attachrow_template_vars array needs to be defined once in front of the
foreach instead of resetting the array on every iteration of the foreach.

PHPBB3-15506

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15506

### CODE REVIEW

**Comment by canonknipser** [comment]
Did a quick test on my testboard, looks fine on preview and edit ;)

**Comment by Derky** [comment]
For me too

**Comment by JulienTant** [comment]
If I decide to apply this on my board, it won't cause any issue with the next update right ?

**Comment by luconsta** [comment]
Well... just for my curiosity: If the problem was solved from January, how is is possible that I've upgdated now (august 2018) and the problem is still there - I have to "patch" the file manually to solve the problem?

**Pull request merged**
