### PR TITLE
[ticket/15227] Check PHP version and remove old unused code

### PR DESCRIPTION
**Pull request by javiexin**
- Move PHP version check from `common.php` to `startup.php` to be effective in more cases.
- Remove redundant code in `startup.php`, only applicable to versions < 5.4

PHPBB3-15227

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-15227

### CODE REVIEW

**Comment by senky** [comment]
Since `STRIP` is always `false` now, wouldn't it be useful to remove it completely from the code? The only usage seems to be [here](https://github.com/phpbb/phpbb/blob/master/phpBB/phpbb/files/filespec.php#L132) and [here](https://github.com/phpbb/phpbb/blob/master/phpBB/phpbb/passwords/driver/md5_phpbb2.php#L98).

**Comment by javiexin** [comment]
I agree. Will push a new commit.

**Comment by javiexin** [comment]
Question: may the function `deregister_globals` be removed now?  It seems to be no longer used (not called anywhere else, it was only called from `startup`, in the removed code).

**Comment by marc1706** [comment]
Yes please.

**Pull request merged**
