### PR TITLE
[ticket/15152] Updates Font Awesome Icons to version 4.7.0

### PR DESCRIPTION
**Pull request by Crizz0**
PHPBB3-15152

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

https://tracker.phpbb.com/browse/PHPBB3-15152

### CODE REVIEW

**Comment by Crizz0** [comment]
Do we need that: `fontawesome-webfont.svg` or can we leave it out?

**Comment by hanakin** [comment]
yes svg is required https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_path.scss#L11

**Comment by Crizz0** [comment]
I was confused, due to the addition of 3300 lines, and oversaw the deleting of 637. So I  thought it was completely new.

**Comment by hanakin** [comment]
They changed the way the file is setup in the code probably for handling the new auto inclusion service

**Comment by hanakin** [comment]
!set Styles

**Pull request merged**
