### PR TITLE
[ticket/14786] Add mcp_forum_actions_before/after events

### PR DESCRIPTION
**Pull request by Senky**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14786

PHPBB3-14786

### CODE REVIEW

**Comment by Mauron** [comment]
If I recall correctly, events have to be sorted alphabetically.

**Comment by Senky** [comment]
@Mauron aren't they?

**Comment by Mauron** [comment]
'after' should be before 'before' but maybe I'm wrong.

**Comment by Senky** [comment]
Oh, now I get it. Thanks!

**Pull request merged**
