### PR TITLE
[ticket/16480] Fix Emoji in report post

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16480

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16480

### CODE REVIEW

**Comment by 3D-I** [comment]
immagine

**Comment by 3D-I** [comment]
One of the fastest approvals I have never seen :smiley: @marc1706

**Comment by marc1706** [comment]
You should see my F5 key. Was eagerly waiting for the next PR to arrive.

**Comment by 3D-I** [comment]
I didn't mean to ruin the party.

**Pull request merged**
