### PR TITLE
[ticket/16487] Fix URL for fontawesome 3.2.0 migration - for 3.3.x

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16487

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16487

### CODE REVIEW

**Comment by 3D-I** [comment]
Depends on https://github.com/phpbb/phpbb/pull/5986

**Comment by rxu** [comment]
I'd suggest just cancel this change for 3.3 as it makes no sense.

**Comment by 3D-I** [comment]
@marc1706 ?

**Comment by marc1706** [comment]
@rxu the fontawesome URL is not being changed in 3.3 and that's exactly what this is for: https://github.com/phpbb/phpbb/pull/5986/files#diff-f8b46cf58b90ce21af8e05dcb0164c88R20

**Comment by 3D-I** [comment]
I call it "consistency" or something, actually.

**Comment by rxu** [comment]
I just can't get why it should be in 3.3 including the #5986 altogether, it would be enough to merge it in 3.2 only. Overwriting the url twice in the same release is senseless.
Also it has nothing to do with consistency as a lot of files are different in 3.2.x and 3.3.x including 3.3.x migrations which are absent in 3.2.x. 3.2.x and 3.3.x simply aren't consistent by definition.
But whatever you decide :)

**Comment by 3D-I** [comment]
We certainly have different points of view and that's good. :+1:

**Comment by marc1706** [comment]
All migrations included in previous versions will always be included in newer ones. The 3.2 migration will be marked as already effectively installed when run on 3.3 and hence will be skipped.

**Pull request merged**
