### PR TITLE
[ticket/16935] Add sphinx tests

### PR DESCRIPTION
**Pull request by rxu**
Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

<a href="https://tracker.phpbb.com/browse/PHPBB3-16935">PHPBB3-16935</a>.

### CODE REVIEW

**Comment by Dark1z** [comment]
Why does the checks always fails at `phpbb_functional_visibility_softdelete_test::test_split_topic` ? 🤔

**Comment by 3D-I** [comment]
Failures are random, depending on the weather and github's mood.

**Comment by Dark1z** [comment]
> Failures are random, depending on the weather and github's mood.

nah! it's at `phpbb_functional_visibility_softdelete_test::test_split_topic` Only !!!

**Comment by 3D-I** [comment]
I see also: `phpbb_functional_search_sphinx_test::test_search_backend`

**Comment by rxu** [comment]
That's because I'm debugging the issue so failures vary. The actual one is `test_split_topic` which I didn't figure out yet. Same code works fine for `master` but not for `3.3.x`.

**Comment by 3D-I** [comment]
We have uncovered the whole mystery, you are the cause of everything.

**Comment by rxu** [comment]
Currently the main cause I suppose is incorrect search indexing of edited posts -> topic titles in `3.3.x` Sphinx search backend which is not the case for `master` for some reason.

**Comment by Dark1z** [comment]
> We have uncovered the whole mystery, you are the cause of everything. 😃

I can see you are in good mood today,
did you flip your "Funny" mode ?

**Comment by 3D-I** [comment]
It's Christmas time, it's short term. 🎅🏼

**Comment by rxu** [comment]
Confirmed that edited posts don't get into delta index on `3.3.x`. No clue where's the culprit in the code though.

**Comment by marc1706** [comment]
Closed and reopened to force GitHub to run the tests again. Couldn't restart them directly. 🤷

**Comment by rxu** [comment]
This code works for `master` but not for `3.3.x` for some reason. Probably different tests order affects or something.

**Comment by wojtekxtx** [comment]
> Closed and reopened to force GitHub to run the tests again. Couldn't restart them directly. 

@marc1706 `Actions` in the menu here on `GH`

**Comment by marc1706** [comment]
I've played around a bit with this but it really seems like tests don't want to work on 3.3.x. Will just close this PR as it's already working on master.

**Pull request closed without merging**
