### PR TITLE
[ticket/15391] image-rendering not needed for Topic/Forum imgs

### PR DESCRIPTION
**Pull request by hanakin**
PHPBB3-15391

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15391

### CODE REVIEW

**Comment by hanakin** [comment]
!set Styles

**Comment by hanakin** [comment]
@Noxwizard can you pls test this when you get a chance

**Comment by marc1706** [comment]
Can you please change the commit message into more meaningful text? Otherwise people will have trouble interpreting why this was changed in the future. Also, why are there 2 PRs for this?

**Comment by hanakin** [comment]
yeah, it was some sort of error after I changed the base it somehow created two

**Pull request merged**
