### PR TITLE
Minor fix: Array [] syntax standardization

### PR DESCRIPTION
**Pull request by Phobos-7**
Change array syntax from [] TO array() etc. as in other lang files.
As in https://area51.phpbb.com/docs/dev/master/language/usage.html#using-the-language-system-in-php

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**): **PHPBB3-16410**

https://tracker.phpbb.com/browse/PHPBB3-16410

### CODE REVIEW

**Comment by mrgoldy** [comment]
phpBB is trying to move to the new array syntax `[]`, and away from the old array syntax `array()`.
So, changing the other files that still have the old syntax, is more desirable.

Also, your commit message is incorrect and will not pass tests.
You will have to use the commit message template as described [here](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html#commit-messages).

**Comment by Phobos-7** [comment]
mrgoldy, Thank you! That's what I thought. I can change array syntax in all lang files and raise another ticket if that would be helpful.

**Comment by mrgoldy** [comment]
Well, your ticket is fine, you'll just have to adjust the description.
So instead of `[]` to `array()`.
It should become `array()` to `[]`.

And you'll have to amend your last commit message.
Oh, and just noticed that you haven't properly created a branch either.
I suggest reading through the contributing guidelines first.

**Comment by hanakin** [comment]
closing this as its intended coding practice

**Pull request closed without merging**
