### PR TITLE
[ticket/15142] Check extension updates on current branch

### PR DESCRIPTION
**Pull request by VSEphpbb**
PHPBB3-15142

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

https://tracker.phpbb.com/browse/PHPBB3-15142

### CODE REVIEW

**Comment by VSEphpbb** [comment]
!set wip

tests need to be added

Depends on https://github.com/phpbb/customisation-db/pull/210

**Comment by VSEphpbb** [comment]
!set WIP

**Comment by VSEphpbb** [comment]
!unset WIP

**Comment by marc1706** [comment]
This has a rather big merge conflict on 3.2 in acp_extensions. Mind taking a look and creating a PR that'll take care of that or should I do that for you?

**Comment by VSEphpbb** [comment]
I won't be able to look at this until next week. Can you?

**Comment by VSEphpbb** [comment]
@marc1706 by your command, it is done

**Comment by marc1706** [comment]
Thank you. I was unfortunately also busy so couldn't get to it.

**Pull request merged**
