### PR TITLE
[ticket/16314] Fix database connections on controllers

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16314

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-16314

### CODE REVIEW

**Comment by 3D-I** [comment]
Not sure if I have to move it to

```
		if ($task)
		{
			$url = $task->get_url();
			$template->assign_var('RUN_CRON_TASK', '<img src="' . $url . '" width="1" height="1" alt="cron" />');

			garbage_collection();
		}
```

I cqan do it in case.

**Comment by 3D-I** [comment]
!set WIP

**Comment by 3D-I** [comment]
!unset WIP

**Comment by marc1706** [comment]
IMHO this is just a hack for a rather bigger problem: Why are controllers even calling `page_footer()`?
The controller helper `render()` method calls it:
```
page_footer(true, false, false);
```
Which means cron is run, but the template is not displayed and the exit_handler() is not called.
As a result of that, the following tasks are executed in `page_footer()`:
- cron image link is generated
- sql report is output
- call to `garbage_collection()` (hence closing SQL connection)

On controller pages, we currently have two events that are being triggered on kernel terminate, hence after the page is output:
- cron_runner_listener: only executed on cron pages. This might try to access the sql connection which will already be closed as `page_footer()` was called in the controller helper
- kernel_terminate_subscriber: executed on all pages. Calls only `exit_handler()`, hence what was skipped in the controller helper `render()` method.

Based on this, I think the correct solution should be:
- Stop calling `page_footer()` from the controller helper `render()` method
- Add method for outputting cron image link and sql report in controller helper
- Add SQL close call to kernel_terminate_subscriber

**Comment by rxu** [comment]
@marc1706 👍 
1st has an obvious implementation.
2nd can be implemented either as a controller helper method or via refactoring relevant code into method from the `page_footer()`.
3rd can be done simply by adding `garbage_collection()` call before the `exit_handler()` call here https://github.com/phpbb/phpbb/blob/3.3.x/phpBB/phpbb/event/kernel_terminate_subscriber.php#L32

**Comment by rxu** [comment]
Applied the solution path locally and it seems to be solving the issue.

**Comment by rxu** [comment]
Or even better, page_footer() already has an injection of controller_helper service. So the whole call cron script can be transferred to the method in controller helper and then called in `render()` as well as in `page_footer()`.
Also I wonder if it's worth to change the [cron related div](https://github.com/phpbb/phpbb/blob/3.3.x/phpBB/styles/prosilver/template/overall_footer.html#L61-L64) in `overall_footer.html` to something like
```html
<!-- IF RUN_CRON_TASK and not S_IS_BOT-->
<div>
	<a id="bottom" class="anchor" accesskey="z"></a>
	{RUN_CRON_TASK}
</div>
<!-- ENDIF -->
```
because now the div is rendered even if no cron is getting called.

**Comment by 3D-I** [comment]
Thanks guys, 
Am I correct understanding that the PR https://github.com/phpbb/phpbb/pull/5831 should replace this one?

**Comment by rxu** [comment]
> Am I correctly understanding that the PR #5831 should replace this one?

Yeah, I guess so.

**Comment by 3D-I** [comment]
Closing then :+1:

**Pull request closed without merging**
