### PR TITLE
[ticket/15151] ACP Cookie settings add explanatory text 

### PR DESCRIPTION
**Pull request by nomind60s**
In ACP->Cookie settings there were a number of fields without explanation text, which can lead to misconfigured settings.

This PR improves the lead section to include a link to the phpBB.com Knowledge Base for troubleshooting and adds explanation text for the Cookie domain, Cookie name and Cookie path fields which could help reduce the number of discussions on the phpBB.com Support forums regarding fixing incorrect cookies.

The explanation text is drawn from a couple of resources, the Knowledge Base article for [Fixing Incorrect Cookies](https://www.phpbb.com/support/docs/en/3.1/kb/article/fixing-incorrect-cookie-settings/) and the development Wiki article on [Support/Cookie domain](https://wiki.phpbb.com/Support/Cookie_Domain).

PHPBB3-15151

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15151

### CODE REVIEW

**Comment by vinny** [comment]
Just like the other phpbb.com links used in the core, this link should be replaced by a redirect, something like [https://www.phpbb.com/go/cookie-settings](https://www.phpbb.com/go/cookie-settings)
@phpbb/website-team @phpbb/development-team

**Comment by marc1706** [comment]
PRs for website:
- https://github.com/phpbb/website/pull/143
- https://github.com/phpbb/phpbb-website/pull/118

**Comment by Nicofuma** [comment]
Thanks for contributing

**Comment by marc1706** [comment]
Just noting that the link now also works: https://www.phpbb.com/go/cookie-settings

**Comment by nomind60s** [comment]
Thanks Marc.

**Pull request merged**
