### PR TITLE
[ticket/16463] Fix "acp_board.php" for "ACP_SUBMIT_CHANGES".

### PR DESCRIPTION
**Pull request by dark-1**
PHPBB3-16463

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16463

### CODE REVIEW

**Comment by dark-1** [comment]
can somebody please restart this job : https://travis-ci.org/github/phpbb/phpbb/jobs/682509357

Thanking you , Best regards 👍

**Comment by mrgoldy** [comment]
Relates to #5228, however does not include the HTML changes.

**Comment by dark-1** [comment]
@mrgoldy ,

Can you please explain a little more,
coz I don't understand with respect to #5228 what more changes are required.

Also there are no changes for `phpBB/adm/style/acp_board.html` in that PR.

Thanking you , Best regards 👍

**Comment by mrgoldy** [comment]
Well, the aim of this PR is to have consistency in the 'Submit changes' fieldset in the ACP.
That is the exact same goal as the mentioned PR, only that one also adjusts HTML of various template files, and this only adds a few legends to the fieldset. So if we want to have true consistency, we still have to make the HTML changes.

**Comment by dark-1** [comment]
The goal in this PR is to fix only in `acp_board`.
Those other changes from #5228 needs to be done via another PR since it's out of scope of this one.
If you want I'll do those in another PR.

BR 👍

**Comment by mrgoldy** [comment]
It's not out of the scope for this PR. It's not within the specific ticket you created, where one already existed. Especially with small adjustments like these, where no functionality is changed and just the appereance within the ACP, it's more than possible to do it in one PR. So please feel free to add those HTML changes to this PR aswell.

**Comment by mrgoldy** [comment]
In order to provide consistency across all modules in the ACP, the submit buttons should be in their own fieldset. `<fieldset><p class="submit-buttons">... buttons ...</p></fieldset>`. This is not the case in all modules, for example the Attachment Settings module. [Screenshot as example](http://prntscr.com/sbzogq). Those HTML changes are already made in #5228 , that's why I referenced that PR.

**Comment by dark-1** [comment]
Ahh!!! Okay... Now I am getting you...
You want me to remove `'legend{int}' => 'ACP_SUBMIT_CHANGES'` from PHP file at `phpBB/includes/acp/acp_board.php`,
and do the required changes in HTML Template file at `phpBB/adm/style/acp_board.html`,
That's what you mean , Right ???

BR 👍

**Comment by mrgoldy** [comment]
No not really haha. Nevermind, you can leave this PR as it is. Thank you.

**Pull request merged**
