### PR TITLE
[ticket/14303] Use UTF8 quotes in app.php lang file

### PR DESCRIPTION
**Pull request by marc1706**
Replaces #4038 

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14303

### CODE REVIEW

**Comment by marc1706** [comment]
@phpbb-es Next time please try to format the commit message the way I changed it to now: https://github.com/phpbb/phpbb/commit/bb5a1716744e79d2f36e49d5dd1cc0a0fac2a0ff

**Comment by cybernet** [comment]
what's the diff ? @marc1706

**Comment by marc1706** [comment]
@cybernet that diff is stated in the commit message? Instead of using double quotes we're using the utf8 variant of double quotes (which is recommend btw).

**Comment by phpbb-es** [comment]
@marc1706 and @CHItA sorry by error on tracker and patch. 
It is somewhat confusing, I review the information before reporting back. ;)

**Comment by CHItA** [comment]
@phpbb-es no problem, it just a bit extra work on merging for us, and we usually just let people know that we have some requirements on commit message format. So don't worry about it, and thank you for your contribution!

**Pull request merged**
