### PR TITLE
[ticket/16829] forumtitle and lastsubject text decoration hover

### PR DESCRIPTION
**Pull request by Prosk8er**
Fix text decoration on hover for forumtitle and last subject

PHPBB3-16829

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16829

### CODE REVIEW

**Comment by Prosk8er** [comment]
Before:
Screenshot 2021-08-03 170842
Screenshot 2021-08-03 170923
Screenshot 2021-08-03 171028
After:
Screenshot 2021-08-03 171113
Screenshot 2021-08-03 171137
Screenshot 2021-08-03 171152

**Review by hanakin — APPROVED** [review]
👍

**Comment by marc1706** [comment]
Thanks for the PR @Prosk8er

**Comment by Prosk8er** [comment]
> Thanks for the PR @Prosk8er

your welcome @marc1706 glad to help out where and when i can

**Pull request merged**
