### PR TITLE
[ticket/16474] Hide vertical scrollbar for attachbox

### PR DESCRIPTION
**Pull request by rxu**
Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

<a href="https://tracker.phpbb.com/browse/PHPBB3-16474">PHPBB3-16474</a>.

<table>
<tr>
<td>Before</td><td>After</td>
</tr>
<tr>
<td>

</td>
<td>

</tr>
</table>

### CODE REVIEW

**Comment by rxu** [comment]
!set Styles

**Comment by hanakin** [comment]
@rxu what browser/system is this I am unable to recreate

**Comment by rxu** [comment]
That's weird because I have it everywhere.
OS: Windows 10.
Browsers: Opera 68.0.3618.63, Chrome 81.0.4044.138, Edge 44.18362.449.0, IE 11.778.18362.0

**Comment by hanakin** [comment]
Well we do not support opera but it could be a windows only thing. As I do not test for windows at the moment

**Pull request merged**
