### PR TITLE
[ticket/16487] Fix URL for fontawesome 3.2.0 migration

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16487

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16487

### CODE REVIEW

**Comment by DavidIQ** [comment]
Shouldn't this be a new migration?

**Comment by 3D-I** [comment]
Hmm, I think you are right @DavidIQ :thinking:

**Comment by rxu** [comment]
Please don't. 3.3 already has a migration for FA 5, so if you add a new one for FA 4 it will be a mess completely.

**Comment by 3D-I** [comment]
Link to that FA-5 migration please?

**Comment by rxu** [comment]
https://github.com/phpbb/phpbb/blob/3.3.x/phpBB/phpbb/db/migration/data/v33x/font_awesome_5_update.php

**Comment by 3D-I** [comment]
Ok, let me see. Thanks.

**Comment by 3D-I** [comment]
> 
> 
> Link to that FA-5 migration please?

That migration depends on 3.3, this one not. Moreover, I created a new migration which depends on 3.2, therefore the migration you linked above can not mess the things up IMHO.

Let me push and we will discuss it, no probs.

**Comment by 3D-I** [comment]
My thought is the FA 5 migration will overwrite this one which fixes the ancient one.

**Comment by rxu** [comment]
Fixing FA4 URL for 3.3 simply makes no sense. If it's possible to merge this migration into 3.2.x only but not into 3.3.x/master, then it would be okay.

**Comment by 3D-I** [comment]
> And the new FA 5 migration should also depend on this one I guess.

**Comment by rxu** [comment]
> Fixing FA4 URL for 3.3 simply makes no sense.

:)

**Comment by 3D-I** [comment]
Yeah, I see what you mean mate. 

It is just a question of consistence, but maybe that's just me. :)

**Comment by marc1706** [comment]
How about adding an effectively installed check that marks the FA 4 migration as effectively installed if the config version is greater or equal to 3.3.0? And of course have the FA 5 migration depend on the new FA 4 migration.

**Comment by 3D-I** [comment]
That's indeed a good idea.

**Comment by 3D-I** [comment]
> And of course have the FA 5 migration depend on the new FA 4 migration.

This means a new PR for that, am I wrong?

**Pull request merged**
