### PR TITLE
[ticket/14315] Correctly set permission roles for multiple groups

### PR DESCRIPTION
**Pull request by marc1706**
The previous code was based on multiple false implications. These changes should fix those.

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14315

### CODE REVIEW

**Comment by Nicofuma** [comment]
Should be possible to write a test for that, right?

**Comment by Nicofuma** [comment]
@marc1706 bump for a test?

**Comment by marc1706** [comment]
Hardly testable thx to all that javascript. I'll probably have to take a look at the ui tests ...

**Comment by Nicofuma** [comment]
IIRC the JS is just to hide/show the tabs using `display: none`. Rigth? Because if it is the case you don't need the UI tests, the form is present in the DOM.

**Comment by marc1706** [comment]
Turns out it didn't actually work without javascript. I've added back the previous select. It will get hidden by the javascript code and replaced by the span that allows us to show tooltips.

**Comment by marc1706** [comment]
This also means I'll probably have to add both normal functional tests and ui tests for the javascript part.

**Comment by marc1706** [comment]
@Nicofuma added ui and functional tests

**Comment by marc1706** [comment]
Having some issues with ui tests randomly acting up

**Comment by marc1706** [comment]
@Nicofuma UI tests seem to be fixed now. Session ID for ACP was incorrectly retrieved from cookies.

**Comment by Nicofuma** [comment]
nice, thanks

**Pull request merged**
