### PR TITLE
[ticket/14161] Wrong var name for core.download_file_send_to_browser_before

### PR DESCRIPTION
**Pull request by Zoddo**
`extension` must be `extensions`

Introduced in fix of [PHPBB3-14101](https://tracker.phpbb.com/browse/PHPBB3-14101) (PR GH-3831)

[PHPBB3-14161](https://tracker.phpbb.com/browse/PHPBB3-14161)

### CODE REVIEW

**Comment by Zoddo** [comment]
!set Event

**Comment by Zoddo** [comment]
I think ... I need to add a `@change` line in the docblock or not?

**Comment by marc1706** [comment]
Yes, please do that.

**Comment by Zoddo** [comment]
@marc1706 : Done :)

**Comment by Nicofuma** [comment]
:+1:

**Pull request merged**
