### PR TITLE
[ticket/15019] Smiley Limit to a Higher Value

### PR DESCRIPTION
**Pull request by Leinad4Mind**
Changing the value from 1000 to 2000 for the smiley limit.

Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket: https://tracker.phpbb.com/browse/PHPBB3-15019

### CODE REVIEW

**Comment by Nicofuma** [comment]
You commit message is not correctly formatted, it must end with PHPBB3-15019 on a single line.
I also think it would be better to completely remove this limit as it does not really have any reason to be today.

**Comment by Leinad4Mind** [comment]
Done. (I guess)

**Comment by hanakin** [comment]
click the format link in you post at the top to read the rules for proper commits. You are missing the `PHPBB3-15019` in the commit message body

**Comment by Elsensee** [comment]
I wonder why this was ever introduced. Looks fine to me as soon as the commit msg is fixed.

**Comment by Leinad4Mind** [comment]
Dunno how to change it via website.

**Comment by VSEphpbb** [comment]
@Elsensee I assume it was added because having more than 1000 smilies is absurd ;)

**Comment by Leinad4Mind** [comment]
Many people wants to add all the emojione collection ~1800 emojis as smilies.
That way they can easely add a emoji system (extension) with a smilie system working very well together. ;)

**Comment by VSEphpbb** [comment]
We already have emoji support since 3.2 AFAIK.

**Comment by Leinad4Mind** [comment]
Exactly, and thats the main reason for this.

**Comment by DavidIQ** [comment]
To duplicate the already existing and supported emojis into smileys?

**Comment by marc1706** [comment]
I've looked into this further and it really seems like having an excessive amount of smilies can significantly slow down the board and cause further issues. The recommended way to go is using emoticons that allow a great range of possible icons. To extend that functionality 1000 smilies is more than enough. As already mentioned, duplicating emoticons to smilies is also not recommended as that doesn't just duplicate content but probably can cause even more issues.

Closing this and the ticket as such.

**Pull request closed without merging**
