### PR TITLE
[ticket/15592] Hide button L_PLACE_INLINE when BBCODE disabled. Update posting_attach_body.html

### PR DESCRIPTION
**Pull request by sudhanshu16**
Checklist:

 Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15592

### CODE REVIEW

**Comment by hanakin** [comment]
this should be rebased against 3.2.x, not master (pls rebase manually and not using github interface as its bugged in relation to Jira integration)

**Comment by 3D-I** [comment]
This is the correct way by my side as well. Simple and effective, consistent with the core code itself.

**Comment by hanakin** [comment]
also, the error is coming from the fact that you used google interface to build your patch and it submits it with an incorrect line ending formats. Suggest you fork the reop and re-submit everything manually to avoid this.

**Comment by sudhanshu16** [comment]
@3D-I @haklop @hanakin 
Thanks for review.
I am on it. Will update after rebase as soon as possible

**Pull request closed without merging**
