### PR TITLE
[ticket/15405] Create minified version of css

### PR DESCRIPTION
**Pull request by hanakin**
This pr is just adding a minified version and the tools to create it. The usage of it can be handled in a different pr. We can look at adding the generation of it to the build/test processes for release by simply running gulp minify.

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

PHPBB3-15405

https://tracker.phpbb.com/browse/PHPBB3-15405

### CODE REVIEW

**Comment by vinny** [comment]
Question: How do you plan to do this in the files bidi.css, plupload.css and tweaks.css?

**Comment by hanakin** [comment]
Tweaks is now irrelevant and is being repurposed in pro silver meaning that it’s been added by default. I made a or for it already. Bidi should never have been included dynamically this is counterintuitive and over complicates the ring so it will also be included by default. As for pupload I have not looked into yet as I have no idea what it’s purpose is.

**Comment by hanakin** [comment]
ok should be good to review now, just merge https://github.com/phpbb/phpbb/pull/5049 first

**Comment by hanakin** [comment]
Closing and replacing with https://github.com/phpbb/phpbb/pull/5496

**Pull request closed without merging**
