### PR TITLE
[ticket/16574] Remove flash BBcode

### PR DESCRIPTION
**Pull request by senky**
PHPBB3-16574

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16574

### CODE REVIEW

**Comment by 3D-I** [comment]
What's the problem here?

**Comment by rxu** [comment]
> What's the problem here?

`flash` BBCode tests weren't removed from text reparser tests, hence the failures.

**Comment by senky** [comment]
It's a draft, please be patient. ;)

**Comment by 3D-I** [comment]
Yeah sure, no rush. Just I wanted to know the reasons why still is draft.

**Comment by 3D-I** [comment]
First you should amend the tracker ticket to be 16574` in the PR template, in order to avoid weird results over there, that's just a note. 
immagine

Morevover I still do not see the reason for to remove FLASH in `4.0.x`, IMHO this should go for `3.3.x` as I said in the tracker long ago. Ref.: https://tracker.phpbb.com/browse/PHPBB3-16574

**Comment by 3D-I** [comment]
https://www.adobe.com/products/flashplayer/end-of-life.html

> Since Adobe will no longer be supporting Flash Player after **December 31, 2020** and Adobe will block Flash content from running in Flash Player beginning **January 12, 2021**, Adobe strongly recommends all users immediately uninstall Flash Player to help protect their systems.  

I personally think this change is due in phpBB 3.3.x, if you don't have time to define it I think I could help continue your work for the good of all. Thanks.

**Comment by 3D-I** [comment]
Any news?

**Comment by MichaIng** [comment]
Giving this a friendly bump as well, and I agree that this should be backported to 3.3.x. It's confusing to have the flash BBCode button present on a fresh phpBB instance 🙂.

**Comment by marc1706** [comment]
Rebased on top of latest master

**Comment by marc1706** [comment]
Cleanup up tests and should now be good for review (cc @senky )

**Comment by hanakin** [comment]
Front-end changes look good to me 👍

**Review by CHItA — APPROVED** [review]

**Comment by neuropass** [comment]
> 
> 
> Given that [Chromium removed support for Flash at the end of last year](https://www.blog.google/products/chrome/saying-goodbye-flash-chrome/) and the other major browsers followed suit, if you're using a browser that still supports Flash you have bigger issues. 😉

is there any time line link available? there used to be a public post somewhere about EOL etc etc regarding different phpBB versions...

**Comment by nomind60s** [comment]
> > Any change for a backport to v3.3? 🙂
> > I see the question came up already, but no agreement on this, yet.
> 
> 3.3 is in maintenance mode so we are only fixing bugs and security issues.
In 3.3, in ACP-Posting->Post settings there is **Allow use of [FLASH] BBCode tag in posts:** which can be set to No to mostly remove the flash BBCode. AFAIK it almost completely removes FLASH from view for the membership, with one exception. In the posting editor, in the side panel under the smilies it still shows [flash] is OFF. 
Screenshot 2022-03-05 062219

I believe a simple bugfix in posting_editor.html that can hide the [flash] is OFF in 3.3.

**Comment by MichaIng** [comment]
Please open a ticket and PR 👍.

**Comment by DavidIQ** [comment]
> I believe a simple bugfix in posting_editor.html that can hide the [flash] is OFF in 3.3.

What's the bug? That the list that shows bbcodes being on or off shows the flash one as being off? Seems like that was intended.

**Comment by MichaIng** [comment]
Not a bug indeed, but it may be irritating when it isn't possible to enable it (reasonably) and on that prominent place it looks like it is still supported.

**Comment by DavidIQ** [comment]
Seems like an anti-pattern to do that.

**Pull request merged**
