### PR TITLE
[ticket/15572] Fix W3C validation error for quote BBCode

### PR DESCRIPTION
**Pull request by AlfredoRamos**
Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-15572

### CODE REVIEW

**Comment by AlfredoRamos** [comment]
!set HTML
!set CSS
!set Styles

**Comment by AlfredoRamos** [comment]
!set WIP

**Comment by 3D-I** [comment]
Does it also take into consideration the quotes in PMs? `@msg_url`

**Comment by AlfredoRamos** [comment]
@3D-I I thought about it but I'm not sure if I should also check for the `@msg_url` (`cite` attribute) since that URL links to a private content, which is not publicly accessible.

**Comment by AlfredoRamos** [comment]
!unset WIP

**Comment by dark-1** [comment]
Well !!! in PM , there is no way for a W3C validator to do any validation.
So this PR is perfect for `@post_url`.

Also nice that you changed `div` to `span` 😄 

Best regards 👍

**Comment by rxu** [comment]
After this change, what will happen with BBCode in old posts (already saved in database)? Will they require reparsing?

**Comment by AlfredoRamos** [comment]
@rxu no, it only requires the user to clear the cache so TextFormatter can read that file to setup those BBCodes again.

**Comment by rxu** [comment]
What I meant is whether quote BBCode in 'old' posts will be broken. So if they won't, that's good.

**Comment by AlfredoRamos** [comment]
@rxu in my tests I didn't had problems with previously posted messages.

Should I keep the `blockquote cite > div` CSS selector just to be sure? Because the worst thing that can happen is that date won't be located at the right of the quoted message.

**Comment by rxu** [comment]
Tested locally: posted a message and then applied the changes from the PR.
Before:
image

After:
image

**Comment by dark-1** [comment]
> After:
> image

I think you forgot the CSS part.
Here : https://github.com/phpbb/phpbb/pull/5932/files#diff-640d4c568fbd9176eefbdfbd5782e31aR487

Best regards 👍

**Comment by rxu** [comment]
I did apply HTML/CSS part while recompiling outdated templates setting is on, but purging cache made it right, my bad :)
image

**Comment by dark-1** [comment]
> I did apply both of HTML/CSS parts while recompiling outdated templates setting is on, but purging cache made it right, my bad :)

Ahh! Nice 😍 .

Best regards 👍

**Comment by mrgoldy** [comment]
> @3D-I I thought about it but I'm not sure if I should also check for the `@msg_url` (`cite` attribute) since that URL links to a private content, which is not publicly accessible.
Could you expand a bit please?
Cause just because it's not accessible for bots, shouldn't mean it can have invalid markup.

**Comment by AlfredoRamos** [comment]
@mrgoldy The missing `cite` attribute (`<blockquote cite="...">`) doesn't make the markup invalid.

I said that I didn't include that attribute on private messages because I didn't see the point for it.

**Comment by marc1706** [comment]
Agreed, the cite attribute will definitely help the search engines there. :)

**Pull request merged**
