### PR TITLE
[ticket/16729] Fix Unknown named parameter in Log - PHP 8

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16729

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16729

### CODE REVIEW

**Comment by rxu** [comment]
Faced this issue as well in extension. Just wonder what was changed so that it worked before but not currently.

**Comment by MichaIng** [comment]
> Just wonder what was changed so that it worked before but not currently.

Ditto, in our case regular user logs caused the error in very rare cases an I was unable to identify the difference of the "faulty" logs versus others, or how resorting/flattening the array does solve it. @3D-I do you have a guess about the origin of the error?

**Comment by 3D-I** [comment]
Nothing changed since 7 years ago in this file's lines (see https://github.com/phpbb/phpbb/commit/668f248c4d88b066a559e23d53d57e7170570c4c ) so I am not sure if something happened here, I would say no. 

There is some good read about named parameters/arguments in PHP8 though
https://stitcher.io/blog/php-8-named-arguments

In our use case the `array_values()` keeps the same `key->value` _explicitely organized by the `foreach()` before._
See https://www.php.net/manual/en/function.array-values.php#114941

Also, a deep search resulted in the same solution for a lot of cases for symfony, wordpress, etc etc.

**Comment by rxu** [comment]
Explanation is here https://wiki.php.net/rfc/named_params#call_user_func_and_friends
> For call_user_func_array(), this behavior constitutes a minor backwards-compatibility break: Previously, array keys were completely ignored by this function. Now, string keys will be interpreted as parameter names.

Hence the error: if your code (f.e. extension) passes non-numeric keys from its logs (f.e. `'username' => 'Joe'`) PHP8 treats it as a named argument. As far as `$username` argument doesn't exist in `$language->lang()` function, PHP8 throws error.

**Comment by MichaIng** [comment]
Thanks, that makes sense.

I still wonder why the `$log_data` parameter is not defined only for very rare user log entries. A lot of user log rows, which do not cause that error, have a `log_data` value, a lot do not. If I remember right, last time the error didn't show up anymore after I removed a log entry without any `log_data` value from the database.

**Comment by rxu** [comment]
Well, it would need `var_dump($lang_arguments);` before the line 698 while error occurs to probably get some idea. Actually the error described in your topic would occur if the array has something like `'log_data' => 'somecontent'` in it. Which shouldnt't happen ever.

**Comment by 3D-I** [comment]
@MichaIng Your use case is different from others where the parameter is diffeent but the same error is thrown, I posted a link in the tracker so that you can see.

@rxu That's a bug related to PHP 8 in any case. If the extension's system is not able to produce a warning or an error... that does not means we can not try and fix bad behaviours. In this case it seems to me that's a simple addition that does not harms, instead it is currently on the chords of the latest code practise.

**Comment by MichaIng** [comment]
I added
```
echo '<pre>' . var_dump($lang_arguments) . '</pre>';
```
between line 697 and 698 and removed the fix for the bug. Error 500 happens and the last line of the page shows:
```
array(2) { [0]=> string(16) "LOG_USER_DELETED" ["log_data"]=> string(73) "User <username> (ID <userID>) has deleted their own account. They had no posts." }
```

**Comment by 3D-I** [comment]
That`s why `array_values()` comes in handy here.

**Comment by MichaIng** [comment]
It it the same problem with the other apps, creating log entries `log_data` field content with non-numerical keys? So basically it is indeed a bug in the extensions and while this can be seen as argument to not change core code, phpBB can be more compatible by pro-actively prevent such errors, extension-wise. Not such a trivial decision, as it may open a can of worms. Also there are reasons for PHP8 being stricter, and it is not always good to work around errors symptom-wise, when it would be possible to solve them root-wise, and maintaining the ability to even detect such originating "bugs", like the missing named argument declarations.

Btw, I verified that the above log entry is indeed the one that causes the error, also it is the only one of that type, present in the database.

**Comment by rxu** [comment]
> And the app seems to produce a `log_data` field with an `"log_data"` key in itself, which causes the error here?

Yeah, with this code in `\brokencrust\deletemyaccount\ucp\main_module.php`:
```// Add the deletion to the user log using ANONYMOUS user_id (we have to do this before the delete otherwise it won't work)
$phpbb_log->add('user', ANONYMOUS, $this->user->data['user_ip'], 'LOG_USER_DELETED', time(), array('reportee_id' => ANONYMOUS, 'log_data' => $log));```

**Comment by MichaIng** [comment]
Another report: https://www.phpbb.com/community/viewtopic.php?t=2594401

@rxu 
Many thanks for pointing this out. Correct should be:
```
$phpbb_log->add('user', ANONYMOUS, $this->user->data['user_ip'], 'LOG_USER_DELETED', time(), array('reportee_id' => ANONYMOUS, $log));
```
right?

I changed the database field from:
```
a:1:{s:8:"log_data";s:73:"User sigamtec (ID 9085) has deleted their own account. They had no posts.";}
```
to
```
a:1:{s:8;s:73:"User sigamtec (ID 9085) has deleted their own account. They had no posts.";}
```
and it works now without applying this commit.

Sadly the extension is not developed anymore, but for me it is very important that users are able to remove their own accounts without needing to contact an admin first. I didn't overlook a newer/maintained extension which provides this functionality, do I? At it's going OOT, sorry 😉.

**Comment by rxu** [comment]
> right?

Yep. It just about getting rid of array index for custom log data.

**Review by CHItA — APPROVED** [review]

**Pull request merged**
