### PR TITLE
[ticket/13513] Use paths relative to the phpBB root in the router

### PR DESCRIPTION
**Pull request by Nicofuma**
https://tracker.phpbb.com/browse/PHPBB3-13513

PHPBB3-13513

### CODE REVIEW

**Comment by Nicofuma** [comment]
bump, this is pretty important (currently the acp login page is broken if an extension try to display a link)

**Comment by naderman** [comment]
@Nicofuma please reply to joas on the tracker.

**Comment by Nicofuma** [comment]
Sorry I missed it

**Comment by marc1706** [comment]
Merged by https://github.com/phpbb/phpbb/commit/c9df29d680990d83fe2380e79a7bd5833f0cac34

**Pull request closed without merging**
