### PR TITLE
[ticket/14961] Add cookie notice as enablable feature

### PR DESCRIPTION
**Pull request by marc1706**
Uses Insites cookieconsent v3.0.3:
https://cookieconsent.insites.com

PHPBB3-14961

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14961

### CODE REVIEW

**Comment by marc1706** [comment]
Full view:
image
Responsive view:
image

ACP view (no cookie bar in ACP btw):
image

**Comment by vinny** [comment]
maybe add a mention in [phpBB/docs/CREDITS.txt](https://github.com/phpbb/phpbb/blob/master/phpBB/docs/CREDITS.txt)

**Comment by Nicofuma** [comment]
TBH, I'm not that sure it should be in core.... I think it would be better as an official ext because we definitely don't want to support any internet law of any country around the world... Too much work. (the same apply for the american law that is currently supported by the core)

**Comment by marc1706** [comment]
I'd rather not ship another extension with something as simple as this cookie notice. Cookie notices have become an industry standard and I think we should have this in the core if people are wishing to enable it.

**Comment by Crizz0** [comment]
I'm fine with that feature in the core. I think it is useful for a lot of phpBB-users and nearly everyone uses that thing at the moment. Personally I don't need it and really hate it, because it is like "attention, we use HTML, CSS, JS..., please accept that".

**Pull request merged**
