### PR TITLE
[ticket/16268] Refactor ACP Resynchronise or reset statistics layout

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16268

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16268

### CODE REVIEW

**Comment by 3D-I** [comment]
immagine

---

immagine

**Comment by hanakin** [comment]
why are we changing these? Design wise it does not really fit the rest of the page...From a UI standpoint it is also jaring.

**Comment by 3D-I** [comment]
Because the way it is now is ugly as hell, not to mention the UI xstandpoint. lol.

immagine

**Comment by hanakin** [comment]
The UI as it is is still cleaner though then the proposal. Neither is
really the proper way to handle this but the current is close enough for
now for 3.3

**Comment by 3D-I** [comment]
That's your opinion, not mine.

**Comment by 3D-I** [comment]
I have a better idea for this, though.

**Pull request closed without merging**
