### PR TITLE
[ticket/14678] Forum title hidden on viewforum without f_list permission

### PR DESCRIPTION
**Pull request by markshawtoronto**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-14678

### CODE REVIEW

**Comment by Crizz0** [comment]
Hi,

please fix your existing commit message, it is too long! No line should contain more than 79 characters! See: https://wiki.phpbb.com/Git#Commit_Messages

How do you do that? Take a look into this section: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Regards

**Comment by markshawtoronto** [comment]
@Crizz0,

I think I fixed it, sorry about that!

**Comment by marc1706** [comment]
This seems more like a misconfiguration than an actual bug. The f_list permission is exactly used for what it does currently. If you don't have the f_list permission, you should not see a listing of the current forum while still being able to see it

**Comment by markshawtoronto** [comment]
Sorry for the delay. I guess that's fair, you can close this PR & ticket.

I'll just workaround the title missing on my forum.

**Comment by marc1706** [comment]
Closing as such

**Pull request closed without merging**
