### PR TITLE
[ticket/16273] Check whether the index exists in memberlist - PHP 7.4

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16273

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16273

### CODE REVIEW

**Comment by rubencm** [comment]
phpBB 3.3 should be compatible with php7.3 too

**Comment by 3D-I** [comment]
> 
> 
> phpBB 3.3 should be compatible with php7.3 too

Tested also with PHP 7.3.5, am I missing something?

**Comment by rubencm** [comment]
I'm not sure, but don't you have to cast it to a boolean now?, since database return an integer

**Comment by rubencm** [comment]
Somehow I think this will fail sooner or later. @3D-I 

PHP 7.3:
```php
false['']; // return null, no error
```

PHP 7.4:
```php
false['']; // php notice: "Trying to access array offset on value of type bool"
false['']??false; // return false, no error
```

I propose change it to this:
```php
$var = $row ? (bool) $row['foo'] : false;
```

**Comment by 3D-I** [comment]
What about?

```
if ($row)
{
	$foe = (bool) $row['foe'];
	$friend = (bool) $row['friend'];
}
```

**Comment by rubencm** [comment]
Yes, is the same

**Comment by 3D-I** [comment]
Dunno what to do here, should I open a new ticket? :thinking:

**Comment by rubencm** [comment]
Probably the same is ok

**Comment by 3D-I** [comment]
Nope, your approach is ok.

**Pull request merged**
