### PR TITLE
[PHPBB3-15133] Pompeiisneaks getimagesize bug

### PR DESCRIPTION
**Pull request by pompeiisneaks**
Checklist:

- [X ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15133

### CODE REVIEW

**Comment by pompeiisneaks** [comment]
Looking over the Travis -ci build failures, (I didn't review them all, just the first few) they're unrelated to the code changes I put in...?

**Comment by DavidIQ** [comment]
You're targeting master when you should be targeting 3.1 or 3.2.

**Comment by pompeiisneaks** [comment]
Actually I targeted  3.2, someone else changed it.PhilOn Mar 22, 2017 8:58 PM, David Colón <notifications@github.com> wrote:You're targeting master when you should be targeting 3.1 or 3.2.

**Comment by hanakin** [comment]
@pompeiisneaks that was changed on the tracker not on github next to the green open button on the top of this page if you read it says `phpbb:master` branch. This should be against `phpbb:3.2.x`

**Comment by DavidIQ** [comment]
Also your commit message is wrong so even after you change the branch you are targeting in this pull request the build will fail anyways.

**Comment by pompeiisneaks** [comment]
Sorry I apparently don't know how to github.  I read the docs that said to merge to the version it was related to, so I swear I did... I've changed the pull request to 3.2.

**Comment by pompeiisneaks** [comment]
DavidIQ what did I miss on the commit message?

**Comment by DavidIQ** [comment]
Don't really know anymore, although you probably didn't follow the commit message requirements which are linked to in the pull request details. You're probably going to have to start a new pull request as this now seems to have 250+ commits, you have merge conflicts, and the build fails.

**Comment by marc1706** [comment]
Please don't close pull requests that target the branch next time. This causes tickets to be re-opened as the linked commits are inside a declined pull request.

**Comment by pompeiisneaks** [comment]
I'm using the same ticket ID that I opened (the bug that is in JIRA) unless you're talking about a different ticket other than the bug in JIRA?  I googled and couldn't find any way to reuse the existing pull request, sorry.  I'd definitely love to find some documentation on that.

**Pull request closed without merging**
