### PR TITLE
[ticket/13767] Remove vendor/s9e/text-formatter/.git during build

### PR DESCRIPTION
**Pull request by s9e**
PHPBB3-13767

### CODE REVIEW

**Comment by marc1706** [comment]
Couldn't you just add that to your .gitattributes for the text-formatter using export-ignore?

**Comment by s9e** [comment]
I don't know anything about export-ignore. build.xml has a bunch of `<delete dir="${dir}/vendor/*/.git" />` commands, I'm just going with the flow.

**Comment by marc1706** [comment]
I'm talking about something like this: https://github.com/marc1706/fast-image-size/blob/master/.gitattributes

That'll prevent hardcoded commands for cleaning the vendor directory.

**Comment by s9e** [comment]
I don't know how that's supposed to work. The fact that there are several commands that delete .git directories leads me to believe that it doesn't.

**Comment by bantu** [comment]
Considering that there are already delete statements for other .git directories, this is fine. We should rearrange this so all .git directories are removed before packaging.

**Comment by bantu** [comment]
unfortunately, phing package fails with a segfault in php right now. not caused by this patch, though. https://gist.github.com/bantu/28ac9251ccf1c908b053

**Comment by s9e** [comment]
@bantu I looked at your segfault out of curiosity and I know *exactly* what line of code triggers it: [this one](https://github.com/s9e/TextFormatter/blob/693fe939bd4e0e0a5b9020af5c8ace7b8606b5bc/src/Bundles/MediaPack.php#L29). Apparently PHP segfaults if a string has too many backslashes. [Here's a similar case from Symfony's issue tracker](https://github.com/symfony/symfony/issues/9462).

I think that https://github.com/s9e/TextFormatter/commit/559f3c4def03e5fbbf5301198ccd69c91d902659 will fix it but I'm waiting on Travis before sending a PR.

**Comment by brunoais** [comment]
This reminds me a sentence somewhat like this:

> Those high level languages memory management... Even though they try to hide it hard that memory doesn't exist for the developer, the developer still needs to think about the memory behind. Worst of all, if they fail at memory management, there's nothing the programmer can do to solve it. He always has to solve the problem differently, if he wants the problem solved.

**Pull request merged**
