### PR TITLE
[ticket/16021] Recognize number of Template Event instances in events.md file

### PR DESCRIPTION
**Pull request by dark-1**
PHPBB3-16021

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16021

### CODE REVIEW

**Comment by battye** [comment]
https://github.com/phpbb/phpbb/blob/22ca7474ea2e597c0ddf726e728298da6e942db9/phpBB/phpbb/event/md_exporter.php#L397

I've seen this in [other places](https://github.com/phpbb/phpbb/blob/c79da081d8ba089f194836a84404ee341dc49960/phpBB/includes/mcp/mcp_logs.php#L47) in phpBB too. Why do we do it this way 
when `list($file) = explode(" ", $file);` would [also work](http://sandbox.onlinephpfunctions.com/code/9903f0101667088b282e4b461cf744399d5d40a0) and not look as weird?

**Comment by dark-1** [comment]
> [phpbb/phpBB/phpbb/event/md_exporter.php](https://github.com/phpbb/phpbb/blob/22ca7474ea2e597c0ddf726e728298da6e942db9/phpBB/phpbb/event/md_exporter.php#L397)
> 
> Line 397 in [22ca747](/phpbb/phpbb/commit/22ca7474ea2e597c0ddf726e728298da6e942db9)
> 
>  				list($file, ) = explode(" ", $file); 
> I've seen this in [other places](https://github.com/phpbb/phpbb/blob/c79da081d8ba089f194836a84404ee341dc49960/phpBB/includes/mcp/mcp_logs.php#L47) in phpBB too. Why do we do it this way
> when `list($file) = explode(" ", $file);` would [also work](http://sandbox.onlinephpfunctions.com/code/9903f0101667088b282e4b461cf744399d5d40a0) and not look as weird?

Check this out : https://discordapp.com/channels/220192692573962241/508793337315328016/568681159597228062

Best regards 👍

**Comment by dark-1** [comment]
@battye ,

Done 👍

**Comment by dark-1** [comment]
@marc1706 ,

May I know why is this PR not merged yet ??
Does it required me to do anything more??

If required , then let me know... I'll do the needful...

Thanking you , Best regards 👍

**Comment by marc1706** [comment]
Nope, just didn't get to it yet.

**Comment by dark-1** [comment]
Thanks 😄

**Pull request merged**
