### PR TITLE
[ticket/11838] OAuth registration from ucp_register

### PR DESCRIPTION
**Pull request by senky**
PHPBB3-11838

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-11838

### CODE REVIEW

**Comment by senky** [comment]
It is not used in the file. I thought we don't want to mix twig with phpbb template syntax in one file...

**Comment by hanakin** [comment]
Negative any changes should use twig

**Comment by hanakin** [comment]
@Nicofuma https://area51.phpbb.com/phpBB/viewtopic.php?f=131&t=58241

**Comment by marc1706** [comment]
@senky the current approach is to use twig syntax whenever changing and/or adding new html code

**Pull request merged**
