### PR TITLE
[ticket/13710] Allow template events near smilies display

### PR DESCRIPTION
**Pull request by RMcGirr83**
[PHPBB3-13710] (https://tracker/phpbb.com/browse/PHPBB3-13710)

### CODE REVIEW

**Comment by prototech** [comment]
The last line in the commit message should simply be PHPBB3-13710. You can link to the ticket using markdown while creating the PR.

**Comment by RMcGirr83** [comment]
***sigh***

**Comment by RMcGirr83** [comment]
!set Event

**Comment by RMcGirr83** [comment]
@Nicofuma you set for 3.1.5 I should update events.md to state as of 3.1.5?

**Pull request merged**
