### PR TITLE
[ticket/16224] Update composer dependencies - 3.2.x version

### PR DESCRIPTION
**Pull request by marc1706**
PHPBB3-16224

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16224

### CODE REVIEW

**Comment by marc1706** [comment]
```
 $ php ../composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 27 updates, 0 removals
  - Updating guzzlehttp/guzzle (5.3.3 => 5.3.4): Downloading (100%)         
  - Updating marc1706/fast-image-size (v1.1.4 => v1.1.5): Loading from cache
  - Updating patchwork/utf8 (v1.3.1 => v1.3.2): Loading from cache
  - Updating symfony/polyfill-ctype (v1.11.0 => v1.13.1): Loading from cache
  - Updating symfony/filesystem (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/config (v2.8.50 => v2.8.52): Loading from cache
  - Updating psr/log (1.1.0 => 1.1.2): Loading from cache
  - Updating symfony/debug (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.11.0 => v1.13.1): Loading from cache
  - Updating symfony/console (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/finder (v2.8.50 => v2.8.52): Loading from cache
  - Installing symfony/polyfill-util (v1.13.1): Loading from cache
  - Installing symfony/polyfill-php56 (v1.13.1): Loading from cache
  - Updating symfony/polyfill-php55 (v1.11.0 => v1.13.1): Downloading (100%)         
  - Updating symfony/polyfill-php54 (v1.11.0 => v1.13.1): Downloading (100%)         
  - Updating symfony/http-foundation (v2.8.50 => v2.8.52): Downloading (100%)         
  - Updating symfony/event-dispatcher (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/http-kernel (v2.8.51 => v2.8.52): Downloading (100%)         
  - Updating symfony/dependency-injection (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/proxy-manager-bridge (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/routing (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/twig-bridge (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/yaml (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/dom-crawler (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/browser-kit (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/css-selector (v2.8.50 => v2.8.52): Loading from cache
  - Updating symfony/process (v2.8.50 => v2.8.52): Loading from cache
  - Updating phpspec/prophecy (1.8.1 => 1.9.0): Loading from cache
  - Updating michelf/php-markdown (1.8.0 => 1.9.0): Downloading (100%)         
Package phpunit/dbunit is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Package sami/sami is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files

```

**Comment by rubencm** [comment]
https://tracker.phpbb.com/browse/PHPBB3-16056

**Comment by marc1706** [comment]
I think that should already be fixed in 3.3.0-b2 as well (just as FYI).

**Comment by rubencm** [comment]
Ok, then I close it

**Pull request merged**
