### PR TITLE
[ticket/15249] Fix the display of Cookie notice on Windows Mobile 8.1

### PR DESCRIPTION
**Pull request by Galixte**
PHPBB3-15249

Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15249

### CODE REVIEW

**Comment by vinny** [comment]
Not sure if we should change external library.

**Comment by DavidIQ** [comment]
We shouldn't, no. This is not the proper fix as it will be lost when this library is updated.

**Comment by Galixte** [comment]
It’s a simple report to you about a possibly way to fix it, but i decide what is the good way.

So, this is the limit of my approach, i’m not a developer.

Do i close this PR ?

**Comment by rxu** [comment]
@Galixte Actually yes, but you can make a suggestion to the library authors here https://github.com/insites/cookieconsent/ (either by creating an issue or a PR 😉 ).

**Comment by Galixte** [comment]
Thanks !-)

**Comment by Galixte** [comment]
@rxu @Nicofuma They answered me: https://github.com/insites/cookieconsent/issues/202#issuecomment-405626304 So, could you tell me if you need to update anything?

**Pull request closed without merging**
