### PR TITLE
[ticket/15378] Add core.twig_environment_inject_assets_after

### PR DESCRIPTION
**Pull request by senky**
PHPBB3-15378

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15378

### CODE REVIEW

**Comment by Elsensee** [comment]
Actually, do you need the `placeholder_salt`? If not, you can just use the `kernel.response` event by Symfony..?

**Comment by senky** [comment]
I don't need this. Ticket author asked for it and I just included as much variables as possible to make event more usable. If you think this is a security risk, I will remove it.

**Comment by Elsensee** [comment]
That's not what I'm trying to say.

First, the placeholder_salt will be basically useless *after* everything containing that salt is replaced.
Second, I wanted to say that there already is such an event, just not in phpBB but in Symfony. It's called `kernel.response`.

**Comment by Nicofuma** [comment]
I don't really like this event. The correct event according to the needs expressed in the ticket is kernel.response as said @Elsensee (but it works only for app.php pages I know, an idea could be to fake this event on other pages).

Otherwise, if you want to manipulate the assets included at the end, I think the best way is to override the assets bag but we need to add a way to override it (maybe with an assets_bag_interface and a factory defined as a service : you can override the factory if you want a different implementation of assets_bag_interface)

**Comment by senky** [comment]
Alright, I'm closing this PR then.

**Pull request closed without merging**
