### PR TITLE
[ticket/14361] Prevent PM count from going negative

### PR DESCRIPTION
**Pull request by ajquick**
3.1.x Branch

Cosmetic fix to prevent the unread / new PM counts from going negative.

PHPBB3-14361

### CODE REVIEW

**Comment by n-aleha** [comment]
@RMcGirr83 
The PM counter can display as negative. I've seen it on a board I run.

**Comment by marc1706** [comment]
The PM counter shouldn't go negative. Instead of suppressing the issue we should rather fix the issue if there is one.

**Comment by exussum12** [comment]
Did a little bit of digging in to this, When generating the number the unique messages are counted (for example 2 groups of people are messaged - person is in both groups)

then when deleted the cache takes away the number of deleted rows. The problem this is trying to solve I assume is not doing another query to properly update the messages.

This fix is incorrect really, the number will still be wrong when its above 0 if this bug has effected it.

**Comment by marc1706** [comment]
Closing this as the PR only fixes the manifestation of the issue instead of the actual issue. Please reply to the ticket if you have more input: https://tracker.phpbb.com/browse/PHPBB3-14361

**Pull request closed without merging**
