### PR TITLE
[ticket/13487] Add factory for db tool class

### PR DESCRIPTION
**Pull request by nickvergessen**
This allows us to split up the large file one by one easily.

https://tracker.phpbb.com/browse/PHPBB3-13487

### CODE REVIEW

**Comment by Nicofuma** [comment]
Actually here we have 2 ways to that on an "easier" (using the DIC to construct the real db tools object):
For both of them we have to define a private service per db tools type (ie per database) and then we can:
1. Using a factory and pass the container to it so instead of calling new we call $container->get('dbal.tools.<driver>')
2. We can  use a compiler pass to rename the real service or to create an alias.

I think I prefer the second solution (and by the way it could be nice to do the same think with the dbal driver)

**Comment by nickvergessen** [comment]
Well im going to add an array implementation which is independent from the used db, does this still work (i don't know anything about compilerpass stuff)

**Comment by Nicofuma** [comment]
When will this implementation be used and when will be the dbal driver dependent implementation?

**Comment by nickvergessen** [comment]
It will be used for generating the schema.json and for tests,
the dbal driver version is used in code and the migrator

**Comment by Nicofuma** [comment]
I think that the array implementation should be an independent public service and requested directly when needed.

**Comment by nickvergessen** [comment]
Can we still ahve this little factory while we are splitting up the current db_tools file since it makes it a lot easier?

**Comment by Nicofuma** [comment]
I think yes but if you do that this way you have to instantiate the class manually in the factory...

**Pull request merged**
