### PR TITLE
Array has 2 duplicate keys with value 'ogg' ('ogg', 'ogg').  

### PR DESCRIPTION
**Pull request by arshidkv12**

### CODE REVIEW

**Comment by rubencm** [comment]
Can you fix the commit messages or can I do it?

**Review by arshidkv12 — COMMENTED** [review]
Changed duplicate key

**Review by arshidkv12 — COMMENTED** [review]
Fixed bug

**Review by arshidkv12 — COMMENTED** [review]
Fixed

**Comment by rubencm** [comment]
https://area51.phpbb.com/docs/dev/master/development/git.html#commit-messages

**Comment by arshidkv12** [comment]
> Can you fix the commit messages or can I do it?

Can you add it?

**Comment by rubencm** [comment]
Sorry, I can't reopen it again :confused: , I have created another pr

**Pull request closed without merging**
