### PR TITLE
[ticket/14164] Add instructions to use the CLI for database updates

### PR DESCRIPTION
**Pull request by Zoddo**
[PHPBB3-14164](https://tracker.phpbb.com/browse/PHPBB3-14164)

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Should probably say something more like: 
> If you have ssh access to your server, you may wish to update via the command line interface. From your board's root, execute the following command

**Comment by Nicofuma** [comment]
:+1: for both of you ;)

**Comment by Oyabun1** [comment]
It probably needs to be clear that the CLI command is only for updating the database, so maybe:
> If you have shell access to your server, you may wish to perform the database update via the command line interface. From your board's root, execute the following command: <code>php bin/phpbbcli.php --safe-mode db:migrate</code>.

**Comment by VSEphpbb** [comment]
> have a shell

is wrong.. Remove the "a"

**Comment by Zoddo** [comment]
@VSEphpbb : Done

**Comment by bantu** [comment]
This goes into the right direction, but it unfortunately looks kind of half-baked right now. `4.i. Full package` to `4.iii. Patch file` still make direct references to (only) `install/database_update.php`.

**Comment by Zoddo** [comment]
@bantu : Done :)

**Pull request merged**
