### PR TITLE
[ticket/14865] Use Stylelint for managing CSS

### PR DESCRIPTION
**Pull request by hanakin**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

https://tracker.phpbb.com/browse/PHPBB3-14865

PHPBB3-14865

### CODE REVIEW

**Comment by VSEphpbb** [comment]
I'd prefer single-rule CSS to be on 1-liners (our css is so big we need to save bytes wherever we can).

Also, colors such as GREEN, should probably be hex instead.

**Comment by hanakin** [comment]
Agree hex should be used not sure where green is being used it shouldn't be. as for the single rule its actually better for changes if its not single line, the size is irrelevant as you should be serving minified version anyway and there is actually smaller file sizes if its not single line with gzip as its not finding as many unique values.

**Comment by VSEphpbb** [comment]
But we are not, AFAIK, serving CSS minified ATM.

Also, while a linter is great, I don't see anything here that is intergating it into Travis CI or the build processes, for example. How is this linter expected to be utilized?

**Comment by hanakin** [comment]
This is still a wip as it needs input on the specific standards.

**Comment by hanakin** [comment]
!wip

**Comment by hanakin** [comment]
!Styles

**Comment by hanakin** [comment]
!Styles

**Comment by marc1706** [comment]
Created a ticket to employ this on travis: https://tracker.phpbb.com/browse/PHPBB3-14970

**Pull request merged**
