### PR TITLE
[ticket/13595] Remove unused instances of the bbcode class

### PR DESCRIPTION
**Pull request by s9e**
There are a few unused instances of the bbcode class created in various places. I think it's just leftover code from PHPBB3-11635.

https://tracker.phpbb.com/browse/PHPBB3-13595

### CODE REVIEW

**Comment by bantu** [comment]
It is not quite clear to me whether https://tracker.phpbb.com/browse/PHPBB3-13595 also affects 3.1 due to the various subtasks in that ticket.
@nickvergessen If this only removes dead code and applies to 3.1, it should go into 3.1 as it is a performance improvement.

**Comment by marc1706** [comment]
I agree with what bantu said

**Comment by s9e** [comment]
@bantu There's no subtask to PHPBB3-13595 so I guess you were talking about PHPBB3-11635? The patches that made this code redundant were applied a long time ago, it's not related to any other future changes.

It's easy enough to verify that no other file uses those `$bbcode` instances:
```
$ grep -R "\\\$bbcode->" phpBB
phpBB/includes/functions_content.php:                   $bbcode->bbcode($bitfield);
phpBB/includes/functions_content.php:           $bbcode->bbcode_second_pass($text, $uid);
```

**Comment by bantu** [comment]
>  There's no subtask to PHPBB3-13595 so I guess you were talking about PHPBB3-11635? 

Correct. Updated.

**Comment by nickvergessen** [comment]
@s9e so are the stray variables also in 3.1? if so, please fix there.

**Comment by s9e** [comment]
Yes, it's in 3.0 onward, including 3.1. What branch should it be based on?

**Comment by nickvergessen** [comment]
develop-ascraeus (sorry for the troubles, we should change the branch naming I think.

**Comment by s9e** [comment]
Ok, I understand now. It was already based on develop-ascraeus, I just didn't pick the right branch for the PR.

**Pull request closed without merging**
