### PR TITLE
[ticket/14393] Fix updater behaviour

### PR DESCRIPTION
**Pull request by CHItA**
[PHPBB3-14393](https://tracker.phpbb.com/browse/PHPBB3-14393)

### CODE REVIEW

**Comment by CHItA** [comment]
This should be tested on windows (i reproduced it on xampp), as the error IIRC haven't occurred on linux.

**Comment by RMcGirr83** [comment]
Making the changes per the PR, the update completed (got a timeout though when running the database update...pretty sure there is already a ticket on that) however doesn't appear that the no longer needed files were removed.  Not sure if that matters or not.

**Comment by CHItA** [comment]
@RMcGirr83 which files weren't removed? It works for me, and if it fails it should fallback to an other method, and should give you a message about that.

**Comment by RMcGirr83** [comment]
All of these
adm/style/install_convert.html
adm/style/install_error.html
adm/style/install_footer.html
adm/style/install_header.html
adm/style/install_install.html
adm/style/install_main.html
adm/style/install_update.html
adm/style/install_update_diff.html
config/auth.yml
config/avatar.yml
config/captcha.yml
config/console.yml
config/content.yml
config/cron.yml
config/db.yml
config/event.yml
config/feed.yml
config/mimetype_guesser.yml
config/notification.yml
config/parameters.yml
config/password.yml
config/profilefield.yml
config/routing.yml
config/services.yml
config/tables.yml
config/user.yml
includes/functions_install.php
includes/functions_upload.php
includes/functions_url_matcher.php
includes/utf/data/utf_canonical_comp.php
includes/utf/data/utf_canonical_decomp.php
includes/utf/data/utf_compatibility_decomp.php
includes/utf/data/utf_nfc_qc.php
includes/utf/data/utf_nfkc_qc.php
includes/utf/data/utf_normalizer_common.php
includes/utf/utf_normalizer.php
phpbb/cache/driver/null.php
phpbb/controller/provider.php
phpbb/db/html_migrator_output_handler.php
phpbb/db/log_wrapper_migrator_output_handler.php
phpbb/db/migrator_output_handler_interface.php
phpbb/db/null_migrator_output_handler.php
phpbb/db/tools.php
phpbb/di/extension/ext.php
phpbb/event/kernel_request_subscriber.php
phpbb/feed/factory.php
phpbb/log/null.php
styles/prosilver/theme/images/alert_close.png
styles/prosilver/theme/images/arrow_down.gif
styles/prosilver/theme/images/arrow_left.gif
styles/prosilver/theme/images/arrow_right.gif
styles/prosilver/theme/images/arrow_up.gif
styles/prosilver/theme/images/bg_button.gif
styles/prosilver/theme/images/feed.gif
styles/prosilver/theme/images/gradient.gif
styles/prosilver/theme/images/icon_acp.gif
styles/prosilver/theme/images/icon_back_top.gif
styles/prosilver/theme/images/icon_bookmark.gif
styles/prosilver/theme/images/icon_bump.gif
styles/prosilver/theme/images/icon_contact.png
styles/prosilver/theme/images/icon_delete_cookies.gif
styles/prosilver/theme/images/icon_faq.gif
styles/prosilver/theme/images/icon_home.gif
styles/prosilver/theme/images/icon_logout.gif
styles/prosilver/theme/images/icon_mark.gif
styles/prosilver/theme/images/icon_mcp.gif
styles/prosilver/theme/images/icon_members.gif
styles/prosilver/theme/images/icon_notification.gif
styles/prosilver/theme/images/icon_pages.gif
styles/prosilver/theme/images/icon_pm.gif
styles/prosilver/theme/images/icon_post_target.gif
styles/prosilver/theme/images/icon_post_target_unread.gif
styles/prosilver/theme/images/icon_print.gif
styles/prosilver/theme/images/icon_profile.gif
styles/prosilver/theme/images/icon_register.gif
styles/prosilver/theme/images/icon_search.gif
styles/prosilver/theme/images/icon_sendemail.gif
styles/prosilver/theme/images/icon_subscribe.gif
styles/prosilver/theme/images/icon_team.gif
styles/prosilver/theme/images/icon_textbox_search.gif
styles/prosilver/theme/images/icon_topic_attach.gif
styles/prosilver/theme/images/icon_topic_deleted.png
styles/prosilver/theme/images/icon_topic_latest.gif
styles/prosilver/theme/images/icon_topic_newest.gif
styles/prosilver/theme/images/icon_topic_poll.gif
styles/prosilver/theme/images/icon_topic_reported.gif
styles/prosilver/theme/images/icon_topic_unapproved.gif
styles/prosilver/theme/images/icon_ucp.gif
styles/prosilver/theme/images/icon_unsubscribe.gif
styles/prosilver/theme/images/icons_button.png
styles/prosilver/theme/images/icons_pagination.png
styles/prosilver/theme/images/subforum_read.gif
styles/prosilver/theme/images/subforum_unread.gif
styles/prosilver/theme/imageset.css

I chose the download method for the update.  Only message I received was an error concerning the timeout with the exception of the normal messages (update database, etc.).

**Comment by CHItA** [comment]
If you use the download method then you have to remove the files manually (this is the way it was).

**Comment by RMcGirr83** [comment]
Okay, I will try again using one of the other methods.

On Mon, Mar 28, 2016 at 7:15 AM, Máté Bartus <notifications@github.com>
wrote:

> If you use the download method then you have to remove the files manually
> (this is the way it was).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/phpbb/phpbb/pull/4255#issuecomment-202343928>
>



-- 
Rich McGirr

**Comment by RMcGirr83** [comment]
Seemed to work just fine with the exception of the database updater timing out.  All files that needed to be removed were removed.  These are the last few lines when the updater timed out.

`Installing Schema: \phpbb\db\migration\data\v320\default_data_type_ids.
Installed Data: \phpbb\db\migration\data\v320\oauth_states; Time: 0.00 seconds` 

is last few lines were it barfed.  Ran the udpater again and got this when it completed.  Xampp is set for max_execution_time=30

noname

**Comment by RMcGirr83** [comment]
Lastly, this is what is displayed after the update
noname

which is a pure browser caching issue but not sure how one would get around that.  Beyond the scope of this ticket though so if you want me to place/open it somewhere else just say so.

Thanks CHIta, glad it finally works as far as removing the files and completing without that CANNOT_DELETE_FILES error.

**Comment by CHItA** [comment]
That is not a timeout, it just impossible to get the number of migrations that will run currently.

**Comment by RMcGirr83** [comment]
@CHItA I know that isn't a timeout, it timed out before that at the, I believe, `Installing Schema: \phpbb\db\migration\data\v320\default_data_type_ids.`

**Comment by CHItA** [comment]
Ah, okay. Nothing i can do about that, that's the migrator.

**Comment by marc1706** [comment]
Shouldn't the migrator itself try to handle timeouts correctly?

**Comment by CHItA** [comment]
i think it doesn't do anything about timeouts

**Comment by marc1706** [comment]
So it runs all those schema changes at once? Should we maybe try to split that up for the mentioned migration?

**Comment by CHItA** [comment]
nope, but the migrator has one entry point, we call into that. as far as i can tell it manages which task to execute but it does execute one, and there is no guarantee that it is less the half of the execution time.

**Comment by marc1706** [comment]
If the schema changes are treated as one task that might definitely take too long. In which case we might want to to think of splitting this up in different migrations or using a custom method for it.

**Comment by CHItA** [comment]
yeah maybe, but that is out of scope for this PR

**Comment by marc1706** [comment]
That's true. Just thinking out loud. :)

**Pull request merged**
