### PR TITLE
[ticket/15951] Add core events to mcp

### PR DESCRIPTION
**Pull request by toxyy**
Allow modification of permissions for normal users to access the mcp
Also allows modification of the hidden form fields when deleting topics
This lets normal users delete their own topics with replies

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15951

### CODE REVIEW

**Comment by 3D-I** [comment]
`Add core events to MCP` maybe?

**Comment by toxyy** [comment]
Yeah it did look a bit bad

**Comment by 3D-I** [comment]
`Add core.mcp_modify_permissions`  ?

**Comment by toxyy** [comment]
The event in that place only runs if you don't normally have permissions, so if you do then the event name would be a little misleading... wasn't sure what to go with.

**Comment by 3D-I** [comment]
Being in the MCP it seems obvious you are modifying related perms.

**Comment by toxyy** [comment]
Add `core.mcp_allow_user_permissions` ?

**Comment by 3D-I** [comment]
> `Add core.mcp_modify_permissions`

**Comment by toxyy** [comment]
Not sure why there's conflicts and why travis is missing...

**Comment by 3D-I** [comment]
You are on master

**Comment by 3D-I** [comment]
try close/open

**Comment by toxyy** [comment]
Still no travis, weird

**Comment by 3D-I** [comment]
You fu**d all up :) apparently.

**Comment by toxyy** [comment]
:( I just rebased and force pushed like before. I'll remake it later if it's messed up

**Pull request closed without merging**
