### PR TITLE
[ticket/14163] Properly fix select all for code tag in Edge

### PR DESCRIPTION
**Pull request by marc1706**
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14163

PHPBB3-14163

### CODE REVIEW

**Comment by bantu** [comment]
@callumacrae Here we are again. :-D

**Comment by marc1706** [comment]
On a side note: it turns out Edge is using the number of lines of the textarea for the select Index instead of the actual character count. Hence why it fails with the old method.

**Comment by bantu** [comment]
@callumacrae Any comments on this?

**Comment by callumacrae** [comment]
No comments, have no idea what is going on!

**Comment by marc1706** [comment]
If you have questions, feel free to ask.

**Comment by bantu** [comment]
This piece of code was previously discussed in #3818

**Comment by marc1706** [comment]
The code we added in #3818 does work, but only for one line. Based on Edge's behavior the API seems to work as outlined here: https://github.com/phpbb/phpbb/pull/3908#issuecomment-140651715

This approach does work perfectly fine for Edge and is probably what we should've used to begin with.

**Pull request merged**
