### PR TITLE
Remove deprecated max-device-width

### PR DESCRIPTION
**Pull request by MikkCZ**
See https://drafts.csswg.org/mediaqueries/#mf-deprecated.

From HTML removed in https://github.com/phpbb/phpbb/commit/96521767f8db215e36e7a00264dd491fc5816caa.

https://tracker.phpbb.com/browse/PHPBB3-14183

### CODE REVIEW

**Comment by Louis7777** [comment]
Man this was so useful when you wanted - for example - a website to transform only for smartphones and not for PCs... I wonder why they are deprecating it...

**Comment by bantu** [comment]
@hanakin What do you think about this? Should this be part of #3912 then?

**Comment by hanakin** [comment]
@bantu yes its actually something I was going to refactor as well I can easily address it in my pr

**Comment by bantu** [comment]
I also don't think we want this in 3.1.x. @nickvergessen

**Comment by bantu** [comment]
This follows #3865 though, which was merged into 3.1.x.

**Comment by bantu** [comment]
@marc1706 You merged #3865. Want to review this / decide whether we want it?

**Comment by marc1706** [comment]
@bantu the difference is that the HTML part caused the 3.1.x prosilver to be invalid HTML5. This however does not. It's also not invalid CSS level 3. Therefore I don't think we should merge this into 3.1.x. A patch against master should be the correct way to go.

**Comment by marc1706** [comment]
@hanakin I guess easiest solution would be if you'd address that in your PR?

**Comment by nickvergessen** [comment]
> the difference is that the HTML part caused the 3.1.x prosilver to be invalid HTML5. This however does not. It's also not invalid CSS level 3. Therefore I don't think we should merge this into 3.1.x. A patch against master should be the correct way to go.

agreed

**Pull request closed without merging**
