### PR TITLE
[master][ticket/16549] Use PHPUnit 9.3+ for PHP 8.0+ tests

### PR DESCRIPTION
**Pull request by rxu**
Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

<a href="https://tracker.phpbb.com/browse/PHPBB3-16549">PHPBB3-16549</a>.

### CODE REVIEW

**Comment by rxu** [comment]
!set WIP

**Comment by rxu** [comment]
!unset WIP

**Comment by rxu** [comment]
To outline this long story:

- wrapper test case functions were added to provide backward compatibility with earlier PHPUnit versions because of a lot functions deprecations/removals/changes in PHPUnit 9+.
- most of changes are related to "Undefined array key" which was promoted from notice to warning in PHP 8.
- `sami/sami` was removed from 'require-dev' as this use way is not supported by the tool and replaced with 'sami.phar' as described in [Sami documentation](https://github.com/FriendsOfPHP/Sami#installation). This is also a pros from the perspective of updating core dependencies as sami is not maintained anymore and its outdated dependencies [will] interfere with the updated phpBB ones.
- `PHPUnit function declarations tiny cleanup` commit is only adjusting some test case functions declarations in a lot of test files (like `public` vs `protected` for setUp* functions etc), so actually doesn't need an actual review.

**Comment by marc1706** [comment]
@rxu can you also merge your 3.3 branch into this and resolve any merge conflicts? Thanks.

**Pull request merged**
