### PR TITLE
[ticket/13469] Fall back to soft_delete if no permissions for delete

### PR DESCRIPTION
**Pull request by Elsensee**
https://tracker.phpbb.com/browse/PHPBB3-13469

### CODE REVIEW

**Comment by Crizz0** [comment]
I tried this in 3.1.2 and found after the changes one strange behavior:
- soft deleting one post at the end of the topic
Everything works. Post is gone for regular users. Moderators can see this posts.

BUT:
1. a regular user quotes a different post
2. a other regular user reads the quote, looks for the original posts --> cannot find it
3. moderators stil saw the "original post"
4. restore/permant delete of the soft deleted post the end of the topic
--> @2.) regular users can reads this original post again

:/ 

PS: Don't know exactly, if it is related to this code or to soft deleted in general.

**Comment by gn36** [comment]
This modification changes the delete mode to soft_delete directly within the auth check, so the behavior you describe should relate to any deletion using soft_delete.

**Comment by nickvergessen** [comment]
We have functional tests for deleting, can this be added somehow?

**Comment by marc1706** [comment]
@Elsensee how are things looking on this one? Would be nice to see some tests for this behavior.

**Comment by Elsensee** [comment]
Uhh, right. Give me some time. :)

**Comment by Elsensee** [comment]
Updated. :)

**Comment by Elsensee** [comment]
`[19:36:40] <Nicofuma> https://github.com/phpbb/phpbb/pull/3284 could you extract the new test to a new method please?`

**Comment by nickvergessen** [comment]
Merged via http://git.io/ve4g7

**Pull request closed without merging**
