### PR TITLE
3.2.x phpbb3 15133

### PR DESCRIPTION
**Pull request by pompeiisneaks**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (PHPBB3-15133)

https://tracker.phpbb.com/browse/PHPBB3-15133

### CODE REVIEW

**Comment by marc1706** [comment]
A few things that are wrong with this one:

- You're still targeting the master branch. Please don't change the base branch on github again. As already pointed out in the other closed PR, you have to rebase your local branch onto 3.2.x instead of simply changing the base branch on github.
- You seem to try to simply hide a failure while getting the image size instead of actually fixing the cause of the failure. Not being able to get an image's size can be the result of many things. However, an image with height or width of 0 is not a valid image and therefore this change is moot.

**Comment by pompeiisneaks** [comment]
First off, I know I explicitly chose the 3.2.x branch whne I did the pull request.  This has to be a bug on github.  (I use gitlab, github, etc on a daily basis at work).  I cancelled the PR because I was told it was no longer valid with so many changes.  

Second, this is a bug in getimagesize, I can open the jpg image fine and after I made this change on my own phpbb installation the image works perfectly, so a: it's not hiding a failure, its a workaround for a php bug, b: it's not a damaged image, it opens fine everywhere else I've used the image.  here's at least one bug where getimagesize is returning bad data on a good jpg: https://bugs.php.net/bug.php?id=72278  in fact if you want a list of all getimagesize jpg bugs, check this small list: https://bugs.php.net/search.php?cmd=display&search_for=getimagesize+jpg+returns+0+for+valid+file&x=0&y=0

**Comment by pompeiisneaks** [comment]
Okay, I just tried pulling a completely new version of my fork, and running the command you specified: 

fatal: Needed a single revision
invalid upstream upstream/3.2.x

I'm definitely not a git guru, but I've used it for a long time.  I used to do branch merges all the time, in Atlassians bitbucket and so long as I chose the branch in the UI correctly I was pulling "TO" it worked, I'm trying one more time to see if I can update this pull request.

**Comment by pompeiisneaks** [comment]
Okay so I'm not supposed to cancel pull reqeusts, but this one is 'wrong' how do I 'disable/remove' a pull request without doing so?  I need to start a completely new pull request from my forked 3.2.x branch into the 3.2.x here, and don't wnat to select all the right settings only to have it pull into master anyway.  Insights?  I'm guessing that I possibly made my edits to a branch I created off of master not off of the 3.2.x branch, but I'm fairly confident (but not positive) my commit was to a 3.2.x based branch and it's commited into my forks 3.2.x branch, but I don't know for sure, and am told not to cancel pull requests.  Is there any documentation on the preferred methodology for this so I can avoid causing problems?

**Comment by marc1706** [comment]
The correct command to rebase is `git rebase upstream/3.2.x`, not `git rebase upstream upstream/3.2.x`
As 3.2.x is not using getimagesize() in the lines you mentioned, the "compatibility fix" is still not the way to go and linking to getimagesize() bugs won't help. Please supply an image that causes this issue (ideally in a zip so github or the site you upload it to don't modify it) so it can be properly fixed.

**Comment by pompeiisneaks** [comment]
[Controls left 80pc.zip](https://github.com/phpbb/phpbb/files/871627/Controls.left.80pc.zip)

example jpg that has no problems being viewed in multiple locations but the getImageSize method returns either width or height as 0.  I don't recall which, but it is a completely viewable jpeg.  I've failed on two separate systems, one my own linux server and on the original hosted server.  I can view it in linux, and on windows just fine and see the width and depth.

**Pull request closed without merging**
