### PR TITLE
[ticket/13591] Add core events to the function obtain_users_online_string()

### PR DESCRIPTION
**Pull request by rxu**
Add functions.php core events to the function obtain_users_online_string()
to allow extensions adding/modifying online users data.

<a href="https://tracker.phpbb.com/browse/PHPBB3-13591" >PHPBB3-13591</a>.

### CODE REVIEW

**Comment by rxu** [comment]
!set WIP

**Comment by rxu** [comment]
!set Event

**Comment by rxu** [comment]
!unset WIP

**Comment by nickvergessen** [comment]
Merged with https://github.com/phpbb/phpbb/commit/261c3bc1d06a05ec7c0c18288b1a04a35819ec12

**Pull request closed without merging**
