### PR TITLE
[ticket/14601] Fix composer.lock

### PR DESCRIPTION
**Pull request by CHItA**
PHPBB3-14601

### CODE REVIEW

**Comment by Nicofuma** [comment]
the tests are still failing, could you check?

**Comment by Nicofuma** [comment]
```
FILE: /home/travis/build/phpbb/phpbb/phpBB/phpbb/attachment/delete.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 9 | ERROR | Either use statement or full name must be used.
   |       | (phpbb.Namespaces.UnusedUse.FullName)
----------------------------------------------------------------------
FILE: /home/travis/build/phpbb/phpbb/phpBB/phpbb/attachment/upload.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 11 | ERROR | Either use statement or full name must be used.
    |       | (phpbb.Namespaces.UnusedUse.FullName)
----------------------------------------------------------------------
```

**Comment by CHItA** [comment]
That is related to the code sniffer change, i guess that would need an other PR

**Comment by CHItA** [comment]
Also line 9 and 11 is the dockblock with the copyright stuff

**Comment by CHItA** [comment]
also that affects 3.2 branch as well

**Pull request merged**
