### PR TITLE
[ticket/15809] Allow twig syntax for template events

### PR DESCRIPTION
**Pull request by senky**
PHPBB3-15809

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15809

### CODE REVIEW

**Comment by rubencm** [comment]
```
preg_match_all('/<!-- EVENT (.*) -->/U', $file_content, $event_list);
$event_list = $event_list[1];
```

**Comment by Elsensee** [comment]
Still can't believe this is done without regular expressions and just with explode()'s...
We can actually just use on regex for both styles then:
```
preg_match_all('/(?:{%|<!--) EVENT (.*) (?:%}|-->)/U', $file_content, $event_list);
$event_list = $event_list[1];
```

**Comment by rubencm** [comment]
Yes, that's better, but is better to have the preg_match_all twice, because one of them will have to be removed, so will be easier.

**Comment by Elsensee** [comment]
You mean when we get rid of the old syntax? We could also just change the regular expression then...

**Comment by rubencm** [comment]
Well, to put the `@deprecated` comment somewhere so its easier to find in the future, but ok

**Comment by marc1706** [comment]
I was thinking about writing a PHP extension to extract the events but until that happens we should probably go with the regex and change it if needed (so just one please).

**Pull request merged**
