### PR TITLE
[ticket/15542] Call Javascript files with assets version

### PR DESCRIPTION
**Pull request by rxu**
Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

<a href="https://tracker.phpbb.com/browse/PHPBB3-15542">PHPBB3-15542</a>.

### CODE REVIEW

**Comment by rxu** [comment]
!set Styles

**Comment by marc1706** [comment]
Wouldn't it make maybe more sense to inject the assets version directly in INCLUDEJS with twig?

**Comment by rxu** [comment]
Probably yes, but isn't it too big change for 3.2? Because that would require changing for a lot of places in template I think. I'm just not sure.

**Comment by hanakin** [comment]
I am not sure why we need versions? These are not dynamic files nor vendor files? What does this solve? End user modification? We are not using a build process at least not yet ie webpack which is where you would need this sort of thing? And even then the build process handles that sort of thing.

**Comment by DavidIQ** [comment]
@hanakin this addresses phpBB package updates that include changes to JavaScript which then produce support requests because things either don't look or work right after an update. Without the assets version changing the old file in cache is used. Having to tell all your users to clear their browser cache or hard refresh (CTRL+F5) is probably not the best solution.

**Comment by rxu** [comment]
Also, assets version got incremented on every cache purge via ACP.

**Comment by hanakin** [comment]
I get that, what I am asking is why we see the need to do anything for 3.2 as we should not be making any real changes in those specific files until 3.3 and in 3.3 we should be using a build process for our js which will handle that...

**Comment by hanakin** [comment]
Something like https://laravel.com/docs/5.3/elixir

**Comment by rxu** [comment]
This PR is just making js calls consistent with all others. Satying about if we're going to make any real changes in those scripts, I'd say that is possible, example: https://github.com/phpbb/phpbb/pull/5070/files#diff-82491f38daf04277fa9e295dee514eda

**Comment by marc1706** [comment]
My point was to keep the INCLUDEJS calls the same and then add the assets version in the twig token parser.

**Comment by Nicofuma** [comment]
I agree with marc on this

**Comment by marc1706** [comment]
@rxu how about this? https://github.com/phpbb/phpbb/pull/5433

**Comment by marc1706** [comment]
Replaced by https://github.com/phpbb/phpbb/pull/5433

**Pull request closed without merging**
