### PR TITLE
[ticket/14972] PHP 7.2 compatibility

### PR DESCRIPTION
**Pull request by rxu**
For the ```master``` branch only. Replaces #4624.

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

<a href="https://tracker.phpbb.com/browse/PHPBB3-14279">PHPBB3-14279</a>.

### CODE REVIEW

**Comment by rxu** [comment]
Yes but most of them are tests and ```sizeof```->```count``` replacements 😃

**Comment by Nicofuma** [comment]
you have a conflict to solve then I'll merge it.

**Comment by rxu** [comment]
@Nicofuma Updated #4862.

**Comment by rxu** [comment]
We need to put 7.2 out of allowed failures when the alias is available on Travis.

**Comment by Nicofuma** [comment]
in the meantime you could remove nigthly from the allowed failures

**Comment by Nicofuma** [comment]
did you try to add 7.2 in the matrix by the way? (it may be already available)

**Comment by rxu** [comment]
Tried and it didn't work. Removed nightly from allowed failures for now.

**Comment by Nicofuma** [comment]
ok

**Comment by rxu** [comment]
Tests pass.

**Pull request merged**
