### PR TITLE
[ticket/13853] Flexible schema for profilefields step 1 configuration

### PR DESCRIPTION
**Pull request by javiexin**
Modify the way adm/style/acp_profile.html STEP 1 (lines 106 to 128)
is coded to make it flexible and expandable to other new types of
profile fields, rather than the current mechanism, hardcoded for
the default types.

A flexible mechanism similar to the one used of STEP 2 is used.

This required a slight modification of the type_interface, and
corresponding modifications to all implementations of that interface.

Includes a fix in the type_interface, missing a required method.

PHPBB3-13853

### CODE REVIEW

**Comment by javiexin** [comment]
There are four redundant commits: two creating changes, and two reverting the same changes.
These other changes are dealt with in a separate PR.

**Comment by javiexin** [comment]
Don't understand why is travis failing on this.  Could anyone translate :) the error message for me?

**Comment by CHItA** [comment]
probably because revert commits are not having the ticket IDs.

**Comment by javiexin** [comment]
So, can i safely ignore them?

**Comment by CHItA** [comment]
If you are familiar with git rebasing and squashing commits, then please fix, otherwise you can just ignore it yes.

**Comment by javiexin** [comment]
Not familiar at all, will ignoret hen

**Comment by javiexin** [comment]
!set WIP

**Comment by javiexin** [comment]
!unset WIP

**Comment by javiexin** [comment]
This should be included in 3.1.6 unless there is any issue with it.  It is not assigned to the milestone, so I am worried in case this travis errors are blocking it, while this is fully ready.

**Comment by javiexin** [comment]
@nickvergessen Please, take a look. Sorry to bother.  It's been more than six weeks since first submission (in a different PR against ascareus, now removed), not assigned to any milestone, no comments beyond the GitHub issues.

**Comment by javiexin** [comment]
Could anyone please review this further, so that it can be either accepted or rejected?
Thanks in advance.

**Comment by Nicofuma** [comment]
The issue is that it involve a BC break for the extensions registering custom profile fields types and we try to avoid BC break in 3.1.x releases as much as we can.

Otherwise the changes looks good

**Comment by Nicofuma** [comment]
@phpbb/development-team 3.1 or 3.2?

**Comment by CHItA** [comment]
I would say 3.2

**Comment by javiexin** [comment]
What do you mean by BC break, and can it be avoided?

**Comment by CHItA** [comment]
BC = Backward Compatibility; Is there any particular reason why you want this in 3.1.x?

**Comment by Nicofuma** [comment]
You changed the interface of a method, therefore any class implementing it is broken.

**Comment by nickvergessen** [comment]
3.2

**Comment by javiexin** [comment]
Ok, I see.

Yes, the class interface is changed, but I have provided implementation of all core classes.

And given the deficiencies in the phpbb core to enable extending the profile fields subsystem, it is not possible that anyone has extended this.

As far as I know, in phpbb there is no validated extension that does this, and the only one in development is my "Advanced Profile Fields" extension, that triggered all these changes.

The reason for 3.1.x is just that, provide end users with an extension that does not require patching the core.  But it has to be 3.2, then so be it. I just need to know to give the right expectations.

Thanks a lot!

**Comment by javiexin** [comment]
I see that the ProfileFields code is (virtually) unchanged from 3.1 to 3.2.
Therefore, I think we can apply this patch to 3.2 and make it (at least) in time for the final release of 3.2.0, whenever that is.

Anything that is needed from my part for this?

Before you ask, the Travis errors are due to a "Revert" commit.  If needed, I can create a new PR against the 3.2 branch that you tell me.

**Comment by javiexin** [comment]
!unset WIP

**Comment by javiexin** [comment]
I have now checked the code against 3.2, and there are NO issues whatsoever.  Only change would be to adapt the use of add_log (in my code, as intended for 3.1) to log->add (new in 3.2).
Please, let me know how to move forward.

By the way, this is not WIP, I consider it final, unless you tell me otherwise (and why, so that I can fix it).

Also, it would benefit 3.1, and could make it into 3.1.11 as well.

**Comment by javiexin** [comment]
Hello again,

I have checked this code versus the "master" branch, as it is a "new feature", and it works.  But I am not confident in creating a new PR against that branch (and closing this one), as it seems that it will include the "Revert" commits that are creating the Travis errors.

Could someone either do it for me, or indicate how to "correctly" doing it, in order to create a new, "clean" PR, without the Travis errors.

For the record, I would like to apply ONLY the following commits: 
https://github.com/phpbb/phpbb/pull/3717/commits/98633626ef7591d0a0694e1d8de0c407006a830f
https://github.com/phpbb/phpbb/pull/3717/commits/bf46b7333b6614b20ac73d1201fc986dda190b0d
https://github.com/phpbb/phpbb/pull/3717/commits/5dfbcacb950fdd7b1b82ddca133b3bcd67e2efc2

Thanks in advance,
-javiexin

**Comment by javiexin** [comment]
Guys, this PR dates back 18 months.  And it is not so complex either.  Don't tell me that nobody has had the time to take a look, and either approve or deny these proposed changes.  I insist, the errors on travis are due to "revert" commits, and if instructed to do so, I will open a new "clean" PR.
I insist that BC is a non-issue: these changes are 100% compatible with the existing code, and I bet they will pass all the tests unchanged (except maybe some parameter).  And, as for extensions, there are NO extensions to my knowledge that will break with this, on the contrary, it will be possible to have more.

Please, tell me something to get this out the door...
-javiexin

**Comment by javiexin** [comment]
Closing this to reopen without wrong commits

**Pull request closed without merging**
