### PR TITLE
[ticket/15069] Refactor template class

### PR DESCRIPTION
**Pull request by javiexin**
PHPBB3-15069

For reference and details, see https://area51.phpbb.com/phpBB/viewtopic.php?f=81&t=50881

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-15069

### CODE REVIEW

**Comment by javiexin** [comment]
Ok, I am all for improving the code, but @hanakin what exactly are you suggesting to break, and what is too verbose?  Sorry I don't understand your comment precisely.  Please, elaborate.

**Comment by hanakin** [comment]
Ill let the dev team member comment, but you rewrote the entire files and there is a lot of docblock making it hard to make sense of whats getting changed  on here for me, its just not a very clean diff is all

**Comment by javiexin** [comment]
Of course, it is a major rewrite, and it adds significant functionality.  The diff does not give you enough information. Maybe looking at the new file alone makes more sense. That is for context, template and base are much clearer.

**Comment by javiexin** [comment]
The failure seems a totally different problem, unrelated to this PR.

**Comment by javiexin** [comment]
Confirmed, the test failure is coming from here https://github.com/phpbb/phpbb/commit/bdc31265cf1e25799daa7f2173e2b5e836e5bb10#diff-80a55b47f049e3e27edb4d6bfd8e7a1dR93

And uncovered by https://github.com/phpbb/phpbb/pull/4622

**Comment by javiexin** [comment]
Fix proposed: https://github.com/phpbb/phpbb/pull/4731

**Comment by javiexin** [comment]
The latest error seems to be coming from the "Merge commit" not having the comment correctly formatted.
Could anyone please squash all commits between https://github.com/phpbb/phpbb/pull/4688/commits/7ad31c98b74b4946483bca99d8892c40de2c1aa9 and https://github.com/phpbb/phpbb/pull/4688/commits/c9c49a2798f74a01dfb5fd970a722ba008e0420f?  If needed, keep message from first commit.
I cannot do it in my local git and then push it here, and I do not want to play with this repository, as I may break more things than what I would fix.
Thanks a lot.

**Comment by hanakin** [comment]
@javiexin just hard reset to 7ad31c9 and rebase instead of merging in master. Then re-commit changes

**Comment by javiexin** [comment]
@hanakin thanks a lot, but I am not confident with this, and I do not want to mess around with the phpbb repository.  Maybe close this request and reopen a new one?
Otherwise, be a bit more explicit, with command that I should type.  Sorry but my Git knowledge is very limited :(

**Comment by hanakin** [comment]
First I recommend using a tool like [git Tower](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjAxeWsiM_SAhUD0iYKHd1uDF8QFggxMAA&url=https%3A%2F%2Fwww.git-tower.com%2F&usg=AFQjCNEFVWWwPuFfH7r3z7KPDv7m1ZsarQ&sig2=rR87XvOoQUPKAHsSsd4fQQ), makes working with git alot simpler 

To not have to use git you could

1. Save backups of the changed files somewhere.
2. Delete branch
3. Recreate branch from `master`
4. open files and manually compare with backups and apply changes
5. `git push ticket/15069 --force` https://www.atlassian.com/git/tutorials/syncing#git-push
6. Close pull request
7. Open new pull request against `master`

**Comment by javiexin** [comment]
Ok, I have now created the new PR against master, following your detailed guide (thanks a lot!!).

But I now still get merge conflicts, that I must resolve, that will result in a commit with an incorrect commit message...

What do I do??

The new PR: https://github.com/phpbb/phpbb/pull/4735

**Pull request closed without merging**
