### PR TITLE
[ticket/14109] InnoDB requires multiple queries when setting FULLTEXT

### PR DESCRIPTION
**Pull request by brunoais**
> InnoDB presently supports one FULLTEXT index creation at a time [1795]

https://tracker.phpbb.com/browse/PHPBB3-14109

### CODE REVIEW

**Comment by bantu** [comment]
There is quite some repetition already and even more post-patch.

**Comment by brunoais** [comment]
What would be preferable, then?

**Comment by dhruvgoel92** [comment]
Closing this PR as its a duplicate of https://github.com/phpbb/phpbb/pull/3839

**Comment by Nicofuma** [comment]
that's not a duplicate actually, the other PR is just based on this one (there is 2 different tickets)

**Comment by marc1706** [comment]
@Nicofuma I guess this should be reopened then?

**Comment by Nicofuma** [comment]
I think yes (forgot to reopen)

**Comment by marc1706** [comment]
Isn't this obsolete after the bug was fixed in MySQL itself?

**Comment by brunoais** [comment]
@marc1706  if you want my opinion, now I'd just bump the minimum MySQL version on phpBB and call it a day.

**Comment by bantu** [comment]
The error in https://bugs.mysql.com/bug.php?id=67004 is triggered on the ALTER statement. This patch thus only partially addresses the issue. It is my understanding that any table changes would have to drop the FULLTEXT indexes before adding e.g. columns. This is rather ridiculous and would require unnecessary additional changes. I am very much in favour of just increasing the required version.

**Comment by bantu** [comment]
Replaced with #4426

**Pull request closed without merging**
