### PR TITLE
Update board.php

### PR DESCRIPTION
**Pull request by Stanzilla**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14184

Add an additional comment to satisfy https://tracker.phpbb.com/browse/PHPBB3-14184

### CODE REVIEW

**Comment by rxu** [comment]
I guess it would be better to add ```'SMTP_SERVER_EXPLAIN'``` entry instead for extended description for the option, with additional changes to the line https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/includes/acp/acp_board.php#L452 to set ```'explain'``` key to ```true``.

**Comment by marc1706** [comment]
I do agree that this should be something to put in an explanation string.

**Comment by Stanzilla** [comment]
Yeah it does, how do you guys handle that? PR into master and gets merged into the branches?

**Comment by marc1706** [comment]
The PR should actually be against `3.1.x` and will then be merged upstream `3.1.x` --> `3.2.x` --> `master`. If you know how to rebase your commits and commit messages, and very much appreciate it if you could update the commit messages to fit this format: https://wiki.phpbb.com/Git#Commit_Messages

Otherwise we'll take care of it while merging the pull request.

**Comment by Stanzilla** [comment]
Made a new PR https://github.com/phpbb/phpbb/pull/4354

**Pull request closed without merging**
