### PR TITLE
[ticket/14596] Deny the installation of Ascraeus under PHP7

### PR DESCRIPTION
**Pull request by 3D-I**
That should end support requests about PHP7

https://tracker.phpbb.com/browse/PHPBB3-14609

### CODE REVIEW

**Comment by RMcGirr83** [comment]
@3D-I your commit will still fail as you are missing PHPBB3-14596  as the last line in the commit messages.

**Comment by 3D-I** [comment]
Into the commit message of my branch, isn't?
Omg, thanks.
Not sure what to do here, close this and make a new one?
Working on the fly here on github and being a new.hub.ie.

**Comment by RMcGirr83** [comment]
You can either close or amend again.  Probably better to close and open a new PR I would imagine.  Each time you make a PR every commit message must contain [ticket/xxx] and PHPBB3-xxx that links to the tracker.

**Comment by 3D-I** [comment]
Ok, to give up isn't an option. Thank you.

**Pull request closed without merging**
