### PR TITLE
[ticket/16325] Ensure lock file is opened for updating

### PR DESCRIPTION
**Pull request by marc1706**
PHPBB3-16325

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16325

### CODE REVIEW

**Comment by rubencm** [comment]
I think open it in binary is not necessary

**Comment by Crizz0** [comment]
I have one report from a user using a Strato webspace, that this fix solved the problem and phpBB 3.3.x is installable.

**Comment by marc1706** [comment]
> I think open it in binary is not necessary

I don't think binary open adds any overhead and in theory I'd expect the opposite to be the case.

**Comment by rubencm** [comment]
Maybe we can rely on the symfony implementation for this, so we don't have to worry about this
https://github.com/symfony/lock/blob/master/Store/FlockStore.php

**Comment by marc1706** [comment]
Probably a good idea to try and use the symfony implementation. However, I do think this is out of the scope of this issue and I'd rather have a look at this in another pull request.

**Comment by marc1706** [comment]
I have created a ticket for that: https://tracker.phpbb.com/browse/PHPBB3-16390

**Pull request merged**
