### PR TITLE
[ticket/13949] Replace colon with colon lang key in memberlist search page

### PR DESCRIPTION
**Pull request by Galixte**
Replacing of one ```:``` with one ```{L_COLON}``` in memberlist search page.

https://tracker.phpbb.com/browse/PHPBB3-13949

### CODE REVIEW

**Comment by CHItA** [comment]
Please use a commit message that meats our [guidelines](https://wiki.phpbb.com/Git#Commit_Messages).

**Comment by Galixte** [comment]
Hi @CHItA,

what information is missing ?

**Comment by CHItA** [comment]
Your commit message should be:
```
[ticket/13949] Replace colon with colon lang key in memberlist search page

PHPBB3-13949
```

**Comment by Galixte** [comment]
Thanks. ;)

**Comment by CHItA** [comment]
I meant the commit message, not the PR description, that was totally fine. If you don't know how to change a commit message, you can learn about it [here](https://help.github.com/articles/changing-a-commit-message/), however if you would not like to do it, probably we can do it for you when merging.

**Comment by Galixte** [comment]
HI @CHItA,

it’s better ?

**Comment by marc1706** [comment]
Replaced by https://github.com/phpbb/phpbb/pull/3715

**Pull request closed without merging**
