### PR TITLE
Update from 1.11.0 to 2.2.4

### PR DESCRIPTION
**Pull request by fonziset**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-12345

### CODE REVIEW

**Comment by CHItA** [comment]
A new style is in the picture for 3.3 with possibly proper front end dependency management, so i'm unsure whether or not this will ever get merged, however, thank you for the contribution.

@hanakin

**Comment by DavidIQ** [comment]
This was likely not tested with any of the current JavaScript included in the project so I wouldn't merge this at all as I don't see any changes or fixes to any of the core's JS, changes that are almost certain to be needed when going from jQuery 1.x to 2.x. Plus there's nothing here upgrading the CDN for jQuery.

**Comment by CHItA** [comment]
Not sure what it would or wouldn't break as i haven't tested this yet (i could imagine that it doesn't break because we don't really do anything super advanced in js).

**Comment by hanakin** [comment]
The entirety of the js will need to be rewritten with the new theme, leveraging Jquery where possible. I agree we should consider updating it when try but we are no where near try for the js aspects not to mention prosilver will need to still function so if the proper testing/changes to prosilver/admin themes  are taken into consideration then I see no issue

**Pull request closed without merging**
