### PR TITLE
[ticket/14863] Properly treat plural rules in confirmation box title

### PR DESCRIPTION
**Pull request by senky**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14863

PHPBB3-14863

### CODE REVIEW

**Comment by Nicofuma** [comment]
I don't think you need the `1` argument. And at the same time, please replace all $user->lang array usage in the line

**Comment by senky** [comment]
Argument is exactly the game changer here. Without it, you end up with situation ticket explains, or php warning about missing arguments to `sprintf` at best. While argument don't hinder strings without parameters, it resolves plural errors.

**Comment by Nicofuma** [comment]
IIRC is already handled by the lang() method, even if you don't give any parameter

**Comment by senky** [comment]
Method call without parameter:
```
[phpBB Debug] PHP Warning: in file [ROOT]/phpbb/user.php on line 513: sprintf(): Too few arguments
```

**Comment by marc1706** [comment]
@Nicofuma I think this is only the case on 3.2.x and newer.

**Pull request merged**
