### PR TITLE
[ticket/16149] Missing profile field data after registration

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16149

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16149

### CODE REVIEW

**Comment by 3D-I** [comment]
!set php

**Comment by 3D-I** [comment]
!set WIP

**Comment by 3D-I** [comment]
@kasimi Thoughts?

* the first commit solves the registration issue

* the second one is "hackish" IMO, returns an array with empty values for each field if the user_id is not in the table. But still is not there, such user_id.

```
array (size=1)
  33 => 
    array (size=7)
      'phpbb_location' => 
        array (size=2)
          'value' => string '' (length=0)
          'data' => 
            array (size=28)
              ...
      'phpbb_website' => 
        array (size=2)
          'value' => string '' (length=0)
          'data' => 
            array (size=28)
              ...
      'phpbb_facebook' => 
        array (size=2)
          'value' => string '' (length=0)
          'data' => 
            array (size=28)
              ...
      'phpbb_twitter' => 
        array (size=2)
          'value' => string '' (length=0)
          'data' => 
            array (size=28)
              ...
      'phpbb_skype' => 
        array (size=2)
          'value' => string '' (length=0)
          'data' => 
            array (size=28)
              ...
      'phpbb_youtube' => 
        array (size=2)
          'value' => string '' (length=0)
          'data' => 
            array (size=28)
              ...
      'phpbb_googleplus' => 
        array (size=2)
          'value' => string '' (length=0)
          'data' => 
            array (size=28)
              ...
```

Else a cron-job or a migration?

**Comment by kasimi** [comment]
Thanks for looking into this, I will test it soon.

As an alternative idea, I wonder what happens if the second condition here is removed: https://github.com/phpbb/phpbb/blob/4025a49a59f64116acf9f0999a39cca475fe6203/phpBB/phpbb/profilefields/manager.php#L367

If `!$this->profile_cache[$used_ident]['field_show_novalue']` is removed, the method returns all CPFs with an empty value for users who have never updated their profile, as would be expected, but it would mean that all callers of the `grab_profile_fields_data()` method that previously relied on getting an empty array would need to check the `field_show_novalue`. As far as I can see, the core already does this anyway.

**Comment by 3D-I** [comment]
I will be back on this as soon as I can, let me know pls if in the meantime you tested it.
There are a couple of things I'd like to discuss, later on.

**Comment by kasimi** [comment]
I tested your code changes in `phpbb/profilefields/manager.php` and it's returning unexpected results as well. For example, if I check "Show field if no value was selected" (the `field_show_novalue` option) for a PF, this PF's information is missing in the newly registered user's PF data that is returned by `grab_profile_fields_data()` even though it should be there. I don't understand what `field_show_novalue` has to do with fetching default CP data.

As for your changes in `includes/ucp/ucp_register.php` I'm not sure why they are needed. The `user_id` is already set in the `user_add()` function: https://github.com/phpbb/phpbb/blob/4db585a4cb2e5359074a82ef088574609155294b/phpBB/includes/functions_user.php#L302 I don't think registration needs fixing. No empty row should be added to the `phpbb_profile_fields_data` table for newly registered users, which is how it currently works.

**Comment by 3D-I** [comment]
Closing ATM.

**Pull request closed without merging**
