### PR TITLE
[ticket/15651] Remove unnecessary condition

### PR DESCRIPTION
**Pull request by senky**
PHPBB3-15651

Checklist:

- [ ] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15651

### CODE REVIEW

**Comment by rubencm** [comment]
https://tracker.phpbb.com/browse/PHPBB3-15090

**Comment by senky** [comment]
Funny thing is, this condition is always false so module was never removed... I guess we need to use explicit calls as [VSE used](https://github.com/VSEphpbb/abbc3/commit/108132bd0662eda01ed740fce1e5730422bfc250).

**Comment by rubencm** [comment]
If that always return false, is a bug in module.exists, so that is what has to be fixed i think

**Comment by senky** [comment]
`module.exists` works just like expected, but maybe `if` should be able to accept input other than false.

**Comment by kasimi** [comment]
`module.remove` doesn't need an `if` check in the migration at all because it checks if the module exists internally: https://github.com/phpbb/phpbb/blob/release-3.2.2/phpBB/phpbb/db/migration/tool/module.php#L386

I agree that the `if` should support calling other tools, and it should be fairly simple: if `$condition` is an array [here](https://github.com/phpbb/phpbb/blob/release-3.2.2/phpBB/phpbb/db/migrator.php#L763), use something like `$this->run_step($this->get_callable_from_step($condition), $last_result, $reverse)`, as the condition, otherwise use `$condition` itself.

**Comment by senky** [comment]
@kasimi does your comment mean this ticket should cover the changes?

**Comment by kasimi** [comment]
No, you're right, the 2nd part of my reply above should be done in a new ticket. But the first part is relevant to this one.

**Comment by senky** [comment]
https://github.com/phpbb/phpbb/pull/5260

**Comment by Nicofuma** [comment]
is it still relevant?

**Comment by senky** [comment]
I think so. PR enabling other tools being used in conditions isn't merged yet. Better safe than sorry.

**Comment by Nicofuma** [comment]
well the other PR will be merged before this one.. so ? (and it's not an issue to try to remove a non existing module?)

**Comment by senky** [comment]
>> and it's not an issue to try to remove a non existing module?

No, because `module.remove` internally checks if module exists. So it's secure.

**Comment by Nicofuma** [comment]
ok

**Pull request merged**
