### PR TITLE
[ticket/16093] Do not display attach-row-tpl

### PR DESCRIPTION
**Pull request by marc1706**
PHPBB3-16093

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16093

### CODE REVIEW

**Comment by hanakin** [comment]
why are you using an id?

**Comment by mrgoldy** [comment]
Also, isn't the attachment system rather depending on jQuery in the first place? Which removes the element from the document completely once initialised. So not sure what the benefit of this is?

**Comment by hanakin** [comment]
It’s not removed when js is disabled

**Comment by marc1706** [comment]
@hanakin done ;)

**Pull request merged**
