### PR TITLE
[ticket/15708] Use truncate from dbal

### PR DESCRIPTION
**Pull request by rubencm**
Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15708

### CODE REVIEW

**Comment by Nicofuma** [comment]
I think it shouls target 3.3

**Comment by rubencm** [comment]
Ok, but the main pull request was for 3.2

**Comment by Nicofuma** [comment]
yeah but we think it's too big for the current state of 3.2

**Comment by rubencm** [comment]
I think the problem i have now is something related with #5330

**Pull request closed without merging**
