### PR TITLE
[ticket/15318] Make user option to disable word censoring effective again

### PR DESCRIPTION
**Pull request by rxu**
For 3.2.x/master only.

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

<a href="https://tracker.phpbb.com/browse/PHPBB3-15318">PHPBB3-15318</a>.

### CODE REVIEW

**Comment by rxu** [comment]
@JoshyPHP I guess I'm missing something (or everything) on fixing this for the text renderer.

**Comment by JoshyPHP** [comment]
Judging by the error message you need to instantiate a global `$auth` object in the tests that use that function.

**Comment by rxu** [comment]
@JoshyPHP PHP error fixed but the test fails.

**Comment by JoshyPHP** [comment]
I don't know why, you'll have to debug it. It may be that tests are based on assumptions that differ from the actual implementation.

**Comment by rxu** [comment]
@JoshyPHP Thanks, got it fixed.

**Pull request merged**
