### PR TITLE
[ticket/10424] Added Date-filter to viewtopic_body.html

### PR DESCRIPTION
**Pull request by balabky9**
As per ticket to only display the Join date on forum posts of a user an edit
was done to viewtopic_body.html of styles/prosilver where a twig date formater
was utilized to get only the Day, Date Month-name and Year in this format.

PHPBB3-10424

Checklist:

- [ ] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [ ] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-10424

### CODE REVIEW

**Comment by hanakin** [comment]
1. why did you recreate the PR (https://github.com/phpbb/phpbb/pull/4758) Close one of them.
2. You need to update your repo as it seems to be behind your PR is removing newly added classes
3. Check comment on old repo

**Comment by vinny** [comment]
As mentioned by bantu in the ticket, I think the line should be removed.

**Comment by balabky9** [comment]
I find the join date valuable. As a forum surfer if a person has been on the forum for a longer time it generally suggest better topic maturity and understanding. So its an important part to display it.

**Comment by hubaishan** [comment]
This PR does not add ability to customize the join date format, the extension in https://www.phpbb.com/customise/db/extension/joined_date_format is more powerful, so I suggest to merge the ext to phpBB and add ability to block joined date as some developers suggest.

**Comment by DavidIQ** [comment]
Yeah no thanks. That's overkill. Stick to the extension if you really want that much control over the display of the join date.

That being said I think removing the join date is something that could be revisited for the new style, but not right now for prosilver.

**Comment by hubaishan** [comment]
Also I am not sure that this PR will handle the timezone of the user how viewing the forum.

**Comment by balabky9** [comment]
It would since its just filtering on the template side. The date variable being passed into the view is not touched at all.

**Comment by marc1706** [comment]
The PR will ignore user's date format settings and only work in the server's default time zone. Also, I don't think directly adding this to the HTML is a good idea.

**Pull request closed without merging**
