### PR TITLE
 twig extension for template name

### PR DESCRIPTION
**Pull request by agrisvv**
Allow twig extension for template name for better IDE support.

https://tracker.phpbb.com/browse/PHPBB3-14421

### CODE REVIEW

**Comment by VSEphpbb** [comment]
phpBB does not use .twig files as part of its core. We should not change core code just to make an IDE's syntax highlighter happy. Besides, my IDE highlights twig syntax in .html fine, but I set it up to do so, and most should allow that if desired.

**Comment by agrisvv** [comment]
i understand you. but i know what some day phpbb code will go to full names of template files, because, templates could bee different type- xml json html xsd.... 
i think it is not hard to change core code, just allow template names with extensions not just *.html.
thanks.

**Comment by VSEphpbb** [comment]
When/if phpBB does switch to twig only templates we will handle the naming recognition properly at that time.

**Comment by marc1706** [comment]
Closing as per explanation of @VSEphpbb

**Pull request closed without merging**
