### PR TITLE
[ticket/14586] Add OAuth1 support

### PR DESCRIPTION
**Pull request by Senky**
[PHPBB3-14586](https://tracker.phpbb.com/browse/PHPBB3-14586)

### CODE REVIEW

**Comment by CHItA** [comment]
IMHO this looks like a feature. @nickvergessen

**Comment by nickvergessen** [comment]
Well, yes and no. But I'd ask @Nicofuma for 3.2 or master

**Comment by marc1706** [comment]
I think this should make it into 3.2.x. It's just a minor change that adds support for twitter auth.
@Nicofuma what do you think?

**Comment by Nicofuma** [comment]
I'd say 3.2.1

**Comment by Senky** [comment]
OK, so do I need to close this PR and open a new one on 3.2 branch?

**Comment by nickvergessen** [comment]
Yes

**Pull request closed without merging**
