### PR TITLE
[ticket/15238] Add console command to fix forums/modules left/right IDs

### PR DESCRIPTION
**Pull request by rxu**
For 3.2.x/master only.

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

<a href="https://tracker.phpbb.com/browse/PHPBB3-15238">PHPBB3-15238</a>.

### CODE REVIEW

**Comment by rxu** [comment]
!set WIP

**Comment by rxu** [comment]
!unset WIP

**Comment by marc1706** [comment]
Please try to follow these instructions when creating the two separate PRs next time: https://area51.phpbb.com/docs/dev/31x/development/git.html#merging-to-3-1-x-and-master-with-different-patches

Would prevent a bit of merge conflict resolution for us. ;)

**Comment by rxu** [comment]
@marc1706 Sure, thatks. But I actually didn't get how could I merge fix-3.1.x into master as the master doesn't even have the patched files in their locations.

**Comment by rxu** [comment]
Oh, it's not actually the case for this particular PR, sorry. Got it.

**Pull request merged**
