### PR TITLE
[ticket/14075] Add template event after poll preview panel

### PR DESCRIPTION
**Pull request by javiexin**
PHPBB3-14075

### CODE REVIEW

**Comment by Elsensee** [comment]
Unrelated commit in branch?

**Comment by javiexin** [comment]
Sync up of my main local repository.  It is a reverse PR.  Does not add any code, as you can see.

**Comment by marc1706** [comment]
Checkout this branch and do:
```
git reset --hard
```
Afterwards run this (if the main phpBB repository does not exist yet or has a different name you'll have to add it first or replace the name of upstream):
```
git fetch upstream
git reset --hard upstream/3.1.x
git cherry-pick 4bbb3e1
git push origin ticket/14075
```

**Comment by javiexin** [comment]
$ git fetch upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by javiexin** [comment]
It give me errors:
$ git fetch remotes/origin
fatal: 'remotes/origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Here is a picture of my setup.  Sorry for my limited git knowledge.
phpbb_repo_setup

**Comment by Nicofuma** [comment]
`git fetch origin`

**Comment by javiexin** [comment]
That was one of the things I tried, same results.  Will do it again anyhow.

**Comment by javiexin** [comment]
A little further, but still not successful:

$ git push origin ticket/14075
Username for 'https://github.com': javiexin
Password for 'https://javiexin@github.com':
To https://github.com/javiexin/phpbb.git
 ! [rejected]        ticket/14075 -> ticket/14075 (non-fast-forward)
error: failed to push some refs to 'https://github.com/javiexin/phpbb.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by javiexin** [comment]
Thanks, now done.  It was the -f that was missing in the last push.
Now, if someone could explain (for dummies like me) what we have done here, and how to do it for all branches that I create... Because this has happened in a number of other PRs from myself (at least three that I recall).  And it might happen in the future as well.
The real question is: how do I keep my local repository in sync with phpbb/3.1.x branch, and yet not have these reverse PRs show up.
Thanks for your help.

**Comment by Zoddo** [comment]
> The real question is: how do I keep my local repository in sync with phpbb/3.1.x branch, and yet not have these reverse PRs show up.

To make sure that your branch is clean:
```
git checkout 3.1.x
git fetch upstream
git reset --hard upstream/3.1.x
git push -f origin 3.1.x
```
The next times, you can simply do a pull/push from upstream to origin:
```
git checkout 3.1.x
git pull --ff-only upstream 3.1.x
git push origin 3.1.x
```

**Comment by marc1706** [comment]
Replaced by #3853

**Pull request closed without merging**
