### PR TITLE
[3.2][ticket/14386] Fix for open_basedir restriction in effect with remote upload avatar

### PR DESCRIPTION
**Pull request by ErnadoO**
PHPBB3-14386

### CODE REVIEW

**Comment by marc1706** [comment]
Previously we used the cache directory with activated safe_mode setting. Your patch changes this to a different behavior. Please fix this the same way as for 3.1.x.

**Comment by ErnadoO** [comment]
Yes but phpBB 3.2 require php5.4, or safe mod has been removed in this version, so this condition is obsolete.
I'm wrong ?

**Comment by marc1706** [comment]
Oh right, forgot about that. Then this should be fine.

**Comment by Nicofuma** [comment]
:+1:

**Comment by marc1706** [comment]
Replacing this with a fast-forward compatible branch

**Comment by marc1706** [comment]
Replaced by #4110

**Pull request closed without merging**
