### PR TITLE
[ticket/14318] Fix SQL error in Notifications Board migration

### PR DESCRIPTION
**Pull request by Senky**
[PHPBB3-14318](https://tracker.phpbb.com/browse/PHPBB3-14318)

### CODE REVIEW

**Comment by RMcGirr83** [comment]
You should prepend your commit with the ticket number per the guidelines.

**Comment by Senky** [comment]
Well, I believe that `[ticket/14318]` prefix is just what you mean.

**Comment by RMcGirr83** [comment]
Correct I guess but as far as I'm aware your initial commit message
`Fix SQL error in Notifications Board migration`
should be like
`[ticket/14318] Fix SQL error in Notifications Board migration`

**Comment by Mauron** [comment]
That is not a commit message, that's the PR title: thatìs why TravisCI check is successful.

**Comment by RMcGirr83** [comment]
If one looks at all the other commit messages the PR title, or whatever you want to call it, all reference the original ticket.  Pretty sure that is a requirement per the guidelines no matter what travis does or does not do.

**Comment by Senky** [comment]
Oh, you meant PR title? Commit message already includes ticket ID. Now, PR title too.

**Comment by Mauron** [comment]
As far as I recall, PR title has not to have the ticket ID.
I read this in a previous PR where the first commit was actually without ticket ID and the author added it to PR title (but the build still failed).

**Pull request merged**
