### PR TITLE
[ticket/13709] Add fallback for email templates used by extensions

### PR DESCRIPTION
**Pull request by Elsensee**
Also add a fallback to english for the core like we do it in `$user->add_lang()`

[PHPBB3-13709](https://tracker.phpbb.com/browse/PHPBB3-13709)

### CODE REVIEW

**Comment by Elsensee** [comment]
Wanted to write tests for this by setting the email template in different languages and then checking for the right path to template with the function `get_filename_for_handle()` of the template class.

But the $template object of the messenger class is protected so I cannot access it.

Any other ideas on how to write a test for this? :)

**Comment by dragosvr92** [comment]
I followed the instructions on my 3.1.3 board and i switched language to one secondary to English. I still got a blank page when i tried to use it, as i dont have its language files for all the installed extensions. :(

**Comment by dragosvr92** [comment]
Nevermind.... This is only for email templates used by extensions, not html templates also :(
https://www.phpbb.com/community/viewtopic.php?f=466&t=2306361

**Comment by Elsensee** [comment]
Correct, but what you're describing *should* already work. => https://github.com/phpbb/phpbb/blob/526329e6972914ac6d62c092da410e349d96d808/phpBB/phpbb/user.php#L656-L684
But you can of course create a ticket in our bugtracker and we will look into it. :)

**Comment by VSEphpbb** [comment]
Template files (except for emails) DO properly fall back if extensions do not have translations...either to the board default if supported by the ext, or to english as a last resort.

**Comment by dragosvr92** [comment]
Well, they do not seem to fall back for me. And seeing that you are wrong in claiming MODs also used to  fall back to en. I tend to think that is not for ext either. But we seem to be off-topic here, so i think we should speak on the phpbb.com link i left above :)

**Comment by VSEphpbb** [comment]
@dragosvr92 As far as extensions go, English fallback is fully supported except email templates which this PR fixes. As for MODs, they fell back too except for MOD's info_acp lang files, which showed up as raw lang keys (and could break an ACP page if it was the first module, typically in the .MODs page)

**Comment by Nicofuma** [comment]
:+1:

**Comment by Elsensee** [comment]
Turns out my approach doesn't work, so I'm back at the point where I have no idea how to write tests for this. If anyone has an idea, please share it.
Otherwise go and merge this. ^^

**Comment by marc1706** [comment]
Have you tried extending the class with a new test class and overwriting unneeded methods with basically more or less blank methods?

**Comment by Nicofuma** [comment]
@Elsensee you need to rebase your branch. After that we could talk about "how to write" the test (don't hesitate to ask on IRC when you have time to work on that)

**Comment by RMcGirr83** [comment]
bump @Elsensee

**Comment by Elsensee** [comment]
Gotcha.

**Comment by rmcgirr83** [comment]
bump @Elsensee again

**Comment by Elsensee** [comment]
Rebased.

And in all honesty: I'd rather write tests for this if we refactor this class instead of now.
Writing tests for new (and/or refactored) code is pretty much the only option I see to have (almost) full code coverage regarding tests.
If you don't think so, I'll sit down and try to write a test for this method, but it'll really be a lot of hacking.

**Comment by marc1706** [comment]
Is there already a ticket that would result in a refactoring of this file? If not, please add it.

**Pull request merged**
