### PR TITLE
[ticket/14815] Fix facebook link on memerberlist.php

### PR DESCRIPTION
**Pull request by khan0604**
PHPBB3-14815

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14815

### CODE REVIEW

**Comment by khan0604** [comment]
I am unable to understand the errors.Can someone please guide me to resolve these errors.

**Comment by Crizz0** [comment]
Imo you need to repair tests for the UCP profilefields:

```
1) phpbb_functional_ucp_profile_test::test_submitting_profile_info
InvalidArgumentException: The current node list is empty.
/home/travis/build/phpbb/phpbb/phpBB/vendor/symfony/dom-crawler/Crawler.php:565
/home/travis/build/phpbb/phpbb/tests/functional/ucp_profile_test.php:37
```

**Comment by khan0604** [comment]
@Crizz0 thanks for your help.The Travis CI build passed. Please help me to pass AppVeyor build.

**Comment by DavidIQ** [comment]
You don't need to worry about the AppVeyor failure as it isn't due to your changes and we are aware of the problem.

**Comment by gooof** [comment]
And you need a new migration file to overwrite the phpbb_profile_fields entry (if available). Don't change the old migration file.

**Comment by Crizz0** [comment]
@khan0604 With "repair" the tests, I meant to keep their functionality but don't remove them. But I think, you just removed them, right?

**Comment by CHItA** [comment]
I think this should be kept as a text field, so users could still only enter they username, and not a full profile URL.

**Comment by khan0604** [comment]
The original code was for a text field type and since I changed the field type of profile field facebook from text to URL to fix the link issue on memberlist.php file the corresponding field does not require any text field type tests.

**Pull request closed without merging**
