### PR TITLE
[ticket/13433] Fix parsing of email addresses

### PR DESCRIPTION
**Pull request by rxu**
Currently email addresses are parsed incorrectly due to the regex structure.
Namely, if localpart consists of several dot separated parts, only the last
part with the trailing dot will be captured.
The patch change this behavior to capture the whole localpart.

<a href="https://tracker.phpbb.com/browse/PHPBB3-13433">PHPBB3-13433</a>.

### CODE REVIEW

**Comment by nickvergessen** [comment]
This needs a test case

**Comment by rxu** [comment]
Yeah, I plan to add it later.

**Comment by rxu** [comment]
Just to mention, there're already some tests for emails partially:
https://github.com/phpbb/phpbb/blob/develop-ascraeus/tests/regex/email_test.php
https://github.com/phpbb/phpbb/blob/develop-ascraeus/tests/functions/make_clickable_test.php

**Comment by nickvergessen** [comment]
There were 6 failures:

**Comment by rxu** [comment]
Fixed #3414.

**Comment by marc1706** [comment]
Merged with https://github.com/phpbb/phpbb/commit/13948718c69b643ff608d357cc4bc400e2b7ee7b

**Pull request closed without merging**
