### PR TITLE
[ticket/16665] Fix Emoji for strings in board settings + new event

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16665

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16665

### CODE REVIEW

**Comment by 3D-I** [comment]
immagine

**Comment by 3D-I** [comment]
I have added a related event, possibly I could create another ticket for this. Please let me know.

**Comment by 3D-I** [comment]
Set !Event

**Review by marc1706 — APPROVED** [review]

**Comment by 3D-I** [comment]
!set Event

**Pull request merged**
