### PR TITLE
Fix on memberlist the sort method.

### PR DESCRIPTION
**Pull request by Leinad4Mind**
This way, after clicking on posts or other, it will sort desc. so the high numbers will apear.
In asc mode, we need to click twice to be able to see who posted more, etc.
Just the username makes sense to be as asc mode.

https://tracker.phpbb.com/browse/PHPBB3-14242

### CODE REVIEW

**Comment by CHItA** [comment]
Your commit message isn't in the [required format](https://wiki.phpbb.com/Git#Commit_Messages).
Also your branch should have the name `ticket/14242`. If you don't know how to do these things, feel free to ask for further help.

Thanks for your contribution!

**Comment by Leinad4Mind** [comment]
Sorry don't know how to do it. :/

**Comment by CHItA** [comment]
All right, we can do that when merging this PR.

**Comment by prototech** [comment]
Replaced by #3996

**Pull request closed without merging**
