### PR TITLE
Fixes for incomplete code changes in prosilver in 3.1.5-RC1

### PR DESCRIPTION
**Pull request by cyberalien**
https://tracker.phpbb.com/browse/PHPBB3-13938

### CODE REVIEW

**Comment by marc1706** [comment]
:+1:

**Comment by callumacrae** [comment]
looks goood

**Comment by nickvergessen** [comment]
Merged into prep via https://github.com/phpbb/phpbb/compare/e59b96e968a4...f688bc6160b6

**Comment by bantu** [comment]
@nickvergessen What happened here? No merge into 3.1.x?

**Comment by nickvergessen** [comment]
Seems like the commits changed ids when I cherry-picked them to the prep branch:
https://github.com/phpbb/phpbb/commit/7ccb19fa001cb0f76499fd19256e60df382c6d2a

**Comment by bantu** [comment]
@nickvergessen Err. Ah. Yes.

**Pull request closed without merging**
