### PR TITLE
[ticket/15554] Simple fotter after load js

### PR DESCRIPTION
**Pull request by ankitjain28may**
Signed-off-by: ankitjain28may <ankitjain28may77@gmail.com>

Checklist:

- [ ] Correct branch: master for new features; 3.2.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15554

### CODE REVIEW

**Comment by CHItA** [comment]
This is not the solution which was requested in the ticket. You would just need to put the the event code (provided in the ticket) after the `</body>` tag.

Also this PR should be based on the 3.2 branch, so I'm closing this PR, feel free to resubmit it against the correct branch.

**Comment by ankitjain28may** [comment]
@CHItA I am sorry but i am not getting the event code you are talking about. Please guide me from where should i start to read so that i will get familiar with the code base.

**Comment by rubencm** [comment]
You don't have to close this pr to add another, he can change the base branch with the github interface

**Comment by CHItA** [comment]
phpBB has an event system (or two), one is for the HTML template files, which are triggered by the comments. This ticket is about adding a template event by placing the comment in the ticket in the file you edited, after the `</body>` tag. There is not much else to this ticket, and I think this is all you could learn from this issue. If you have other questions about the codebase, please open a topic in the area51 forums, or chat with us on IRC.

**Pull request closed without merging**
