### PR TITLE
[ticket/16850][3.3] Update webfont loader

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16850

Ref.: https://github.com/phpbb/phpbb/pull/6271

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16850

### CODE REVIEW

**Comment by 3D-I** [comment]
@marc1706 what if we use this CDN instead? `https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js`

**Comment by 3D-I** [comment]
Newer version is hosted elsewhere, like

https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js
https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.min.js
https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js

**Comment by marc1706** [comment]
I would opt for the minimized version from jsdelivr

**Comment by marc1706** [comment]
@3D-I if your target is to fix issues between RC1 and the stable release, please target prep-release- next time. Thanks.

**Pull request merged**
