### PR TITLE
[ticket/15985] List ban duration in logs

### PR DESCRIPTION
**Pull request by stevendegroote**
Log the length of a ban, so moderators can check afterwards how long previous
bans were.

PHPBB3-15985

Checklist:

- [ ] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-12345

### CODE REVIEW

**Comment by 3D-I** [comment]
Is this PR intended for 3.2.x?

**Comment by stevendegroote** [comment]
I think that can be part of 3.2 indeed.

**Comment by 3D-I** [comment]
So you should change the destination branch here, clicking on it:

immagine

**Comment by 3D-I** [comment]
In fact, the flow is:

1 - switch/checkout to `3.2.x`
2 - create the branch (ticket/number)
3 - push the branch

You need to start from `3.2.x` not `master`

**Comment by stevendegroote** [comment]
Ok, good to know. Thought the team decided that.

**Pull request closed without merging**
