### PR TITLE
[ticket/16816] acp style html validation fixes

### PR DESCRIPTION
**Pull request by Prosk8er**
Fix acp style html validation errors and warnings

PHPBB3-16816

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16816

### CODE REVIEW

**Comment by hanakin** [comment]
I know these are just trivial changes, but normally when any changes are made to the html/css we require before and after screenshots be posted as well on here. It helps us more quickly review and merge things. It also provides us with a visual que to what is being worked on. Thanks 😉

**Comment by Prosk8er** [comment]
only change you might notice is to adm/style/acp_inactive.html
before
Screenshot 2021-07-10 071400
after
Screenshot 2021-07-10 071444
the others will look exactly the same

**Comment by 3D-I** [comment]
There is something wrong in both of them.
The last `mark` has no checkbox.

**Comment by hanakin** [comment]
I get that from the code it's not just about appearance as I mentioned it's also to let us know visually what you specific section you are adjusting in the markup.

**Comment by Prosk8er** [comment]
@hanakin gotcha i'll keep that in mind also

**Review by hanakin — APPROVED** [review]
Looks good to me

**Pull request merged**
