### PR TITLE
[ticket/12933] Handle case when * is last character of word

### PR DESCRIPTION
**Pull request by dhruvgoel92**
PHPBB3-12933
https://tracker.phpbb.com/browse/PHPBB3-12933
ASC Patch: https://github.com/phpbb/phpbb/pull/3338

### CODE REVIEW

**Comment by dhruvgoel92** [comment]
Develop PR: https://github.com/phpbb/phpbb/pull/3338

**Comment by bantu** [comment]
@dhruvgoel92 https://tracker.phpbb.com/browse/PHPBB3-13548 links to here, here links to https://tracker.phpbb.com/browse/PHPBB3-12933. What is going on here?

**Comment by bantu** [comment]
All cleared up.

**Comment by bantu** [comment]
Replacing with #3349

**Pull request closed without merging**
