### PR TITLE
[ticket/16503] Fix WhoIs lookup

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16503

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16503

### CODE REVIEW

**Comment by 3D-I** [comment]
IP v6

immagine


IP v4

immagine

**Comment by CrazyC0d3r** [comment]
Whois lookups no longer work on my board after applying the new file changes. I get that following:
`This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

%ERROR:101: no entries found
%
% No entries found in source RIPE.

% This query was served by the RIPE Database Query Service version 1.97.1 (ANGUS)`

**Comment by kasimi** [comment]
@CrazyC0d3r https://tracker.phpbb.com/browse/PHPBB3-16508

**Comment by 3D-I** [comment]
https://github.com/phpbb/phpbb/pull/5998

**Comment by CrazyC0d3r** [comment]
Whois remains broken for me when implementing these code changes on my 3.2.9 board.

I always get:

> This is the RIPE Database query service.
> % The objects are in RPSL format.
> %
> % The RIPE Database is subject to Terms and Conditions.
> % See http://www.ripe.net/db/support/db-terms-conditions.pdf
> 
> % Note: this output has been filtered.
> % To receive output for a database update, use the "-B" flag.
> 
> %ERROR:101: no entries found
> %
> % No entries found in source RIPE.
> 
> % This query was served by the RIPE Database Query Service version 1.97.1 (ANGUS)

I need to look into this further. :/

**Pull request merged**
