### PR TITLE
[ticket/14694] User DateTimeZone warnings. 

### PR DESCRIPTION
**Pull request by bovidiu**
Checklist:
- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket [**PHPBB3-14694**](https://tracker.phpbb.com/browse/PHPBB3-14694)

### CODE REVIEW

**Comment by bovidiu** [comment]
Can someone explain me where exactly fails ? ( i would like to fix it)

**Comment by marc1706** [comment]
Your commit message does not follow the format that is outlined in the linked format (see checklist above). Therefore the build is failing

**Comment by marc1706** [comment]
Also, your changes do not seem to follow our coding guidelines as well:
```
FILE: /home/travis/build/phpbb/phpbb/phpBB/phpbb/user.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
----------------------------------------------------------------------
 192 | ERROR | There should be exactly one space between the keyword and
     |       | opening parenthesis
     |       | (phpbb.ControlStructures.OpeningParenthesis.NoSpaceBeforeOpeningParenthesis)
 192 | ERROR | Opening brace should be on a new line
     |       | (phpbb.ControlStructures.OpeningBraceBsdAllman.BraceOnSameLine)
-----------------------
```
These are also linked to in the above checklist

**Comment by bovidiu** [comment]
@marc1706 Thank you for your feedback!
Can you please help again, what's now the issues ?

**Comment by Crizz0** [comment]
Your commit message is still wrong. Please use this template for it: https://wiki.phpbb.com/Git#Commit_Messages

Thank you

**Comment by bantu** [comment]
I am having a hard time understanding the fix. To me it looks like if the user specified an incorrect timezone, an Exception will be thrown which is not caught. @bovidiu Can you enlighten me?

**Comment by bantu** [comment]
@bovidiu ?

**Comment by marc1706** [comment]
Setting this to "Pending Closure" as author hasn't replied in over 2 months.
@bovidiu mind replying to bantu's question?

**Comment by rxu** [comment]
Should be fixed with #5916.

**Pull request closed without merging**
