### PR TITLE
[ticket/15058] Force browser to redownload stylesheets

### PR DESCRIPTION
**Pull request by DavidIQ**
Checklist:

- [X] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [X] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [X] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15058

### CODE REVIEW

**Comment by marc1706** [comment]
Why don't you append the assets version to the stylesheet.css links in overall_header and simple_header ?

**Comment by DavidIQ** [comment]
We do that already and it's not enough apparently.

**Comment by javiexin** [comment]
What I have seen is that even though the asset version is appended to stylesheet.css, it then imports other files, that have the SAME name as before (no asset version appended), so the browser interprets that it is the same file it already has, and it does not reload them.
What I had to do in my own local testing bed was to remove "import" and either include  the nested files in overall_header directly (appending the asset version) or actually including the rules into stylesheet.css.
The resolution here is smarter, of course, but will require to bump the number in stylesheet.css for every change that happens in an stylesheet, at least from version to version, and that in case the user has not modified manually any stylesheet css file.
I think some automated way of doing it would be required.  
What about templated CSS for key elements, as _stylesheet.css_?
Something like replacing  in _overall_header.html_
`<link href="{T_STYLESHEET_LINK}" rel="stylesheet">`
by
`<!-- INCLUDE stylesheet_css.html -->`
And then, use in _stylesheet_css.html_
```
<link href="{T_THEME_PATH}/normalize.css?assets_version={T_ASSETS_VERSION}" rel="stylesheet">
...
```

**Comment by marc1706** [comment]
The goal for future versions is to compile the stylesheet into one and minimize it as well. I don't think we should spend too much time on trying to split this into a separate file that will then load all stylesheets one by one again. We could try using assets management like symfony's assetic in 3.2 but I think for now this change is ok as a quick fix.

**Pull request merged**
