### PR TITLE
[ticket/13474] Deny access on backup files of config.php

### PR DESCRIPTION
**Pull request by tas2580**
https://tracker.phpbb.com/browse/PHPBB3-13474

### CODE REVIEW

**Comment by tas2580** [comment]
Maybe you don't need <Files "config.php"> because <Files "config.*"> includes .php but maybe there are Apache versions with no support of .*

**Comment by Nicofuma** [comment]
I don't think that we should try to match every backup file introduced by any editor because in this case this PR isn't enough (you are missing emacs and vim backup files per example)

**Comment by Nicofuma** [comment]
well IIRC emacs and vim can create other backup files... no matter
But add the same changed to the web.config file please

**Comment by nickvergessen** [comment]
commit message must have the following end:
```

PHPBB3-13474
```

**Comment by bantu** [comment]
> I don't think that we should try to match every backup file introduced by any editor because in this case this PR isn't enough (you are missing emacs and vim backup files per example)

I agree. This change is pointless in my opinion. Some editors use a prefix, some use a suffix, etc. etc.

**Comment by tas2580** [comment]
If an editor use a prefix its no problem because the file ends with .php and so the content will not be shown.

Why deny access to config.php its no problem to view config.php in a webbrowser, but its a problem if you can view config.bak or config.old in a webbrowser.
Of course this will not hide all possible config backups, there are to much editors and to much configurations, so you can never get all, there I agree with you. But you can get with a small change a lot of editors and configurations, so why do not do this?
Nicofuma is right in web.config should done the same as in htaccess and when you have Apache and IIS.

Maybe you will see the problem when I give you a list with config backups of phpBB, I will run a little script over tonight so that I can give you some examples tomorrow.

**Comment by nickvergessen** [comment]
Closing as per ticket

**Pull request closed without merging**
