### PR TITLE
[ticket/16343] Fix Quick reply subject

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16343

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16343

### CODE REVIEW

**Comment by 3D-I** [comment]
immagine

**Comment by rxu** [comment]
Personally, I don't like this change as last post subject is editable by the last post's author so can be even empty. phpBB is flat so users reply to a topic and not to post.
Also, if you, say, merge posts/topic into another topic, you'll get merged post's/topic's last post subject here instead of the "parent" topic's title and have to edit last post subject after merging as such.

**Comment by 3D-I** [comment]
If the topic has one post only the `post subject` is the topic title, if it has 2 or more posts then it is the `last post subject`.

When you reply with the button to a topic you get the `topic's last post subject` or the `post subject` into the form depending on the above conditions, that's what the quick reply has to do: **obey to the standard.** IMHO :smiley_cat: 

Moreover, when you parse via CLI the _posts/topics/forums/PMs_ this are the indexes related, which are parsed:

```
		'forums'	=> 'forum_last_post_subject',
		'topics'	=> 'topic_last_post_subject',
		'posts'		=> 'post_subject',
		'pms'		=> 'message_subject',
```

**Comment by mrgoldy** [comment]
Not sure if I follow, but when replying to a topic (regardless of how many replies that topic has) I always get the `Re: <topic title>` and never the `Re: <last post subject>`

**Comment by 3D-I** [comment]
> 
> 
> Not sure if I follow, but when replying to a topic (regardless of how many replies that topic has) I always get the `Re: <topic title>` and never the `Re: <last post subject>`

Yes you are correct, same goes to @rxu - I missed something here, my bad.

Closing as such.

**Pull request closed without merging**
