### PR TITLE
[ticket/14997] Fixing Event Position

### PR DESCRIPTION
**Pull request by TarantinoMariachi**
Fixing position as it is correctly on subsilver, orelse it will appear some problems when using polls or on topics with page numbers.

Checklist:

- [X] Correct branch: yes correct 3.1 branch
- [X] Tests pass
- [X] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [X] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):
Doesnt seems that I need to create a ticket for this little problem

Could not automatically create an issue. Please create one on https://tracker.phpbb.com/ and replace this text with a link to it.

### CODE REVIEW

**Comment by DavidIQ** [comment]
"Doesnt seems that I need to create a ticket for this little problem"
You do actually. [All pull requests need to be associated to a ticket.](https://github.com/phpbb/phpbb#contribute)

**Comment by Leinad4Mind** [comment]
https://tracker.phpbb.com/browse/PHPBB3-14997, you're welcome.

**Comment by DavidIQ** [comment]
And the [commit message](https://area51.phpbb.com/docs/dev/31x/development/git.html#commit-messages) is wrong. Probably easier to redo this pull request and follow the guidelines.

**Comment by marc1706** [comment]
Replaced by #4663

**Pull request closed without merging**
