### PR TITLE
[ticket/13972] Change hard coded time check to use flood interval

### PR DESCRIPTION
**Pull request by RMcGirr83**
https://tracker.phpbb.com/browse/PHPBB3-13972

PHPBB3-13972

### CODE REVIEW

**Comment by RMcGirr83** [comment]
Maybe the check should be removed completely with the exception of someone pressing the cancel button?  Flood check is handled later on in the file.

**Comment by ElooKoN** [comment]
See also: https://www.phpbb.com/community/viewtopic.php?p=14370186#p14370186

**Comment by RMcGirr83** [comment]
Bump @marc1706 @Nicofuma @CHItA

**Comment by marc1706** [comment]
This check doesn't actually make much sense. The point of it is some kind of flood control. As a result of that, one should see an error message. It does however redirect to viewtopic without no apparent reason. Removing the second part (``` || ($current_time - $lastclick < intval($config['flood_interval']) && $submit)```) will properly trigger the flood control so I'd rather go with checking that.
As this is a change of behavior I'd vote for merging this into 3.2 only though.
@Nicofuma ^

**Comment by Nicofuma** [comment]
Fine with 3.2

**Comment by RMcGirr83** [comment]
https://github.com/phpbb/phpbb/pull/4210

**Pull request closed without merging**
