### PR TITLE
[ticket/14018] Fix responsive quick link menus

### PR DESCRIPTION
**Pull request by VSEphpbb**
https://tracker.phpbb.com/browse/PHPBB3-14018

PHPBB3-14018

### CODE REVIEW

**Comment by callumacrae** [comment]
Why can't this be done as em?

**Comment by marc1706** [comment]
Yes, please elaborate how to reproduce this issue and why em doesn't work here.

**Comment by callumacrae** [comment]
Why on earth is the font-size being set to zero? That's completely the wrong approach to hiding text on mobile.

I'd suggest actually fixing the main issue instead of fixing the symptoms of the weirdness.

**Comment by VSEphpbb** [comment]
Check the ticket for elaboration. Resize your browser down to mobile phone size to see the Quick Links menu vanish in the header, and get distorted in the footer.

In responsive, the font size is 0 from here: https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/styles/prosilver/theme/common.css#L1264-L1266

Changing that to a non-zero breaks the layout in the nav bars. So it's 0 for a reason. So we need to use px for the `a.responsive-menu-link`s because em relative to 0 is just 0.

**Comment by VSEphpbb** [comment]
Here's another version. Using em again.
1. First, replacing omitted font size from the footer navbar
2. em is 1.455 because the base font size is 11px, and we're trying to get to 16px so that = 1.455em
3. Instead of hiding the "Quick Links" text by using font-size:0, instead use width:0 with overflow and word wrap trickery. hopefully it's browser compatible (works for me on Mac with latest Safari, Chrome and FF and on iOS).

**Comment by callumacrae** [comment]
lgtm :+1:

**Pull request merged**
