### PR TITLE
[ticket/12539] Live member search improvements

### PR DESCRIPTION
**Pull request by mrgoldy**
PHPBB3-12539

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-12539

---

This will add the ability to navigate the search results in the _Live Member Search_ in the _Memberlist > Find a Member_ functionallity.

Able to navigate with the `arrow keys` (up and down).
Set the value of the selected row with `enter`
Close the dropdown with `escape`.
Show the loading indicator

--- 

Branch is set to 3.3.x as it is rather pointless for 4.0 as it is stated that entire JS will be redone for that version.

### CODE REVIEW

**Comment by marc1706** [comment]
Can we also prevent the caret from moving while navigating through the list in the dropdown? Right now the caret jumps to the beginning of the text one has entered when pressing the up key. This will result in users then accidentally typing at the beginning of the entered string instead of appending to the end.

**Comment by mrgoldy** [comment]
The cursor (or caret) is no longer repositioning upon navigating the search results, for both the up (start) and down (end) arrow. It now just sticks to its current position.

**Comment by marc1706** [comment]
Last question: do you think applying the selected username with Enter makes more sense than using the Tab key? I somehow would want to use the tab key but not sure how others feel about it.

**Comment by mrgoldy** [comment]
We can also do both, if you want.

 But if you look at it in general, ‘enter’ is selecting and ‘tab’ is going to the next input. Not setting a value. 

As for that matter, if you want to implement ‘tab’ somewhere, it sounds more logical to use it to navigate through the search results. Acting similar to arrow down.

**Comment by VSEphpbb** [comment]
I Don't know about tab. My brain says up and down arrows to navigate, enter to select, and ESC to close

**Pull request merged**
