### PR TITLE
[ticket/7362] Add alt attribute on topic icons

### PR DESCRIPTION
**Pull request by Zoddo**
https://tracker.phpbb.com/browse/PHPBB3-7362

### CODE REVIEW

**Comment by Nicofuma** [comment]
While it is already an improvement, it looks 'too small'. With this patch we display the image name but it's often meaningless. Instead we could provide an optional description and if the description is not set, fallback to the image name.

By the way, what about the alt/title thing?

**Comment by Zoddo** [comment]
@Nicofuma : So, I think it would be better to do this in 3.2 in this case, no?

**Comment by Nicofuma** [comment]
We could do that indeed: keep this patch in 3.1 and do more in 3.2

**Comment by Zoddo** [comment]
@Nicofuma : Yes, I think we can merge this patch for 3.1 and open an another ticket to do more in 3.2

**Comment by Nicofuma** [comment]
please, create a ticket for 3.2 and send a PR if you want :)

**Comment by Nicofuma** [comment]
Could you also add the alt to the topic icon list in posting please?

**Pull request merged**
