### PR TITLE
[ticket/16550] Fix undefined variable url in PMs

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16550

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16550

### CODE REVIEW

**Comment by kasimi** [comment]
I think this needs to be fixed in 3.2.x as well: https://github.com/phpbb/phpbb/blob/release-3.2.10-RC2/phpBB/includes/functions_privmsgs.php#L2083

**Comment by 3D-I** [comment]
Yeah, just I don't know if that's the case. @marc1706 ?

**Comment by marc1706** [comment]
We can fix it for the final version without another RC. Please create a PR against prep-release-3.2.10, thanks

**Comment by 3D-I** [comment]
https://github.com/phpbb/phpbb/pull/6025

**Pull request merged**
