### PR TITLE
[ticket/14672] Add template event after topic title

### PR DESCRIPTION
**Pull request by rmcgirr83**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14672

PHPBB3-14672

### CODE REVIEW

**Comment by rmcgirr83** [comment]
!set Event

**Comment by rmcgirr83** [comment]
And travis has failed once again.  This is painful as hell.

@marc1706 @Nicofuma

**Comment by VSEphpbb** [comment]
It's failing because you didn't add your template event to the events docs.

**Comment by rmcgirr83** [comment]
Ah, :facepalm:

**Pull request merged**
