### PR TITLE
[ticket/13264] Do not force approved state if post visibility is known

### PR DESCRIPTION
**Pull request by marc1706**
Post visibility is used if it is set to a valid value.

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13264

### CODE REVIEW

**Comment by Lady-G** [comment]
Post visibility also affects $url construction. Discussed in [Re: PHPBB3-13264 - Editing an unapproved post as a moderator/admin approves it](https://area51.phpbb.com/phpBB/viewtopic.php?p=288501#p288501 "Re: PHPBB3-13264 - Editing an unapproved post as a moderator/admin approves it")

**Comment by Lady-G** [comment]
Post visibility also affects $url construction. Discussed in [Re: PHPBB3-13264 - Editing an unapproved post as a moderator/admin approves it](https://area51.phpbb.com/phpBB/viewtopic.php?p=288501#p288501 "Re: PHPBB3-13264 - Editing an unapproved post as a moderator/admin approves it")

**Comment by marc1706** [comment]
This has also been modified now.

**Comment by CHItA** [comment]
I don't think that this patch makes too much sense functionality-wise, i think it would make more sense what Zoddo suggested (and probably with that checkbox checked by default).

**Comment by marc1706** [comment]
I don't see a suggestion by Zoddo anywhere?

**Comment by CHItA** [comment]
My bad, Crizzo.

**Comment by Crizz0** [comment]
That was: don't approve the post with editing it and add checkbox in the editor, to be able to approve the post, if you want to. :)

**Comment by CHItA** [comment]
Yeah, you see you got it wrong as well. :)

**Comment by Crizz0** [comment]
I got it wrong? Why?

**Pull request merged**
