### PR TITLE
[ticket/16036] Add S_FORM_TOKEN_LOGIN to all login forms

### PR DESCRIPTION
**Pull request by rubencm**
PHPBB3-16036

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

I haven't added it to ucp_login_link.php because i don't know what is that file for

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16036

### CODE REVIEW

**Comment by 3D-I** [comment]
@rubencm ucp_login_link.php is for OAuth's account linkage.

**Comment by rubencm** [comment]
Is login broken there too?

**Comment by 3D-I** [comment]
Nope, I tried yesterday with this PR as it is now. But I will try to link a new account, I will report very soon.

**Comment by rubencm** [comment]
Thank you

**Comment by 3D-I** [comment]
Hold the line pls...

**Comment by 3D-I** [comment]
immagine

It's all right here.

BTW, you can only link an account in ucp, obviously if you are already logged in.

**Comment by 3D-I** [comment]
@rubencm seems there are issues still in posting.php..
tried to login while as anonymous I tried to post a new topic..

**Comment by 3D-I** [comment]
> 
> 
> @rubencm seems there are issues still in posting.php..
> tried to login with OAuth while as anonymous I tried to post a new topic..
> It doesn't happens with normal credentials though
> 
> **Edit**: it's a 400. Due to the URL (posting.php etc..) not being there in the API stored as a callback.
> 
> SO that's another issue, not related.

https://github.com/phpbb/phpbb/pull/5592

**Pull request merged**
