### PR TITLE
[ticket/14228] Vertical align of numbers in polls

### PR DESCRIPTION
**Pull request by Galixte**
https://tracker.phpbb.com/browse/PHPBB3-14228

### CODE REVIEW

**Comment by CHItA** [comment]
Could you please amend the commit message to include the ticket ID
```
[ticket/14228] Vertical align of numbers in polls

https://tracker.phpbb.com/browse/PHPBB3-14228

PHPBB3-14228
```

**Comment by Galixte** [comment]
It’s a failure, sorry.

**Comment by CHItA** [comment]
Nevermind, we can do that for you.

**Comment by Galixte** [comment]
New PR here: https://github.com/phpbb/phpbb/pull/3958.

**Pull request closed without merging**
