### PR TITLE
[ticket/15144] Attachment icon display should only occur

### PR DESCRIPTION
**Pull request by rmcgirr83**
if there are attachments in reports

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

https://tracker.phpbb.com/browse/PHPBB3-15144

PHPBB3-15144

### CODE REVIEW

**Comment by rmcgirr83** [comment]
This PR fails but not due to anything I did...I don't think.

**Comment by rubencm** [comment]
It fails because this hasn't been merged yet
https://github.com/phpbb/phpbb/pull/4751

**Comment by rmcgirr83** [comment]
Why would that commit matter?

**Comment by DavidIQ** [comment]
Not having it is causing tests to fail.

On Mar 23, 2017, at 11:36 AM, Rich McGirr <notifications@github.com<mailto:notifications@github.com>> wrote:


Why would that commit matter?

**Comment by rmcgirr83** [comment]
Okay I guess the devs will take care of that then.

**Comment by rmcgirr83** [comment]
Poke @DavidIQ  mind closing and reopening to restart the travis stuffs?

**Comment by rmcgirr83** [comment]
Thanks @Crizz0 :+1:

**Comment by Nicofuma** [comment]
The ATTACH_ICON_IMG variable may be used by alternate styles, you should keep it available and with the same semantics

**Comment by Nicofuma** [comment]
You need to restore the image generation too (only keep the template changes)

**Comment by rmcgirr83** [comment]
Done and meh travis :roll_eyes:

**Comment by Nicofuma** [comment]
You forgot to follow the guidelines for your latests commits :)

**Comment by rmcgirr83** [comment]
They passed though? Anything I need to do?

**Comment by Nicofuma** [comment]
Yes, you need to amend your commit messages to add the [ticket/15144]  title prefix and the PHPBB3-15144 suffix

**Comment by rmcgirr83** [comment]
Hmmm, I uhhh seem to have royally screwed this, very simple, one up.

**Comment by Nicofuma** [comment]
Your forgot your second commit :p

From here you have 2 solutions, both using rebase:
 - Squash your commits
 - Rebase and ammend the second commit message

For the first solution you need to use `git rebase -i 3.2.x` and then checked fixup for the last 2 commits
For the second solution you need to use  `git rebase -i 3.2.x` too and then checked edit for the second commit

**Comment by rmcgirr83** [comment]
I'll just start a new commit.  This one is a mess.

**Pull request closed without merging**
