### PR TITLE
[ticket/16074] Fix Twemoji URL for ZWJ sequences

### PR DESCRIPTION
**Pull request by JoshyPHP**
PHPBB3-16074

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16074

### CODE REVIEW

**Comment by JoshyPHP** [comment]
The regression test will make the 3.3.x branch fail until its s9e/text-formatter dependency is updated to the next release of the library.

**Comment by marc1706** [comment]
And the next release would then be 2.0.1?

**Comment by JoshyPHP** [comment]
Most probably, yes.

**Comment by marc1706** [comment]
@JoshyPHP does the new 2.0.1 release contain those mentioned changes for the 2.0 branch?

**Pull request merged**
