### PR TITLE
[ticket/14830] Fix FORM_INVALID error during some ACP setting operations

### PR DESCRIPTION
**Pull request by rxu**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Caused by #4452.

<a href="https://tracker.phpbb.com/browse/PHPBB3-14830">PHPBB3-14830</a>.

### CODE REVIEW

**Comment by Zenju** [comment]
The patch seems to fix the index creation, but there is a second regression compared to 3.1.9 (also FORM_INVALID) when switching the search backend via ACP from "phpBB Native Fulltext" to "MySQL Fulltext". I don't have much time to analyze what's going on, but using the 3.1.9 version of acp_search.php fixes both bugs for me.

**Comment by rxu** [comment]
That is because the confirm box (which is triggered if the search backend is going to be changed) doesn't have the form token key.

**Comment by marc1706** [comment]
Looks good apart from that.

**Comment by rxu** [comment]
@marc1706 Pulled from #4484.

**Pull request merged**
