### PR TITLE
[ticket/14764] Wrong link to database update script has been fixed

### PR DESCRIPTION
**Pull request by Crizz0**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14764

PHPBB3-14764

### CODE REVIEW

**Comment by marc1706** [comment]
Are the routes to the installer not available in the acp using the prod environment or why are you manually generating a link to it?

**Comment by Crizz0** [comment]
I did not try to use the routes there. I'll test it.

**Comment by Crizz0** [comment]
@Nicofuma told me, that i'm not able to use the routes in that file, because they are only available in the installer enviroment.

**Comment by marc1706** [comment]
Ok, then it's fine like that.

**Comment by marc1706** [comment]
This reads weirdly:
`Visit the <a href="%1$s" title="%1$s">update process</a> and read the notice <em>Update database only</em> and press <strong>Submit</strong>.`
I'd prefer `updater` instead of `update process`. Also, shouldn't user rather select `Update database only` instead of reading it?

**Comment by Crizz0** [comment]
But is it checked and the only choice. ;)

Am 4. September 2016 17:51:00 MESZ, schrieb Marc Alexander <notifications@github.com>:

**Comment by DavidIQ** [comment]
Also I think we're using "click" not "press" for button and link interaction.

On Sep 4, 2016, at 11:52 AM, Christian Schnegelberger <notifications@github.com<mailto:notifications@github.com>> wrote:

But is it checked and the only choice. ;)

Am 4. September 2016 17:51:00 MESZ, schrieb Marc Alexander <notifications@github.com<mailto:notifications@github.com>>:
>This reads weirdly:
>`Visit the <a href="%1$s" title="%1$s">update process</a> and read the
>notice <em>Update database only</em> and press
><strong>Submit</strong>.`
>I'd prefer `updater` instead of `update process`. Also, shouldn't user
>rather select `Update database only` instead of reading it?
>
>--
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpbb/phpbb/pull/4435#issuecomment-244610966

-

**Comment by Crizz0** [comment]
I'll change that. 😊

Am 4. September 2016 17:55:17 MESZ, schrieb "David Colón" <notifications@github.com>:
>Also I think we're using "click" not "press" for button and link
>interaction.
>
>On Sep 4, 2016, at 11:52 AM, Christian Schnegelberger

**Comment by marc1706** [comment]
It's still an option and not a notice. Maybe something like:
`Visit the <a href="%1$s" title="%1$s">update process</a>, ensure <em>Update database only</em> is selected and click <strong>Submit</strong>.`
There is no comma before the and as this is British English.

**Pull request merged**
