### PR TITLE
[ticket/15088] Avoid code repetitions in extension manager

### PR DESCRIPTION
**Pull request by javiexin**
There are multiple identical queries in the extension manager, that can 
be made into a separate function, reused everywhere it is needed. 
Smaller code, and easier to maintain (single change to fix all uses).

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-15088

### CODE REVIEW

**Comment by javiexin** [comment]
The Travis error is coming from the testing framework itself, but I don't see where.
The issue is that it might not be initializing correctly the $ext_manager->extensions array, and there is a discrepancy between that and the DB contents; that, or the DB is not updated/initialized correctly.
I have changed the way the check is done in the code, and it fails in a similar way (duplicate key in the DB when the check is done in the extensions array, and trying to merge a non-array object when checking the DB, so the error is really a discrepancy between DB and extensions array).
This is not happening in the fully working case (the actual forum software, not the testing framework).  Or at least I haven't been able to replicate the issue in a clean system.
So, if someone with better knowledge about the testing framework could check it, I would be really thankful.

**Comment by javiexin** [comment]
Found it.  The config object was initialized empty, and the phpbb version is required and checked in the extension manager load_extensions method, used to get data from the DB into the extensions array.

**Comment by javiexin** [comment]
Would it be possible to merge this, at least for 3.2.1 (ideally for 3.1.11 as well)?
I am working on a couple of additions (PRs) that are based on/use this one (for 3.2/master), so it would be cleaner than this is merged before.
Thanks.

**Comment by javiexin** [comment]
Any chance this will make it to 3.1.11 and 3.2.1?

**Comment by marc1706** [comment]
We're currently looking at a 3.2.2 rather close after 3.2.1 in which we'd incorporate these changes. We'd like to review this more extensively and not fiddle too much with the 3.1 system before reaching EOM.

**Comment by javiexin** [comment]
Fair enough, thanks a lot

**Comment by marc1706** [comment]
I think it makes more sense to have refactoring in 3.3 instead of 3.2. Therefore changing the target

**Comment by rubencm** [comment]
Close in favour of #5557

**Pull request closed without merging**
