### PR TITLE
[ticket/13680] Updated quote notifications

### PR DESCRIPTION
**Pull request by s9e**
Added get_quote_authors() to text_formatter.utils service to retrieve the names used in first-level quotes.

https://tracker.phpbb.com/browse/PHPBB3-13680

### CODE REVIEW

**Comment by s9e** [comment]
I feel that the name get_quote_authors() is slightly misleading because it only returns the names used in the first level of quotes. I don't know if there's a better name for it though.

**Comment by Elsensee** [comment]
> Fatal error: Call to a member function get_quote_authors() on a non-object in /home/travis/build/phpbb/phpbb/phpBB/phpbb/notification/type/quote.php on line 78

I can't think of a better name too. Maybe `get_first_quote_authors()` but I'm really not that good at naming stuff.. ^^

**Comment by Nicofuma** [comment]
utils is static, I'd prefer to inject it as a service

About the name... I can't imagine a better name

**Comment by s9e** [comment]
@Nicofuma It's a service, available as `text_formatter.utils` which is itself an alias to `text_formatter.s9e.utils`. The service was created as part of the s9e\TextFormatter PR, that's why it doesn't appear in the diff.

**Comment by Nicofuma** [comment]
I was duped by the tests indeed

**Comment by nickvergessen** [comment]
Would be nice if we can fix that on 3.1 aswell, do you have any idea?
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/phpbb/notification/type/quote.php#L38
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/phpbb/notification/type/quote.php#L80-L86

**Comment by s9e** [comment]
I mentionned a possible algorithm in the A51 topic, but I haven't given it much thought.

> I think the way you'll have to fix it in 3.1 is you'll have to iterate over every quote tag with a regexp like `(\[/?quote(?:=&quot;.*?&quot;):\w+\])` and maintain a counter with the number of quote tags currently open. And of course, only notify the authors of the outermost quotes.

**Comment by Nicofuma** [comment]
@nickvergessen what do you think about that? merge it now in 3.2 or wait for a patch against 3.1 and merge both together?

**Comment by s9e** [comment]
Merge this one. 3.1 would require a completely different patch.

**Comment by nickvergessen** [comment]
> Merge this one. 3.1 would require a completely different patch.

this

**Comment by Nicofuma** [comment]
https://tracker.phpbb.com/browse/PHPBB3-13855 for 3.1.x

**Pull request merged**
