### PR TITLE
[ticket/16799] Fix OAuth external account linking and login - PHP 8

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16799

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16799

### CODE REVIEW

**Comment by 3D-I** [comment]
Fixing the phpBB code is what this PR is devoted to.
There is a secondary issue though, due to the vendor code itself.

More here:
https://tracker.phpbb.com/browse/PHPBB3-16799?focusedCommentId=64401&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-64401

**Comment by rxu** [comment]
@3D-I Actually I was preparing PR with additional functional test, but thanks, I guess I could add that later.

**Comment by rxu** [comment]
Specifically this commit https://github.com/rxu/phpbb3/commit/b46e8e1c0bfcce863cee9f31d6fb332fda1b3b8e
I can send PR with it or alternatively you could pull it into your current PR if wishing :)

**Comment by 3D-I** [comment]
> 
> 
> Specifically this commit [rxu@7b5ad8b](https://github.com/rxu/phpbb3/commit/7b5ad8bb74f66721d9c0742794f002272aec5b4d)
> I can send PR with it or alternatively you could pull it into your current PR if wishing :)

You can send your PR. I am therefore closing this one.

**Pull request closed without merging**
