### PR TITLE
[ticket/14716] Update dependencies to latest versions

### PR DESCRIPTION
**Pull request by marc1706**
Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-14716

This addresses some issues with symfony that resulted in
issues when open_basedir restrictions were enabled, as well
as issues with JPEG images in fast-image-size.
The phpBB class extending the twig lexer also had to be
modified to ensure compatibility after BC was broken by
the PR https://github.com/twigphp/Twig/pull/2182 for twig
1.27.

PHPBB3-14716

### CODE REVIEW

**Comment by marc1706** [comment]
Reported twig BC break as a separate issue: https://github.com/twigphp/Twig/issues/2218

**Comment by blitze** [comment]
The update to the dependencies appears to have introduced some path issues with INCLUDECSS and INCLUDEJS when the page is accessed from an extension controller. For example, the official Pages extension adds css like so: . When I go to /phpBB/app.php/page/foo it is trying to include the css as /phpBB/**app.php/page/**ext/phpbb/pages/styles/prosilver/theme/pages_controller.css instead of /phpBB/ext/phpbb/pages/styles/prosilver/theme/pages_controller.css

Without  a full knowledge of how this all works, it appears that the fix is to precede the generated relative path of \phpbb\template\asset::set_path on line 188 with a leading './' like so: $this->components['path'] = './' . $path. This fixed the problem for me.

**Comment by VSEphpbb** [comment]
@blitze I'm not able to reproduce that. However, Pages is not currently compatible with phpBB 3.2. Also `<!-- INCLUDECSS @phpbb_pages/../theme/pages_controller.css -->` is old and should instead try `<!-- INCLUDECSS @phpbb_pages/pages_controller.css -->`

**Comment by VSEphpbb** [comment]
Oh wait, I am seeing this, with all INCLUDECSS, even just go to the FAQ page to see it happen.

**Comment by marc1706** [comment]
Could either of you create a new ticket in the tracker (https://tracker.phpbb.com)? Then we can properly fix this before rolling out RC2.

**Comment by marc1706** [comment]
Might actually be caused by the prior update to twig as that introduced relative path issues:
https://github.com/phpbb/phpbb/commit/7a5fbd0257d7b15b8230fa6c60581cc197cb1a47

**Comment by marc1706** [comment]
We're reverting back to twig 1.26.* due to issues introduced in 1.27:
https://github.com/phpbb/phpbb/pull/4516

**Pull request merged**
