### PR TITLE
[Ticket/14069] Incorrect sql_fetchfield call in style_update_p1 migration

### PR DESCRIPTION
**Pull request by marcovo**
Corrected the sql_fetch_field() call in style_update_p1 migration

PHPBB3-14069

### CODE REVIEW

**Comment by marcovo** [comment]
I don't know whether the commit 'Merge pull request #1 from phpbb/3.1.x' is a problem... it was just to synchronise my fork with the phpBB repository... Is there a better way to do that?

**Comment by rxu** [comment]
Good catch.

**Comment by Elsensee** [comment]
Rebasing.

**Comment by marcovo** [comment]
Ok;
1. The Travis check failed, it says:
Inspecting commit message of commit 3988b42008fe67892c2292dffbefe9d80b67cc1f
Unexpected EOF encountered 
Aborting commit.

What is wrong with the commit message? Did I overlook something?

2. How do I rebase? I can find a command I can run in the terminal (git rebase --interactive phpbb:3.1.x) but it doesn't work.. Shouldn't I be able to do this on the github website?

**Comment by marcovo** [comment]
Found how to do rebasing here:
http://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository

I'll try again :)

**Comment by VSEphpbb** [comment]
The commit message is missing PHPBB3-14069

**Comment by marcovo** [comment]
Yeah I saw it, the new pull request is here:
https://github.com/phpbb/phpbb/pull/3811

Thanks for noting it though :)

**Pull request closed without merging**
