### PR TITLE
[ticket/15830] Move event to a more useful place

### PR DESCRIPTION
**Pull request by Elsensee**
Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket:
https://tracker.phpbb.com/browse/PHPBB3-15830

### CODE REVIEW

**Comment by marc1706** [comment]
I think we should split this into two events. One before the parsing to be able to modify the template, and one after parsing to modify the actual output after parsing.

**Comment by Denitz** [comment]
@Elsensee Can you add an extra event in your brunch?

**Comment by marc1706** [comment]
@Elsensee any update on this?

**Comment by Elsensee** [comment]
Will do on Monday at latest.

**Comment by marc1706** [comment]
@Elsensee you need to rebase, sorry ;)

**Comment by Elsensee** [comment]
Rebased. I have removed the template parameter that was added just recently, because... well.. it's useless now, I guess?

**Comment by senky** [comment]
@Elsensee no it is not. I added it on purpose so please keep it. I use it to assign additional variables.

**Comment by Elsensee** [comment]
@senky The template variable is still there, just in another, more useful event or do you need it in that specific event?

**Comment by senky** [comment]
Oh I see. It's OK this way.

**Comment by Elsensee** [comment]
Great! :)

**Pull request merged**
