### PR TITLE
[ticket/13826] Add test listener to cleanup variables

### PR DESCRIPTION
**Pull request by Nicofuma**
PHPBB3-13826

### CODE REVIEW

**Comment by nickvergessen** [comment]
What is the use of this?

**Comment by Nicofuma** [comment]
I sent the PR too early... I'm still doing some tests.
Basically it should speed up the tests

**Comment by marc1706** [comment]
Status?

**Comment by Nicofuma** [comment]
still WIP, didn't have time to look at it

**Comment by CHItA** [comment]
I guess we should just optimize tests in the future if you don't work on it then let's just close it.

**Pull request closed without merging**
