### PR TITLE
[ticket/13496] Change set_config_count() calls with $config->increment()

### PR DESCRIPTION
**Pull request by MGaetan89**
https://tracker.phpbb.com/browse/PHPBB3-13496

PHPBB3-13496

### CODE REVIEW

**Comment by MGaetan89** [comment]
!set WIP

**Comment by Nicofuma** [comment]
status?

**Comment by MGaetan89** [comment]
I haven't found the cause of the failling test yet.

**Comment by Nicofuma** [comment]
$config may have not been set before and so can be null here, you should replace this line (https://github.com/phpbb/phpbb/blob/6c5541e0e5ad7cd0324a29f45c824a26f3f91464/tests/content_visibility/delete_post_test.php#L295) by `$config = new \phpbb\config\config(array('search_type' => 'phpbb_mock_search'));` and search this kind of construction in all the tests

**Comment by MGaetan89** [comment]
Thanks for your help. Tests are running with your fix.
I look for a similar use elsewhere, and did not find anything as well.

**Comment by MGaetan89** [comment]
Yay, tests are passing now :-)

**Comment by MGaetan89** [comment]
!unset WIP

**Comment by MGaetan89** [comment]
!set WIP

**Comment by MGaetan89** [comment]
@bantu rebased and tests are passing.

**Comment by bantu** [comment]
@MGaetan89 Errrr. Yes, that is weird. Only use $config. Use multiple lines for the combined array.

**Comment by MGaetan89** [comment]
!unset WIP

**Comment by MGaetan89** [comment]
Done. Tests are running.

**Comment by MGaetan89** [comment]
Ready to be merged now.

**Pull request merged**
