### PR TITLE
Ticket phpbb3 15109

### PR DESCRIPTION
**Pull request by YasaraPeiris**
Added a dropdown to place all smilies Sain full screen editor in area51, community & other places where a user can post a reply to save some screen space..

Could not automatically create an issue. Please create one on https://tracker.phpbb.com/ and replace this text with a link to it.

### CODE REVIEW

**Comment by hanakin** [comment]
this needs to be applied to master not 3.2.x it looks like you based it correctly just selected the wrong option when you created your pr

**Comment by YasaraPeiris** [comment]
Hello Micheal,

Thanks for your quick response. Would it be okay if I commit this to master
now? Or else what do I need to do ?

Yasara Peiris,
University of Moratuwa,
Mobile : +94 710 197 418 <+94%2071%20019%207418>
Email   :  yasarapeiris.13@cse.mrt.ac.lk

**Comment by hanakin** [comment]
1. I would first do a git reset as you need to fix your commit msgs since they do not follow the proper format outlined in the link i provided.
2. Then stash everything and checkout create a new branch from master
3. Apply the stash from before to the new branch
4. create the proper commit msg
5. force push to origin
6. fix the pr title and msg to match the linked format.

**Comment by YasaraPeiris** [comment]
Thank you very much for your support. I'll work on that

**Comment by hanakin** [comment]
not sure what you mean git reset is something you need to do on your local branch... Are you familiar with git? If not I would suggest asking for help with this on ICQ channel #phpbb-dev, someone on there should be able to assist.

**Comment by hanakin** [comment]
thats not going to fix anything...never perform anything that requires a new commit except for changes to the code that you make ie reverts/merges these should never require a commit, if it does then there is a better way to handle it.

**Comment by YasaraPeiris** [comment]
I have created new branch and made a new pull request. But not sure whether
it is accepted or not. (ticket/PHPBB-- 15109). It would be really grateful
if you could let me know whether there is any issue with what I have done.
Sorry for bothering you sir .

Thank you.




*Yasara Peiris,University of Moratuwa,mobile : +94 710 197 418email   :
 yasarapeiris.13@cse.mrt.ac.lk <yasarapeiris.13@cse.mrt.ac.lk>*

**Comment by hanakin** [comment]
Pls close this as its a duplicate!

**Pull request closed without merging**
