### PR TITLE
[ticket/15329] Parse drafts before saving them (and decode)

### PR DESCRIPTION
**Pull request by Elsensee**
Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-15329

### CODE REVIEW

**Comment by Elsensee** [comment]
@senky As you can see, I'm messing a bit around with the PM system. I don't know if drafts will still be a thing in your #5351 - just a heads up.

**Comment by senky** [comment]
@Elsensee that's OK, I didn't implement drafts yet (nor do I want but apparently they are used...)

**Comment by hanakin** [comment]
We probably should keep it

**Comment by marc1706** [comment]
We should keep post drafts, pm drafts shouldn't be a thing IMHO

**Pull request merged**
