### PR TITLE
[ticket/14295]Add approval icon

### PR DESCRIPTION
**Pull request by hanakin**
PHPBB3-14295

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14295

### CODE REVIEW

**Comment by hanakin** [comment]
Ready for review @prototech

**Comment by hanakin** [comment]
!set Styles

**Comment by hanakin** [comment]
@cyberalien @marc1706

**Comment by marc1706** [comment]
The padding on the left side is IMHO too big and should also be handled by this PR.
padding_too_big

By the way, are you preparing a PR for the report icon? There currently isn't any:
no_icon_report

**Comment by hanakin** [comment]
finally managed to fix my install so ill have another look at this and might aswell just do both y I am at it. These were somewhat dependent on https://tracker.phpbb.com/browse/PHPBB3-14296 & https://github.com/phpbb/phpbb/pull/3938 I guess as depending on if the icons need to completely change based on weather we wish to merge the paging modifications

**Comment by hanakin** [comment]
@marc1706 This should be good now fixed the padding and added the report icons aswell. If the icons end up changing from https://tracker.phpbb.com/browse/PHPBB3-14296 ill update them in that pr.

**Comment by hanakin** [comment]
oops forgot to push repot icon should be good now

**Pull request merged**
