### PR TITLE
[ticket/12505] Remove outdated media handling in attachments

### PR DESCRIPTION
**Pull request by n-aleha**
Remove code for handling media in RealPlayer, QuickTime, and Windows Media
Player.

[PHPBB3-12505](https://tracker.phpbb.com/browse/PHPBB3-12505)

### CODE REVIEW

**Comment by Nicofuma** [comment]
status?

**Comment by n-aleha** [comment]
Haven't touched this in a while.

**Comment by marc1706** [comment]
Yes, rebasing this into the current master branch would certainly a good first step.

**Comment by n-aleha** [comment]
Rebased to master.

**Comment by n-aleha** [comment]
Replace by https://github.com/phpbb/phpbb/pull/3478

**Pull request closed without merging**
