### PR TITLE
[ticket/16435] Restore calling page_footer() events in controllers

### PR DESCRIPTION
**Pull request by rxu**
A variant of restoring BC broken in #5831.

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

<a href="https://tracker.phpbb.com/browse/PHPBB3-16435">PHPBB3-16435</a>.

### CODE REVIEW

**Comment by marc1706** [comment]
Hm, I'm not really a fan of reverting back to the page_footer() function as this will be removed at some point. What do you think about adding a BC layer to the controller helper render method instead?
```diff
diff --git a/phpBB/phpbb/controller/helper.php b/phpBB/phpbb/controller/helper.php
index 1b07ab9f7d..5033e227c6 100644
--- a/phpBB/phpbb/controller/helper.php
+++ b/phpBB/phpbb/controller/helper.php
@@ -143,11 +143,58 @@ class helper
 			'body'	=> $template_file,
 		));
 
-		$this->display_footer();
+		$run_cron = true;
+		$page_footer_override = false;
+
+		/**
+		 * Execute code and/or overwrite page_footer()
+		 *
+		 * @event core.page_footer
+		 * @var	bool	run_cron			Shall we run cron tasks
+		 * @var	bool	page_footer_override	Shall we skip displaying the page footer
+		 * @since 3.1.0-a1
+		 * @changed 3.3.1-RC1 Added to controller helper render() method for backwards compatibility
+		 */
+		$vars = array('run_cron', 'page_footer_override');
+		extract($this->dispatcher->trigger_event('core.page_footer', compact($vars)));
+
+		if (!$page_footer_override)
+		{
+			$this->display_footer($run_cron);
+		}
 
 		$headers = !empty($this->user->data['is_bot']) ? array('X-PHPBB-IS-BOT' => 'yes') : array();
 
-		return new Response($this->template->assign_display('body'), $status_code, $headers);
+		$display_template = false;
+		$exit_handler = true; // not used
+
+		/**
+		 * Execute code and/or modify output before displaying the template.
+		 *
+		 * @event core.page_footer_after
+		 * @var	bool display_template	Whether or not to display the template
+		 * @var	bool exit_handler		Whether or not to run the exit_handler() (no effect on controller pages)
+		 *
+		 * @since 3.1.0-RC5
+		 * @changed 3.3.1-RC1 Added to controller helper render() method for backwards compatibility
+		 */
+		$vars = array('display_template', 'exit_handler');
+		extract($this->dispatcher->trigger_event('core.page_footer_after', compact($vars)));
+
+		$response = new Response($display_template ? $this->template->assign_display('body') : '', $status_code, $headers);
+
+		/**
+		 * Modify response before output
+		 *
+		 * @event core.controller_helper_render_response
+		 * @var	Response response	Symfony response object
+		 *
+		 * @since 3.3.1-RC1
+		 */
+		$vars = ['response'];
+		extract($this->dispatcher->trigger_event('core.controller_helper_render_response', compact($vars)));
+
+		return $response;
 	}
 
 	/**

```

**Comment by rxu** [comment]
Well, so duplicating core events basically. Looks hackish a bit to be honest, but if we have no choice...
Also there's an alternative which probably can seem too much, but we could move those events and just replace `\includes\functions.php\page_footer()` with `\phpbb\controller\helper\display_footer()` in all front pages. As an example, for `viewtopic.php`:

```diff
 phpBB/viewtopic.php | 20 +++++++++++++-------
 1 file changed, 13 insertions(+), 7 deletions(-)

diff --git a/phpBB/viewtopic.php b/phpBB/viewtopic.php
index 3d9de55a84..f7f0796434 100644
--- a/phpBB/viewtopic.php
+++ b/phpBB/viewtopic.php
@@ -2416,12 +2416,18 @@ $page_title = $topic_data['topic_title'] . ($start ? ' - ' . sprintf($user->lang
 $vars = array('page_title', 'topic_data', 'forum_id', 'start', 'post_list');
 extract($phpbb_dispatcher->trigger_event('core.viewtopic_modify_page_title', compact($vars)));
 
-// Output the page
-page_header($page_title, true, $forum_id);
-
-$template->set_filenames(array(
-	'body' => ($view == 'print') ? 'viewtopic_print.html' : 'viewtopic_body.html')
-);
+$template_file = ($view == 'print') ? 'viewtopic_print.html' : 'viewtopic_body.html';
 make_jumpbox(append_sid("{$phpbb_root_path}viewforum.$phpEx"), $forum_id);
 
-page_footer();
+/* @var $http_kernel \Symfony\Component\HttpKernel\HttpKernel */
+$http_kernel = $phpbb_container->get('http_kernel');
+
+/** @var \phpbb\controller\helper $controller_helper */
+$controller_helper = $phpbb_container->get('controller.helper');
+
+/* @var $symfony_request \phpbb\symfony_request */
+$symfony_request = $phpbb_container->get('symfony_request');
+
+$response =  $controller_helper->render($template_file, $page_title, 200, true, $forum_id, 'forum', true);
+$response->send();
+$http_kernel->terminate($symfony_request, $response);
```

**Comment by 3D-I** [comment]
I am for the first commit https://github.com/phpbb/phpbb/pull/5967/commits/846fa0c91614ee91dd8b5107721c1609f243623b
Alternatively for the Marc's proposal.

**Comment by marc1706** [comment]
I thought about this for a bit and I agree that my solution is a bit hackish but IMHO it makes sense with regards to where we'll move in the next feature release of phpBB. We'll move to controllers and hence page_footer() and page_header() will become pretty much obsolete in their current form. Hence the events would have to be moved over anyhow.
Also, replacing the calls to page_footer() in all files now would cause issues for people that still use custom PHP front-end files.

**Comment by 3D-I** [comment]
> Also, replacing the calls to page_footer() in all files now would cause issues for people that still use custom PHP front-end files.

Agreed.

**Comment by rxu** [comment]
@marc1706 okay. Shall I implement it in this PR in according to your diff? :)

**Comment by marc1706** [comment]
Yes, that would be great. Thanks.

**Comment by rxu** [comment]
Should be ready now.

**Pull request merged**
