### PR TITLE
[ticket/13175] Check if account is already linked when using OAuth

### PR DESCRIPTION
**Pull request by rubencm**
PHPBB3-13175

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-13175

### CODE REVIEW

**Comment by 3D-I** [comment]
Wouldn't it be better to allow multiusers with some option?
We did it in an Oauth2 extension already.

**Comment by rubencm** [comment]
Well, I was seeing how oauth works a little in depth, and I just realized this error.

About the extension, which extension is, to see how it is implemented? If is linkedaccounts, that looks to me like a completely new (but related) feature.
Create a dialog asking with which account login is not a bad idea

**Comment by marc1706** [comment]
Yes, I think the initial implementation did not expect users to link more than one account. It's probably best to create new ticket for the possibility to have more than one account and implement that later.

**Comment by 3D-I** [comment]
@rubencm Is an ext of us, not public. And yes I do agree with @marc1706 here.

**Pull request merged**
