### PR TITLE
[ticket/13982] Add events around ranks

### PR DESCRIPTION
**Pull request by javiexin**
Add events to present information around ranks in the memberlist,
user profile, viewtopic profile and private message profile.

PHPBB3-13982

### CODE REVIEW

**Comment by CHItA** [comment]
Rebase please

**Comment by javiexin** [comment]
What do I need to do?  I do not understand your request.

**Comment by CHItA** [comment]
Rebase your branch to the head of 3.1.x (as your PR contains merge conflicts), though if you don't know how to do that, we can do it for you on merging.

**Comment by javiexin** [comment]
I thought I was on the 3.1.x head.  How do I make sure I am?

**Comment by CHItA** [comment]
This can occur when another PR is merged into the branch you've sent your PR against, and the two PRs have conflicts. You can see it if you update your local 3.1.x branch. However, as I said, don't worry about it.

**Comment by javiexin** [comment]
Thanks.  I think the merge conflict comes from events.md, and I know for sure there will be more conflicts there (see https://github.com/phpbb/phpbb/pull/3742)

**Pull request merged**
