### PR TITLE
Master

### PR DESCRIPTION
**Pull request by melvingb**
https://tracker.phpbb.com/browse/PHPBB3-14369

### CODE REVIEW

**Comment by DavidIQ** [comment]
This is wrong.

**Comment by melvingb** [comment]
Why?

**Comment by DavidIQ** [comment]
You sent a pull request for the wrong thing.  The other one you sent is a little more on track, but still wrong.

**Comment by melvingb** [comment]
But the pull request is wrong or the style fix?

**Comment by DavidIQ** [comment]
This pull request is very wrong and you can tell right away from reading the action you're trying to perform right at the top of this very page.  Whatever it is you were trying to do here should not have included 2,463 commits.

**Comment by melvingb** [comment]
Ufff thanks, I thought that was a mistake of mine :)

**Pull request closed without merging**
