### PR TITLE
[ticket/17385] Fix for CDB version checks with missing SSL flag

### PR DESCRIPTION
**Pull request by LukeWCS**
Checklist:

- [ ] Correct branch: master for new features; 3.3.x for fixes
- [ ] Tests pass
- [ ] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [ ] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB-17385

### CODE REVIEW

**Comment by rxu** [comment]
Personally, I'd make the fix more generic and unlink it from phpbb.com (that looks hackish a bit tbh). F.e. if `ssl` is not set, then try with use_ssl = true, if it returns error then try with use_ssl = false, if it returns error too then report it to admin (regardless of the host).

**Comment by LukeWCS** [comment]
@rxu 
> I'd make the fix more generic and unlink it from phpbb.com (that looks hackish a bit tbh)
In general, I agree with you, it is not perfect. ;-) But since a version check of a CDB Ext only works if SSL is used anyway, this is less tragic. Especially because the fix only targets phpBB.com and does not affect other version servers at all.

Your proposed method has one disadvantage: we already have phpBB installations with an extremely large number of extensions and timeout problems. See this topic in the EMP support area:

[MySQL server has gone away [2006]](https://www.phpbb.com/customise/db/extension/extension_manager_plus/support/topic/247519)

If we now work with HTTPS first and then with HTTP again if SSL fails, the timeout problem gets even worse because phpBB unfortunately does not implement the versions in chunks, but all at once.

**Comment by gn36** [comment]
In my eyes, the whole problem arises because the version checker doesn't follow 301 Redirects. phpBB.com redirects correctly from http:// addresses to https. But instead of following this like every web browser, phpBB installations simply give up like on a 404 error.
In my eyes the best solution would be to follow that redirect. This would also allow extension writers to restructure their servers in the future without loosing connection to all older extension installations, as long as they setup correct redirects.
If you want to ensure that we don't get into endless redirect loops, you could limit the number of redirects followed and check if you check the same URL multiple times. For sure, this is more complicated than the suggested solution, but in my eyes, it would be more correct than what we have right now.
Yes, the simpler solution would be to check with SSL if non-SSL fails, but that might not be where the new file is at all moved to.

**Comment by rxu** [comment]
> So solution could be to backport the guzzle update from master

Indeed, on master there's no such an issue. Good catch, backporting it looks like a good idea.

**Comment by marc1706** [comment]
I've created a PR that backports these changes to 3.3.x:
https://github.com/phpbb/phpbb/pull/6715

**Comment by LukeWCS** [comment]
I think this PR can be closed, as it is obsolete.

**Comment by marc1706** [comment]
Closing as such. See #6715.

**Pull request closed without merging**
