### PR TITLE
[ticket/16834] Fix tag svg invalid in Entity - PHP8

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16834

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16834

### CODE REVIEW

**Comment by 3D-I** [comment]
image

---

image

**Comment by hanakin** [comment]
This is not a fix for the underlying issue. G tag needs to be supported in the dom. We are using the icon function here for a reason.

**Comment by 3D-I** [comment]
> 
> 
> This is not a fix for the underlying issue. G tag needs to be supported in the dom. We are using the icon function here for a reason.

I haven't found a valid alternative, I will be more than glad to read if somebody have one.
What about the reason for using the icon function here?

**Comment by hanakin** [comment]
This was our test case for more complex icons that required other tags. Not sure why you are getting this error mrgoldy or @phpbb/development-team wrote the icon stuff perhaps he could shed some light onto the specific error? I'm not really familiar with the backend enough to figure that out

**Comment by 3D-I** [comment]
`mrgoldy` is the one who wrote this comment in fact.

`DOMDocument does not like HTML5 and SVGs` 

at those times `PHP 8` was not out to test it, he suppressed the error using the at sign (@) that's used as error control operator in PHP, see: https://www.php.net/manual/en/language.operators.errorcontrol.php

There is not a viable solution for DOM in this case; https://github.com/phpbb/phpbb/blob/f836605ab8281adc17d5a2508f40c6072490c2c8/phpBB/phpbb/template/twig/extension/icon.php#L198-L203 - see line 202.

**Comment by rxu** [comment]
Will this hack help?
```php
// Hide html5/svg errors
libxml_use_internal_errors(true);
$doc->loadHTML($code, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
```

**Comment by 3D-I** [comment]
> 
> 
> Will this hack help?
> 


It works apparently 👍🏼  Where did you find it?

If it's preferable I can push that change in its place.

**Comment by rxu** [comment]
> Where did you find it?

Here https://www.php.net/manual/ru/domdocument.loadhtml.php#125526

**Review by hanakin — APPROVED** [review]
Pending a backend dev review this seems good to me

**Review by marc1706 — APPROVED** [review]

**Pull request merged**
