### PR TITLE
[ticket/17097] Fix PHP 8.2 deprecation warnings

### PR DESCRIPTION
**Pull request by m-ober**
Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/master/coding-guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-17097

### CODE REVIEW

**Comment by m-ober** [comment]
Maybe it would be better to add `role_cache` as property to the `auth` class, but I don't know if this was left out intentional.

In case of `phpbb_root_path` it looks like it was simply forgotten.

**Comment by m-ober** [comment]
We could also replace the `ReturnTypeWillChange` attributes with the actual return type, *except* for `offsetGet`, which has a `mixed` return type that is only supported by PHP >=8.0.

**Comment by m-ober** [comment]
As this question came up in chat, Attributes are backwards compatible as long as they are on a separate line. Then, they are just parsed as comments by PHP <8.0.

**Comment by marc1706** [comment]
> Maybe it would be better to add `role_cache` as property to the `auth` class, but I don't know if this was left out intentional.
> 
> In case of `phpbb_root_path` it looks like it was simply forgotten.

It actually does not need to be a class property as it's never used as such. In master, it was changed to no longer use this:
https://github.com/phpbb/phpbb/commit/774c609c4a33b3ff4d7673e23feab266689e96cb#diff-d3edffaad6045eb7577d57cbb613c8903eb4d239c9f41aeaabfd1218ebdc596c

**Review by marc1706 — APPROVED** [review]

**Comment by m-ober** [comment]
@marc1706 Thanks for the review! I have cherry-picked the changes from master (for the changes regarding the `$role_cache` variable only). Also, I have added the `#[\ReturnTypeWillChange]` attribute to the same methods in the `config` class. I never got a deprecation notice from this class, but as it is also implementing the `ArrayAccess` interface, it could trigger the same notices.

**Comment by m-ober** [comment]
Any idea why the "Check commit message" step is failing? The error message is not very helpful.

**Comment by rubencm** [comment]
It should be

```
[ticket/17097] Fix PHP 8.2 deprecation warnings]

PHPBB3-17097
```

**Comment by m-ober** [comment]
@rubencm Thanks, fixed.

**Review by marc1706 — APPROVED** [review]

**Comment by marc1706** [comment]
Thanks for your contribution 👍

**Pull request merged**
