### PR TITLE
[ticket/14068] Add template events before and after poll panel 

### PR DESCRIPTION
**Pull request by javiexin**
In viewtopic.

PHPBB3-14068

### CODE REVIEW

**Comment by Nicofuma** [comment]
it's to display poll related information or just for the location?

**Comment by javiexin** [comment]
Both. To fully override poll panel, by setting S_HAS_POLL to false (for that we would only need one event), but also to include a panel either before or after the poll. For example, an ad that goes before the first post would be between poll and post, might not be desirable.

**Comment by Nicofuma** [comment]
ok

**Comment by marc1706** [comment]
Replaced by #3852

**Pull request closed without merging**
