### PR TITLE
[ticket/16640] Show MCP link in menu

### PR DESCRIPTION
**Pull request by otseng**
PHPBB3-16640

Fix MCP link in menubar when viewing a post report

Checklist:

- [x] Correct branch: master for new features; 3.3.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16640

### CODE REVIEW

**Comment by otseng** [comment]
Screen Shot 2020-11-24 at 12 03 48 AM

**Comment by rxu** [comment]
@otseng do you have an idea why it doesn't work as is? Just out of interest, didn't dig into the current core code yet.

**Comment by otseng** [comment]
> @otseng do you have an idea why it doesn't work as is? Just out of interest, didn't dig into the current core code yet.

In mcp_reports.php, it's calling trigger_error() so it never goes past $module->load_active() in mcp.php

**Comment by marc1706** [comment]
Great job looking into this and thanks for your PR. 👍

**Pull request merged**
