### PR TITLE
[ticket/16436] Display correct "no topics" message when filtering by time

### PR DESCRIPTION
**Pull request by mrgoldy**
PHPBB3-16436

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-16436

### CODE REVIEW

**Comment by hanakin** [comment]
I am not sure we want to put logic in the templates like this?

**Comment by mrgoldy** [comment]
I am still not quite sure what needs to be altered here.. 
The language variable should be determine template side, not in php.
So do you want another template variable indicating that the 'days filter' is active?

**Comment by marc1706** [comment]
I think this solution is fine.

**Comment by marc1706** [comment]
Merged into 3.3.x

**Pull request closed without merging**
