### PR TITLE
[ticket/15241] Add ACP template event acp_profile_contact_last

### PR DESCRIPTION
**Pull request by javiexin**
Event to place code in Profile Field configuration screen, as additional information for 
Contact Profile Fields.

PHPBB-15241

Checklist:

- [x] Correct branch: master for new features; 3.2.x, 3.1.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master / 3.2.x](https://area51.phpbb.com/docs/master/coding-guidelines.html), [3.1.x](https://area51.phpbb.com/docs/31x/coding-guidelines.html)
- [x] Commit follows commit message [format](https://wiki.phpbb.com/Git#Commit_Messages)

Tracker ticket:

https://tracker.phpbb.com/browse/PHPBB3-15241

### CODE REVIEW

**Comment by javiexin** [comment]
!set Event

**Comment by javiexin** [comment]
The Travis error is on the commit message:

> Inspecting commit message of commit f030780505fae3fb662bc870072ba3b25bf369f9
> Unexpected EOF encountered 

However, the commit message is fine:

> [ticket/15241] Add ACP template event acp_profile_contact_last
> 
> PHPBB-15241

**Comment by DavidIQ** [comment]
According to [this](https://area51.phpbb.com/docs/dev/31x/development/git.html#commit-messages) the ticket number and description should be separated by a single empty line. You don't have a description so the error is caused by either not having a description or not having the required empty line before the ticket number.

**Comment by javiexin** [comment]
Thanks a lot David.  The only thing I can think of is that the empty line (that is there) is not empty but has an space or tab...  I will amend the commit anyhow.

**Pull request merged**
