### PR TITLE
[ticket/15630] ACP_COOKIE_SETTINGS_EXPLAIN change <b> to <strong>

### PR DESCRIPTION
**Pull request by Crizz0**
PHPBB3-15630

Checklist:

- [x] Correct branch: master for new features; 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.2.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15630

### CODE REVIEW

**Comment by Crizz0** [comment]
This travis fail is not related to my PR, correct?

**Comment by hanakin** [comment]
@Crizz0 no it’s not

**Comment by marc1706** [comment]
Can you also add this change to your PR (e.g. cherry-pick commit)? https://github.com/phpbb/phpbb/pull/5120

**Comment by Crizz0** [comment]
@marc1706 There you go! :)

**Pull request merged**
