### PR TITLE
[ticket/15591] Add jabber permission check

### PR DESCRIPTION
**Pull request by ansavin**
We want to make jabber address unvisible for those users who are not allowed
to send instant (jabber) messages

PHPBB3-15591

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

Tracker ticket (set the ticket ID to **your ticket ID**):

https://tracker.phpbb.com/browse/PHPBB3-15591

### CODE REVIEW

**Comment by mrgoldy** [comment]
Hello and thank you for your PR.

Your commit message is unfortunately not completely correct. The first line can not be longer than 80 characters. Which yours is at the moment. So I would suggest amending it to something like:
```
[ticket/15591] Add jabber permission check

We want to make jabber address unvisible for those users who are not allowed
to send instant (jabber) messages

PHPBB3-15591
```

Also, you're basing this PR on master, while this can be against 3.2 (depending on how quick you are) or 3.3, as it's futile to do this against master, as Jabber will be removed in 4.0 (which is the master branch).

So you'll have to `git commit amend` the commit message and `git rebase` to the correct base branch.

**Comment by ansavin** [comment]
> Hello and thank you for your PR.
> 
> Your commit message is unfortunately not completely correct. The first line can not be longer than 80 characters. Which yours is at the moment. So I would suggest amending it to something like:
> 
> ```
> [ticket/15591] Add jabber permission check
> 
> We want to make jabber address unvisible for those users who are not allowed
> to send instant (jabber) messages
> 
> PHPBB3-15591
> ```
> 
> Also, you're basing this PR on master, while this can be against 3.2 (depending on how quick you are) or 3.3, as it's futile to do this against master, as Jabber will be removed in 4.0 (which is the master branch).
> 
> So you'll have to `git commit --amend` the commit message and `git rebase` to the correct base branch.

Hello, thanks for the review!
I have changed base branch to 3.2.x and amended commit message.
Do I understand correctly that this fix will be automatically merged into 3.3.x too?

**Comment by mrgoldy** [comment]
Branches get automatically merged into the 'higher branch', with a lack of a better word.
So 3.2.x gets merged into 3.3.x, and 3.3.x gets merged into master.

**Comment by mrgoldy** [comment]
Unfortunately travis is still testing with master branch. So you might have to force push once more.

**Pull request merged**
