### PR TITLE
[ticket/14000] Added support for emoji

### PR DESCRIPTION
**Pull request by s9e**
https://tracker.phpbb.com/browse/PHPBB3-14000
https://area51.phpbb.com/phpBB/viewtopic.php?f=126&t=48141

### CODE REVIEW

**Comment by s9e** [comment]
@CHItA I'm going to mark this WIP because I want to research the default handling of some characters such as ✔︎ ✖︎ ©︎ ®︎ ™︎ which should normally be preserved as text.

**Comment by s9e** [comment]
!set WIP

**Comment by s9e** [comment]
@CHItA I have no more modifications planned. The PR has been rebased and if the tests pass, it should be good to go. I linked the A51 topic at the top.

**Comment by s9e** [comment]
!unset WIP

**Comment by CHItA** [comment]
:+1:

**Comment by Nicofuma** [comment]
:+1:

**Comment by androidlamine** [comment]
https://twemoji.maxcdn.com/36x36/1f600.png

**Pull request merged**
