### PR TITLE
[ticket/16161] Enable BBcodes without closing tag

### PR DESCRIPTION
**Pull request by 3D-I**
PHPBB3-16161

Checklist:

- [x] Correct branch: master for new features; 3.3.x & 3.2.x for fixes
- [x] Tests pass
- [x] Code follows coding guidelines: [master](https://area51.phpbb.com/docs/dev/master/development/coding_guidelines.html), [3.3.x](https://area51.phpbb.com/docs/dev/3.3.x/development/coding_guidelines.html) and [3.2.x](https://area51.phpbb.com/docs/dev/3.2.x/development/coding_guidelines.html)
- [x] Commit follows commit message [format](https://area51.phpbb.com/docs/dev/3.3.x/development/git.html)

https://tracker.phpbb.com/browse/PHPBB3-16161

### CODE REVIEW

**Comment by 3D-I** [comment]
!set php

**Comment by battye** [comment]
Could you please explain this feature @3D-I? I don't understand why we don't want closing tags?

**Comment by 3D-I** [comment]
Not every HTML tag requires the closing tag, despite XHTML.
I encountered my problem creating a `thumbnail` BBcode.

A classic example is the `` one, see: https://www.w3schools.com/tags/tag_img.asp

And defined here, in fact: https://github.com/phpbb/phpbb/blob/9217b85c68bbe18a4357a6ca187d2dda17fee803/phpBB/styles/prosilver/template/bbcode.html#L69

As an example you can try the phpBB code `[img]` this way and see it works (_see also the rendered html_)

`[img=https://www.phpbb.com/assets/images/icons/rss-20.png]`

**Comment by battye** [comment]
Thanks for explaining that @3D-I - I understand now 👍

**Pull request merged**
